<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;

class SettingsTableSeeder extends Seeder
{

    /**
     * Auto generated seed file
     *
     * @return void
     */
    public function run()
    {
        

        \DB::table('settings')->delete();
        
        \DB::table('settings')->insert(array (
            0 => 
            array (
                'id' => 8,
                'key' => 'attn_mode_annual_leave',
                'name' => 'ចំនួនថ្ងៃឈប់សម្រាក ប្រចាំឆ្នាំ',
                'value' => '12',
                'options' => '[]',
                'group' => 'attn',
                'created_by' => 1,
                'updated_by' => 1,
                'deleted_by' => 0,
                'desp' => NULL,
                'created_at' => '2025-03-18 08:38:47',
                'updated_at' => '2025-09-28 13:57:29',
                'deleted_at' => NULL,
            ),
            1 => 
            array (
                'id' => 1,
                'key' => 'total_days_per_month',
                'name' => 'ចំនួនថ្ងៃសរុបក្នុង ១ ខែ',
                'value' => '30',
                'options' => '[]',
                'group' => 'rental',
                'created_by' => 1,
                'updated_by' => 1,
                'deleted_by' => 0,
                'desp' => NULL,
                'created_at' => '2024-12-07 11:21:38',
                'updated_at' => '2025-09-28 13:58:11',
                'deleted_at' => NULL,
            ),
            2 => 
            array (
                'id' => 15,
                'key' => 'daily_working_hours',
                'name' => 'ចំនួនម៉ោងសរុបក្នុង១ថ្ងៃ',
                'value' => '8',
                'options' => '[]',
                'group' => 'attn',
                'created_by' => 1,
                'updated_by' => 1,
                'deleted_by' => 0,
                'desp' => 'ម៉ោងនេះនិងត្រូវបានប្រើប្រាស់សម្រាប់បុគ្គលិកដែលមិនមាន កាលវិភាគការងារ។',
                'created_at' => '2025-09-28 14:00:16',
                'updated_at' => '2025-09-28 14:25:52',
                'deleted_at' => NULL,
            ),
            3 => 
            array (
                'id' => 7,
                'key' => 'attn_mode_maternity_leave',
                'name' => 'ចំនួនថ្ងៃឈប់សម្រាក មាតុភាព',
                'value' => '90',
                'options' => NULL,
                'group' => 'attn',
                'created_by' => 1,
                'updated_by' => 1,
                'deleted_by' => 0,
                'desp' => NULL,
                'created_at' => '2025-03-18 08:38:47',
                'updated_at' => '2025-03-18 08:38:47',
                'deleted_at' => NULL,
            ),
            4 => 
            array (
                'id' => 6,
                'key' => 'electricity_price',
                'name' => 'ថ្លៃអគ្គីសនី ១ គីឡូវ៉ាត់',
                'value' => '0.5',
                'options' => NULL,
                'group' => 'utils',
                'created_by' => 1,
                'updated_by' => 1,
                'deleted_by' => 0,
                'desp' => NULL,
                'created_at' => '2025-01-15 13:14:32',
                'updated_at' => '2025-01-15 13:14:32',
                'deleted_at' => NULL,
            ),
            5 => 
            array (
                'id' => 5,
                'key' => 'water_price',
                'name' => 'ថ្លៃទឹកក្នុង ១ ម៉ែត្រគួប',
                'value' => '0.25',
                'options' => NULL,
                'group' => 'utils',
                'created_by' => 1,
                'updated_by' => 1,
                'deleted_by' => 0,
                'desp' => NULL,
                'created_at' => '2025-01-15 13:14:32',
                'updated_at' => '2025-01-15 13:14:32',
                'deleted_at' => NULL,
            ),
            6 => 
            array (
                'id' => 3,
                'key' => 'total_amount_late_pay',
                'name' => 'ចំនួនទឹកប្រាក់ពិន័យបង់ប្រាក់ឈ្នួលយឺត',
                'value' => '30',
                'options' => NULL,
                'group' => 'rental',
                'created_by' => 1,
                'updated_by' => 1,
                'deleted_by' => 0,
                'desp' => NULL,
                'created_at' => '2024-12-07 11:21:38',
                'updated_at' => '2024-12-07 11:21:38',
                'deleted_at' => NULL,
            ),
            7 => 
            array (
                'id' => 11,
                'key' => 'attn_ot_percentage',
                'name' => 'អាត្រាគណនាប្រាក់ម៉ោងធ្វើការលើស ថ្ងៃធម្មតា',
                'value' => '150',
                'options' => NULL,
                'group' => 'attn',
                'created_by' => 1,
                'updated_by' => 1,
                'deleted_by' => 0,
                'desp' => NULL,
                'created_at' => '2025-03-18 09:29:41',
                'updated_at' => '2025-03-18 09:29:41',
                'deleted_at' => NULL,
            ),
            8 => 
            array (
                'id' => 10,
                'key' => 'attn_mode_sick_leave',
                'name' => 'ចំនួនថ្ងៃឈប់សម្រាក ពេលមានជំងឺ',
                'value' => '30',
                'options' => NULL,
                'group' => 'attn',
                'created_by' => 1,
                'updated_by' => 1,
                'deleted_by' => 0,
                'desp' => NULL,
                'created_at' => '2025-03-18 08:38:47',
                'updated_at' => '2025-03-18 08:38:47',
                'deleted_at' => NULL,
            ),
            9 => 
            array (
                'id' => 9,
                'key' => 'attn_mode_married_leave',
                'name' => 'ចំនួនថ្ងៃឈប់សម្រាក អាពាហ៍ពិពាហ៍',
                'value' => '7',
                'options' => NULL,
                'group' => 'attn',
                'created_by' => 1,
                'updated_by' => 1,
                'deleted_by' => 0,
                'desp' => NULL,
                'created_at' => '2025-03-18 08:38:47',
                'updated_at' => '2025-03-18 08:38:47',
                'deleted_at' => NULL,
            ),
            10 => 
            array (
                'id' => 2,
                'key' => 'total_days_late_payment',
                'name' => 'ចំនួនថ្ងៃពន្យាពេលបង់ថ្លៃឈ្នួលយឺត',
                'value' => '7',
                'options' => NULL,
                'group' => 'rental',
                'created_by' => 1,
                'updated_by' => 1,
                'deleted_by' => 0,
                'desp' => NULL,
                'created_at' => '2024-12-07 11:21:38',
                'updated_at' => '2024-12-07 11:21:38',
                'deleted_at' => NULL,
            ),
            11 => 
            array (
                'id' => 13,
                'key' => 'attn_ot_holiday_percentage',
                'name' => 'អាត្រាគណនាប្រាក់ម៉ោងធ្វើការលើស ថ្ងៃបុណ្យ',
                'value' => '200',
                'options' => NULL,
                'group' => 'attn',
                'created_by' => 1,
                'updated_by' => 1,
                'deleted_by' => 0,
                'desp' => NULL,
                'created_at' => '2025-03-18 12:30:49',
                'updated_at' => '2025-03-18 12:30:49',
                'deleted_at' => NULL,
            ),
            12 => 
            array (
                'id' => 12,
                'key' => 'attn_ot_weekend_percentage',
                'name' => 'អាត្រាគណនាប្រាក់ម៉ោងធ្វើការលើស ថ្ងៃចុងសប្ដាហ៍',
                'value' => '100',
                'options' => NULL,
                'group' => 'attn',
                'created_by' => 1,
                'updated_by' => 1,
                'deleted_by' => 0,
                'desp' => NULL,
                'created_at' => '2025-03-18 12:30:49',
                'updated_at' => '2025-03-18 12:30:49',
                'deleted_at' => NULL,
            ),
            13 => 
            array (
                'id' => 4,
                'key' => 'daily_exchange_rate',
                'name' => 'អត្រាការប្រាក់ប្រចាំថ្ងៃ',
                'value' => '4100',
                'options' => NULL,
                'group' => 'money',
                'created_by' => 1,
                'updated_by' => 1,
                'deleted_by' => 0,
                'desp' => NULL,
                'created_at' => '2024-12-12 09:06:04',
                'updated_at' => '2024-12-12 09:06:04',
                'deleted_at' => NULL,
            ),
            14 => 
            array (
                'id' => 14,
                'key' => 'attn_bonus_permonth',
                'name' => 'ប្រាក់ធ្វើការទៀងទាត់',
                'value' => '20',
                'options' => NULL,
                'group' => 'attn',
                'created_by' => 1,
                'updated_by' => 1,
                'deleted_by' => 0,
                'desp' => NULL,
                'created_at' => '2025-03-18 14:55:25',
                'updated_at' => '2025-03-18 14:55:25',
                'deleted_at' => NULL,
            ),
            15 => 
            array (
                'id' => 21,
                'key' => 'attn_min_minute_overtime',
                'name' => 'ចំនួននាទីយកជាការពេលថែមម៉ោង',
                'value' => '30',
                'options' => NULL,
                'group' => 'attn',
                'created_by' => 1,
                'updated_by' => 1,
                'deleted_by' => NULL,
                'desp' => NULL,
                'created_at' => '2025-11-10 19:38:48',
                'updated_at' => '2025-11-10 19:38:48',
                'deleted_at' => NULL,
            ),
            16 => 
            array (
                'id' => 22,
                'key' => 'attn_undertime_ignore_minute',
                'name' => 'ចំនួននាទីអនុគ្រោះសម្រាប់ការយឺតឬចេញមុន',
                'value' => '10',
                'options' => NULL,
                'group' => 'attn',
                'created_by' => 1,
                'updated_by' => 1,
                'deleted_by' => NULL,
                'desp' => NULL,
                'created_at' => '2025-11-10 19:39:49',
                'updated_at' => '2025-11-10 19:39:49',
                'deleted_at' => NULL,
            ),
            17 => 
            array (
                'id' => 23,
                'key' => 'dinner_pay_per_hour_ot',
                'name' => 'ប្រាក់អាហារធ្វើការថែមម៉ោងក្នុង១ម៉ោង',
                'value' => '0.25',
                'options' => NULL,
                'group' => 'bonus',
                'created_by' => 1,
                'updated_by' => 1,
                'deleted_by' => NULL,
                'desp' => NULL,
                'created_at' => '2025-01-15 13:14:32',
                'updated_at' => '2025-01-15 13:14:32',
                'deleted_at' => NULL,
            ),
            18 => 
            array (
                'id' => 25,
                'key' => 'tax_base_reduction',
                'name' => 'មូលដ្ឋានកាត់បន្ថយពន្ធ',
                'value' => '150000',
                'options' => NULL,
                'group' => 'tax',
                'created_by' => 1,
                'updated_by' => 1,
                'deleted_by' => NULL,
                'desp' => NULL,
                'created_at' => '2025-11-18 17:41:05',
                'updated_at' => '2025-11-18 17:41:05',
                'deleted_at' => NULL,
            ),
            19 => 
            array (
                'id' => 26,
                'key' => 'salary_withhold_tax',
                'name' => 'មូលដ្ឋានកាត់ពន្ធប្រាក់បៀវត្ស',
                'value' => '10',
                'options' => NULL,
                'group' => 'tax',
                'created_by' => 1,
                'updated_by' => 1,
                'deleted_by' => NULL,
                'desp' => NULL,
                'created_at' => '2025-11-18 17:49:12',
                'updated_at' => '2025-11-18 17:49:12',
                'deleted_at' => NULL,
            ),
            20 => 
            array (
                'id' => 24,
                'key' => 'trip_fee',
                'name' => 'ប្រាក់ធ្វើដំណើរ',
                'value' => '7',
                'options' => NULL,
                'group' => 'bonus',
                'created_by' => 1,
                'updated_by' => 1,
                'deleted_by' => NULL,
                'desp' => NULL,
                'created_at' => '2025-01-15 13:14:32',
                'updated_at' => '2025-01-15 13:14:32',
                'deleted_at' => NULL,
            ),
            21 => 
            array (
                'id' => 27,
                'key' => 'nssf_withhold_tax',
                'name' => 'ពន្ធសោធននិវត្ស',
                'value' => '5',
                'options' => NULL,
                'group' => 'tax',
                'created_by' => 1,
                'updated_by' => 1,
                'deleted_by' => NULL,
                'desp' => NULL,
                'created_at' => '2025-11-18 19:37:40',
                'updated_at' => '2025-11-18 19:37:40',
                'deleted_at' => NULL,
            ),
        ));
        
        
    }
}