<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;

class ChaptersTableSeeder extends Seeder
{

    /**
     * Auto generated seed file
     *
     * @return void
     */
    public function run()
    {
        

        \DB::table('chapters')->delete();
        
        \DB::table('chapters')->insert(array (
            0 => 
            array (
                'id' => 1,
                'number' => 'ជំពូកទោល ',
                'title' => 'បទប្បញ្ញត្ដិទូទៅ ',
                'book_id' => 1,
                'kunty_id' => 1,
                'matika_id' => 0,
                'created_by' => 0,
                'updated_by' => 0,
                'created_at' => '2015-06-16 00:00:00',
                'updated_at' => '2015-06-16 00:00:00',
            ),
            1 => 
            array (
                'id' => 2,
                'number' => 'ជំពូកទី ១ ',
                'title' => 'រូបវន្ដបុគ្គល ',
                'book_id' => 1,
                'kunty_id' => 2,
                'matika_id' => 0,
                'created_by' => 0,
                'updated_by' => 0,
                'created_at' => '2015-06-16 00:00:00',
                'updated_at' => '2015-06-16 00:00:00',
            ),
            2 => 
            array (
                'id' => 3,
                'number' => 'ជំពូកទី ២ ',
                'title' => 'នីតិបុគ្គល ',
                'book_id' => 1,
                'kunty_id' => 2,
                'matika_id' => 0,
                'created_by' => 0,
                'updated_by' => 0,
                'created_at' => '2015-06-16 00:00:00',
                'updated_at' => '2015-06-16 00:00:00',
            ),
            3 => 
            array (
                'id' => 4,
                'number' => 'ជំពូកទី ១ ',
                'title' => 'បទប្បញ្ញត្ដិទូទៅ ',
                'book_id' => 1,
                'kunty_id' => 3,
                'matika_id' => 0,
                'created_by' => 0,
                'updated_by' => 0,
                'created_at' => '2015-06-16 00:00:00',
                'updated_at' => '2015-06-16 00:00:00',
            ),
            4 => 
            array (
                'id' => 5,
                'number' => 'ជំពូកទី ២',
                'title' => 'កម្មសិទ្ធិ',
                'book_id' => 1,
                'kunty_id' => 3,
                'matika_id' => 0,
                'created_by' => 3,
                'updated_by' => 3,
                'created_at' => '2015-06-16 00:00:00',
                'updated_at' => '2018-02-02 17:24:22',
            ),
            5 => 
            array (
                'id' => 6,
                'number' => 'ជំពូកទី ៣ ',
                'title' => 'សិទ្ធិកាន់កាប់ ',
                'book_id' => 1,
                'kunty_id' => 3,
                'matika_id' => 0,
                'created_by' => 0,
                'updated_by' => 0,
                'created_at' => '2015-06-16 00:00:00',
                'updated_at' => '2015-06-16 00:00:00',
            ),
            6 => 
            array (
                'id' => 7,
                'number' => 'ជំពូកទី ៤ ',
                'title' => 'សិទ្ធិជួលអចិន្រ្ដៃយ៍ ',
                'book_id' => 1,
                'kunty_id' => 3,
                'matika_id' => 0,
                'created_by' => 0,
                'updated_by' => 0,
                'created_at' => '2015-06-16 00:00:00',
                'updated_at' => '2015-06-16 00:00:00',
            ),
            7 => 
            array (
                'id' => 8,
                'number' => 'ជំពូកទី ៥ ',
                'title' => 'ផលុបភោគ ',
                'book_id' => 1,
                'kunty_id' => 3,
                'matika_id' => 0,
                'created_by' => 0,
                'updated_by' => 0,
                'created_at' => '2015-06-16 00:00:00',
                'updated_at' => '2015-06-16 00:00:00',
            ),
            8 => 
            array (
                'id' => 9,
                'number' => 'ជំពូកទី ៦ ',
                'title' => 'សិទ្ធិប្រើប្រាស់ និង សិទ្ធិអាស្រ័យនៅ ',
                'book_id' => 1,
                'kunty_id' => 3,
                'matika_id' => 0,
                'created_by' => 0,
                'updated_by' => 0,
                'created_at' => '2015-06-16 00:00:00',
                'updated_at' => '2015-06-16 00:00:00',
            ),
            9 => 
            array (
                'id' => 10,
                'number' => 'ជំពូកទី ៧ ',
                'title' => 'សេវភាព ',
                'book_id' => 1,
                'kunty_id' => 3,
                'matika_id' => 0,
                'created_by' => 0,
                'updated_by' => 0,
                'created_at' => '2015-06-16 00:00:00',
                'updated_at' => '2015-06-16 00:00:00',
            ),
            10 => 
            array (
                'id' => 11,
                'number' => 'ជំពូកទី ៨ ',
                'title' => 'កម្មសិទ្ធិ និង សិទ្ធិប្រត្យក្សផ្សេងៗ របស់រដ្ឋ វត្ដអារាមនៃព្រះពុទ្ធសាសនា ',
                'book_id' => 1,
                'kunty_id' => 3,
                'matika_id' => 0,
                'created_by' => 0,
                'updated_by' => 0,
                'created_at' => '2015-06-16 00:00:00',
                'updated_at' => '2015-06-16 00:00:00',
            ),
            11 => 
            array (
                'id' => 12,
                'number' => 'ជំពូកទី ៩ ',
                'title' => 'សិទ្ធិដែលត្រូវបានបង្កើតឡើងដោយសម្បទានដីធ្លី ',
                'book_id' => 1,
                'kunty_id' => 3,
                'matika_id' => 0,
                'created_by' => 0,
                'updated_by' => 0,
                'created_at' => '2015-06-16 00:00:00',
                'updated_at' => '2015-06-16 00:00:00',
            ),
            12 => 
            array (
                'id' => 13,
                'number' => 'ជំពូកទី ១ ',
                'title' => 'បទប្បញ្ញត្ដិទូទៅ ',
                'book_id' => 1,
                'kunty_id' => 4,
                'matika_id' => 0,
                'created_by' => 0,
                'updated_by' => 0,
                'created_at' => '2015-06-16 00:00:00',
                'updated_at' => '2015-06-16 00:00:00',
            ),
            13 => 
            array (
                'id' => 14,
                'number' => 'ជំពូកទី ២ ',
                'title' => 'ការបង្ហាញឆន្ទៈ និង កិច្ចសន្យា ',
                'book_id' => 1,
                'kunty_id' => 4,
                'matika_id' => 0,
                'created_by' => 0,
                'updated_by' => 0,
                'created_at' => '2015-06-16 00:00:00',
                'updated_at' => '2015-06-16 00:00:00',
            ),
            14 => 
            array (
                'id' => 15,
                'number' => 'ជំពូកទី ៣ ',
                'title' => 'ការអនុវត្ដកិច្ចសន្យា ',
                'book_id' => 1,
                'kunty_id' => 4,
                'matika_id' => 0,
                'created_by' => 0,
                'updated_by' => 0,
                'created_at' => '2015-06-16 00:00:00',
                'updated_at' => '2015-06-16 00:00:00',
            ),
            15 => 
            array (
                'id' => 16,
                'number' => 'ជំពូកទី ៤ ',
                'title' => 'ការសង្រ្គោះចំពោះការបំពានលើកិច្ចសន្យា ',
                'book_id' => 1,
                'kunty_id' => 4,
                'matika_id' => 0,
                'created_by' => 0,
                'updated_by' => 0,
                'created_at' => '2015-06-16 00:00:00',
                'updated_at' => '2015-06-16 00:00:00',
            ),
            16 => 
            array (
                'id' => 17,
                'number' => 'ជំពូកទី ៥ ',
                'title' => 'ការទទួលបន្ទុកហានិភ័យ ',
                'book_id' => 1,
                'kunty_id' => 4,
                'matika_id' => 0,
                'created_by' => 0,
                'updated_by' => 0,
                'created_at' => '2015-06-16 00:00:00',
                'updated_at' => '2015-06-16 00:00:00',
            ),
            17 => 
            array (
                'id' => 18,
                'number' => 'ជំពូកទី ៦ ',
                'title' => 'អានុភាពនៃសិទ្ធិលើបំណុលចំពោះតតិយជន ',
                'book_id' => 1,
                'kunty_id' => 4,
                'matika_id' => 0,
                'created_by' => 0,
                'updated_by' => 0,
                'created_at' => '2015-06-16 00:00:00',
                'updated_at' => '2015-06-16 00:00:00',
            ),
            18 => 
            array (
                'id' => 19,
                'number' => 'ជំពូកទី ៧ ',
                'title' => 'ការរលត់កាតព្វកិច្ច ',
                'book_id' => 1,
                'kunty_id' => 4,
                'matika_id' => 0,
                'created_by' => 0,
                'updated_by' => 0,
                'created_at' => '2015-06-16 00:00:00',
                'updated_at' => '2015-06-16 00:00:00',
            ),
            19 => 
            array (
                'id' => 20,
                'number' => 'ជំពូកទី ៨ ',
                'title' => 'អាជ្ញាយុកាលនៃការរំលត់សិទ្ធិលើបំណុល ',
                'book_id' => 1,
                'kunty_id' => 4,
                'matika_id' => 0,
                'created_by' => 0,
                'updated_by' => 0,
                'created_at' => '2015-06-16 00:00:00',
                'updated_at' => '2015-06-16 00:00:00',
            ),
            20 => 
            array (
                'id' => 21,
                'number' => 'ជំពូកទី ៩ ',
                'title' => 'អនុប្បទានសិទ្ធិលើបំណុល ការទទួលកាតព្វកិច្ច ',
                'book_id' => 1,
                'kunty_id' => 4,
                'matika_id' => 0,
                'created_by' => 0,
                'updated_by' => 0,
                'created_at' => '2015-06-16 00:00:00',
                'updated_at' => '2015-06-16 00:00:00',
            ),
            21 => 
            array (
                'id' => 22,
                'number' => 'ជំពូកទី ១ ',
                'title' => 'ការលក់ទិញ ',
                'book_id' => 1,
                'kunty_id' => 5,
                'matika_id' => 0,
                'created_by' => 0,
                'updated_by' => 0,
                'created_at' => '2015-06-16 00:00:00',
                'updated_at' => '2015-06-16 00:00:00',
            ),
            22 => 
            array (
                'id' => 23,
                'number' => 'ជំពូកទី ២ ',
                'title' => 'ការដូរ ',
                'book_id' => 1,
                'kunty_id' => 5,
                'matika_id' => 0,
                'created_by' => 0,
                'updated_by' => 0,
                'created_at' => '2015-06-16 00:00:00',
                'updated_at' => '2015-06-16 00:00:00',
            ),
            23 => 
            array (
                'id' => 24,
                'number' => 'ជំពូកទី ៣ ',
                'title' => 'ប្រទានកម្ម ',
                'book_id' => 1,
                'kunty_id' => 5,
                'matika_id' => 0,
                'created_by' => 0,
                'updated_by' => 0,
                'created_at' => '2015-06-16 00:00:00',
                'updated_at' => '2015-06-16 00:00:00',
            ),
            24 => 
            array (
                'id' => 25,
                'number' => 'ជំពូកទី ៤ ',
                'title' => 'ការខ្ចីបរិភោគ ',
                'book_id' => 1,
                'kunty_id' => 5,
                'matika_id' => 0,
                'created_by' => 0,
                'updated_by' => 0,
                'created_at' => '2015-06-16 00:00:00',
                'updated_at' => '2015-06-16 00:00:00',
            ),
            25 => 
            array (
                'id' => 26,
                'number' => 'ជំពូកទី ៥ ',
                'title' => 'ភតិសន្យា ',
                'book_id' => 1,
                'kunty_id' => 5,
                'matika_id' => 0,
                'created_by' => 0,
                'updated_by' => 0,
                'created_at' => '2015-06-16 00:00:00',
                'updated_at' => '2015-06-16 00:00:00',
            ),
            26 => 
            array (
                'id' => 27,
                'number' => 'ជំពូកទី ៦ ',
                'title' => 'ការខ្ចីប្រើ ',
                'book_id' => 1,
                'kunty_id' => 5,
                'matika_id' => 0,
                'created_by' => 0,
                'updated_by' => 0,
                'created_at' => '2015-06-16 00:00:00',
                'updated_at' => '2015-06-16 00:00:00',
            ),
            27 => 
            array (
                'id' => 28,
                'number' => 'ជំពូកទី ៧ ',
                'title' => 'អាណត្ដិ ',
                'book_id' => 1,
                'kunty_id' => 5,
                'matika_id' => 0,
                'created_by' => 0,
                'updated_by' => 0,
                'created_at' => '2015-06-16 00:00:00',
                'updated_at' => '2015-06-16 00:00:00',
            ),
            28 => 
            array (
                'id' => 29,
                'number' => 'ជំពូកទី ៨ ',
                'title' => 'កិច្ចសន្យាម៉ៅការ ',
                'book_id' => 1,
                'kunty_id' => 5,
                'matika_id' => 0,
                'created_by' => 0,
                'updated_by' => 0,
                'created_at' => '2015-06-16 00:00:00',
                'updated_at' => '2015-06-16 00:00:00',
            ),
            29 => 
            array (
                'id' => 30,
                'number' => 'ជំពូកទី ៩ ',
                'title' => 'កិច្ចសន្យាការងារ ',
                'book_id' => 1,
                'kunty_id' => 5,
                'matika_id' => 0,
                'created_by' => 0,
                'updated_by' => 0,
                'created_at' => '2015-06-16 00:00:00',
                'updated_at' => '2015-06-16 00:00:00',
            ),
            30 => 
            array (
                'id' => 31,
                'number' => 'ជំពូកទី ១០ ',
                'title' => 'បញ្ញើ ',
                'book_id' => 1,
                'kunty_id' => 5,
                'matika_id' => 0,
                'created_by' => 0,
                'updated_by' => 0,
                'created_at' => '2015-06-16 00:00:00',
                'updated_at' => '2015-06-16 00:00:00',
            ),
            31 => 
            array (
                'id' => 32,
                'number' => 'ជំពូកទី ១១ ',
                'title' => 'កិច្ចសន្យាក្រុមហ៊ុន ',
                'book_id' => 1,
                'kunty_id' => 5,
                'matika_id' => 0,
                'created_by' => 0,
                'updated_by' => 0,
                'created_at' => '2015-06-16 00:00:00',
                'updated_at' => '2015-06-16 00:00:00',
            ),
            32 => 
            array (
                'id' => 33,
                'number' => 'ជំពូកទី ១២ ',
                'title' => 'កិច្ចសន្យាធនលាភសាមយិកមួយជីវិត ',
                'book_id' => 1,
                'kunty_id' => 5,
                'matika_id' => 0,
                'created_by' => 0,
                'updated_by' => 0,
                'created_at' => '2015-06-16 00:00:00',
                'updated_at' => '2015-06-16 00:00:00',
            ),
            33 => 
            array (
                'id' => 34,
                'number' => 'ជំពូកទី ១៣ ',
                'title' => 'ការសះជា ',
                'book_id' => 1,
                'kunty_id' => 5,
                'matika_id' => 0,
                'created_by' => 0,
                'updated_by' => 0,
                'created_at' => '2015-06-16 00:00:00',
                'updated_at' => '2015-06-16 00:00:00',
            ),
            34 => 
            array (
                'id' => 35,
                'number' => 'ជំពូកទី ១៤ ',
                'title' => 'ការគ្រប់គ្រងដោយឈឺឆ្អាល ',
                'book_id' => 1,
                'kunty_id' => 5,
                'matika_id' => 0,
                'created_by' => 0,
                'updated_by' => 0,
                'created_at' => '2015-06-16 00:00:00',
                'updated_at' => '2015-06-16 00:00:00',
            ),
            35 => 
            array (
                'id' => 36,
                'number' => 'ជំពូកទី ១៥ ',
                'title' => 'សេចក្ដីចម្រើនដោយឥតហេតុ ',
                'book_id' => 1,
                'kunty_id' => 5,
                'matika_id' => 0,
                'created_by' => 0,
                'updated_by' => 0,
                'created_at' => '2015-06-16 00:00:00',
                'updated_at' => '2015-06-16 00:00:00',
            ),
            36 => 
            array (
                'id' => 37,
                'number' => 'ជំពូកទី ១៦ ',
                'title' => 'អំពើអនីត្យានុកូល ',
                'book_id' => 1,
                'kunty_id' => 5,
                'matika_id' => 0,
                'created_by' => 0,
                'updated_by' => 0,
                'created_at' => '2015-06-16 00:00:00',
                'updated_at' => '2015-06-16 00:00:00',
            ),
            37 => 
            array (
                'id' => 38,
                'number' => 'ជំពូកទី ១ ',
                'title' => 'បទប្បញ្ញត្ដិទូទៅ ',
                'book_id' => 1,
                'kunty_id' => 6,
                'matika_id' => 0,
                'created_by' => 0,
                'updated_by' => 0,
                'created_at' => '2015-06-16 00:00:00',
                'updated_at' => '2015-06-16 00:00:00',
            ),
            38 => 
            array (
                'id' => 39,
                'number' => 'ជំពូកទី ២ ',
                'title' => 'សិទ្ធិឃាត់ទុក ',
                'book_id' => 1,
                'kunty_id' => 6,
                'matika_id' => 0,
                'created_by' => 0,
                'updated_by' => 0,
                'created_at' => '2015-06-16 00:00:00',
                'updated_at' => '2015-06-16 00:00:00',
            ),
            39 => 
            array (
                'id' => 40,
                'number' => 'ជំពូកទី ៣ ',
                'title' => 'ឯកសិទ្ធិ ',
                'book_id' => 1,
                'kunty_id' => 6,
                'matika_id' => 0,
                'created_by' => 0,
                'updated_by' => 0,
                'created_at' => '2015-06-16 00:00:00',
                'updated_at' => '2015-06-16 00:00:00',
            ),
            40 => 
            array (
                'id' => 41,
                'number' => 'ជំពូកទី ៤ ',
                'title' => 'សិទ្ធិលើការបញ្ចាំ ',
                'book_id' => 1,
                'kunty_id' => 6,
                'matika_id' => 0,
                'created_by' => 0,
                'updated_by' => 0,
                'created_at' => '2015-06-16 00:00:00',
                'updated_at' => '2015-06-16 00:00:00',
            ),
            41 => 
            array (
                'id' => 42,
                'number' => 'ជំពូកទី ៥ ',
                'title' => 'ហ៊ីប៉ូតែក ',
                'book_id' => 1,
                'kunty_id' => 6,
                'matika_id' => 0,
                'created_by' => 0,
                'updated_by' => 0,
                'created_at' => '2015-06-16 00:00:00',
                'updated_at' => '2015-06-16 00:00:00',
            ),
            42 => 
            array (
                'id' => 43,
                'number' => 'ជំពូកទី ៦ ',
                'title' => 'ប្រាតិភោគដោយអនុប្បទាន ',
                'book_id' => 1,
                'kunty_id' => 6,
                'matika_id' => 0,
                'created_by' => 0,
                'updated_by' => 0,
                'created_at' => '2015-06-16 00:00:00',
                'updated_at' => '2015-06-16 00:00:00',
            ),
            43 => 
            array (
                'id' => 44,
                'number' => 'ជំពូកទី ៧ ',
                'title' => 'ការធានា ',
                'book_id' => 1,
                'kunty_id' => 6,
                'matika_id' => 0,
                'created_by' => 0,
                'updated_by' => 0,
                'created_at' => '2015-06-16 00:00:00',
                'updated_at' => '2015-06-16 00:00:00',
            ),
            44 => 
            array (
                'id' => 45,
                'number' => 'ជំពូកទី ៨ ',
                'title' => 'កាតព្វកិច្ចដោយសាមគ្គីភាព ',
                'book_id' => 1,
                'kunty_id' => 6,
                'matika_id' => 0,
                'created_by' => 0,
                'updated_by' => 0,
                'created_at' => '2015-06-16 00:00:00',
                'updated_at' => '2015-06-16 00:00:00',
            ),
            45 => 
            array (
                'id' => 46,
                'number' => 'ជំពូកទី ១ ',
                'title' => 'បទប្បញ្ញត្ដិទូទៅ ',
                'book_id' => 1,
                'kunty_id' => 7,
                'matika_id' => 0,
                'created_by' => 0,
                'updated_by' => 0,
                'created_at' => '2015-06-16 00:00:00',
                'updated_at' => '2015-06-16 00:00:00',
            ),
            46 => 
            array (
                'id' => 47,
                'number' => 'ជំពូកទី ២ ',
                'title' => 'កំជាប់ពាក្យ ',
                'book_id' => 1,
                'kunty_id' => 7,
                'matika_id' => 0,
                'created_by' => 0,
                'updated_by' => 0,
                'created_at' => '2015-06-16 00:00:00',
                'updated_at' => '2015-06-16 00:00:00',
            ),
            47 => 
            array (
                'id' => 48,
                'number' => 'ជំពូកទី ៣ ',
                'title' => 'អាពាហ៍ពិពាហ៍ ',
                'book_id' => 1,
                'kunty_id' => 7,
                'matika_id' => 0,
                'created_by' => 0,
                'updated_by' => 0,
                'created_at' => '2015-06-16 00:00:00',
                'updated_at' => '2015-06-16 00:00:00',
            ),
            48 => 
            array (
                'id' => 49,
                'number' => 'ជំពូកទី ៤ ',
                'title' => 'ឪពុកម្ដាយ និង កូន ',
                'book_id' => 1,
                'kunty_id' => 7,
                'matika_id' => 0,
                'created_by' => 0,
                'updated_by' => 0,
                'created_at' => '2015-06-16 00:00:00',
                'updated_at' => '2015-06-16 00:00:00',
            ),
            49 => 
            array (
                'id' => 50,
                'number' => 'ជំពូកទី ៥ ',
                'title' => 'អំណាចមេបា ',
                'book_id' => 1,
                'kunty_id' => 7,
                'matika_id' => 0,
                'created_by' => 0,
                'updated_by' => 0,
                'created_at' => '2015-06-16 00:00:00',
                'updated_at' => '2015-06-16 00:00:00',
            ),
            50 => 
            array (
                'id' => 51,
                'number' => 'ជំពូកទី ៦ ',
                'title' => 'អាណាព្យាបាល ',
                'book_id' => 1,
                'kunty_id' => 7,
                'matika_id' => 0,
                'created_by' => 0,
                'updated_by' => 0,
                'created_at' => '2015-06-16 00:00:00',
                'updated_at' => '2015-06-16 00:00:00',
            ),
            51 => 
            array (
                'id' => 52,
                'number' => 'ជំពូកទី ៧ ',
                'title' => 'ហិតូបត្ថម្ភ ',
                'book_id' => 1,
                'kunty_id' => 7,
                'matika_id' => 0,
                'created_by' => 0,
                'updated_by' => 0,
                'created_at' => '2015-06-16 00:00:00',
                'updated_at' => '2015-06-16 00:00:00',
            ),
            52 => 
            array (
                'id' => 53,
                'number' => 'ជំពូកទី ៨ ',
                'title' => 'អាហារកាតព្វកិច្ច ',
                'book_id' => 1,
                'kunty_id' => 7,
                'matika_id' => 0,
                'created_by' => 0,
                'updated_by' => 0,
                'created_at' => '2015-06-16 00:00:00',
                'updated_at' => '2015-06-16 00:00:00',
            ),
            53 => 
            array (
                'id' => 54,
                'number' => 'ជំពូកទី ១ ',
                'title' => 'បទប្បញ្ញត្ដិទូទៅ ',
                'book_id' => 1,
                'kunty_id' => 8,
                'matika_id' => 0,
                'created_by' => 0,
                'updated_by' => 0,
                'created_at' => '2015-06-16 00:00:00',
                'updated_at' => '2015-06-16 00:00:00',
            ),
            54 => 
            array (
                'id' => 55,
                'number' => 'ជំពូកទី ២ ',
                'title' => 'សន្ដតិកម្មតាមច្បាប់ ',
                'book_id' => 1,
                'kunty_id' => 8,
                'matika_id' => 0,
                'created_by' => 0,
                'updated_by' => 0,
                'created_at' => '2015-06-16 00:00:00',
                'updated_at' => '2015-06-16 00:00:00',
            ),
            55 => 
            array (
                'id' => 56,
                'number' => 'ជំពូកទី ៣ ',
                'title' => 'សន្ដតិកម្មតាមមតកសាសន៍ ',
                'book_id' => 1,
                'kunty_id' => 8,
                'matika_id' => 0,
                'created_by' => 0,
                'updated_by' => 0,
                'created_at' => '2015-06-16 00:00:00',
                'updated_at' => '2015-06-16 00:00:00',
            ),
            56 => 
            array (
                'id' => 57,
                'number' => 'ជំពូកទី ៤ ',
                'title' => 'ភាគបម្រុង ',
                'book_id' => 1,
                'kunty_id' => 8,
                'matika_id' => 0,
                'created_by' => 0,
                'updated_by' => 0,
                'created_at' => '2015-06-16 00:00:00',
                'updated_at' => '2015-06-16 00:00:00',
            ),
            57 => 
            array (
                'id' => 58,
                'number' => 'ជំពូកទី ៥ ',
                'title' => 'ការយល់ព្រម និង ការបោះបង់សន្ដតិកម្ម ',
                'book_id' => 1,
                'kunty_id' => 8,
                'matika_id' => 0,
                'created_by' => 0,
                'updated_by' => 0,
                'created_at' => '2015-06-16 00:00:00',
                'updated_at' => '2015-06-16 00:00:00',
            ),
            58 => 
            array (
                'id' => 59,
                'number' => 'ជំពូកទី ៦ ',
                'title' => 'ការគ្រប់គ្រង និង ការបែងចែកមត៌ក ',
                'book_id' => 1,
                'kunty_id' => 8,
                'matika_id' => 0,
                'created_by' => 0,
                'updated_by' => 0,
                'created_at' => '2015-06-16 00:00:00',
                'updated_at' => '2015-06-16 00:00:00',
            ),
            59 => 
            array (
                'id' => 60,
                'number' => 'ជំពូកទី ៧ ',
                'title' => 'នត្ថិភាពនៃសន្ដតិជន ',
                'book_id' => 1,
                'kunty_id' => 8,
                'matika_id' => 0,
                'created_by' => 0,
                'updated_by' => 0,
                'created_at' => '2015-06-16 00:00:00',
                'updated_at' => '2015-06-16 00:00:00',
            ),
            60 => 
            array (
                'id' => 61,
                'number' => 'ជំពូកទី ៨ ',
                'title' => 'ការទាមទារឲ្យធ្វើបដិទានសន្ដតិកម្ម ',
                'book_id' => 1,
                'kunty_id' => 8,
                'matika_id' => 0,
                'created_by' => 0,
                'updated_by' => 0,
                'created_at' => '2015-06-16 00:00:00',
                'updated_at' => '2015-06-16 00:00:00',
            ),
            61 => 
            array (
                'id' => 62,
                'number' => 'ជំពូកទោល',
                'title' => 'អវសានប្បញ្ញត្តិ',
                'book_id' => 1,
                'kunty_id' => 9,
                'matika_id' => 0,
                'created_by' => 0,
                'updated_by' => 0,
                'created_at' => '2015-06-16 00:00:00',
                'updated_at' => '2015-06-16 00:00:00',
            ),
            62 => 
            array (
                'id' => 63,
                'number' => 'ជំពូកទី ១ ',
                'title' => 'គោលបំណងនៃក្រមនីតិវិធីរដ្ឋប្បវេណី គោលបំណងនៃបណ្ដឹងរដ្ឋប្បវេណី ',
                'book_id' => 2,
                'kunty_id' => 10,
                'matika_id' => 0,
                'created_by' => 0,
                'updated_by' => 0,
                'created_at' => '2015-06-16 00:00:00',
                'updated_at' => '2015-06-16 00:00:00',
            ),
            63 => 
            array (
                'id' => 64,
                'number' => 'ជំពូកទី ២ ',
                'title' => 'តុលាការ ',
                'book_id' => 2,
                'kunty_id' => 10,
                'matika_id' => 0,
                'created_by' => 0,
                'updated_by' => 0,
                'created_at' => '2015-06-16 00:00:00',
                'updated_at' => '2015-06-16 00:00:00',
            ),
            64 => 
            array (
                'id' => 65,
                'number' => 'ជំពូកទី ៣ ',
                'title' => 'ភាគី ',
                'book_id' => 2,
                'kunty_id' => 10,
                'matika_id' => 0,
                'created_by' => 0,
                'updated_by' => 0,
                'created_at' => '2015-06-16 00:00:00',
                'updated_at' => '2015-06-16 00:00:00',
            ),
            65 => 
            array (
                'id' => 66,
                'number' => 'ជំពូកទី ៤ ',
                'title' => 'ប្រាក់ប្រដាប់ក្ដី ',
                'book_id' => 2,
                'kunty_id' => 10,
                'matika_id' => 0,
                'created_by' => 0,
                'updated_by' => 0,
                'created_at' => '2015-06-16 00:00:00',
                'updated_at' => '2015-06-16 00:00:00',
            ),
            66 => 
            array (
                'id' => 67,
                'number' => 'ជំពូកទី ៥ ',
                'title' => 'ប្រាតិភោគលើបណ្ដឹង ',
                'book_id' => 2,
                'kunty_id' => 10,
                'matika_id' => 0,
                'created_by' => 0,
                'updated_by' => 0,
                'created_at' => '2015-06-16 00:00:00',
                'updated_at' => '2015-06-16 00:00:00',
            ),
            67 => 
            array (
                'id' => 68,
                'number' => 'ជំពូកទី ១ ',
                'title' => 'បណ្ដឹង ',
                'book_id' => 2,
                'kunty_id' => 11,
                'matika_id' => 0,
                'created_by' => 0,
                'updated_by' => 0,
                'created_at' => '2015-06-16 00:00:00',
                'updated_at' => '2015-06-16 00:00:00',
            ),
            68 => 
            array (
                'id' => 69,
                'number' => 'ជំពូកទី ២ ',
                'title' => 'ការទាញហេតុផលដោយផ្ទាល់មាត់់ និង ការរៀបចំ ',
                'book_id' => 2,
                'kunty_id' => 11,
                'matika_id' => 0,
                'created_by' => 0,
                'updated_by' => 0,
                'created_at' => '2015-06-16 00:00:00',
                'updated_at' => '2015-06-16 00:00:00',
            ),
            69 => 
            array (
                'id' => 70,
                'number' => 'ជំពូកទី ៣ ',
                'title' => 'ភស្ដុតាង ',
                'book_id' => 2,
                'kunty_id' => 11,
                'matika_id' => 0,
                'created_by' => 0,
                'updated_by' => 0,
                'created_at' => '2015-06-16 00:00:00',
                'updated_at' => '2015-06-16 00:00:00',
            ),
            70 => 
            array (
                'id' => 71,
                'number' => 'ជំពូកទី ៤ ',
                'title' => 'ការផ្អាក និង បង្អង់នីតិវិធីនៃបណ្ដឹង ',
                'book_id' => 2,
                'kunty_id' => 11,
                'matika_id' => 0,
                'created_by' => 0,
                'updated_by' => 0,
                'created_at' => '2015-06-16 00:00:00',
                'updated_at' => '2015-06-16 00:00:00',
            ),
            71 => 
            array (
                'id' => 72,
                'number' => 'ជំពូកទី ៥ ',
                'title' => 'ការសម្រេចសេចក្ដី ',
                'book_id' => 2,
                'kunty_id' => 11,
                'matika_id' => 0,
                'created_by' => 0,
                'updated_by' => 0,
                'created_at' => '2015-06-16 00:00:00',
                'updated_at' => '2015-06-16 00:00:00',
            ),
            72 => 
            array (
                'id' => 73,
                'number' => 'ជំពូកទី ៦ ',
                'title' => 'ការបញ្ចប់នីតិវិធីដោយមិនធ្វើទៅតាមការសម្រេចសេចក្ដី ',
                'book_id' => 2,
                'kunty_id' => 11,
                'matika_id' => 0,
                'created_by' => 0,
                'updated_by' => 0,
                'created_at' => '2015-06-16 00:00:00',
                'updated_at' => '2015-06-16 00:00:00',
            ),
            73 => 
            array (
                'id' => 74,
                'number' => 'ជំពូកទី ៧ ',
                'title' => 'បទប្បញ្ញត្ដិពិសេសស្ដីពីរឿងក្ដីចំនួនទឹកប្រាក់តិច ',
                'book_id' => 2,
                'kunty_id' => 11,
                'matika_id' => 0,
                'created_by' => 0,
                'updated_by' => 0,
                'created_at' => '2015-06-16 00:00:00',
                'updated_at' => '2015-06-16 00:00:00',
            ),
            74 => 
            array (
                'id' => 75,
                'number' => 'ជំពូកទី ៨ ',
                'title' => 'កាលបរិច្ឆេទ អំឡុងពេល និង ការបញ្ជូន ',
                'book_id' => 2,
                'kunty_id' => 11,
                'matika_id' => 0,
                'created_by' => 0,
                'updated_by' => 0,
                'created_at' => '2015-06-16 00:00:00',
                'updated_at' => '2015-06-16 00:00:00',
            ),
            75 => 
            array (
                'id' => 76,
                'number' => 'ជំពូកទី ៩ ',
                'title' => 'ការមើលសំណុំរឿង ',
                'book_id' => 2,
                'kunty_id' => 11,
                'matika_id' => 0,
                'created_by' => 0,
                'updated_by' => 0,
                'created_at' => '2015-06-16 00:00:00',
                'updated_at' => '2015-06-16 00:00:00',
            ),
            76 => 
            array (
                'id' => 77,
                'number' => 'ជំពូកទី ១ ',
                'title' => 'បទប្បញ្ញត្ដិទូទៅ ',
                'book_id' => 2,
                'kunty_id' => 12,
                'matika_id' => 0,
                'created_by' => 0,
                'updated_by' => 0,
                'created_at' => '2015-06-16 00:00:00',
                'updated_at' => '2015-06-16 00:00:00',
            ),
            77 => 
            array (
                'id' => 78,
                'number' => 'ជំពូកទី ២ ',
                'title' => 'បណ្ដឹងឧទ្ធរណ៍ ',
                'book_id' => 2,
                'kunty_id' => 12,
                'matika_id' => 0,
                'created_by' => 0,
                'updated_by' => 0,
                'created_at' => '2015-06-16 00:00:00',
                'updated_at' => '2015-06-16 00:00:00',
            ),
            78 => 
            array (
                'id' => 79,
                'number' => 'ជំពូកទី ៣ ',
                'title' => 'បណ្ដឹងសាទុក្ខ ',
                'book_id' => 2,
                'kunty_id' => 12,
                'matika_id' => 0,
                'created_by' => 0,
                'updated_by' => 0,
                'created_at' => '2015-06-16 00:00:00',
                'updated_at' => '2015-06-16 00:00:00',
            ),
            79 => 
            array (
                'id' => 80,
                'number' => 'ជំពូកទី ៤ ',
                'title' => 'បណ្ដឹងជំទាស់ ',
                'book_id' => 2,
                'kunty_id' => 12,
                'matika_id' => 0,
                'created_by' => 0,
                'updated_by' => 0,
                'created_at' => '2015-06-16 00:00:00',
                'updated_at' => '2015-06-16 00:00:00',
            ),
            80 => 
            array (
                'id' => 81,
                'number' => 'ជំពូកទី ១ ',
                'title' => 'បទប្បញ្ញត្ដិទូទៅ ',
                'book_id' => 2,
                'kunty_id' => 15,
                'matika_id' => 0,
                'created_by' => 0,
                'updated_by' => 0,
                'created_at' => '2015-06-16 00:00:00',
                'updated_at' => '2015-06-16 00:00:00',
            ),
            81 => 
            array (
                'id' => 82,
                'number' => 'ជំពូកទី ២ ',
                'title' => 'ការអនុវត្ដដោយបង្ខំ ចំពោះសិទ្ធិទាមទារដែលមានគោលបំណងឲ្យសងជាប្រាក់ ',
                'book_id' => 2,
                'kunty_id' => 15,
                'matika_id' => 0,
                'created_by' => 0,
                'updated_by' => 0,
                'created_at' => '2015-06-16 00:00:00',
                'updated_at' => '2015-06-16 00:00:00',
            ),
            82 => 
            array (
                'id' => 83,
                'number' => 'ជំពូកទី ៣ ',
                'title' => 'បទប្បញ្ញត្ដិពិសេសស្ដីពីការអនុវត្ដសិទ្ធិប្រាតិភោគ ',
                'book_id' => 2,
                'kunty_id' => 15,
                'matika_id' => 0,
                'created_by' => 0,
                'updated_by' => 0,
                'created_at' => '2015-06-16 00:00:00',
                'updated_at' => '2015-06-16 00:00:00',
            ),
            83 => 
            array (
                'id' => 84,
                'number' => 'ជំពូកទី ៤ ',
                'title' => 'ការអនុវត្ដដោយបង្ខំចំពោះសិទ្ធិទាមទារដែលគ្មានគោលបំណងឲ្យសងជាប្រាក់ ',
                'book_id' => 2,
                'kunty_id' => 15,
                'matika_id' => 0,
                'created_by' => 0,
                'updated_by' => 0,
                'created_at' => '2015-06-16 00:00:00',
                'updated_at' => '2015-06-16 00:00:00',
            ),
            84 => 
            array (
                'id' => 85,
                'number' => 'ជំពូកទី ១ ',
                'title' => 'បទប្បញ្ញត្ដិទូទៅ ',
                'book_id' => 2,
                'kunty_id' => 16,
                'matika_id' => 0,
                'created_by' => 0,
                'updated_by' => 0,
                'created_at' => '2015-06-16 00:00:00',
                'updated_at' => '2015-06-16 00:00:00',
            ),
            85 => 
            array (
                'id' => 86,
                'number' => 'ជំពូកទី ២ ',
                'title' => 'ដីកាសម្រេចរក្សាការពារ ',
                'book_id' => 2,
                'kunty_id' => 16,
                'matika_id' => 0,
                'created_by' => 0,
                'updated_by' => 0,
                'created_at' => '2015-06-16 00:00:00',
                'updated_at' => '2015-06-16 00:00:00',
            ),
            86 => 
            array (
                'id' => 87,
                'number' => 'ជំពូកទី ៣ ',
                'title' => 'ការអនុវត្ដរក្សាការពារ ',
                'book_id' => 2,
                'kunty_id' => 16,
                'matika_id' => 0,
                'created_by' => 0,
                'updated_by' => 0,
                'created_at' => '2015-06-16 00:00:00',
                'updated_at' => '2015-06-16 00:00:00',
            ),
            87 => 
            array (
                'id' => 88,
                'number' => 'ជំពូកទោល',
                'title' => 'អវសានប្បញ្ញត្តិ',
                'book_id' => 2,
                'kunty_id' => 18,
                'matika_id' => 0,
                'created_by' => 0,
                'updated_by' => 0,
                'created_at' => '2015-06-16 00:00:00',
                'updated_at' => '2015-06-16 00:00:00',
            ),
            88 => 
            array (
                'id' => 89,
                'number' => 'ជំពូកទី ១ ',
                'title' => 'គោលការណ៍ទូទៅ ',
                'book_id' => 3,
                'kunty_id' => 19,
                'matika_id' => 1,
                'created_by' => 0,
                'updated_by' => 0,
                'created_at' => '2015-06-16 00:00:00',
                'updated_at' => '2015-06-16 00:00:00',
            ),
            89 => 
            array (
                'id' => 90,
                'number' => 'ជំពូកទី ២ ',
                'title' => 'ការអនុវត្ដច្បាប់ព្រហ្មទណ្ឌនៅក្នុងពេលវេលា ',
                'book_id' => 3,
                'kunty_id' => 19,
                'matika_id' => 1,
                'created_by' => 0,
                'updated_by' => 0,
                'created_at' => '2015-06-16 00:00:00',
                'updated_at' => '2015-06-16 00:00:00',
            ),
            90 => 
            array (
                'id' => 91,
                'number' => 'ជំពូកទី ៣ ',
                'title' => 'ការអនុវត្ដច្បាប់ព្រហ្មទណ្ឌកម្ពុជានៅក្នុងលំហ ',
                'book_id' => 3,
                'kunty_id' => 19,
                'matika_id' => 1,
                'created_by' => 0,
                'updated_by' => 0,
                'created_at' => '2015-06-16 00:00:00',
                'updated_at' => '2015-06-16 00:00:00',
            ),
            91 => 
            array (
                'id' => 92,
                'number' => 'ជំពូកទី ១ ',
                'title' => 'បទប្បញ្ញត្ដិទូទៅ ',
                'book_id' => 3,
                'kunty_id' => 19,
                'matika_id' => 2,
                'created_by' => 0,
                'updated_by' => 0,
                'created_at' => '2015-06-16 00:00:00',
                'updated_at' => '2015-06-16 00:00:00',
            ),
            92 => 
            array (
                'id' => 93,
                'number' => 'ជំពូកទី ២ ',
                'title' => 'មូលហេតុនៃការមិនទទួលខុសត្រូវ ឬការសម្រាលនូវ ',
                'book_id' => 3,
                'kunty_id' => 19,
                'matika_id' => 2,
                'created_by' => 0,
                'updated_by' => 0,
                'created_at' => '2015-06-16 00:00:00',
                'updated_at' => '2015-06-16 00:00:00',
            ),
            93 => 
            array (
                'id' => 94,
                'number' => 'ជំពូកទី ៣ ',
                'title' => 'ការទទួលខុសត្រូវព្រហ្មទណ្ឌរបស់អនីតិជន ',
                'book_id' => 3,
                'kunty_id' => 19,
                'matika_id' => 2,
                'created_by' => 0,
                'updated_by' => 0,
                'created_at' => '2015-06-16 00:00:00',
                'updated_at' => '2015-06-16 00:00:00',
            ),
            94 => 
            array (
                'id' => 95,
                'number' => 'ជំពូកទី ៤ ',
                'title' => 'ការទទួលខុសត្រូវព្រហ្មទណ្ឌរបស់នីតិបុគ្គល ',
                'book_id' => 3,
                'kunty_id' => 19,
                'matika_id' => 2,
                'created_by' => 0,
                'updated_by' => 0,
                'created_at' => '2015-06-16 00:00:00',
                'updated_at' => '2015-06-16 00:00:00',
            ),
            95 => 
            array (
                'id' => 96,
                'number' => 'ជំពូកទី ១ ',
                'title' => 'ប្រភេទនៃទោស ',
                'book_id' => 3,
                'kunty_id' => 19,
                'matika_id' => 3,
                'created_by' => 0,
                'updated_by' => 0,
                'created_at' => '2015-06-16 00:00:00',
                'updated_at' => '2015-06-16 00:00:00',
            ),
            96 => 
            array (
                'id' => 97,
                'number' => 'ជំពូកទី ២ ',
                'title' => 'ស្ថានទម្ងន់ទោស និងស្ថានសម្រាលទោស ',
                'book_id' => 3,
                'kunty_id' => 19,
                'matika_id' => 3,
                'created_by' => 0,
                'updated_by' => 0,
                'created_at' => '2015-06-16 00:00:00',
                'updated_at' => '2015-06-16 00:00:00',
            ),
            97 => 
            array (
                'id' => 98,
                'number' => 'ជំពូកទី ៣ ',
                'title' => 'របបនៃការប្រកាសទោស ',
                'book_id' => 3,
                'kunty_id' => 19,
                'matika_id' => 3,
                'created_by' => 0,
                'updated_by' => 0,
                'created_at' => '2015-06-16 00:00:00',
                'updated_at' => '2015-06-16 00:00:00',
            ),
            98 => 
            array (
                'id' => 142,
                'number' => 'ជំពូកទី ២ ',
                'title' => 'មន្រ្ដីនគរបាលយុត្ដិធម៌ ',
                'book_id' => 4,
                'kunty_id' => 26,
                'matika_id' => 19,
                'created_by' => 0,
                'updated_by' => 0,
                'created_at' => '2015-06-16 00:00:00',
                'updated_at' => '2015-06-16 00:00:00',
            ),
            99 => 
            array (
                'id' => 99,
                'number' => 'ជំពូកទី ៤ ',
                'title' => 'វិធានអនុវត្ដនៅក្នុងករណីបទល្មើសត្រួតគ្នា ',
                'book_id' => 3,
                'kunty_id' => 19,
                'matika_id' => 3,
                'created_by' => 0,
                'updated_by' => 0,
                'created_at' => '2015-06-16 00:00:00',
                'updated_at' => '2015-06-16 00:00:00',
            ),
            100 => 
            array (
                'id' => 100,
                'number' => 'ជំពូកទី ៥ ',
                'title' => 'មូលហេតុទូទៅដែលមានផលប៉ះពាល់ដល់ការអនុវត្ដទោស ',
                'book_id' => 3,
                'kunty_id' => 19,
                'matika_id' => 3,
                'created_by' => 0,
                'updated_by' => 0,
                'created_at' => '2015-06-16 00:00:00',
                'updated_at' => '2015-06-16 00:00:00',
            ),
            101 => 
            array (
                'id' => 101,
                'number' => 'ជំពូកទី ៦ ',
                'title' => 'ទោសដែលអាចអនុវត្ដចំពោះអនីតិជន ',
                'book_id' => 3,
                'kunty_id' => 19,
                'matika_id' => 3,
                'created_by' => 0,
                'updated_by' => 0,
                'created_at' => '2015-06-16 00:00:00',
                'updated_at' => '2015-06-16 00:00:00',
            ),
            102 => 
            array (
                'id' => 102,
                'number' => 'ជំពូកទី ៧ ',
                'title' => 'ទោសដែលត្រូវអនុវត្ដចំពោះនីតិបុគ្គល ',
                'book_id' => 3,
                'kunty_id' => 19,
                'matika_id' => 3,
                'created_by' => 0,
                'updated_by' => 0,
                'created_at' => '2015-06-16 00:00:00',
                'updated_at' => '2015-06-16 00:00:00',
            ),
            103 => 
            array (
                'id' => 103,
                'number' => 'ជំពូកទី ១ ',
                'title' => 'បទឧក្រិដ្ឋប្រល័យពូជសាសន៍ ',
                'book_id' => 3,
                'kunty_id' => 20,
                'matika_id' => 4,
                'created_by' => 0,
                'updated_by' => 0,
                'created_at' => '2015-06-16 00:00:00',
                'updated_at' => '2015-06-16 00:00:00',
            ),
            104 => 
            array (
                'id' => 104,
                'number' => 'ជំពូកទី ២ ',
                'title' => 'បទឧក្រិដ្ឋប្រឆាំងមនុស្សជាតិ ',
                'book_id' => 3,
                'kunty_id' => 20,
                'matika_id' => 4,
                'created_by' => 0,
                'updated_by' => 0,
                'created_at' => '2015-06-16 00:00:00',
                'updated_at' => '2015-06-16 00:00:00',
            ),
            105 => 
            array (
                'id' => 105,
                'number' => 'ជំពូកទី ៣ ',
                'title' => 'បទឧក្រិដ្ឋសង្រ្គាម ',
                'book_id' => 3,
                'kunty_id' => 20,
                'matika_id' => 4,
                'created_by' => 0,
                'updated_by' => 0,
                'created_at' => '2015-06-16 00:00:00',
                'updated_at' => '2015-06-16 00:00:00',
            ),
            106 => 
            array (
                'id' => 106,
                'number' => 'ជំពូកទី ១ ',
                'title' => 'ការប៉ះពាល់ដល់ជីវិតមនុស្ស ',
                'book_id' => 3,
                'kunty_id' => 20,
                'matika_id' => 5,
                'created_by' => 0,
                'updated_by' => 0,
                'created_at' => '2015-06-16 00:00:00',
                'updated_at' => '2015-06-16 00:00:00',
            ),
            107 => 
            array (
                'id' => 107,
                'number' => 'ជំពូកទី ២ ',
                'title' => 'ការប៉ះពាល់ដល់បូរណភាពនៃបុគ្គល ',
                'book_id' => 3,
                'kunty_id' => 20,
                'matika_id' => 5,
                'created_by' => 0,
                'updated_by' => 0,
                'created_at' => '2015-06-16 00:00:00',
                'updated_at' => '2015-06-16 00:00:00',
            ),
            108 => 
            array (
                'id' => 108,
                'number' => 'ជំពូកទី ៣ ',
                'title' => 'ការបំពានខាងផ្លូវភេទ ',
                'book_id' => 3,
                'kunty_id' => 20,
                'matika_id' => 5,
                'created_by' => 0,
                'updated_by' => 0,
                'created_at' => '2015-06-16 00:00:00',
                'updated_at' => '2015-06-16 00:00:00',
            ),
            109 => 
            array (
                'id' => 109,
                'number' => 'ជំពូកទី ៤ ',
                'title' => 'ការប៉ះពាល់ដល់សេរីភាព ',
                'book_id' => 3,
                'kunty_id' => 20,
                'matika_id' => 5,
                'created_by' => 0,
                'updated_by' => 0,
                'created_at' => '2015-06-16 00:00:00',
                'updated_at' => '2015-06-16 00:00:00',
            ),
            110 => 
            array (
                'id' => 110,
                'number' => 'ជំពូកទី ៥ ',
                'title' => 'ការប៉ះពាល់ដល់សេចក្ដីថ្លៃថ្នូរ ',
                'book_id' => 3,
                'kunty_id' => 20,
                'matika_id' => 5,
                'created_by' => 0,
                'updated_by' => 0,
                'created_at' => '2015-06-16 00:00:00',
                'updated_at' => '2015-06-16 00:00:00',
            ),
            111 => 
            array (
                'id' => 111,
                'number' => 'ជំពូកទី ៦ ',
                'title' => 'ការប៉ះពាល់ដល់បុគ្គលភាព ',
                'book_id' => 3,
                'kunty_id' => 20,
                'matika_id' => 5,
                'created_by' => 0,
                'updated_by' => 0,
                'created_at' => '2015-06-16 00:00:00',
                'updated_at' => '2015-06-16 00:00:00',
            ),
            112 => 
            array (
                'id' => 112,
                'number' => 'ជំពូកទី ១ ',
                'title' => 'អំពើបោះបង់អនីតិជន ',
                'book_id' => 3,
                'kunty_id' => 20,
                'matika_id' => 6,
                'created_by' => 0,
                'updated_by' => 0,
                'created_at' => '2015-06-16 00:00:00',
                'updated_at' => '2015-06-16 00:00:00',
            ),
            113 => 
            array (
                'id' => 113,
                'number' => 'ជំពូកទី ២ ',
                'title' => 'ការបោះបង់គ្រួសារ ',
                'book_id' => 3,
                'kunty_id' => 20,
                'matika_id' => 6,
                'created_by' => 0,
                'updated_by' => 0,
                'created_at' => '2015-06-16 00:00:00',
                'updated_at' => '2015-06-16 00:00:00',
            ),
            114 => 
            array (
                'id' => 114,
                'number' => 'ជំពូកទី ៣ ',
                'title' => 'ការប៉ះពាល់ដល់ការថែរក្សាអនីតិជន ',
                'book_id' => 3,
                'kunty_id' => 20,
                'matika_id' => 6,
                'created_by' => 0,
                'updated_by' => 0,
                'created_at' => '2015-06-16 00:00:00',
                'updated_at' => '2015-06-16 00:00:00',
            ),
            115 => 
            array (
                'id' => 115,
                'number' => 'ជំពូកទី ៤ ',
                'title' => 'ការប៉ះពាល់ដល់បុត្ដភាព ',
                'book_id' => 3,
                'kunty_id' => 20,
                'matika_id' => 6,
                'created_by' => 0,
                'updated_by' => 0,
                'created_at' => '2015-06-16 00:00:00',
                'updated_at' => '2015-06-16 00:00:00',
            ),
            116 => 
            array (
                'id' => 116,
                'number' => 'ជំពូកទី ៥ ',
                'title' => 'ការដាក់អនីតិជនឲ្យស្ថិតក្នុងស្ថានភាពគ្រោះថ្នាក់ ',
                'book_id' => 3,
                'kunty_id' => 20,
                'matika_id' => 6,
                'created_by' => 0,
                'updated_by' => 0,
                'created_at' => '2015-06-16 00:00:00',
                'updated_at' => '2015-06-16 00:00:00',
            ),
            117 => 
            array (
                'id' => 117,
                'number' => 'ជំពូកទី ៦ ',
                'title' => 'ការប៉ះពាល់ផ្សេងទៀតដល់គ្រួសារ ',
                'book_id' => 3,
                'kunty_id' => 20,
                'matika_id' => 6,
                'created_by' => 0,
                'updated_by' => 0,
                'created_at' => '2015-06-16 00:00:00',
                'updated_at' => '2015-06-16 00:00:00',
            ),
            118 => 
            array (
                'id' => 118,
                'number' => 'ជំពូកទី ១ ',
                'title' => 'ការលួច និងបទល្មើសប្រហាក់ប្រហែល ',
                'book_id' => 3,
                'kunty_id' => 21,
                'matika_id' => 7,
                'created_by' => 0,
                'updated_by' => 0,
                'created_at' => '2015-06-16 00:00:00',
                'updated_at' => '2015-06-16 00:00:00',
            ),
            119 => 
            array (
                'id' => 119,
                'number' => 'ជំពូកទី ២ ',
                'title' => 'ការឆបោក និងអំពើប្រហាក់ប្រហែល ',
                'book_id' => 3,
                'kunty_id' => 21,
                'matika_id' => 7,
                'created_by' => 0,
                'updated_by' => 0,
                'created_at' => '2015-06-16 00:00:00',
                'updated_at' => '2015-06-16 00:00:00',
            ),
            120 => 
            array (
                'id' => 120,
                'number' => 'ជំពូកទី ៣ ',
                'title' => 'ការរំលោភលើទំនុកចិត្ដ និងអំពើប្រហាក់ប្រហែល ',
                'book_id' => 3,
                'kunty_id' => 21,
                'matika_id' => 7,
                'created_by' => 0,
                'updated_by' => 0,
                'created_at' => '2015-06-16 00:00:00',
                'updated_at' => '2015-06-16 00:00:00',
            ),
            121 => 
            array (
                'id' => 121,
                'number' => 'ជំពូកទី ៤ ',
                'title' => 'បទល្មើសបំពេញបន្ថែម ',
                'book_id' => 3,
                'kunty_id' => 21,
                'matika_id' => 7,
                'created_by' => 0,
                'updated_by' => 0,
                'created_at' => '2015-06-16 00:00:00',
                'updated_at' => '2015-06-16 00:00:00',
            ),
            122 => 
            array (
                'id' => 122,
                'number' => 'ជំពូកទី ១ ',
                'title' => 'ការបំផ្លិចបំផ្លាញ ការធ្វើឲ្យទ្រុឌទ្រោម និងការធ្វើឲ្យខូចខាត ',
                'book_id' => 3,
                'kunty_id' => 21,
                'matika_id' => 8,
                'created_by' => 0,
                'updated_by' => 0,
                'created_at' => '2015-06-16 00:00:00',
                'updated_at' => '2015-06-16 00:00:00',
            ),
            123 => 
            array (
                'id' => 123,
                'number' => 'ជំពូកទី ២ ',
                'title' => 'បទល្មើសក្នុងវិស័យព័ត៌មានវិទ្យា ',
                'book_id' => 3,
                'kunty_id' => 21,
                'matika_id' => 8,
                'created_by' => 0,
                'updated_by' => 0,
                'created_at' => '2015-06-16 00:00:00',
                'updated_at' => '2015-06-16 00:00:00',
            ),
            124 => 
            array (
                'id' => 124,
                'number' => 'ជំពូកទី ១ ',
                'title' => 'ការរំលោភបំពានដល់អង្គព្រះមហាក្សត្រ ',
                'book_id' => 3,
                'kunty_id' => 22,
                'matika_id' => 9,
                'created_by' => 0,
                'updated_by' => 0,
                'created_at' => '2015-06-16 00:00:00',
                'updated_at' => '2015-06-16 00:00:00',
            ),
            125 => 
            array (
                'id' => 125,
                'number' => 'ជំពូកទី ២ ',
                'title' => 'ការប៉ះពាល់ដល់សន្ដិសុខនៃរដ្ឋ ',
                'book_id' => 3,
                'kunty_id' => 22,
                'matika_id' => 9,
                'created_by' => 0,
                'updated_by' => 0,
                'created_at' => '2015-06-16 00:00:00',
                'updated_at' => '2015-06-16 00:00:00',
            ),
            126 => 
            array (
                'id' => 126,
                'number' => 'ជំពូកទី ៣ ',
                'title' => 'ការប៉ះពាល់ដល់សន្ដិសុខសាធារណៈ ',
                'book_id' => 3,
                'kunty_id' => 22,
                'matika_id' => 9,
                'created_by' => 0,
                'updated_by' => 0,
                'created_at' => '2015-06-16 00:00:00',
                'updated_at' => '2015-06-16 00:00:00',
            ),
            127 => 
            array (
                'id' => 127,
                'number' => 'ជំពូកទី ៤ ',
                'title' => 'ការប៉ះពាល់ដល់អាជ្ញាធររបស់រដ្ឋ ',
                'book_id' => 3,
                'kunty_id' => 22,
                'matika_id' => 9,
                'created_by' => 0,
                'updated_by' => 0,
                'created_at' => '2015-06-16 00:00:00',
                'updated_at' => '2015-06-16 00:00:00',
            ),
            128 => 
            array (
                'id' => 128,
                'number' => 'ជំពូកទី ៥ ',
                'title' => 'ការប៉ះពាល់ដល់សាសនារបស់រដ្ឋ ',
                'book_id' => 3,
                'kunty_id' => 22,
                'matika_id' => 9,
                'created_by' => 0,
                'updated_by' => 0,
                'created_at' => '2015-06-16 00:00:00',
                'updated_at' => '2015-06-16 00:00:00',
            ),
            129 => 
            array (
                'id' => 129,
                'number' => 'ជំពូកទី ១ ',
                'title' => 'ការប៉ះពាល់ដល់ស្ថាប័នយុត្ដិធម៌ ',
                'book_id' => 3,
                'kunty_id' => 22,
                'matika_id' => 10,
                'created_by' => 0,
                'updated_by' => 0,
                'created_at' => '2015-06-16 00:00:00',
                'updated_at' => '2015-06-16 00:00:00',
            ),
            130 => 
            array (
                'id' => 130,
                'number' => 'ជំពូកទី ២ ',
                'title' => 'ការប៉ះពាល់ដល់សកម្មភាពរបស់តុលាការ ',
                'book_id' => 3,
                'kunty_id' => 22,
                'matika_id' => 10,
                'created_by' => 0,
                'updated_by' => 0,
                'created_at' => '2015-06-16 00:00:00',
                'updated_at' => '2015-06-16 00:00:00',
            ),
            131 => 
            array (
                'id' => 131,
                'number' => 'ជំពូកទី ៣ ',
                'title' => 'បទល្មើសទាក់ទងដល់ការឃុំឃាំង ',
                'book_id' => 3,
                'kunty_id' => 22,
                'matika_id' => 10,
                'created_by' => 0,
                'updated_by' => 0,
                'created_at' => '2015-06-16 00:00:00',
                'updated_at' => '2015-06-16 00:00:00',
            ),
            132 => 
            array (
                'id' => 132,
                'number' => 'ជំពូកទី ៤ ',
                'title' => 'ការបំពានលើសេចក្ដីសម្រេចខ្លះៗ របស់តុលាការ ',
                'book_id' => 3,
                'kunty_id' => 22,
                'matika_id' => 10,
                'created_by' => 0,
                'updated_by' => 0,
                'created_at' => '2015-06-16 00:00:00',
                'updated_at' => '2015-06-16 00:00:00',
            ),
            133 => 
            array (
                'id' => 133,
                'number' => 'ជំពូកទី ១ ',
                'title' => 'ការប៉ះពាល់ដល់រដ្ឋបាលសាធារណៈ ដោយអ្នកតំណាងអាជ្ញាធរសាធារណៈ ',
                'book_id' => 3,
                'kunty_id' => 22,
                'matika_id' => 11,
                'created_by' => 0,
                'updated_by' => 0,
                'created_at' => '2015-06-16 00:00:00',
                'updated_at' => '2015-06-16 00:00:00',
            ),
            134 => 
            array (
                'id' => 134,
                'number' => 'ជំពូកទី ២ ',
                'title' => 'ការប៉ះពាល់ដល់រដ្ឋបាលសាធារណៈ ធ្វើឡើងដោយបុគ្គលឯកជន ',
                'book_id' => 3,
                'kunty_id' => 22,
                'matika_id' => 11,
                'created_by' => 0,
                'updated_by' => 0,
                'created_at' => '2015-06-16 00:00:00',
                'updated_at' => '2015-06-16 00:00:00',
            ),
            135 => 
            array (
                'id' => 135,
                'number' => 'ជំពូកទី ១ ',
                'title' => 'ការក្លែងបន្លំ ',
                'book_id' => 3,
                'kunty_id' => 22,
                'matika_id' => 12,
                'created_by' => 0,
                'updated_by' => 0,
                'created_at' => '2015-06-16 00:00:00',
                'updated_at' => '2015-06-16 00:00:00',
            ),
            136 => 
            array (
                'id' => 136,
                'number' => 'ជំពូកទី ២ ',
                'title' => 'ការក្លែងឯកសាររបស់អាជ្ញាធរសាធារណៈ ',
                'book_id' => 3,
                'kunty_id' => 22,
                'matika_id' => 12,
                'created_by' => 0,
                'updated_by' => 0,
                'created_at' => '2015-06-16 00:00:00',
                'updated_at' => '2015-06-16 00:00:00',
            ),
            137 => 
            array (
                'id' => 137,
                'number' => 'ជំពូកទី ១ ',
                'title' => 'បទប្បញ្ញត្ដិទូទៅ ',
                'book_id' => 4,
                'kunty_id' => 26,
                'matika_id' => 16,
                'created_by' => 0,
                'updated_by' => 0,
                'created_at' => '2015-06-16 00:00:00',
                'updated_at' => '2015-06-16 00:00:00',
            ),
            138 => 
            array (
                'id' => 138,
                'number' => 'ជំពូកទី ២ ',
                'title' => 'មុខការរបស់អគ្គព្រះរាជអាជ្ញាអមតុលាការកំពូល ',
                'book_id' => 4,
                'kunty_id' => 26,
                'matika_id' => 16,
                'created_by' => 0,
                'updated_by' => 0,
                'created_at' => '2015-06-16 00:00:00',
                'updated_at' => '2015-06-16 00:00:00',
            ),
            139 => 
            array (
                'id' => 139,
                'number' => 'ជំពូកទី ៣ ',
                'title' => 'មុខការរបស់អគ្គព្រះរាជអាជ្ញា អមសាលាឧទ្ធរណ៍ ',
                'book_id' => 4,
                'kunty_id' => 26,
                'matika_id' => 16,
                'created_by' => 0,
                'updated_by' => 0,
                'created_at' => '2015-06-16 00:00:00',
                'updated_at' => '2015-06-16 00:00:00',
            ),
            140 => 
            array (
                'id' => 140,
                'number' => 'ជំពូកទី ៤ ',
                'title' => 'មុខការរបស់ព្រះរាជអាជ្ញាអមសាលាដំបូង ',
                'book_id' => 4,
                'kunty_id' => 26,
                'matika_id' => 16,
                'created_by' => 0,
                'updated_by' => 0,
                'created_at' => '2015-06-16 00:00:00',
                'updated_at' => '2015-06-16 00:00:00',
            ),
            141 => 
            array (
                'id' => 141,
                'number' => 'ជំពូកទី ១ ',
                'title' => 'បទប្បញ្ញត្ដិទូទៅ ',
                'book_id' => 4,
                'kunty_id' => 26,
                'matika_id' => 19,
                'created_by' => 0,
                'updated_by' => 0,
                'created_at' => '2015-06-16 00:00:00',
                'updated_at' => '2015-06-16 00:00:00',
            ),
            142 => 
            array (
                'id' => 143,
                'number' => 'ជំពូកទី ៣ ',
                'title' => 'ភ្នាក់ងារនគរបាលយុត្ដិធម៌ ',
                'book_id' => 4,
                'kunty_id' => 26,
                'matika_id' => 19,
                'created_by' => 0,
                'updated_by' => 0,
                'created_at' => '2015-06-16 00:00:00',
                'updated_at' => '2015-06-16 00:00:00',
            ),
            143 => 
            array (
                'id' => 144,
                'number' => 'ជំពូកទី ៤ ',
                'title' => 'ការកំណត់សមត្ថកិច្ចរបស់នគរបាលជាតិ និងកងរាជអាវុធហត្ថ ',
                'book_id' => 4,
                'kunty_id' => 26,
                'matika_id' => 19,
                'created_by' => 0,
                'updated_by' => 0,
                'created_at' => '2015-06-16 00:00:00',
                'updated_at' => '2015-06-16 00:00:00',
            ),
            144 => 
            array (
                'id' => 145,
                'number' => 'ជំពូកទី ៥ ',
                'title' => 'មន្រ្ដីរាជការ និងភ្នាក់ងារសាធារណៈដទៃទៀត ដែលមាននីតិសម្បទាពិសេសសម្រាប់ពិនិត្យ ',
                'book_id' => 4,
                'kunty_id' => 26,
                'matika_id' => 19,
                'created_by' => 0,
                'updated_by' => 0,
                'created_at' => '2015-06-16 00:00:00',
                'updated_at' => '2015-06-16 00:00:00',
            ),
            145 => 
            array (
                'id' => 146,
                'number' => 'ជំពូកទី ១ ',
                'title' => 'បទឧក្រិដ្ឋ ឬបទមជ្ឈិមជាក់ស្ដែង ',
                'book_id' => 4,
                'kunty_id' => 27,
                'matika_id' => 21,
                'created_by' => 0,
                'updated_by' => 0,
                'created_at' => '2015-06-16 00:00:00',
                'updated_at' => '2015-06-16 00:00:00',
            ),
            146 => 
            array (
                'id' => 147,
                'number' => 'ជំពូកទី ២ ',
                'title' => 'វិធានការស្រាវជ្រាវ ',
                'book_id' => 4,
                'kunty_id' => 27,
                'matika_id' => 21,
                'created_by' => 0,
                'updated_by' => 0,
                'created_at' => '2015-06-16 00:00:00',
                'updated_at' => '2015-06-16 00:00:00',
            ),
            147 => 
            array (
                'id' => 148,
                'number' => 'ជំពូកទី ៣ ',
                'title' => 'ការឃាត់ខ្លួន ',
                'book_id' => 4,
                'kunty_id' => 27,
                'matika_id' => 21,
                'created_by' => 0,
                'updated_by' => 0,
                'created_at' => '2015-06-16 00:00:00',
                'updated_at' => '2015-06-16 00:00:00',
            ),
            148 => 
            array (
                'id' => 149,
                'number' => 'ជំពូកទី ៤ ',
                'title' => 'ការបញ្ជូនខ្លួន ',
                'book_id' => 4,
                'kunty_id' => 27,
                'matika_id' => 21,
                'created_by' => 0,
                'updated_by' => 0,
                'created_at' => '2015-06-16 00:00:00',
                'updated_at' => '2015-06-16 00:00:00',
            ),
            149 => 
            array (
                'id' => 150,
                'number' => 'ជំពូកទី ៥ ',
                'title' => 'វិធានទាក់ទងនឹងការស៊ើបអង្កេតករណីជាក់ស្ដែង ',
                'book_id' => 4,
                'kunty_id' => 27,
                'matika_id' => 21,
                'created_by' => 0,
                'updated_by' => 0,
                'created_at' => '2015-06-16 00:00:00',
                'updated_at' => '2015-06-16 00:00:00',
            ),
            150 => 
            array (
                'id' => 151,
                'number' => 'ជំពូកទី ១ ',
                'title' => 'បទប្បញ្ញត្ដិទូទៅ ',
                'book_id' => 4,
                'kunty_id' => 28,
                'matika_id' => 24,
                'created_by' => 0,
                'updated_by' => 0,
                'created_at' => '2015-06-16 00:00:00',
                'updated_at' => '2015-06-16 00:00:00',
            ),
            151 => 
            array (
                'id' => 152,
                'number' => 'ជំពូកទី ២ ',
                'title' => 'ការស្រាវជ្រាវរបស់ចៅក្រមស៊ើបសួរ ',
                'book_id' => 4,
                'kunty_id' => 28,
                'matika_id' => 24,
                'created_by' => 0,
                'updated_by' => 0,
                'created_at' => '2015-06-16 00:00:00',
                'updated_at' => '2015-06-16 00:00:00',
            ),
            152 => 
            array (
                'id' => 153,
                'number' => 'ជំពូកទី ៣ ',
                'title' => 'វិធានការនិរន្ដរាយ ',
                'book_id' => 4,
                'kunty_id' => 28,
                'matika_id' => 24,
                'created_by' => 0,
                'updated_by' => 0,
                'created_at' => '2015-06-16 00:00:00',
                'updated_at' => '2015-06-16 00:00:00',
            ),
            153 => 
            array (
                'id' => 154,
                'number' => 'ជំពូកទី ៤ ',
                'title' => 'ការកោះហៅ និងការជូនដំណឹង ',
                'book_id' => 4,
                'kunty_id' => 28,
                'matika_id' => 24,
                'created_by' => 0,
                'updated_by' => 0,
                'created_at' => '2015-06-16 00:00:00',
                'updated_at' => '2015-06-16 00:00:00',
            ),
            154 => 
            array (
                'id' => 155,
                'number' => 'ជំពូកទី ៥ ',
                'title' => 'ការបិទការស៊ើបសួរ ',
                'book_id' => 4,
                'kunty_id' => 28,
                'matika_id' => 24,
                'created_by' => 0,
                'updated_by' => 0,
                'created_at' => '2015-06-16 00:00:00',
                'updated_at' => '2015-06-16 00:00:00',
            ),
            155 => 
            array (
                'id' => 156,
                'number' => 'ជំពូកទី ៦ ',
                'title' => 'មោឃភាពនៃការស៊ើបសួរ ',
                'book_id' => 4,
                'kunty_id' => 28,
                'matika_id' => 24,
                'created_by' => 0,
                'updated_by' => 0,
                'created_at' => '2015-06-16 00:00:00',
                'updated_at' => '2015-06-16 00:00:00',
            ),
            156 => 
            array (
                'id' => 157,
                'number' => 'ជំពូកទី ១ ',
                'title' => 'បទប្បញ្ញត្ដិទូទៅ ',
                'book_id' => 4,
                'kunty_id' => 28,
                'matika_id' => 25,
                'created_by' => 0,
                'updated_by' => 0,
                'created_at' => '2015-06-16 00:00:00',
                'updated_at' => '2015-06-16 00:00:00',
            ),
            157 => 
            array (
                'id' => 158,
                'number' => 'ជំពូកទី ២ ',
                'title' => 'បណ្ដឹងឧទ្ធរណ៍ចំពោះដីការបស់ចៅក្រមស៊ើបសួរ ',
                'book_id' => 4,
                'kunty_id' => 28,
                'matika_id' => 25,
                'created_by' => 0,
                'updated_by' => 0,
                'created_at' => '2015-06-16 00:00:00',
                'updated_at' => '2015-06-16 00:00:00',
            ),
            158 => 
            array (
                'id' => 159,
                'number' => 'ជំពូកទី ៣ ',
                'title' => 'ការឃុំខ្លួនបណ្ដោះអាសន្ន ',
                'book_id' => 4,
                'kunty_id' => 28,
                'matika_id' => 25,
                'created_by' => 0,
                'updated_by' => 0,
                'created_at' => '2015-06-16 00:00:00',
                'updated_at' => '2015-06-16 00:00:00',
            ),
            159 => 
            array (
                'id' => 160,
                'number' => 'ជំពូកទី ៤ ',
                'title' => 'មោឃភាព ',
                'book_id' => 4,
                'kunty_id' => 28,
                'matika_id' => 25,
                'created_by' => 0,
                'updated_by' => 0,
                'created_at' => '2015-06-16 00:00:00',
                'updated_at' => '2015-06-16 00:00:00',
            ),
            160 => 
            array (
                'id' => 161,
                'number' => 'ជំពូកទី ៥ ',
                'title' => 'អំណាចផ្ទាល់ខ្លួនរបស់ប្រធានសភាស៊ើបសួរ ',
                'book_id' => 4,
                'kunty_id' => 28,
                'matika_id' => 25,
                'created_by' => 0,
                'updated_by' => 0,
                'created_at' => '2015-06-16 00:00:00',
                'updated_at' => '2015-06-16 00:00:00',
            ),
            161 => 
            array (
                'id' => 162,
                'number' => 'ជំពូកទី ១ ',
                'title' => 'សមត្ថកិច្ច និងការប្ដឹងទៅតុលាការ ',
                'book_id' => 4,
                'kunty_id' => 29,
                'matika_id' => 26,
                'created_by' => 0,
                'updated_by' => 0,
                'created_at' => '2015-06-16 00:00:00',
                'updated_at' => '2015-06-16 00:00:00',
            ),
            162 => 
            array (
                'id' => 163,
                'number' => 'ជំពូកទី ២ ',
                'title' => 'ការចូលខ្លួនរបស់ភាគី ',
                'book_id' => 4,
                'kunty_id' => 30,
                'matika_id' => 0,
                'created_by' => 0,
                'updated_by' => 0,
                'created_at' => '2015-06-16 00:00:00',
                'updated_at' => '2015-06-16 00:00:00',
            ),
            163 => 
            array (
                'id' => 164,
                'number' => 'ជំពូកទី ៣ ',
                'title' => 'ការពិភាក្សាដេញដោល ',
                'book_id' => 4,
                'kunty_id' => 30,
                'matika_id' => 0,
                'created_by' => 0,
                'updated_by' => 0,
                'created_at' => '2015-06-16 00:00:00',
                'updated_at' => '2015-06-16 00:00:00',
            ),
            164 => 
            array (
                'id' => 165,
                'number' => 'ជំពូកទី ៤ ',
                'title' => 'សេចក្ដីសម្រេច ',
                'book_id' => 4,
                'kunty_id' => 30,
                'matika_id' => 0,
                'created_by' => 0,
                'updated_by' => 0,
                'created_at' => '2015-06-16 00:00:00',
                'updated_at' => '2015-06-16 00:00:00',
            ),
            165 => 
            array (
                'id' => 166,
                'number' => 'ជំពូកទី ១ ',
                'title' => 'សមត្ថកិច្ចរបស់សភាព្រហ្មទណ្ឌនៃសាលាឧទ្ធរណ៍ ',
                'book_id' => 4,
                'kunty_id' => 30,
                'matika_id' => 27,
                'created_by' => 0,
                'updated_by' => 0,
                'created_at' => '2015-06-16 00:00:00',
                'updated_at' => '2015-06-16 00:00:00',
            ),
            166 => 
            array (
                'id' => 167,
                'number' => 'ជំពូកទី ២ ',
                'title' => 'ភាពដែលអាចទទួលយកបាននៃបណ្ដឹងឧទ្ធរណ៍ ',
                'book_id' => 4,
                'kunty_id' => 30,
                'matika_id' => 27,
                'created_by' => 0,
                'updated_by' => 0,
                'created_at' => '2015-06-16 00:00:00',
                'updated_at' => '2015-06-16 00:00:00',
            ),
            167 => 
            array (
                'id' => 168,
                'number' => 'ជំពូកទី ៣ ',
                'title' => 'នីតិវិធីនៅចំពោះមុខសាលាឧទ្ធរណ៍ ',
                'book_id' => 4,
                'kunty_id' => 30,
                'matika_id' => 27,
                'created_by' => 0,
                'updated_by' => 0,
                'created_at' => '2015-06-16 00:00:00',
                'updated_at' => '2015-06-16 00:00:00',
            ),
            168 => 
            array (
                'id' => 169,
                'number' => 'ជំពូកទី ៤ ',
                'title' => 'អានុភាពនៃបណ្ដឹងឧទ្ធរណ៍ ',
                'book_id' => 4,
                'kunty_id' => 30,
                'matika_id' => 27,
                'created_by' => 0,
                'updated_by' => 0,
                'created_at' => '2015-06-16 00:00:00',
                'updated_at' => '2015-06-16 00:00:00',
            ),
            169 => 
            array (
                'id' => 170,
                'number' => 'ជំពូកទី ៥ ',
                'title' => 'បណ្ដឹងទាស់ចំពោះសាលដីកាចេញដោយកំបាំងមុខ ',
                'book_id' => 4,
                'kunty_id' => 30,
                'matika_id' => 27,
                'created_by' => 0,
                'updated_by' => 0,
                'created_at' => '2015-06-16 00:00:00',
                'updated_at' => '2015-06-16 00:00:00',
            ),
            170 => 
            array (
                'id' => 171,
                'number' => 'ជំពូកទី ១ ',
                'title' => 'វិធានទាក់ទងនឹងការឃុំខ្លួន ',
                'book_id' => 4,
                'kunty_id' => 33,
                'matika_id' => 36,
                'created_by' => 0,
                'updated_by' => 0,
                'created_at' => '2015-06-16 00:00:00',
                'updated_at' => '2015-06-16 00:00:00',
            ),
            171 => 
            array (
                'id' => 172,
                'number' => 'ជំពូកទី ២ ',
                'title' => 'ការដោះលែងដោយមានលក្ខខណ្ឌ ',
                'book_id' => 4,
                'kunty_id' => 33,
                'matika_id' => 36,
                'created_by' => 0,
                'updated_by' => 0,
                'created_at' => '2015-06-16 00:00:00',
                'updated_at' => '2015-06-16 00:00:00',
            ),
            172 => 
            array (
                'id' => 173,
                'number' => 'ជំពូកទី ១ ',
                'title' => 'ការផ្ដល់នីតិសម្បទាឡើងវិញតាមផ្លូវតុលាការ ',
                'book_id' => 4,
                'kunty_id' => 33,
                'matika_id' => 38,
                'created_by' => 0,
                'updated_by' => 0,
                'created_at' => '2015-06-16 00:00:00',
                'updated_at' => '2015-06-16 00:00:00',
            ),
            173 => 
            array (
                'id' => 174,
                'number' => 'ជំពូកទី ២ ',
                'title' => 'ការមាននីតិសម្បទាឡើងវិញដោយពេញលក្ខណៈច្បាប់ ',
                'book_id' => 4,
                'kunty_id' => 33,
                'matika_id' => 38,
                'created_by' => 0,
                'updated_by' => 0,
                'created_at' => '2015-06-16 00:00:00',
                'updated_at' => '2015-06-16 00:00:00',
            ),
            174 => 
            array (
                'id' => 175,
                'number' => 'ជំពូកទី ១ ',
                'title' => 'ចៅក្រម ',
                'book_id' => 4,
                'kunty_id' => 34,
                'matika_id' => 41,
                'created_by' => 0,
                'updated_by' => 0,
                'created_at' => '2015-06-16 00:00:00',
                'updated_at' => '2015-06-16 00:00:00',
            ),
            175 => 
            array (
                'id' => 176,
                'number' => 'ជំពូកទី ២ ',
                'title' => 'បត្យាប័ន ',
                'book_id' => 4,
                'kunty_id' => 34,
                'matika_id' => 41,
                'created_by' => 0,
                'updated_by' => 0,
                'created_at' => '2015-06-16 00:00:00',
                'updated_at' => '2015-06-16 00:00:00',
            ),
            176 => 
            array (
                'id' => 177,
                'number' => 'ជំពូកទី ៣ ',
                'title' => 'ការឆ្លងកាត់ ',
                'book_id' => 4,
                'kunty_id' => 34,
                'matika_id' => 41,
                'created_by' => 0,
                'updated_by' => 0,
                'created_at' => '2015-06-16 00:00:00',
                'updated_at' => '2015-06-16 00:00:00',
            ),
            177 => 
            array (
                'id' => 178,
                'number' => 'ជំពូកទី ៤ ',
                'title' => 'បទប្បញ្ញត្ដិដោយឡែកស្ដីពីការប្រតិបត្ដិទោសមួយចំនួន ',
                'book_id' => 4,
                'kunty_id' => 34,
                'matika_id' => 41,
                'created_by' => 0,
                'updated_by' => 0,
                'created_at' => '2015-06-16 00:00:00',
                'updated_at' => '2015-06-16 00:00:00',
            ),
            178 => 
            array (
                'id' => 179,
                'number' => 'ជំពូកទី ៥ ',
                'title' => 'នីតិបុគ្គល ',
                'book_id' => 4,
                'kunty_id' => 34,
                'matika_id' => 41,
                'created_by' => 0,
                'updated_by' => 0,
                'created_at' => '2015-06-16 00:00:00',
                'updated_at' => '2015-06-16 00:00:00',
            ),
            179 => 
            array (
                'id' => 180,
                'number' => 'ជំពូកទី ១ ',
                'title' => 'ការបាត់បង់លិខិតស្នាម ',
                'book_id' => 4,
                'kunty_id' => 34,
                'matika_id' => 42,
                'created_by' => 0,
                'updated_by' => 0,
                'created_at' => '2015-06-16 00:00:00',
                'updated_at' => '2015-06-16 00:00:00',
            ),
            180 => 
            array (
                'id' => 181,
                'number' => 'ជំពូកទី ២ ',
                'title' => 'ការបកស្រាយ និងការកែតម្រូវសេចក្ដីសម្រេច ',
                'book_id' => 4,
                'kunty_id' => 34,
                'matika_id' => 42,
                'created_by' => 0,
                'updated_by' => 0,
                'created_at' => '2015-06-16 00:00:00',
                'updated_at' => '2015-06-16 00:00:00',
            ),
        ));
        
        
    }
}