<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;

class CountesiesTableSeeder extends Seeder
{

    /**
     * Auto generated seed file
     *
     * @return void
     */
    public function run()
    {
        

        \DB::table('countesies')->delete();
        
        \DB::table('countesies')->insert(array (
            0 => 
            array (
                'id' => 1,
                'name' => 'ឧកញ៉ា',
                'desp' => '1',
                'tpid' => '0',
                'pid' => 0,
                'cids' => NULL,
                'image' => NULL,
                'record_index' => NULL,
                'active' => NULL,
                'created_at' => '2023-09-09 04:15:54',
                'updated_at' => '2023-09-09 04:15:54',
                'deleted_at' => NULL,
                'prefix' => NULL,
            ),
            1 => 
            array (
                'id' => 2,
                'name' => 'ឯកឧត្តម',
                'desp' => '2',
                'tpid' => '0',
                'pid' => 0,
                'cids' => NULL,
                'image' => NULL,
                'record_index' => NULL,
                'active' => NULL,
                'created_at' => '2023-09-09 04:15:54',
                'updated_at' => '2023-09-09 04:15:54',
                'deleted_at' => NULL,
                'prefix' => NULL,
            ),
            2 => 
            array (
                'id' => 3,
                'name' => 'លោក',
                'desp' => '3',
                'tpid' => '0',
                'pid' => 0,
                'cids' => NULL,
                'image' => NULL,
                'record_index' => NULL,
                'active' => NULL,
                'created_at' => '2023-09-09 04:15:54',
                'updated_at' => '2023-09-09 04:15:54',
                'deleted_at' => NULL,
                'prefix' => NULL,
            ),
            3 => 
            array (
                'id' => 4,
                'name' => 'លោកស្រី',
                'desp' => '4',
                'tpid' => '0',
                'pid' => 0,
                'cids' => NULL,
                'image' => NULL,
                'record_index' => NULL,
                'active' => NULL,
                'created_at' => '2023-09-09 04:15:54',
                'updated_at' => '2023-09-09 04:15:54',
                'deleted_at' => NULL,
                'prefix' => NULL,
            ),
            4 => 
            array (
                'id' => 5,
                'name' => 'កញ្ញា',
                'desp' => '5',
                'tpid' => '0',
                'pid' => 0,
                'cids' => NULL,
                'image' => NULL,
                'record_index' => NULL,
                'active' => NULL,
                'created_at' => '2023-09-09 04:15:54',
                'updated_at' => '2023-09-09 04:15:54',
                'deleted_at' => NULL,
                'prefix' => NULL,
            ),
            5 => 
            array (
                'id' => 6,
                'name' => 'លោកជំទាវ',
                'desp' => '6',
                'tpid' => '0',
                'pid' => 0,
                'cids' => NULL,
                'image' => NULL,
                'record_index' => NULL,
                'active' => NULL,
                'created_at' => '2023-09-09 04:15:54',
                'updated_at' => '2023-09-09 04:15:54',
                'deleted_at' => NULL,
                'prefix' => NULL,
            ),
            6 => 
            array (
                'id' => 7,
                'name' => 'សម្តេច',
                'desp' => '7',
                'tpid' => '0',
                'pid' => 0,
                'cids' => NULL,
                'image' => NULL,
                'record_index' => NULL,
                'active' => NULL,
                'created_at' => '2023-09-09 04:15:54',
                'updated_at' => '2023-09-09 04:15:54',
                'deleted_at' => NULL,
                'prefix' => NULL,
            ),
            7 => 
            array (
                'id' => 8,
                'name' => 'ព្រះអង្គម្ចាស់',
                'desp' => '8',
                'tpid' => '0',
                'pid' => 0,
                'cids' => NULL,
                'image' => NULL,
                'record_index' => NULL,
                'active' => NULL,
                'created_at' => '2023-09-09 04:15:54',
                'updated_at' => '2023-09-09 04:15:54',
                'deleted_at' => NULL,
                'prefix' => NULL,
            ),
            8 => 
            array (
                'id' => 9,
                'name' => 'ព្រះអង្គម្ចាស់ក្សត្រី',
                'desp' => '9',
                'tpid' => '0',
                'pid' => 0,
                'cids' => NULL,
                'image' => NULL,
                'record_index' => NULL,
                'active' => NULL,
                'created_at' => '2023-09-09 04:15:54',
                'updated_at' => '2023-09-09 04:15:54',
                'deleted_at' => NULL,
                'prefix' => NULL,
            ),
            9 => 
            array (
                'id' => 10,
                'name' => 'សម្ដេចអគ្គមហាសេនាបតីតេជោ',
                'desp' => '10',
                'tpid' => '0',
                'pid' => 0,
                'cids' => NULL,
                'image' => NULL,
                'record_index' => NULL,
                'active' => NULL,
                'created_at' => '2023-09-09 04:15:54',
                'updated_at' => '2023-09-09 04:15:54',
                'deleted_at' => NULL,
                'prefix' => NULL,
            ),
            10 => 
            array (
                'id' => 11,
                'name' => 'លោកឧកញ៉ា',
                'desp' => '11',
                'tpid' => '0',
                'pid' => 0,
                'cids' => NULL,
                'image' => NULL,
                'record_index' => NULL,
                'active' => NULL,
                'created_at' => '2023-09-09 04:15:54',
                'updated_at' => '2023-09-09 04:15:54',
                'deleted_at' => NULL,
                'prefix' => NULL,
            ),
            11 => 
            array (
                'id' => 12,
                'name' => 'អ្នកឧកញ៉ា',
                'desp' => '12',
                'tpid' => '0',
                'pid' => 0,
                'cids' => NULL,
                'image' => NULL,
                'record_index' => NULL,
                'active' => NULL,
                'created_at' => '2023-09-09 04:15:54',
                'updated_at' => '2023-09-09 04:15:54',
                'deleted_at' => NULL,
                'prefix' => NULL,
            ),
            12 => 
            array (
                'id' => 13,
                'name' => 'ព្រះមហាក្សត្រ',
                'desp' => '13',
                'tpid' => '0',
                'pid' => 0,
                'cids' => NULL,
                'image' => NULL,
                'record_index' => NULL,
                'active' => NULL,
                'created_at' => '2023-09-09 04:15:54',
                'updated_at' => '2023-09-09 04:15:54',
                'deleted_at' => NULL,
                'prefix' => NULL,
            ),
            13 => 
            array (
                'id' => 14,
                'name' => 'សម្ដេចពញ្ញាចក្រី',
                'desp' => '14',
                'tpid' => '0',
                'pid' => 0,
                'cids' => NULL,
                'image' => NULL,
                'record_index' => NULL,
                'active' => NULL,
                'created_at' => '2023-09-09 04:15:54',
                'updated_at' => '2023-09-09 04:15:54',
                'deleted_at' => NULL,
                'prefix' => NULL,
            ),
            14 => 
            array (
                'id' => 15,
                'name' => 'សម្ដេចមហាពោធិសា',
                'desp' => '15',
                'tpid' => '0',
                'pid' => 0,
                'cids' => NULL,
                'image' => NULL,
                'record_index' => NULL,
                'active' => NULL,
                'created_at' => '2023-09-09 04:15:54',
                'updated_at' => '2023-09-09 04:15:54',
                'deleted_at' => NULL,
                'prefix' => NULL,
            ),
            15 => 
            array (
                'id' => 16,
                'name' => 'សម្ដេចក្រលាហោម',
                'desp' => '16',
                'tpid' => '0',
                'pid' => 0,
                'cids' => NULL,
                'image' => NULL,
                'record_index' => NULL,
                'active' => NULL,
                'created_at' => '2023-09-09 04:15:54',
                'updated_at' => '2023-09-09 04:15:54',
                'deleted_at' => NULL,
                'prefix' => NULL,
            ),
            16 => 
            array (
                'id' => 17,
                'name' => 'ឯកឧត្តមបណ្ឌិតសភាចារ្យ',
                'desp' => '17',
                'tpid' => '0',
                'pid' => 0,
                'cids' => NULL,
                'image' => NULL,
                'record_index' => NULL,
                'active' => NULL,
                'created_at' => '2023-09-09 04:15:54',
                'updated_at' => '2023-09-09 04:15:54',
                'deleted_at' => NULL,
                'prefix' => NULL,
            ),
            17 => 
            array (
                'id' => 18,
                'name' => 'មន្ត្រី',
                'desp' => '18',
                'tpid' => '0',
                'pid' => 0,
                'cids' => NULL,
                'image' => NULL,
                'record_index' => NULL,
                'active' => NULL,
                'created_at' => '2023-09-09 04:15:54',
                'updated_at' => '2023-09-09 04:15:54',
                'deleted_at' => NULL,
                'prefix' => NULL,
            ),
            18 => 
            array (
                'id' => 19,
                'name' => 'នាង',
                'desp' => '19',
                'tpid' => '0',
                'pid' => 0,
                'cids' => NULL,
                'image' => NULL,
                'record_index' => NULL,
                'active' => NULL,
                'created_at' => '2023-09-09 04:15:54',
                'updated_at' => '2023-09-09 04:15:54',
                'deleted_at' => NULL,
                'prefix' => NULL,
            ),
            19 => 
            array (
                'id' => 20,
                'name' => 'លោកជំទាវកតិព្រឹទ្ធបណ្ឌិត',
                'desp' => '20',
                'tpid' => '0',
                'pid' => 0,
                'cids' => NULL,
                'image' => NULL,
                'record_index' => NULL,
                'active' => NULL,
                'created_at' => '2023-09-09 04:15:54',
                'updated_at' => '2023-09-09 04:15:54',
                'deleted_at' => NULL,
                'prefix' => NULL,
            ),
            20 => 
            array (
                'id' => 21,
                'name' => 'បណ្ឌិត',
                'desp' => '21',
                'tpid' => '0',
                'pid' => 0,
                'cids' => NULL,
                'image' => NULL,
                'record_index' => NULL,
                'active' => NULL,
                'created_at' => '2023-09-09 04:15:54',
                'updated_at' => '2023-09-09 04:15:54',
                'deleted_at' => NULL,
                'prefix' => NULL,
            ),
            21 => 
            array (
                'id' => 22,
                'name' => 'អ្នកស្រី',
                'desp' => 'អ្នកស្រី',
                'tpid' => '0',
                'pid' => 0,
                'cids' => NULL,
                'image' => NULL,
                'record_index' => NULL,
                'active' => NULL,
                'created_at' => '2023-09-09 04:15:54',
                'updated_at' => '2023-09-09 04:15:54',
                'deleted_at' => NULL,
                'prefix' => NULL,
            ),
            22 => 
            array (
                'id' => 23,
                'name' => 'អ្នកនាង',
                'desp' => 'អ្នកនាង',
                'tpid' => '0',
                'pid' => 0,
                'cids' => NULL,
                'image' => NULL,
                'record_index' => NULL,
                'active' => NULL,
                'created_at' => '2023-09-09 04:15:54',
                'updated_at' => '2023-09-09 04:15:54',
                'deleted_at' => NULL,
                'prefix' => NULL,
            ),
            23 => 
            array (
                'id' => 24,
                'name' => 'កុមារា',
                'desp' => 'កុមារា',
                'tpid' => '0',
                'pid' => 0,
                'cids' => NULL,
                'image' => NULL,
                'record_index' => NULL,
                'active' => NULL,
                'created_at' => '2023-09-09 04:15:54',
                'updated_at' => '2023-09-09 04:15:54',
                'deleted_at' => NULL,
                'prefix' => NULL,
            ),
            24 => 
            array (
                'id' => 25,
                'name' => 'កុមារី',
                'desp' => 'កុមារី',
                'tpid' => '0',
                'pid' => 0,
                'cids' => NULL,
                'image' => NULL,
                'record_index' => NULL,
                'active' => NULL,
                'created_at' => '2023-09-09 04:15:54',
                'updated_at' => '2023-09-09 04:15:54',
                'deleted_at' => NULL,
                'prefix' => NULL,
            ),
            25 => 
            array (
                'id' => 26,
                'name' => 'ទារក',
                'desp' => 'ទារក',
                'tpid' => '0',
                'pid' => 0,
                'cids' => NULL,
                'image' => NULL,
                'record_index' => NULL,
                'active' => NULL,
                'created_at' => '2023-09-09 04:15:54',
                'updated_at' => '2023-09-09 04:15:54',
                'deleted_at' => NULL,
                'prefix' => NULL,
            ),
            26 => 
            array (
                'id' => 27,
                'name' => 'ទារិកា',
                'desp' => 'ទារិកា',
                'tpid' => '0',
                'pid' => 0,
                'cids' => NULL,
                'image' => NULL,
                'record_index' => NULL,
                'active' => NULL,
                'created_at' => '2023-09-09 04:15:54',
                'updated_at' => '2023-09-09 04:15:54',
                'deleted_at' => NULL,
                'prefix' => NULL,
            ),
            27 => 
            array (
                'id' => 28,
                'name' => 'សម្ដេចមហាបវរធិបតី',
                'desp' => 'សម្ដេចបវរធិបតី',
                'tpid' => NULL,
                'pid' => NULL,
                'cids' => NULL,
                'image' => NULL,
                'record_index' => NULL,
                'active' => NULL,
                'created_at' => '2024-11-30 14:29:05',
                'updated_at' => '2024-11-30 14:29:05',
                'deleted_at' => NULL,
                'prefix' => NULL,
            ),
            28 => 
            array (
                'id' => 30,
                'name' => 'ឯកឧត្តមសន្តិបណ្ឌិត',
                'desp' => 'ឯកឧត្តមសន្តិបណ្ឌិត',
                'tpid' => NULL,
                'pid' => NULL,
                'cids' => NULL,
                'image' => NULL,
                'record_index' => NULL,
                'active' => NULL,
                'created_at' => '2024-11-30 14:35:03',
                'updated_at' => '2024-11-30 14:35:03',
                'deleted_at' => NULL,
                'prefix' => NULL,
            ),
            29 => 
            array (
                'id' => 31,
                'name' => 'ឯកឧត្តមអគ្គបណ្ឌិតសភាចារ្យ',
                'desp' => 'ឯកឧត្តមអគ្គបណ្ឌិតសភាចារ',
                'tpid' => NULL,
                'pid' => NULL,
                'cids' => NULL,
                'image' => NULL,
                'record_index' => NULL,
                'active' => NULL,
                'created_at' => '2024-11-30 14:35:03',
                'updated_at' => '2024-11-30 14:35:03',
                'deleted_at' => NULL,
                'prefix' => NULL,
            ),
            30 => 
            array (
                'id' => 32,
                'name' => 'ឯកឧត្តមបណ្ឌិតសភាចារ្យ',
                'desp' => 'ឯកឧត្តមបណ្ឌិតសភាចារ្យ',
                'tpid' => NULL,
                'pid' => NULL,
                'cids' => NULL,
                'image' => NULL,
                'record_index' => NULL,
                'active' => NULL,
                'created_at' => '2024-11-30 14:35:30',
                'updated_at' => '2024-11-30 14:35:30',
                'deleted_at' => NULL,
                'prefix' => NULL,
            ),
            31 => 
            array (
                'id' => 33,
                'name' => 'ឯកឧត្តមអភិសន្តិបណ្ឌិត',
                'desp' => 'ឯកឧត្តមអភិសន្តិបណ្ឌិត',
                'tpid' => NULL,
                'pid' => NULL,
                'cids' => NULL,
                'image' => NULL,
                'record_index' => NULL,
                'active' => NULL,
                'created_at' => '2024-11-30 14:38:23',
                'updated_at' => '2024-11-30 14:38:23',
                'deleted_at' => NULL,
                'prefix' => NULL,
            ),
            32 => 
            array (
                'id' => 34,
                'name' => 'ឯកឧត្តមកិត្តិសង្គហបណ្ឌិត',
                'desp' => 'ឯកឧត្តមកិត្តិសង្គហបណ្ឌិត',
                'tpid' => NULL,
                'pid' => NULL,
                'cids' => NULL,
                'image' => NULL,
                'record_index' => NULL,
                'active' => NULL,
                'created_at' => '2024-11-30 14:38:23',
                'updated_at' => '2024-11-30 14:38:23',
                'deleted_at' => NULL,
                'prefix' => NULL,
            ),
            33 => 
            array (
                'id' => 35,
                'name' => 'ឯកឧត្តមកិត្តិនីតិកោសលបណ្ឌិត',
                'desp' => 'ឯកឧត្តមកិត្តិនីតិកោសលបណ្ឌិត',
                'tpid' => NULL,
                'pid' => NULL,
                'cids' => NULL,
                'image' => NULL,
                'record_index' => NULL,
                'active' => NULL,
                'created_at' => '2024-11-30 14:38:23',
                'updated_at' => '2024-11-30 14:38:23',
                'deleted_at' => NULL,
                'prefix' => NULL,
            ),
            34 => 
            array (
                'id' => 36,
                'name' => 'ឯកឧត្តមសន្តិបណ្ឌិត',
                'desp' => 'ឯកឧត្តមសន្តិបណ្ឌិត',
                'tpid' => NULL,
                'pid' => NULL,
                'cids' => NULL,
                'image' => NULL,
                'record_index' => NULL,
                'active' => NULL,
                'created_at' => '2024-11-30 14:39:19',
                'updated_at' => '2024-11-30 14:39:19',
                'deleted_at' => NULL,
                'prefix' => NULL,
            ),
            35 => 
            array (
                'id' => 37,
                'name' => 'ឯកឧត្តមសាស្ត្រាចារ្យ',
                'desp' => 'ឯកឧត្តមសាស្ត្រាចារ្យ',
                'tpid' => NULL,
                'pid' => NULL,
                'cids' => NULL,
                'image' => NULL,
                'record_index' => NULL,
                'active' => NULL,
                'created_at' => '2024-11-30 14:40:06',
                'updated_at' => '2024-11-30 14:40:06',
                'deleted_at' => NULL,
                'prefix' => NULL,
            ),
            36 => 
            array (
                'id' => 38,
                'name' => 'លោកជំទាវបណ្ឌិតសភាចារ្យ',
                'desp' => 'លោកជំទាវបណ្ឌិតសភាចារ្យ',
                'tpid' => NULL,
                'pid' => NULL,
                'cids' => NULL,
                'image' => NULL,
                'record_index' => NULL,
                'active' => NULL,
                'created_at' => '2024-11-30 14:40:30',
                'updated_at' => '2024-11-30 14:40:30',
                'deleted_at' => NULL,
                'prefix' => NULL,
            ),
            37 => 
            array (
                'id' => 39,
                'name' => 'លោកជំទាវកិត្តិបណ្ឌិត',
                'desp' => 'លោកជំទាវកិត្តិបណ្ឌិត',
                'tpid' => NULL,
                'pid' => NULL,
                'cids' => NULL,
                'image' => NULL,
                'record_index' => NULL,
                'active' => NULL,
                'created_at' => '2024-11-30 14:40:59',
                'updated_at' => '2024-11-30 14:40:59',
                'deleted_at' => NULL,
                'prefix' => NULL,
            ),
            38 => 
            array (
                'id' => 40,
                'name' => 'លោកជំទាវបណ្ឌិត',
                'desp' => 'លោកជំទាវបណ្ឌិត',
                'tpid' => NULL,
                'pid' => NULL,
                'cids' => NULL,
                'image' => NULL,
                'record_index' => NULL,
                'active' => NULL,
                'created_at' => '2024-11-30 14:42:47',
                'updated_at' => '2024-11-30 14:42:47',
                'deleted_at' => NULL,
                'prefix' => NULL,
            ),
            39 => 
            array (
                'id' => 41,
                'name' => 'ឯកឧត្តមនាយឧត្តមសេនីយ៍',
                'desp' => 'ឯកឧត្តមនាយឧត្តមសេនីយ៍',
                'tpid' => NULL,
                'pid' => NULL,
                'cids' => NULL,
                'image' => NULL,
                'record_index' => NULL,
                'active' => NULL,
                'created_at' => '2024-11-30 14:42:47',
                'updated_at' => '2024-11-30 14:42:47',
                'deleted_at' => NULL,
                'prefix' => NULL,
            ),
            40 => 
            array (
                'id' => 42,
                'name' => 'ឯកឧត្តមបណ្ឌិត',
                'desp' => 'ឯកឧត្តមបណ្ឌិត',
                'tpid' => NULL,
                'pid' => NULL,
                'cids' => NULL,
                'image' => NULL,
                'record_index' => NULL,
                'active' => NULL,
                'created_at' => '2024-11-30 14:42:47',
                'updated_at' => '2024-11-30 14:42:47',
                'deleted_at' => NULL,
                'prefix' => NULL,
            ),
            41 => 
            array (
                'id' => 43,
                'name' => 'ឯកឧត្តមកិត្តិសង្គហបណ្ឌិត',
                'desp' => 'ឯកឧត្តមកិត្តិសង្គហបណ្ឌិត',
                'tpid' => NULL,
                'pid' => NULL,
                'cids' => NULL,
                'image' => NULL,
                'record_index' => NULL,
                'active' => NULL,
                'created_at' => '2024-11-30 14:42:47',
                'updated_at' => '2024-11-30 14:42:47',
                'deleted_at' => NULL,
                'prefix' => NULL,
            ),
            42 => 
            array (
                'id' => 44,
                'name' => 'ឯកឧត្តមកិត្តិបណ្ឌិត',
                'desp' => 'ឯកឧត្តមកតិបណ្ឌិត',
                'tpid' => NULL,
                'pid' => NULL,
                'cids' => NULL,
                'image' => NULL,
                'record_index' => NULL,
                'active' => NULL,
                'created_at' => '2024-11-30 14:42:47',
                'updated_at' => '2024-11-30 14:42:47',
                'deleted_at' => NULL,
                'prefix' => NULL,
            ),
            43 => 
            array (
                'id' => 45,
                'name' => 'ឯកឧត្តមនាយឧត្តមសេនីយ៍សន្តិបណ្ឌិត',
                'desp' => 'ឯកឧត្តមនាយឧត្តមសេនីយ៍សន្តិបណ្ឌិត',
                'tpid' => NULL,
                'pid' => NULL,
                'cids' => NULL,
                'image' => NULL,
                'record_index' => NULL,
                'active' => NULL,
                'created_at' => '2024-11-30 14:42:47',
                'updated_at' => '2024-11-30 14:42:47',
                'deleted_at' => NULL,
                'prefix' => NULL,
            ),
            44 => 
            array (
                'id' => 46,
                'name' => 'ឯកឧត្តមឧត្តមសេនីយ៍ឯក',
                'desp' => 'ឯកឧត្តមឧត្តមសេនីយ៍ឯក',
                'tpid' => NULL,
                'pid' => NULL,
                'cids' => NULL,
                'image' => NULL,
                'record_index' => NULL,
                'active' => NULL,
                'created_at' => '2024-11-30 14:42:47',
                'updated_at' => '2024-11-30 14:42:47',
                'deleted_at' => NULL,
                'prefix' => NULL,
            ),
            45 => 
            array (
                'id' => 47,
                'name' => 'ខុសឈ្មោះ',
                'desp' => 'ខុសឈ្មោះ',
                'tpid' => NULL,
                'pid' => NULL,
                'cids' => NULL,
                'image' => NULL,
                'record_index' => NULL,
                'active' => NULL,
                'created_at' => '2024-11-30 14:42:47',
                'updated_at' => '2024-11-30 14:42:47',
                'deleted_at' => '2024-11-30 14:49:56',
                'prefix' => NULL,
            ),
        ));
        
        
    }
}