<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;

class DocumentTransactionsTableSeeder extends Seeder
{

    /**
     * Auto generated seed file
     *
     * @return void
     */
    public function run()
    {
        

        \DB::table('document_transactions')->delete();
        
        \DB::table('document_transactions')->insert(array (
            0 => 
            array (
                'id' => 76,
                'document_id' => 77,
                'sender_id' => 1342,
                'subject' => 'l;akjsdf;l',
                'sent_at' => NULL,
                'previous_transaction_id' => 0,
                'next_transaction_id' => 0,
                'created_by' => 1342,
                'updated_by' => 1342,
                'deleted_by' => 0,
                'created_at' => '2026-01-28 18:43:46',
                'updated_at' => '2026-01-28 18:43:46',
                'deleted_at' => NULL,
                'tpid' => NULL,
                'date_in' => '2026-01-28 00:00:00',
                'status' => 'draft',
            ),
            1 => 
            array (
                'id' => 49,
                'document_id' => 50,
                'sender_id' => 392,
                'subject' => 'ប្រធានបទនៃការបញ្ជូនឯកសារ 2',
                'sent_at' => '2026-01-14 16:48:23',
                'previous_transaction_id' => 48,
                'next_transaction_id' => 50,
                'created_by' => 392,
                'updated_by' => 392,
                'deleted_by' => 0,
                'created_at' => '2026-01-14 16:48:23',
                'updated_at' => '2026-01-14 16:48:23',
                'deleted_at' => NULL,
                'tpid' => '48',
                'date_in' => NULL,
                'status' => NULL,
            ),
            2 => 
            array (
                'id' => 50,
                'document_id' => 51,
                'sender_id' => 430,
                'subject' => 'ប្រធានបទនៃការបញ្ជូនឯកសារ 3',
                'sent_at' => '2026-01-14 16:48:23',
                'previous_transaction_id' => 49,
                'next_transaction_id' => 51,
                'created_by' => 430,
                'updated_by' => 430,
                'deleted_by' => 0,
                'created_at' => '2026-01-14 16:48:23',
                'updated_at' => '2026-01-14 16:48:23',
                'deleted_at' => NULL,
                'tpid' => '48:49',
                'date_in' => NULL,
                'status' => NULL,
            ),
            3 => 
            array (
                'id' => 51,
                'document_id' => 52,
                'sender_id' => 3470,
                'subject' => 'ប្រធានបទនៃការបញ្ជូនឯកសារ 4',
                'sent_at' => '2026-01-14 16:48:23',
                'previous_transaction_id' => 50,
                'next_transaction_id' => 52,
                'created_by' => 3470,
                'updated_by' => 3470,
                'deleted_by' => 0,
                'created_at' => '2026-01-14 16:48:23',
                'updated_at' => '2026-01-14 16:48:23',
                'deleted_at' => NULL,
                'tpid' => '48:49:50',
                'date_in' => NULL,
                'status' => NULL,
            ),
            4 => 
            array (
                'id' => 52,
                'document_id' => 53,
                'sender_id' => 2245,
                'subject' => 'ប្រធានបទនៃការបញ្ជូនឯកសារ 5',
                'sent_at' => '2026-01-14 16:48:23',
                'previous_transaction_id' => 51,
                'next_transaction_id' => 53,
                'created_by' => 2245,
                'updated_by' => 2245,
                'deleted_by' => 0,
                'created_at' => '2026-01-14 16:48:23',
                'updated_at' => '2026-01-14 16:48:23',
                'deleted_at' => NULL,
                'tpid' => '48:49:50:51',
                'date_in' => NULL,
                'status' => NULL,
            ),
            5 => 
            array (
                'id' => 53,
                'document_id' => 54,
                'sender_id' => 2162,
                'subject' => 'ប្រធានបទនៃការបញ្ជូនឯកសារ 6',
                'sent_at' => '2026-01-14 16:48:23',
                'previous_transaction_id' => 52,
                'next_transaction_id' => 54,
                'created_by' => 2162,
                'updated_by' => 2162,
                'deleted_by' => 0,
                'created_at' => '2026-01-14 16:48:23',
                'updated_at' => '2026-01-14 16:48:23',
                'deleted_at' => NULL,
                'tpid' => '48:49:50:51:52',
                'date_in' => NULL,
                'status' => NULL,
            ),
            6 => 
            array (
                'id' => 54,
                'document_id' => 55,
                'sender_id' => 1364,
                'subject' => 'ប្រធានបទនៃការបញ្ជូនឯកសារ 7',
                'sent_at' => '2026-01-14 16:48:23',
                'previous_transaction_id' => 53,
                'next_transaction_id' => 55,
                'created_by' => 1364,
                'updated_by' => 1364,
                'deleted_by' => 0,
                'created_at' => '2026-01-14 16:48:23',
                'updated_at' => '2026-01-14 16:48:23',
                'deleted_at' => NULL,
                'tpid' => '48:49:50:51:52:53',
                'date_in' => NULL,
                'status' => NULL,
            ),
            7 => 
            array (
                'id' => 55,
                'document_id' => 56,
                'sender_id' => 1813,
                'subject' => 'ប្រធានបទនៃការបញ្ជូនឯកសារ 8',
                'sent_at' => '2026-01-14 16:48:23',
                'previous_transaction_id' => 54,
                'next_transaction_id' => 56,
                'created_by' => 1813,
                'updated_by' => 1813,
                'deleted_by' => 0,
                'created_at' => '2026-01-14 16:48:23',
                'updated_at' => '2026-01-14 16:48:23',
                'deleted_at' => NULL,
                'tpid' => '48:49:50:51:52:53:54',
                'date_in' => NULL,
                'status' => NULL,
            ),
            8 => 
            array (
                'id' => 56,
                'document_id' => 57,
                'sender_id' => 110,
                'subject' => 'ប្រធានបទនៃការបញ្ជូនឯកសារ 9',
                'sent_at' => '2026-01-14 16:48:23',
                'previous_transaction_id' => 55,
                'next_transaction_id' => 57,
                'created_by' => 110,
                'updated_by' => 110,
                'deleted_by' => 0,
                'created_at' => '2026-01-14 16:48:23',
                'updated_at' => '2026-01-14 16:48:23',
                'deleted_at' => NULL,
                'tpid' => '48:49:50:51:52:53:54:55',
                'date_in' => NULL,
                'status' => NULL,
            ),
            9 => 
            array (
                'id' => 57,
                'document_id' => 58,
                'sender_id' => 3280,
                'subject' => 'ប្រធានបទនៃការបញ្ជូនឯកសារ 10',
                'sent_at' => '2026-01-14 16:48:23',
                'previous_transaction_id' => 56,
                'next_transaction_id' => 58,
                'created_by' => 3280,
                'updated_by' => 3280,
                'deleted_by' => 0,
                'created_at' => '2026-01-14 16:48:23',
                'updated_at' => '2026-01-14 16:48:23',
                'deleted_at' => NULL,
                'tpid' => '48:49:50:51:52:53:54:55:56',
                'date_in' => NULL,
                'status' => NULL,
            ),
            10 => 
            array (
                'id' => 58,
                'document_id' => 59,
                'sender_id' => 1080,
                'subject' => 'ប្រធានបទនៃការបញ្ជូនឯកសារ 11',
                'sent_at' => '2026-01-14 16:48:23',
                'previous_transaction_id' => 57,
                'next_transaction_id' => 59,
                'created_by' => 1080,
                'updated_by' => 1080,
                'deleted_by' => 0,
                'created_at' => '2026-01-14 16:48:23',
                'updated_at' => '2026-01-14 16:48:23',
                'deleted_at' => NULL,
                'tpid' => '48:49:50:51:52:53:54:55:56:57',
                'date_in' => NULL,
                'status' => NULL,
            ),
            11 => 
            array (
                'id' => 59,
                'document_id' => 60,
                'sender_id' => 3178,
                'subject' => 'ប្រធានបទនៃការបញ្ជូនឯកសារ 12',
                'sent_at' => '2026-01-14 16:48:23',
                'previous_transaction_id' => 58,
                'next_transaction_id' => 60,
                'created_by' => 3178,
                'updated_by' => 3178,
                'deleted_by' => 0,
                'created_at' => '2026-01-14 16:48:23',
                'updated_at' => '2026-01-14 16:48:23',
                'deleted_at' => NULL,
                'tpid' => '48:49:50:51:52:53:54:55:56:57:58',
                'date_in' => NULL,
                'status' => NULL,
            ),
            12 => 
            array (
                'id' => 60,
                'document_id' => 61,
                'sender_id' => 1464,
                'subject' => 'ប្រធានបទនៃការបញ្ជូនឯកសារ 13',
                'sent_at' => '2026-01-14 16:48:23',
                'previous_transaction_id' => 59,
                'next_transaction_id' => 61,
                'created_by' => 1464,
                'updated_by' => 1464,
                'deleted_by' => 0,
                'created_at' => '2026-01-14 16:48:23',
                'updated_at' => '2026-01-14 16:48:23',
                'deleted_at' => NULL,
                'tpid' => '48:49:50:51:52:53:54:55:56:57:58:59',
                'date_in' => NULL,
                'status' => NULL,
            ),
            13 => 
            array (
                'id' => 61,
                'document_id' => 62,
                'sender_id' => 2501,
                'subject' => 'ប្រធានបទនៃការបញ្ជូនឯកសារ 14',
                'sent_at' => '2026-01-14 16:48:23',
                'previous_transaction_id' => 60,
                'next_transaction_id' => 62,
                'created_by' => 2501,
                'updated_by' => 2501,
                'deleted_by' => 0,
                'created_at' => '2026-01-14 16:48:23',
                'updated_at' => '2026-01-14 16:48:23',
                'deleted_at' => NULL,
                'tpid' => '48:49:50:51:52:53:54:55:56:57:58:59:60',
                'date_in' => NULL,
                'status' => NULL,
            ),
            14 => 
            array (
                'id' => 62,
                'document_id' => 63,
                'sender_id' => 468,
                'subject' => 'ប្រធានបទនៃការបញ្ជូនឯកសារ 15',
                'sent_at' => '2026-01-14 16:48:23',
                'previous_transaction_id' => 61,
                'next_transaction_id' => 63,
                'created_by' => 468,
                'updated_by' => 468,
                'deleted_by' => 0,
                'created_at' => '2026-01-14 16:48:23',
                'updated_at' => '2026-01-14 16:48:23',
                'deleted_at' => NULL,
                'tpid' => '48:49:50:51:52:53:54:55:56:57:58:59:60:61',
                'date_in' => NULL,
                'status' => NULL,
            ),
            15 => 
            array (
                'id' => 63,
                'document_id' => 64,
                'sender_id' => 2712,
                'subject' => 'ប្រធានបទនៃការបញ្ជូនឯកសារ 16',
                'sent_at' => '2026-01-14 16:48:23',
                'previous_transaction_id' => 62,
                'next_transaction_id' => 64,
                'created_by' => 2712,
                'updated_by' => 2712,
                'deleted_by' => 0,
                'created_at' => '2026-01-14 16:48:23',
                'updated_at' => '2026-01-14 16:48:23',
                'deleted_at' => NULL,
                'tpid' => '48:49:50:51:52:53:54:55:56:57:58:59:60:61:62',
                'date_in' => NULL,
                'status' => NULL,
            ),
            16 => 
            array (
                'id' => 65,
                'document_id' => 66,
                'sender_id' => 1335,
                'subject' => 'ប្រធានបទនៃការបញ្ជូនឯកសារ 18',
                'sent_at' => '2026-01-14 16:48:23',
                'previous_transaction_id' => 64,
                'next_transaction_id' => NULL,
                'created_by' => 1335,
                'updated_by' => 1335,
                'deleted_by' => 0,
                'created_at' => '2026-01-14 16:48:23',
                'updated_at' => '2026-01-14 16:48:23',
                'deleted_at' => NULL,
                'tpid' => '48:49:50:51:52:53:54:55:56:57:58:59:60:61:62:63:64',
                'date_in' => NULL,
                'status' => NULL,
            ),
            17 => 
            array (
                'id' => 64,
                'document_id' => 65,
                'sender_id' => 3097,
                'subject' => 'ប្រធានបទនៃការបញ្ជូនឯកសារ 17',
                'sent_at' => '2026-01-14 16:48:23',
                'previous_transaction_id' => 63,
                'next_transaction_id' => 65,
                'created_by' => 3097,
                'updated_by' => 3097,
                'deleted_by' => 0,
                'created_at' => '2026-01-14 16:48:23',
                'updated_at' => '2026-01-14 16:48:23',
                'deleted_at' => NULL,
                'tpid' => '48:49:50:51:52:53:54:55:56:57:58:59:60:61:62:63',
                'date_in' => NULL,
                'status' => NULL,
            ),
            18 => 
            array (
                'id' => 66,
                'document_id' => 67,
                'sender_id' => 370,
                'subject' => 'ប្រធានបទនៃការបញ្ជូនឯកសារ 1',
                'sent_at' => NULL,
                'previous_transaction_id' => 48,
                'next_transaction_id' => 0,
                'created_by' => 370,
                'updated_by' => 370,
                'deleted_by' => 0,
                'created_at' => '2026-01-15 16:33:47',
                'updated_at' => '2026-01-15 16:33:47',
                'deleted_at' => NULL,
                'tpid' => '48:',
                'date_in' => '2026-01-15 16:33:47',
                'status' => NULL,
            ),
            19 => 
            array (
                'id' => 77,
                'document_id' => 78,
                'sender_id' => 1342,
                'subject' => 'alskjf;l',
                'sent_at' => NULL,
                'previous_transaction_id' => 0,
                'next_transaction_id' => 0,
                'created_by' => 1342,
                'updated_by' => 1342,
                'deleted_by' => 0,
                'created_at' => '2026-01-28 18:45:01',
                'updated_at' => '2026-01-28 18:45:01',
                'deleted_at' => NULL,
                'tpid' => NULL,
                'date_in' => '2026-01-29 00:00:00',
                'status' => 'draft',
            ),
            20 => 
            array (
                'id' => 67,
                'document_id' => 68,
                'sender_id' => 370,
                'subject' => 'ប្រធានបទនៃការបញ្ជូនឯកសារ 1',
                'sent_at' => NULL,
                'previous_transaction_id' => 48,
                'next_transaction_id' => 0,
                'created_by' => 370,
                'updated_by' => 370,
                'deleted_by' => 0,
                'created_at' => '2026-01-15 16:43:06',
                'updated_at' => '2026-01-15 16:43:06',
                'deleted_at' => NULL,
                'tpid' => '48:',
                'date_in' => '2026-01-15 16:43:06',
                'status' => NULL,
            ),
            21 => 
            array (
                'id' => 48,
                'document_id' => 49,
                'sender_id' => 3840,
                'subject' => 'ប្រធានបទនៃការបញ្ជូនឯកសារ 1',
                'sent_at' => '2026-01-14 16:48:23',
                'previous_transaction_id' => NULL,
                'next_transaction_id' => 68,
                'created_by' => 3840,
                'updated_by' => 3840,
                'deleted_by' => 0,
                'created_at' => '2026-01-14 16:48:23',
                'updated_at' => '2026-01-15 16:51:49',
                'deleted_at' => NULL,
                'tpid' => NULL,
                'date_in' => NULL,
                'status' => NULL,
            ),
            22 => 
            array (
                'id' => 68,
                'document_id' => 69,
                'sender_id' => 370,
                'subject' => 'ប្រធានបទនៃការបញ្ជូនឯកសារ 1',
                'sent_at' => NULL,
                'previous_transaction_id' => 48,
                'next_transaction_id' => 0,
                'created_by' => 370,
                'updated_by' => 370,
                'deleted_by' => 0,
                'created_at' => '2026-01-15 16:51:49',
                'updated_at' => '2026-01-15 16:51:49',
                'deleted_at' => NULL,
                'tpid' => '48:',
                'date_in' => '2026-01-15 16:51:49',
                'status' => NULL,
            ),
            23 => 
            array (
                'id' => 69,
                'document_id' => 70,
                'sender_id' => 1342,
                'subject' => 'កម្មវត្ថុនៃឯកសារ',
                'sent_at' => NULL,
                'previous_transaction_id' => 0,
                'next_transaction_id' => 0,
                'created_by' => 1342,
                'updated_by' => 1342,
                'deleted_by' => 0,
                'created_at' => '2026-01-28 16:09:39',
                'updated_at' => '2026-01-28 16:09:39',
                'deleted_at' => NULL,
                'tpid' => NULL,
                'date_in' => '2026-01-28 00:00:00',
                'status' => 'draft',
            ),
            24 => 
            array (
                'id' => 70,
                'document_id' => 71,
                'sender_id' => 1342,
                'subject' => 'កម្មវត្ថុ',
                'sent_at' => NULL,
                'previous_transaction_id' => 0,
                'next_transaction_id' => 0,
                'created_by' => 1342,
                'updated_by' => 1342,
                'deleted_by' => 0,
                'created_at' => '2026-01-28 18:15:56',
                'updated_at' => '2026-01-28 18:15:56',
                'deleted_at' => NULL,
                'tpid' => NULL,
                'date_in' => '2026-01-28 00:00:00',
                'status' => 'draft',
            ),
            25 => 
            array (
                'id' => 71,
                'document_id' => 72,
                'sender_id' => 1342,
                'subject' => 'aklsjfd;lk',
                'sent_at' => NULL,
                'previous_transaction_id' => 0,
                'next_transaction_id' => 0,
                'created_by' => 1342,
                'updated_by' => 1342,
                'deleted_by' => 0,
                'created_at' => '2026-01-28 18:35:05',
                'updated_at' => '2026-01-28 18:35:05',
                'deleted_at' => NULL,
                'tpid' => NULL,
                'date_in' => '2026-01-28 00:00:00',
                'status' => 'draft',
            ),
            26 => 
            array (
                'id' => 72,
                'document_id' => 73,
                'sender_id' => 1342,
                'subject' => 'alksjd;lj',
                'sent_at' => NULL,
                'previous_transaction_id' => 0,
                'next_transaction_id' => 0,
                'created_by' => 1342,
                'updated_by' => 1342,
                'deleted_by' => 0,
                'created_at' => '2026-01-28 18:36:09',
                'updated_at' => '2026-01-28 18:36:09',
                'deleted_at' => NULL,
                'tpid' => NULL,
                'date_in' => '2026-01-28 00:00:00',
                'status' => 'draft',
            ),
            27 => 
            array (
                'id' => 73,
                'document_id' => 74,
                'sender_id' => 1342,
                'subject' => ';alkjdf;lkj',
                'sent_at' => NULL,
                'previous_transaction_id' => 0,
                'next_transaction_id' => 0,
                'created_by' => 1342,
                'updated_by' => 1342,
                'deleted_by' => 0,
                'created_at' => '2026-01-28 18:37:22',
                'updated_at' => '2026-01-28 18:37:22',
                'deleted_at' => NULL,
                'tpid' => NULL,
                'date_in' => '2026-01-28 00:00:00',
                'status' => 'draft',
            ),
            28 => 
            array (
                'id' => 74,
                'document_id' => 75,
                'sender_id' => 1342,
                'subject' => 'al;ksjd;lk',
                'sent_at' => NULL,
                'previous_transaction_id' => 0,
                'next_transaction_id' => 0,
                'created_by' => 1342,
                'updated_by' => 1342,
                'deleted_by' => 0,
                'created_at' => '2026-01-28 18:38:57',
                'updated_at' => '2026-01-28 18:38:57',
                'deleted_at' => NULL,
                'tpid' => NULL,
                'date_in' => '2026-01-28 00:00:00',
                'status' => 'draft',
            ),
            29 => 
            array (
                'id' => 75,
                'document_id' => 76,
                'sender_id' => 1342,
                'subject' => 'a;lskdl;\'ajsl;',
                'sent_at' => NULL,
                'previous_transaction_id' => 0,
                'next_transaction_id' => 0,
                'created_by' => 1342,
                'updated_by' => 1342,
                'deleted_by' => 0,
                'created_at' => '2026-01-28 18:40:03',
                'updated_at' => '2026-01-28 18:40:04',
                'deleted_at' => NULL,
                'tpid' => NULL,
                'date_in' => '2026-01-28 00:00:00',
                'status' => 'draft',
            ),
            30 => 
            array (
                'id' => 78,
                'document_id' => 79,
                'sender_id' => 1342,
                'subject' => 'kjasdlfkhj',
                'sent_at' => NULL,
                'previous_transaction_id' => 0,
                'next_transaction_id' => 0,
                'created_by' => 1342,
                'updated_by' => 1342,
                'deleted_by' => 0,
                'created_at' => '2026-01-29 08:35:02',
                'updated_at' => '2026-01-29 08:35:02',
                'deleted_at' => NULL,
                'tpid' => NULL,
                'date_in' => '2026-01-29 00:00:00',
                'status' => 'draft',
            ),
            31 => 
            array (
                'id' => 79,
                'document_id' => 80,
                'sender_id' => 1342,
                'subject' => 'jjdjh',
                'sent_at' => NULL,
                'previous_transaction_id' => 0,
                'next_transaction_id' => 0,
                'created_by' => 1342,
                'updated_by' => 1342,
                'deleted_by' => 0,
                'created_at' => '2026-01-29 08:36:45',
                'updated_at' => '2026-01-29 08:36:45',
                'deleted_at' => NULL,
                'tpid' => NULL,
                'date_in' => '2026-01-30 00:00:00',
                'status' => 'draft',
            ),
            32 => 
            array (
                'id' => 80,
                'document_id' => 81,
                'sender_id' => 1342,
                'subject' => 'ការវិភាគ',
                'sent_at' => NULL,
                'previous_transaction_id' => 0,
                'next_transaction_id' => 0,
                'created_by' => 1342,
                'updated_by' => 1342,
                'deleted_by' => 0,
                'created_at' => '2026-01-29 13:38:52',
                'updated_at' => '2026-01-29 13:38:52',
                'deleted_at' => NULL,
                'tpid' => NULL,
                'date_in' => '2026-01-29 00:00:00',
                'status' => 'draft',
            ),
            33 => 
            array (
                'id' => 81,
                'document_id' => 82,
                'sender_id' => 1342,
                'subject' => 'alksjfd',
                'sent_at' => NULL,
                'previous_transaction_id' => 0,
                'next_transaction_id' => 0,
                'created_by' => 1342,
                'updated_by' => 1342,
                'deleted_by' => 0,
                'created_at' => '2026-01-29 13:40:12',
                'updated_at' => '2026-01-29 13:40:12',
                'deleted_at' => NULL,
                'tpid' => NULL,
                'date_in' => '2026-01-29 00:00:00',
                'status' => 'draft',
            ),
            34 => 
            array (
                'id' => 82,
                'document_id' => 83,
                'sender_id' => 1342,
                'subject' => 'កម្មវិត្ថុ',
                'sent_at' => NULL,
                'previous_transaction_id' => 0,
                'next_transaction_id' => 0,
                'created_by' => 1342,
                'updated_by' => 1342,
                'deleted_by' => 0,
                'created_at' => '2026-01-29 13:42:05',
                'updated_at' => '2026-01-29 13:42:05',
                'deleted_at' => NULL,
                'tpid' => NULL,
                'date_in' => '2026-01-29 00:00:00',
                'status' => 'draft',
            ),
            35 => 
            array (
                'id' => 83,
                'document_id' => 84,
                'sender_id' => 1342,
                'subject' => 'កខគ',
                'sent_at' => NULL,
                'previous_transaction_id' => 0,
                'next_transaction_id' => 0,
                'created_by' => 1342,
                'updated_by' => 1342,
                'deleted_by' => 0,
                'created_at' => '2026-01-29 13:43:21',
                'updated_at' => '2026-01-29 13:43:21',
                'deleted_at' => NULL,
                'tpid' => NULL,
                'date_in' => '2026-01-29 00:00:00',
                'status' => 'draft',
            ),
            36 => 
            array (
                'id' => 84,
                'document_id' => 85,
                'sender_id' => 1342,
                'subject' => 'កម្មវត្ថុ',
                'sent_at' => NULL,
                'previous_transaction_id' => 0,
                'next_transaction_id' => 0,
                'created_by' => 1342,
                'updated_by' => 1342,
                'deleted_by' => 0,
                'created_at' => '2026-01-29 14:00:52',
                'updated_at' => '2026-01-29 14:00:53',
                'deleted_at' => NULL,
                'tpid' => NULL,
                'date_in' => '2026-01-29 00:00:00',
                'status' => 'draft',
            ),
            37 => 
            array (
                'id' => 85,
                'document_id' => 86,
                'sender_id' => 1342,
                'subject' => 'ABC',
                'sent_at' => NULL,
                'previous_transaction_id' => 0,
                'next_transaction_id' => 0,
                'created_by' => 1342,
                'updated_by' => 1342,
                'deleted_by' => 0,
                'created_at' => '2026-01-29 14:01:55',
                'updated_at' => '2026-01-29 14:01:55',
                'deleted_at' => NULL,
                'tpid' => NULL,
                'date_in' => '2026-01-29 00:00:00',
                'status' => 'draft',
            ),
            38 => 
            array (
                'id' => 86,
                'document_id' => 87,
                'sender_id' => 1342,
                'subject' => 'ABC',
                'sent_at' => NULL,
                'previous_transaction_id' => 0,
                'next_transaction_id' => 0,
                'created_by' => 1342,
                'updated_by' => 1342,
                'deleted_by' => 0,
                'created_at' => '2026-01-29 14:02:27',
                'updated_at' => '2026-01-29 14:02:27',
                'deleted_at' => NULL,
                'tpid' => NULL,
                'date_in' => '2026-01-29 00:00:00',
                'status' => 'draft',
            ),
            39 => 
            array (
                'id' => 87,
                'document_id' => 88,
                'sender_id' => 1342,
                'subject' => 'ABC',
                'sent_at' => NULL,
                'previous_transaction_id' => 0,
                'next_transaction_id' => 0,
                'created_by' => 1342,
                'updated_by' => 1342,
                'deleted_by' => 0,
                'created_at' => '2026-01-29 14:03:21',
                'updated_at' => '2026-01-29 14:03:21',
                'deleted_at' => NULL,
                'tpid' => NULL,
                'date_in' => '2026-01-29 00:00:00',
                'status' => 'draft',
            ),
            40 => 
            array (
                'id' => 88,
                'document_id' => 89,
                'sender_id' => 1342,
                'subject' => 'abc',
                'sent_at' => NULL,
                'previous_transaction_id' => 0,
                'next_transaction_id' => 0,
                'created_by' => 1342,
                'updated_by' => 1342,
                'deleted_by' => 0,
                'created_at' => '2026-01-29 14:07:47',
                'updated_at' => '2026-01-29 14:07:47',
                'deleted_at' => NULL,
                'tpid' => NULL,
                'date_in' => '2026-01-29 00:00:00',
                'status' => 'draft',
            ),
            41 => 
            array (
                'id' => 89,
                'document_id' => 90,
                'sender_id' => 1342,
                'subject' => ';laksjdf',
                'sent_at' => NULL,
                'previous_transaction_id' => 0,
                'next_transaction_id' => 0,
                'created_by' => 1342,
                'updated_by' => 1342,
                'deleted_by' => 0,
                'created_at' => '2026-01-29 14:08:43',
                'updated_at' => '2026-01-29 14:08:43',
                'deleted_at' => NULL,
                'tpid' => NULL,
                'date_in' => '2026-01-29 00:00:00',
                'status' => 'draft',
            ),
            42 => 
            array (
                'id' => 90,
                'document_id' => 91,
                'sender_id' => 1342,
                'subject' => 'a;slkfdj',
                'sent_at' => NULL,
                'previous_transaction_id' => 0,
                'next_transaction_id' => 0,
                'created_by' => 1342,
                'updated_by' => 1342,
                'deleted_by' => 0,
                'created_at' => '2026-01-29 14:11:15',
                'updated_at' => '2026-01-29 14:11:15',
                'deleted_at' => NULL,
                'tpid' => NULL,
                'date_in' => '2026-01-29 00:00:00',
                'status' => 'draft',
            ),
            43 => 
            array (
                'id' => 91,
                'document_id' => 92,
                'sender_id' => 1342,
                'subject' => 'aklsjfd',
                'sent_at' => NULL,
                'previous_transaction_id' => 0,
                'next_transaction_id' => 0,
                'created_by' => 1342,
                'updated_by' => 1342,
                'deleted_by' => 0,
                'created_at' => '2026-01-29 17:06:04',
                'updated_at' => '2026-01-29 17:06:04',
                'deleted_at' => NULL,
                'tpid' => NULL,
                'date_in' => '2026-01-29 00:00:00',
                'status' => 'draft',
            ),
            44 => 
            array (
                'id' => 92,
                'document_id' => 93,
                'sender_id' => 1342,
                'subject' => 'LKAJD;L;ALSKJD',
                'sent_at' => NULL,
                'previous_transaction_id' => 0,
                'next_transaction_id' => 0,
                'created_by' => 1342,
                'updated_by' => 1342,
                'deleted_by' => 0,
                'created_at' => '2026-01-29 17:11:22',
                'updated_at' => '2026-01-29 17:11:22',
                'deleted_at' => NULL,
                'tpid' => NULL,
                'date_in' => '2026-01-29 00:00:00',
                'status' => 'draft',
            ),
        ));
        
        
    }
}