<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;

class DocumentTransactionReceiversTableSeeder extends Seeder
{

    /**
     * Auto generated seed file
     *
     * @return void
     */
    public function run()
    {
        

        \DB::table('document_transaction_receivers')->delete();
        
        \DB::table('document_transaction_receivers')->insert(array (
            0 => 
            array (
                'id' => 264,
                'document_transaction_id' => 48,
                'receiver_id' => 749,
                'seen_at' => NULL,
                'download_at' => NULL,
                'preview_at' => NULL,
                'created_by' => 0,
                'updated_by' => 0,
                'deleted_by' => 0,
                'created_at' => '2026-01-14 16:48:23',
                'updated_at' => '2026-01-14 16:48:23',
                'deleted_at' => NULL,
                'accepted_at' => NULL,
            ),
            1 => 
            array (
                'id' => 265,
                'document_transaction_id' => 48,
                'receiver_id' => 2579,
                'seen_at' => NULL,
                'download_at' => NULL,
                'preview_at' => NULL,
                'created_by' => 0,
                'updated_by' => 0,
                'deleted_by' => 0,
                'created_at' => '2026-01-14 16:48:23',
                'updated_at' => '2026-01-14 16:48:23',
                'deleted_at' => NULL,
                'accepted_at' => NULL,
            ),
            2 => 
            array (
                'id' => 266,
                'document_transaction_id' => 48,
                'receiver_id' => 2191,
                'seen_at' => NULL,
                'download_at' => NULL,
                'preview_at' => NULL,
                'created_by' => 0,
                'updated_by' => 0,
                'deleted_by' => 0,
                'created_at' => '2026-01-14 16:48:23',
                'updated_at' => '2026-01-14 16:48:23',
                'deleted_at' => NULL,
                'accepted_at' => NULL,
            ),
            3 => 
            array (
                'id' => 267,
                'document_transaction_id' => 48,
                'receiver_id' => 1051,
                'seen_at' => NULL,
                'download_at' => NULL,
                'preview_at' => NULL,
                'created_by' => 0,
                'updated_by' => 0,
                'deleted_by' => 0,
                'created_at' => '2026-01-14 16:48:23',
                'updated_at' => '2026-01-14 16:48:23',
                'deleted_at' => NULL,
                'accepted_at' => NULL,
            ),
            4 => 
            array (
                'id' => 268,
                'document_transaction_id' => 48,
                'receiver_id' => 224,
                'seen_at' => NULL,
                'download_at' => NULL,
                'preview_at' => NULL,
                'created_by' => 0,
                'updated_by' => 0,
                'deleted_by' => 0,
                'created_at' => '2026-01-14 16:48:23',
                'updated_at' => '2026-01-14 16:48:23',
                'deleted_at' => NULL,
                'accepted_at' => NULL,
            ),
            5 => 
            array (
                'id' => 269,
                'document_transaction_id' => 49,
                'receiver_id' => 28,
                'seen_at' => NULL,
                'download_at' => NULL,
                'preview_at' => NULL,
                'created_by' => 0,
                'updated_by' => 0,
                'deleted_by' => 0,
                'created_at' => '2026-01-14 16:48:23',
                'updated_at' => '2026-01-14 16:48:23',
                'deleted_at' => NULL,
                'accepted_at' => NULL,
            ),
            6 => 
            array (
                'id' => 270,
                'document_transaction_id' => 49,
                'receiver_id' => 1422,
                'seen_at' => NULL,
                'download_at' => NULL,
                'preview_at' => NULL,
                'created_by' => 0,
                'updated_by' => 0,
                'deleted_by' => 0,
                'created_at' => '2026-01-14 16:48:23',
                'updated_at' => '2026-01-14 16:48:23',
                'deleted_at' => NULL,
                'accepted_at' => NULL,
            ),
            7 => 
            array (
                'id' => 271,
                'document_transaction_id' => 49,
                'receiver_id' => 1034,
                'seen_at' => NULL,
                'download_at' => NULL,
                'preview_at' => NULL,
                'created_by' => 0,
                'updated_by' => 0,
                'deleted_by' => 0,
                'created_at' => '2026-01-14 16:48:23',
                'updated_at' => '2026-01-14 16:48:23',
                'deleted_at' => NULL,
                'accepted_at' => NULL,
            ),
            8 => 
            array (
                'id' => 272,
                'document_transaction_id' => 49,
                'receiver_id' => 3035,
                'seen_at' => NULL,
                'download_at' => NULL,
                'preview_at' => NULL,
                'created_by' => 0,
                'updated_by' => 0,
                'deleted_by' => 0,
                'created_at' => '2026-01-14 16:48:23',
                'updated_at' => '2026-01-14 16:48:23',
                'deleted_at' => NULL,
                'accepted_at' => NULL,
            ),
            9 => 
            array (
                'id' => 273,
                'document_transaction_id' => 49,
                'receiver_id' => 3397,
                'seen_at' => NULL,
                'download_at' => NULL,
                'preview_at' => NULL,
                'created_by' => 0,
                'updated_by' => 0,
                'deleted_by' => 0,
                'created_at' => '2026-01-14 16:48:23',
                'updated_at' => '2026-01-14 16:48:23',
                'deleted_at' => NULL,
                'accepted_at' => NULL,
            ),
            10 => 
            array (
                'id' => 274,
                'document_transaction_id' => 49,
                'receiver_id' => 1078,
                'seen_at' => NULL,
                'download_at' => NULL,
                'preview_at' => NULL,
                'created_by' => 0,
                'updated_by' => 0,
                'deleted_by' => 0,
                'created_at' => '2026-01-14 16:48:23',
                'updated_at' => '2026-01-14 16:48:23',
                'deleted_at' => NULL,
                'accepted_at' => NULL,
            ),
            11 => 
            array (
                'id' => 275,
                'document_transaction_id' => 49,
                'receiver_id' => 203,
                'seen_at' => NULL,
                'download_at' => NULL,
                'preview_at' => NULL,
                'created_by' => 0,
                'updated_by' => 0,
                'deleted_by' => 0,
                'created_at' => '2026-01-14 16:48:23',
                'updated_at' => '2026-01-14 16:48:23',
                'deleted_at' => NULL,
                'accepted_at' => NULL,
            ),
            12 => 
            array (
                'id' => 276,
                'document_transaction_id' => 49,
                'receiver_id' => 306,
                'seen_at' => NULL,
                'download_at' => NULL,
                'preview_at' => NULL,
                'created_by' => 0,
                'updated_by' => 0,
                'deleted_by' => 0,
                'created_at' => '2026-01-14 16:48:23',
                'updated_at' => '2026-01-14 16:48:23',
                'deleted_at' => NULL,
                'accepted_at' => NULL,
            ),
            13 => 
            array (
                'id' => 277,
                'document_transaction_id' => 49,
                'receiver_id' => 3340,
                'seen_at' => NULL,
                'download_at' => NULL,
                'preview_at' => NULL,
                'created_by' => 0,
                'updated_by' => 0,
                'deleted_by' => 0,
                'created_at' => '2026-01-14 16:48:23',
                'updated_at' => '2026-01-14 16:48:23',
                'deleted_at' => NULL,
                'accepted_at' => NULL,
            ),
            14 => 
            array (
                'id' => 278,
                'document_transaction_id' => 50,
                'receiver_id' => 1506,
                'seen_at' => NULL,
                'download_at' => NULL,
                'preview_at' => NULL,
                'created_by' => 0,
                'updated_by' => 0,
                'deleted_by' => 0,
                'created_at' => '2026-01-14 16:48:23',
                'updated_at' => '2026-01-14 16:48:23',
                'deleted_at' => NULL,
                'accepted_at' => NULL,
            ),
            15 => 
            array (
                'id' => 279,
                'document_transaction_id' => 50,
                'receiver_id' => 1959,
                'seen_at' => NULL,
                'download_at' => NULL,
                'preview_at' => NULL,
                'created_by' => 0,
                'updated_by' => 0,
                'deleted_by' => 0,
                'created_at' => '2026-01-14 16:48:23',
                'updated_at' => '2026-01-14 16:48:23',
                'deleted_at' => NULL,
                'accepted_at' => NULL,
            ),
            16 => 
            array (
                'id' => 280,
                'document_transaction_id' => 50,
                'receiver_id' => 2033,
                'seen_at' => NULL,
                'download_at' => NULL,
                'preview_at' => NULL,
                'created_by' => 0,
                'updated_by' => 0,
                'deleted_by' => 0,
                'created_at' => '2026-01-14 16:48:23',
                'updated_at' => '2026-01-14 16:48:23',
                'deleted_at' => NULL,
                'accepted_at' => NULL,
            ),
            17 => 
            array (
                'id' => 281,
                'document_transaction_id' => 50,
                'receiver_id' => 2974,
                'seen_at' => NULL,
                'download_at' => NULL,
                'preview_at' => NULL,
                'created_by' => 0,
                'updated_by' => 0,
                'deleted_by' => 0,
                'created_at' => '2026-01-14 16:48:23',
                'updated_at' => '2026-01-14 16:48:23',
                'deleted_at' => NULL,
                'accepted_at' => NULL,
            ),
            18 => 
            array (
                'id' => 282,
                'document_transaction_id' => 50,
                'receiver_id' => 1413,
                'seen_at' => NULL,
                'download_at' => NULL,
                'preview_at' => NULL,
                'created_by' => 0,
                'updated_by' => 0,
                'deleted_by' => 0,
                'created_at' => '2026-01-14 16:48:23',
                'updated_at' => '2026-01-14 16:48:23',
                'deleted_at' => NULL,
                'accepted_at' => NULL,
            ),
            19 => 
            array (
                'id' => 283,
                'document_transaction_id' => 51,
                'receiver_id' => 1729,
                'seen_at' => NULL,
                'download_at' => NULL,
                'preview_at' => NULL,
                'created_by' => 0,
                'updated_by' => 0,
                'deleted_by' => 0,
                'created_at' => '2026-01-14 16:48:23',
                'updated_at' => '2026-01-14 16:48:23',
                'deleted_at' => NULL,
                'accepted_at' => NULL,
            ),
            20 => 
            array (
                'id' => 284,
                'document_transaction_id' => 51,
                'receiver_id' => 1485,
                'seen_at' => NULL,
                'download_at' => NULL,
                'preview_at' => NULL,
                'created_by' => 0,
                'updated_by' => 0,
                'deleted_by' => 0,
                'created_at' => '2026-01-14 16:48:23',
                'updated_at' => '2026-01-14 16:48:23',
                'deleted_at' => NULL,
                'accepted_at' => NULL,
            ),
            21 => 
            array (
                'id' => 285,
                'document_transaction_id' => 51,
                'receiver_id' => 3573,
                'seen_at' => NULL,
                'download_at' => NULL,
                'preview_at' => NULL,
                'created_by' => 0,
                'updated_by' => 0,
                'deleted_by' => 0,
                'created_at' => '2026-01-14 16:48:23',
                'updated_at' => '2026-01-14 16:48:23',
                'deleted_at' => NULL,
                'accepted_at' => NULL,
            ),
            22 => 
            array (
                'id' => 286,
                'document_transaction_id' => 51,
                'receiver_id' => 993,
                'seen_at' => NULL,
                'download_at' => NULL,
                'preview_at' => NULL,
                'created_by' => 0,
                'updated_by' => 0,
                'deleted_by' => 0,
                'created_at' => '2026-01-14 16:48:23',
                'updated_at' => '2026-01-14 16:48:23',
                'deleted_at' => NULL,
                'accepted_at' => NULL,
            ),
            23 => 
            array (
                'id' => 287,
                'document_transaction_id' => 52,
                'receiver_id' => 3402,
                'seen_at' => NULL,
                'download_at' => NULL,
                'preview_at' => NULL,
                'created_by' => 0,
                'updated_by' => 0,
                'deleted_by' => 0,
                'created_at' => '2026-01-14 16:48:23',
                'updated_at' => '2026-01-14 16:48:23',
                'deleted_at' => NULL,
                'accepted_at' => NULL,
            ),
            24 => 
            array (
                'id' => 288,
                'document_transaction_id' => 52,
                'receiver_id' => 3144,
                'seen_at' => NULL,
                'download_at' => NULL,
                'preview_at' => NULL,
                'created_by' => 0,
                'updated_by' => 0,
                'deleted_by' => 0,
                'created_at' => '2026-01-14 16:48:23',
                'updated_at' => '2026-01-14 16:48:23',
                'deleted_at' => NULL,
                'accepted_at' => NULL,
            ),
            25 => 
            array (
                'id' => 289,
                'document_transaction_id' => 52,
                'receiver_id' => 898,
                'seen_at' => NULL,
                'download_at' => NULL,
                'preview_at' => NULL,
                'created_by' => 0,
                'updated_by' => 0,
                'deleted_by' => 0,
                'created_at' => '2026-01-14 16:48:23',
                'updated_at' => '2026-01-14 16:48:23',
                'deleted_at' => NULL,
                'accepted_at' => NULL,
            ),
            26 => 
            array (
                'id' => 290,
                'document_transaction_id' => 52,
                'receiver_id' => 2299,
                'seen_at' => NULL,
                'download_at' => NULL,
                'preview_at' => NULL,
                'created_by' => 0,
                'updated_by' => 0,
                'deleted_by' => 0,
                'created_at' => '2026-01-14 16:48:23',
                'updated_at' => '2026-01-14 16:48:23',
                'deleted_at' => NULL,
                'accepted_at' => NULL,
            ),
            27 => 
            array (
                'id' => 291,
                'document_transaction_id' => 52,
                'receiver_id' => 2835,
                'seen_at' => NULL,
                'download_at' => NULL,
                'preview_at' => NULL,
                'created_by' => 0,
                'updated_by' => 0,
                'deleted_by' => 0,
                'created_at' => '2026-01-14 16:48:23',
                'updated_at' => '2026-01-14 16:48:23',
                'deleted_at' => NULL,
                'accepted_at' => NULL,
            ),
            28 => 
            array (
                'id' => 292,
                'document_transaction_id' => 52,
                'receiver_id' => 2709,
                'seen_at' => NULL,
                'download_at' => NULL,
                'preview_at' => NULL,
                'created_by' => 0,
                'updated_by' => 0,
                'deleted_by' => 0,
                'created_at' => '2026-01-14 16:48:23',
                'updated_at' => '2026-01-14 16:48:23',
                'deleted_at' => NULL,
                'accepted_at' => NULL,
            ),
            29 => 
            array (
                'id' => 293,
                'document_transaction_id' => 52,
                'receiver_id' => 2290,
                'seen_at' => NULL,
                'download_at' => NULL,
                'preview_at' => NULL,
                'created_by' => 0,
                'updated_by' => 0,
                'deleted_by' => 0,
                'created_at' => '2026-01-14 16:48:23',
                'updated_at' => '2026-01-14 16:48:23',
                'deleted_at' => NULL,
                'accepted_at' => NULL,
            ),
            30 => 
            array (
                'id' => 294,
                'document_transaction_id' => 52,
                'receiver_id' => 151,
                'seen_at' => NULL,
                'download_at' => NULL,
                'preview_at' => NULL,
                'created_by' => 0,
                'updated_by' => 0,
                'deleted_by' => 0,
                'created_at' => '2026-01-14 16:48:23',
                'updated_at' => '2026-01-14 16:48:23',
                'deleted_at' => NULL,
                'accepted_at' => NULL,
            ),
            31 => 
            array (
                'id' => 295,
                'document_transaction_id' => 52,
                'receiver_id' => 3415,
                'seen_at' => NULL,
                'download_at' => NULL,
                'preview_at' => NULL,
                'created_by' => 0,
                'updated_by' => 0,
                'deleted_by' => 0,
                'created_at' => '2026-01-14 16:48:23',
                'updated_at' => '2026-01-14 16:48:23',
                'deleted_at' => NULL,
                'accepted_at' => NULL,
            ),
            32 => 
            array (
                'id' => 296,
                'document_transaction_id' => 53,
                'receiver_id' => 3621,
                'seen_at' => NULL,
                'download_at' => NULL,
                'preview_at' => NULL,
                'created_by' => 0,
                'updated_by' => 0,
                'deleted_by' => 0,
                'created_at' => '2026-01-14 16:48:23',
                'updated_at' => '2026-01-14 16:48:23',
                'deleted_at' => NULL,
                'accepted_at' => NULL,
            ),
            33 => 
            array (
                'id' => 297,
                'document_transaction_id' => 53,
                'receiver_id' => 596,
                'seen_at' => NULL,
                'download_at' => NULL,
                'preview_at' => NULL,
                'created_by' => 0,
                'updated_by' => 0,
                'deleted_by' => 0,
                'created_at' => '2026-01-14 16:48:23',
                'updated_at' => '2026-01-14 16:48:23',
                'deleted_at' => NULL,
                'accepted_at' => NULL,
            ),
            34 => 
            array (
                'id' => 298,
                'document_transaction_id' => 53,
                'receiver_id' => 2192,
                'seen_at' => NULL,
                'download_at' => NULL,
                'preview_at' => NULL,
                'created_by' => 0,
                'updated_by' => 0,
                'deleted_by' => 0,
                'created_at' => '2026-01-14 16:48:23',
                'updated_at' => '2026-01-14 16:48:23',
                'deleted_at' => NULL,
                'accepted_at' => NULL,
            ),
            35 => 
            array (
                'id' => 299,
                'document_transaction_id' => 53,
                'receiver_id' => 2207,
                'seen_at' => NULL,
                'download_at' => NULL,
                'preview_at' => NULL,
                'created_by' => 0,
                'updated_by' => 0,
                'deleted_by' => 0,
                'created_at' => '2026-01-14 16:48:23',
                'updated_at' => '2026-01-14 16:48:23',
                'deleted_at' => NULL,
                'accepted_at' => NULL,
            ),
            36 => 
            array (
                'id' => 300,
                'document_transaction_id' => 53,
                'receiver_id' => 2690,
                'seen_at' => NULL,
                'download_at' => NULL,
                'preview_at' => NULL,
                'created_by' => 0,
                'updated_by' => 0,
                'deleted_by' => 0,
                'created_at' => '2026-01-14 16:48:23',
                'updated_at' => '2026-01-14 16:48:23',
                'deleted_at' => NULL,
                'accepted_at' => NULL,
            ),
            37 => 
            array (
                'id' => 301,
                'document_transaction_id' => 53,
                'receiver_id' => 3613,
                'seen_at' => NULL,
                'download_at' => NULL,
                'preview_at' => NULL,
                'created_by' => 0,
                'updated_by' => 0,
                'deleted_by' => 0,
                'created_at' => '2026-01-14 16:48:23',
                'updated_at' => '2026-01-14 16:48:23',
                'deleted_at' => NULL,
                'accepted_at' => NULL,
            ),
            38 => 
            array (
                'id' => 302,
                'document_transaction_id' => 53,
                'receiver_id' => 41,
                'seen_at' => NULL,
                'download_at' => NULL,
                'preview_at' => NULL,
                'created_by' => 0,
                'updated_by' => 0,
                'deleted_by' => 0,
                'created_at' => '2026-01-14 16:48:23',
                'updated_at' => '2026-01-14 16:48:23',
                'deleted_at' => NULL,
                'accepted_at' => NULL,
            ),
            39 => 
            array (
                'id' => 303,
                'document_transaction_id' => 53,
                'receiver_id' => 3779,
                'seen_at' => NULL,
                'download_at' => NULL,
                'preview_at' => NULL,
                'created_by' => 0,
                'updated_by' => 0,
                'deleted_by' => 0,
                'created_at' => '2026-01-14 16:48:23',
                'updated_at' => '2026-01-14 16:48:23',
                'deleted_at' => NULL,
                'accepted_at' => NULL,
            ),
            40 => 
            array (
                'id' => 304,
                'document_transaction_id' => 53,
                'receiver_id' => 3004,
                'seen_at' => NULL,
                'download_at' => NULL,
                'preview_at' => NULL,
                'created_by' => 0,
                'updated_by' => 0,
                'deleted_by' => 0,
                'created_at' => '2026-01-14 16:48:23',
                'updated_at' => '2026-01-14 16:48:23',
                'deleted_at' => NULL,
                'accepted_at' => NULL,
            ),
            41 => 
            array (
                'id' => 305,
                'document_transaction_id' => 54,
                'receiver_id' => 1055,
                'seen_at' => NULL,
                'download_at' => NULL,
                'preview_at' => NULL,
                'created_by' => 0,
                'updated_by' => 0,
                'deleted_by' => 0,
                'created_at' => '2026-01-14 16:48:23',
                'updated_at' => '2026-01-14 16:48:23',
                'deleted_at' => NULL,
                'accepted_at' => NULL,
            ),
            42 => 
            array (
                'id' => 306,
                'document_transaction_id' => 55,
                'receiver_id' => 3531,
                'seen_at' => NULL,
                'download_at' => NULL,
                'preview_at' => NULL,
                'created_by' => 0,
                'updated_by' => 0,
                'deleted_by' => 0,
                'created_at' => '2026-01-14 16:48:23',
                'updated_at' => '2026-01-14 16:48:23',
                'deleted_at' => NULL,
                'accepted_at' => NULL,
            ),
            43 => 
            array (
                'id' => 307,
                'document_transaction_id' => 55,
                'receiver_id' => 3065,
                'seen_at' => NULL,
                'download_at' => NULL,
                'preview_at' => NULL,
                'created_by' => 0,
                'updated_by' => 0,
                'deleted_by' => 0,
                'created_at' => '2026-01-14 16:48:23',
                'updated_at' => '2026-01-14 16:48:23',
                'deleted_at' => NULL,
                'accepted_at' => NULL,
            ),
            44 => 
            array (
                'id' => 308,
                'document_transaction_id' => 55,
                'receiver_id' => 3317,
                'seen_at' => NULL,
                'download_at' => NULL,
                'preview_at' => NULL,
                'created_by' => 0,
                'updated_by' => 0,
                'deleted_by' => 0,
                'created_at' => '2026-01-14 16:48:23',
                'updated_at' => '2026-01-14 16:48:23',
                'deleted_at' => NULL,
                'accepted_at' => NULL,
            ),
            45 => 
            array (
                'id' => 309,
                'document_transaction_id' => 55,
                'receiver_id' => 1761,
                'seen_at' => NULL,
                'download_at' => NULL,
                'preview_at' => NULL,
                'created_by' => 0,
                'updated_by' => 0,
                'deleted_by' => 0,
                'created_at' => '2026-01-14 16:48:23',
                'updated_at' => '2026-01-14 16:48:23',
                'deleted_at' => NULL,
                'accepted_at' => NULL,
            ),
            46 => 
            array (
                'id' => 310,
                'document_transaction_id' => 55,
                'receiver_id' => 3085,
                'seen_at' => NULL,
                'download_at' => NULL,
                'preview_at' => NULL,
                'created_by' => 0,
                'updated_by' => 0,
                'deleted_by' => 0,
                'created_at' => '2026-01-14 16:48:23',
                'updated_at' => '2026-01-14 16:48:23',
                'deleted_at' => NULL,
                'accepted_at' => NULL,
            ),
            47 => 
            array (
                'id' => 311,
                'document_transaction_id' => 55,
                'receiver_id' => 3654,
                'seen_at' => NULL,
                'download_at' => NULL,
                'preview_at' => NULL,
                'created_by' => 0,
                'updated_by' => 0,
                'deleted_by' => 0,
                'created_at' => '2026-01-14 16:48:23',
                'updated_at' => '2026-01-14 16:48:23',
                'deleted_at' => NULL,
                'accepted_at' => NULL,
            ),
            48 => 
            array (
                'id' => 312,
                'document_transaction_id' => 56,
                'receiver_id' => 1297,
                'seen_at' => NULL,
                'download_at' => NULL,
                'preview_at' => NULL,
                'created_by' => 0,
                'updated_by' => 0,
                'deleted_by' => 0,
                'created_at' => '2026-01-14 16:48:23',
                'updated_at' => '2026-01-14 16:48:23',
                'deleted_at' => NULL,
                'accepted_at' => NULL,
            ),
            49 => 
            array (
                'id' => 313,
                'document_transaction_id' => 56,
                'receiver_id' => 2776,
                'seen_at' => NULL,
                'download_at' => NULL,
                'preview_at' => NULL,
                'created_by' => 0,
                'updated_by' => 0,
                'deleted_by' => 0,
                'created_at' => '2026-01-14 16:48:23',
                'updated_at' => '2026-01-14 16:48:23',
                'deleted_at' => NULL,
                'accepted_at' => NULL,
            ),
            50 => 
            array (
                'id' => 314,
                'document_transaction_id' => 56,
                'receiver_id' => 819,
                'seen_at' => NULL,
                'download_at' => NULL,
                'preview_at' => NULL,
                'created_by' => 0,
                'updated_by' => 0,
                'deleted_by' => 0,
                'created_at' => '2026-01-14 16:48:23',
                'updated_at' => '2026-01-14 16:48:23',
                'deleted_at' => NULL,
                'accepted_at' => NULL,
            ),
            51 => 
            array (
                'id' => 315,
                'document_transaction_id' => 57,
                'receiver_id' => 3325,
                'seen_at' => NULL,
                'download_at' => NULL,
                'preview_at' => NULL,
                'created_by' => 0,
                'updated_by' => 0,
                'deleted_by' => 0,
                'created_at' => '2026-01-14 16:48:23',
                'updated_at' => '2026-01-14 16:48:23',
                'deleted_at' => NULL,
                'accepted_at' => NULL,
            ),
            52 => 
            array (
                'id' => 316,
                'document_transaction_id' => 57,
                'receiver_id' => 1646,
                'seen_at' => NULL,
                'download_at' => NULL,
                'preview_at' => NULL,
                'created_by' => 0,
                'updated_by' => 0,
                'deleted_by' => 0,
                'created_at' => '2026-01-14 16:48:23',
                'updated_at' => '2026-01-14 16:48:23',
                'deleted_at' => NULL,
                'accepted_at' => NULL,
            ),
            53 => 
            array (
                'id' => 317,
                'document_transaction_id' => 57,
                'receiver_id' => 676,
                'seen_at' => NULL,
                'download_at' => NULL,
                'preview_at' => NULL,
                'created_by' => 0,
                'updated_by' => 0,
                'deleted_by' => 0,
                'created_at' => '2026-01-14 16:48:23',
                'updated_at' => '2026-01-14 16:48:23',
                'deleted_at' => NULL,
                'accepted_at' => NULL,
            ),
            54 => 
            array (
                'id' => 318,
                'document_transaction_id' => 57,
                'receiver_id' => 1369,
                'seen_at' => NULL,
                'download_at' => NULL,
                'preview_at' => NULL,
                'created_by' => 0,
                'updated_by' => 0,
                'deleted_by' => 0,
                'created_at' => '2026-01-14 16:48:23',
                'updated_at' => '2026-01-14 16:48:23',
                'deleted_at' => NULL,
                'accepted_at' => NULL,
            ),
            55 => 
            array (
                'id' => 319,
                'document_transaction_id' => 57,
                'receiver_id' => 1865,
                'seen_at' => NULL,
                'download_at' => NULL,
                'preview_at' => NULL,
                'created_by' => 0,
                'updated_by' => 0,
                'deleted_by' => 0,
                'created_at' => '2026-01-14 16:48:23',
                'updated_at' => '2026-01-14 16:48:23',
                'deleted_at' => NULL,
                'accepted_at' => NULL,
            ),
            56 => 
            array (
                'id' => 320,
                'document_transaction_id' => 57,
                'receiver_id' => 860,
                'seen_at' => NULL,
                'download_at' => NULL,
                'preview_at' => NULL,
                'created_by' => 0,
                'updated_by' => 0,
                'deleted_by' => 0,
                'created_at' => '2026-01-14 16:48:23',
                'updated_at' => '2026-01-14 16:48:23',
                'deleted_at' => NULL,
                'accepted_at' => NULL,
            ),
            57 => 
            array (
                'id' => 321,
                'document_transaction_id' => 57,
                'receiver_id' => 969,
                'seen_at' => NULL,
                'download_at' => NULL,
                'preview_at' => NULL,
                'created_by' => 0,
                'updated_by' => 0,
                'deleted_by' => 0,
                'created_at' => '2026-01-14 16:48:23',
                'updated_at' => '2026-01-14 16:48:23',
                'deleted_at' => NULL,
                'accepted_at' => NULL,
            ),
            58 => 
            array (
                'id' => 322,
                'document_transaction_id' => 57,
                'receiver_id' => 3133,
                'seen_at' => NULL,
                'download_at' => NULL,
                'preview_at' => NULL,
                'created_by' => 0,
                'updated_by' => 0,
                'deleted_by' => 0,
                'created_at' => '2026-01-14 16:48:23',
                'updated_at' => '2026-01-14 16:48:23',
                'deleted_at' => NULL,
                'accepted_at' => NULL,
            ),
            59 => 
            array (
                'id' => 323,
                'document_transaction_id' => 58,
                'receiver_id' => 1063,
                'seen_at' => NULL,
                'download_at' => NULL,
                'preview_at' => NULL,
                'created_by' => 0,
                'updated_by' => 0,
                'deleted_by' => 0,
                'created_at' => '2026-01-14 16:48:23',
                'updated_at' => '2026-01-14 16:48:23',
                'deleted_at' => NULL,
                'accepted_at' => NULL,
            ),
            60 => 
            array (
                'id' => 324,
                'document_transaction_id' => 58,
                'receiver_id' => 3596,
                'seen_at' => NULL,
                'download_at' => NULL,
                'preview_at' => NULL,
                'created_by' => 0,
                'updated_by' => 0,
                'deleted_by' => 0,
                'created_at' => '2026-01-14 16:48:23',
                'updated_at' => '2026-01-14 16:48:23',
                'deleted_at' => NULL,
                'accepted_at' => NULL,
            ),
            61 => 
            array (
                'id' => 325,
                'document_transaction_id' => 58,
                'receiver_id' => 1724,
                'seen_at' => NULL,
                'download_at' => NULL,
                'preview_at' => NULL,
                'created_by' => 0,
                'updated_by' => 0,
                'deleted_by' => 0,
                'created_at' => '2026-01-14 16:48:23',
                'updated_at' => '2026-01-14 16:48:23',
                'deleted_at' => NULL,
                'accepted_at' => NULL,
            ),
            62 => 
            array (
                'id' => 326,
                'document_transaction_id' => 58,
                'receiver_id' => 1218,
                'seen_at' => NULL,
                'download_at' => NULL,
                'preview_at' => NULL,
                'created_by' => 0,
                'updated_by' => 0,
                'deleted_by' => 0,
                'created_at' => '2026-01-14 16:48:23',
                'updated_at' => '2026-01-14 16:48:23',
                'deleted_at' => NULL,
                'accepted_at' => NULL,
            ),
            63 => 
            array (
                'id' => 327,
                'document_transaction_id' => 58,
                'receiver_id' => 2155,
                'seen_at' => NULL,
                'download_at' => NULL,
                'preview_at' => NULL,
                'created_by' => 0,
                'updated_by' => 0,
                'deleted_by' => 0,
                'created_at' => '2026-01-14 16:48:23',
                'updated_at' => '2026-01-14 16:48:23',
                'deleted_at' => NULL,
                'accepted_at' => NULL,
            ),
            64 => 
            array (
                'id' => 328,
                'document_transaction_id' => 58,
                'receiver_id' => 3048,
                'seen_at' => NULL,
                'download_at' => NULL,
                'preview_at' => NULL,
                'created_by' => 0,
                'updated_by' => 0,
                'deleted_by' => 0,
                'created_at' => '2026-01-14 16:48:23',
                'updated_at' => '2026-01-14 16:48:23',
                'deleted_at' => NULL,
                'accepted_at' => NULL,
            ),
            65 => 
            array (
                'id' => 329,
                'document_transaction_id' => 59,
                'receiver_id' => 551,
                'seen_at' => NULL,
                'download_at' => NULL,
                'preview_at' => NULL,
                'created_by' => 0,
                'updated_by' => 0,
                'deleted_by' => 0,
                'created_at' => '2026-01-14 16:48:23',
                'updated_at' => '2026-01-14 16:48:23',
                'deleted_at' => NULL,
                'accepted_at' => NULL,
            ),
            66 => 
            array (
                'id' => 330,
                'document_transaction_id' => 59,
                'receiver_id' => 2284,
                'seen_at' => NULL,
                'download_at' => NULL,
                'preview_at' => NULL,
                'created_by' => 0,
                'updated_by' => 0,
                'deleted_by' => 0,
                'created_at' => '2026-01-14 16:48:23',
                'updated_at' => '2026-01-14 16:48:23',
                'deleted_at' => NULL,
                'accepted_at' => NULL,
            ),
            67 => 
            array (
                'id' => 331,
                'document_transaction_id' => 59,
                'receiver_id' => 2678,
                'seen_at' => NULL,
                'download_at' => NULL,
                'preview_at' => NULL,
                'created_by' => 0,
                'updated_by' => 0,
                'deleted_by' => 0,
                'created_at' => '2026-01-14 16:48:23',
                'updated_at' => '2026-01-14 16:48:23',
                'deleted_at' => NULL,
                'accepted_at' => NULL,
            ),
            68 => 
            array (
                'id' => 332,
                'document_transaction_id' => 59,
                'receiver_id' => 461,
                'seen_at' => NULL,
                'download_at' => NULL,
                'preview_at' => NULL,
                'created_by' => 0,
                'updated_by' => 0,
                'deleted_by' => 0,
                'created_at' => '2026-01-14 16:48:23',
                'updated_at' => '2026-01-14 16:48:23',
                'deleted_at' => NULL,
                'accepted_at' => NULL,
            ),
            69 => 
            array (
                'id' => 333,
                'document_transaction_id' => 59,
                'receiver_id' => 1998,
                'seen_at' => NULL,
                'download_at' => NULL,
                'preview_at' => NULL,
                'created_by' => 0,
                'updated_by' => 0,
                'deleted_by' => 0,
                'created_at' => '2026-01-14 16:48:23',
                'updated_at' => '2026-01-14 16:48:23',
                'deleted_at' => NULL,
                'accepted_at' => NULL,
            ),
            70 => 
            array (
                'id' => 334,
                'document_transaction_id' => 59,
                'receiver_id' => 766,
                'seen_at' => NULL,
                'download_at' => NULL,
                'preview_at' => NULL,
                'created_by' => 0,
                'updated_by' => 0,
                'deleted_by' => 0,
                'created_at' => '2026-01-14 16:48:23',
                'updated_at' => '2026-01-14 16:48:23',
                'deleted_at' => NULL,
                'accepted_at' => NULL,
            ),
            71 => 
            array (
                'id' => 335,
                'document_transaction_id' => 59,
                'receiver_id' => 909,
                'seen_at' => NULL,
                'download_at' => NULL,
                'preview_at' => NULL,
                'created_by' => 0,
                'updated_by' => 0,
                'deleted_by' => 0,
                'created_at' => '2026-01-14 16:48:23',
                'updated_at' => '2026-01-14 16:48:23',
                'deleted_at' => NULL,
                'accepted_at' => NULL,
            ),
            72 => 
            array (
                'id' => 336,
                'document_transaction_id' => 59,
                'receiver_id' => 1914,
                'seen_at' => NULL,
                'download_at' => NULL,
                'preview_at' => NULL,
                'created_by' => 0,
                'updated_by' => 0,
                'deleted_by' => 0,
                'created_at' => '2026-01-14 16:48:23',
                'updated_at' => '2026-01-14 16:48:23',
                'deleted_at' => NULL,
                'accepted_at' => NULL,
            ),
            73 => 
            array (
                'id' => 337,
                'document_transaction_id' => 60,
                'receiver_id' => 3437,
                'seen_at' => NULL,
                'download_at' => NULL,
                'preview_at' => NULL,
                'created_by' => 0,
                'updated_by' => 0,
                'deleted_by' => 0,
                'created_at' => '2026-01-14 16:48:23',
                'updated_at' => '2026-01-14 16:48:23',
                'deleted_at' => NULL,
                'accepted_at' => NULL,
            ),
            74 => 
            array (
                'id' => 338,
                'document_transaction_id' => 60,
                'receiver_id' => 1650,
                'seen_at' => NULL,
                'download_at' => NULL,
                'preview_at' => NULL,
                'created_by' => 0,
                'updated_by' => 0,
                'deleted_by' => 0,
                'created_at' => '2026-01-14 16:48:23',
                'updated_at' => '2026-01-14 16:48:23',
                'deleted_at' => NULL,
                'accepted_at' => NULL,
            ),
            75 => 
            array (
                'id' => 339,
                'document_transaction_id' => 60,
                'receiver_id' => 2042,
                'seen_at' => NULL,
                'download_at' => NULL,
                'preview_at' => NULL,
                'created_by' => 0,
                'updated_by' => 0,
                'deleted_by' => 0,
                'created_at' => '2026-01-14 16:48:23',
                'updated_at' => '2026-01-14 16:48:23',
                'deleted_at' => NULL,
                'accepted_at' => NULL,
            ),
            76 => 
            array (
                'id' => 340,
                'document_transaction_id' => 60,
                'receiver_id' => 630,
                'seen_at' => NULL,
                'download_at' => NULL,
                'preview_at' => NULL,
                'created_by' => 0,
                'updated_by' => 0,
                'deleted_by' => 0,
                'created_at' => '2026-01-14 16:48:23',
                'updated_at' => '2026-01-14 16:48:23',
                'deleted_at' => NULL,
                'accepted_at' => NULL,
            ),
            77 => 
            array (
                'id' => 341,
                'document_transaction_id' => 60,
                'receiver_id' => 2658,
                'seen_at' => NULL,
                'download_at' => NULL,
                'preview_at' => NULL,
                'created_by' => 0,
                'updated_by' => 0,
                'deleted_by' => 0,
                'created_at' => '2026-01-14 16:48:23',
                'updated_at' => '2026-01-14 16:48:23',
                'deleted_at' => NULL,
                'accepted_at' => NULL,
            ),
            78 => 
            array (
                'id' => 342,
                'document_transaction_id' => 60,
                'receiver_id' => 501,
                'seen_at' => NULL,
                'download_at' => NULL,
                'preview_at' => NULL,
                'created_by' => 0,
                'updated_by' => 0,
                'deleted_by' => 0,
                'created_at' => '2026-01-14 16:48:23',
                'updated_at' => '2026-01-14 16:48:23',
                'deleted_at' => NULL,
                'accepted_at' => NULL,
            ),
            79 => 
            array (
                'id' => 343,
                'document_transaction_id' => 60,
                'receiver_id' => 3669,
                'seen_at' => NULL,
                'download_at' => NULL,
                'preview_at' => NULL,
                'created_by' => 0,
                'updated_by' => 0,
                'deleted_by' => 0,
                'created_at' => '2026-01-14 16:48:23',
                'updated_at' => '2026-01-14 16:48:23',
                'deleted_at' => NULL,
                'accepted_at' => NULL,
            ),
            80 => 
            array (
                'id' => 344,
                'document_transaction_id' => 60,
                'receiver_id' => 2813,
                'seen_at' => NULL,
                'download_at' => NULL,
                'preview_at' => NULL,
                'created_by' => 0,
                'updated_by' => 0,
                'deleted_by' => 0,
                'created_at' => '2026-01-14 16:48:23',
                'updated_at' => '2026-01-14 16:48:23',
                'deleted_at' => NULL,
                'accepted_at' => NULL,
            ),
            81 => 
            array (
                'id' => 345,
                'document_transaction_id' => 60,
                'receiver_id' => 1883,
                'seen_at' => NULL,
                'download_at' => NULL,
                'preview_at' => NULL,
                'created_by' => 0,
                'updated_by' => 0,
                'deleted_by' => 0,
                'created_at' => '2026-01-14 16:48:23',
                'updated_at' => '2026-01-14 16:48:23',
                'deleted_at' => NULL,
                'accepted_at' => NULL,
            ),
            82 => 
            array (
                'id' => 346,
                'document_transaction_id' => 60,
                'receiver_id' => 447,
                'seen_at' => NULL,
                'download_at' => NULL,
                'preview_at' => NULL,
                'created_by' => 0,
                'updated_by' => 0,
                'deleted_by' => 0,
                'created_at' => '2026-01-14 16:48:23',
                'updated_at' => '2026-01-14 16:48:23',
                'deleted_at' => NULL,
                'accepted_at' => NULL,
            ),
            83 => 
            array (
                'id' => 347,
                'document_transaction_id' => 61,
                'receiver_id' => 3754,
                'seen_at' => NULL,
                'download_at' => NULL,
                'preview_at' => NULL,
                'created_by' => 0,
                'updated_by' => 0,
                'deleted_by' => 0,
                'created_at' => '2026-01-14 16:48:23',
                'updated_at' => '2026-01-14 16:48:23',
                'deleted_at' => NULL,
                'accepted_at' => NULL,
            ),
            84 => 
            array (
                'id' => 348,
                'document_transaction_id' => 61,
                'receiver_id' => 2804,
                'seen_at' => NULL,
                'download_at' => NULL,
                'preview_at' => NULL,
                'created_by' => 0,
                'updated_by' => 0,
                'deleted_by' => 0,
                'created_at' => '2026-01-14 16:48:23',
                'updated_at' => '2026-01-14 16:48:23',
                'deleted_at' => NULL,
                'accepted_at' => NULL,
            ),
            85 => 
            array (
                'id' => 349,
                'document_transaction_id' => 61,
                'receiver_id' => 2961,
                'seen_at' => NULL,
                'download_at' => NULL,
                'preview_at' => NULL,
                'created_by' => 0,
                'updated_by' => 0,
                'deleted_by' => 0,
                'created_at' => '2026-01-14 16:48:23',
                'updated_at' => '2026-01-14 16:48:23',
                'deleted_at' => NULL,
                'accepted_at' => NULL,
            ),
            86 => 
            array (
                'id' => 350,
                'document_transaction_id' => 61,
                'receiver_id' => 3044,
                'seen_at' => NULL,
                'download_at' => NULL,
                'preview_at' => NULL,
                'created_by' => 0,
                'updated_by' => 0,
                'deleted_by' => 0,
                'created_at' => '2026-01-14 16:48:23',
                'updated_at' => '2026-01-14 16:48:23',
                'deleted_at' => NULL,
                'accepted_at' => NULL,
            ),
            87 => 
            array (
                'id' => 351,
                'document_transaction_id' => 61,
                'receiver_id' => 3792,
                'seen_at' => NULL,
                'download_at' => NULL,
                'preview_at' => NULL,
                'created_by' => 0,
                'updated_by' => 0,
                'deleted_by' => 0,
                'created_at' => '2026-01-14 16:48:23',
                'updated_at' => '2026-01-14 16:48:23',
                'deleted_at' => NULL,
                'accepted_at' => NULL,
            ),
            88 => 
            array (
                'id' => 352,
                'document_transaction_id' => 61,
                'receiver_id' => 1547,
                'seen_at' => NULL,
                'download_at' => NULL,
                'preview_at' => NULL,
                'created_by' => 0,
                'updated_by' => 0,
                'deleted_by' => 0,
                'created_at' => '2026-01-14 16:48:23',
                'updated_at' => '2026-01-14 16:48:23',
                'deleted_at' => NULL,
                'accepted_at' => NULL,
            ),
            89 => 
            array (
                'id' => 353,
                'document_transaction_id' => 62,
                'receiver_id' => 952,
                'seen_at' => NULL,
                'download_at' => NULL,
                'preview_at' => NULL,
                'created_by' => 0,
                'updated_by' => 0,
                'deleted_by' => 0,
                'created_at' => '2026-01-14 16:48:23',
                'updated_at' => '2026-01-14 16:48:23',
                'deleted_at' => NULL,
                'accepted_at' => NULL,
            ),
            90 => 
            array (
                'id' => 354,
                'document_transaction_id' => 62,
                'receiver_id' => 3722,
                'seen_at' => NULL,
                'download_at' => NULL,
                'preview_at' => NULL,
                'created_by' => 0,
                'updated_by' => 0,
                'deleted_by' => 0,
                'created_at' => '2026-01-14 16:48:23',
                'updated_at' => '2026-01-14 16:48:23',
                'deleted_at' => NULL,
                'accepted_at' => NULL,
            ),
            91 => 
            array (
                'id' => 355,
                'document_transaction_id' => 62,
                'receiver_id' => 3061,
                'seen_at' => NULL,
                'download_at' => NULL,
                'preview_at' => NULL,
                'created_by' => 0,
                'updated_by' => 0,
                'deleted_by' => 0,
                'created_at' => '2026-01-14 16:48:23',
                'updated_at' => '2026-01-14 16:48:23',
                'deleted_at' => NULL,
                'accepted_at' => NULL,
            ),
            92 => 
            array (
                'id' => 356,
                'document_transaction_id' => 63,
                'receiver_id' => 2688,
                'seen_at' => NULL,
                'download_at' => NULL,
                'preview_at' => NULL,
                'created_by' => 0,
                'updated_by' => 0,
                'deleted_by' => 0,
                'created_at' => '2026-01-14 16:48:23',
                'updated_at' => '2026-01-14 16:48:23',
                'deleted_at' => NULL,
                'accepted_at' => NULL,
            ),
            93 => 
            array (
                'id' => 357,
                'document_transaction_id' => 63,
                'receiver_id' => 3504,
                'seen_at' => NULL,
                'download_at' => NULL,
                'preview_at' => NULL,
                'created_by' => 0,
                'updated_by' => 0,
                'deleted_by' => 0,
                'created_at' => '2026-01-14 16:48:23',
                'updated_at' => '2026-01-14 16:48:23',
                'deleted_at' => NULL,
                'accepted_at' => NULL,
            ),
            94 => 
            array (
                'id' => 358,
                'document_transaction_id' => 63,
                'receiver_id' => 564,
                'seen_at' => NULL,
                'download_at' => NULL,
                'preview_at' => NULL,
                'created_by' => 0,
                'updated_by' => 0,
                'deleted_by' => 0,
                'created_at' => '2026-01-14 16:48:23',
                'updated_at' => '2026-01-14 16:48:23',
                'deleted_at' => NULL,
                'accepted_at' => NULL,
            ),
            95 => 
            array (
                'id' => 359,
                'document_transaction_id' => 64,
                'receiver_id' => 2813,
                'seen_at' => NULL,
                'download_at' => NULL,
                'preview_at' => NULL,
                'created_by' => 0,
                'updated_by' => 0,
                'deleted_by' => 0,
                'created_at' => '2026-01-14 16:48:23',
                'updated_at' => '2026-01-14 16:48:23',
                'deleted_at' => NULL,
                'accepted_at' => NULL,
            ),
            96 => 
            array (
                'id' => 360,
                'document_transaction_id' => 64,
                'receiver_id' => 1527,
                'seen_at' => NULL,
                'download_at' => NULL,
                'preview_at' => NULL,
                'created_by' => 0,
                'updated_by' => 0,
                'deleted_by' => 0,
                'created_at' => '2026-01-14 16:48:23',
                'updated_at' => '2026-01-14 16:48:23',
                'deleted_at' => NULL,
                'accepted_at' => NULL,
            ),
            97 => 
            array (
                'id' => 361,
                'document_transaction_id' => 64,
                'receiver_id' => 1240,
                'seen_at' => NULL,
                'download_at' => NULL,
                'preview_at' => NULL,
                'created_by' => 0,
                'updated_by' => 0,
                'deleted_by' => 0,
                'created_at' => '2026-01-14 16:48:23',
                'updated_at' => '2026-01-14 16:48:23',
                'deleted_at' => NULL,
                'accepted_at' => NULL,
            ),
            98 => 
            array (
                'id' => 362,
                'document_transaction_id' => 64,
                'receiver_id' => 1175,
                'seen_at' => NULL,
                'download_at' => NULL,
                'preview_at' => NULL,
                'created_by' => 0,
                'updated_by' => 0,
                'deleted_by' => 0,
                'created_at' => '2026-01-14 16:48:23',
                'updated_at' => '2026-01-14 16:48:23',
                'deleted_at' => NULL,
                'accepted_at' => NULL,
            ),
            99 => 
            array (
                'id' => 363,
                'document_transaction_id' => 64,
                'receiver_id' => 3168,
                'seen_at' => NULL,
                'download_at' => NULL,
                'preview_at' => NULL,
                'created_by' => 0,
                'updated_by' => 0,
                'deleted_by' => 0,
                'created_at' => '2026-01-14 16:48:23',
                'updated_at' => '2026-01-14 16:48:23',
                'deleted_at' => NULL,
                'accepted_at' => NULL,
            ),
            100 => 
            array (
                'id' => 364,
                'document_transaction_id' => 64,
                'receiver_id' => 887,
                'seen_at' => NULL,
                'download_at' => NULL,
                'preview_at' => NULL,
                'created_by' => 0,
                'updated_by' => 0,
                'deleted_by' => 0,
                'created_at' => '2026-01-14 16:48:23',
                'updated_at' => '2026-01-14 16:48:23',
                'deleted_at' => NULL,
                'accepted_at' => NULL,
            ),
            101 => 
            array (
                'id' => 365,
                'document_transaction_id' => 65,
                'receiver_id' => 3068,
                'seen_at' => NULL,
                'download_at' => NULL,
                'preview_at' => NULL,
                'created_by' => 0,
                'updated_by' => 0,
                'deleted_by' => 0,
                'created_at' => '2026-01-14 16:48:23',
                'updated_at' => '2026-01-14 16:48:23',
                'deleted_at' => NULL,
                'accepted_at' => NULL,
            ),
            102 => 
            array (
                'id' => 366,
                'document_transaction_id' => 65,
                'receiver_id' => 3815,
                'seen_at' => NULL,
                'download_at' => NULL,
                'preview_at' => NULL,
                'created_by' => 0,
                'updated_by' => 0,
                'deleted_by' => 0,
                'created_at' => '2026-01-14 16:48:23',
                'updated_at' => '2026-01-14 16:48:23',
                'deleted_at' => NULL,
                'accepted_at' => NULL,
            ),
            103 => 
            array (
                'id' => 367,
                'document_transaction_id' => 65,
                'receiver_id' => 2262,
                'seen_at' => NULL,
                'download_at' => NULL,
                'preview_at' => NULL,
                'created_by' => 0,
                'updated_by' => 0,
                'deleted_by' => 0,
                'created_at' => '2026-01-14 16:48:23',
                'updated_at' => '2026-01-14 16:48:23',
                'deleted_at' => NULL,
                'accepted_at' => NULL,
            ),
            104 => 
            array (
                'id' => 368,
                'document_transaction_id' => 65,
                'receiver_id' => 779,
                'seen_at' => NULL,
                'download_at' => NULL,
                'preview_at' => NULL,
                'created_by' => 0,
                'updated_by' => 0,
                'deleted_by' => 0,
                'created_at' => '2026-01-14 16:48:23',
                'updated_at' => '2026-01-14 16:48:23',
                'deleted_at' => NULL,
                'accepted_at' => NULL,
            ),
            105 => 
            array (
                'id' => 369,
                'document_transaction_id' => 65,
                'receiver_id' => 278,
                'seen_at' => NULL,
                'download_at' => NULL,
                'preview_at' => NULL,
                'created_by' => 0,
                'updated_by' => 0,
                'deleted_by' => 0,
                'created_at' => '2026-01-14 16:48:23',
                'updated_at' => '2026-01-14 16:48:23',
                'deleted_at' => NULL,
                'accepted_at' => NULL,
            ),
            106 => 
            array (
                'id' => 370,
                'document_transaction_id' => 48,
                'receiver_id' => 1342,
                'seen_at' => NULL,
                'download_at' => '2026-01-15 16:52:09',
                'preview_at' => '2026-01-15 16:52:55',
                'created_by' => 0,
                'updated_by' => 0,
                'deleted_by' => 0,
                'created_at' => '2026-01-14 16:48:23',
                'updated_at' => '2026-01-15 16:52:55',
                'deleted_at' => NULL,
                'accepted_at' => '2026-01-15 16:51:49',
            ),
        ));
        
        
    }
}