<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;

class DocumentTransactionsTableSeeder extends Seeder
{

    /**
     * Auto generated seed file
     *
     * @return void
     */
    public function run()
    {
        

        \DB::table('document_transactions')->delete();
        
        \DB::table('document_transactions')->insert(array (
            0 => 
            array (
                'id' => 135,
                'document_id' => 136,
                'sender_id' => 1342,
                'subject' => 'សារាចរលេខ_១១_សរ_ស្ដីពីការធ្វើបច្ចុប្បន្នភាពរចនាសម្ព័ន្ធនិងជំរឿនមន្ត្រី',
                'sent_at' => '2026-02-04 15:50:41',
                'previous_transaction_id' => 0,
                'next_transaction_id' => 0,
                'created_by' => 1342,
                'updated_by' => 1342,
                'deleted_by' => 0,
                'created_at' => '2026-02-04 15:50:41',
                'updated_at' => '2026-02-04 15:50:41',
                'deleted_at' => NULL,
                'tpid' => NULL,
                'date_in' => '2026-02-04 00:00:00',
                'status' => 'pending',
                'organization_structure_id' => 0,
            ),
            1 => 
            array (
                'id' => 136,
                'document_id' => 137,
                'sender_id' => 1342,
                'subject' => 'កិច្ចសន្យាជួលឃ្លាំង_និងបន្ទប់ជួល',
                'sent_at' => '2026-02-04 16:00:47',
                'previous_transaction_id' => 0,
                'next_transaction_id' => 0,
                'created_by' => 1342,
                'updated_by' => 1342,
                'deleted_by' => 0,
                'created_at' => '2026-02-04 16:00:47',
                'updated_at' => '2026-02-04 16:00:47',
                'deleted_at' => NULL,
                'tpid' => NULL,
                'date_in' => '2026-02-04 00:00:00',
                'status' => 'pending',
                'organization_structure_id' => 0,
            ),
            2 => 
            array (
                'id' => 137,
                'document_id' => 138,
                'sender_id' => 1157,
                'subject' => 'សៀវភៅ អំណានជាអំណាច',
                'sent_at' => '2026-02-05 10:44:54',
                'previous_transaction_id' => 0,
                'next_transaction_id' => 0,
                'created_by' => 1157,
                'updated_by' => 1157,
                'deleted_by' => 0,
                'created_at' => '2026-02-05 10:44:54',
                'updated_at' => '2026-02-05 10:44:54',
                'deleted_at' => NULL,
                'tpid' => NULL,
                'date_in' => '2026-02-05 00:00:00',
                'status' => 'pending',
                'organization_structure_id' => 0,
            ),
            3 => 
            array (
                'id' => 145,
                'document_id' => 146,
                'sender_id' => 1157,
                'subject' => 'asdfas',
                'sent_at' => NULL,
                'previous_transaction_id' => 0,
                'next_transaction_id' => 0,
                'created_by' => 1157,
                'updated_by' => 1157,
                'deleted_by' => 0,
                'created_at' => '2026-02-05 13:41:06',
                'updated_at' => '2026-02-05 13:41:06',
                'deleted_at' => NULL,
                'tpid' => NULL,
                'date_in' => '2026-02-05 00:00:00',
                'status' => 'draft',
                'organization_structure_id' => 0,
            ),
            4 => 
            array (
                'id' => 146,
                'document_id' => 147,
                'sender_id' => 1157,
                'subject' => 'asdfas',
                'sent_at' => '2026-02-05 13:41:35',
                'previous_transaction_id' => 0,
                'next_transaction_id' => 0,
                'created_by' => 1157,
                'updated_by' => 1157,
                'deleted_by' => 0,
                'created_at' => '2026-02-05 13:41:35',
                'updated_at' => '2026-02-05 13:41:35',
                'deleted_at' => NULL,
                'tpid' => NULL,
                'date_in' => '2026-02-05 00:00:00',
                'status' => 'pending',
                'organization_structure_id' => 0,
            ),
            5 => 
            array (
                'id' => 144,
                'document_id' => 145,
                'sender_id' => 1157,
                'subject' => 'asdfas',
                'sent_at' => NULL,
                'previous_transaction_id' => 0,
                'next_transaction_id' => 0,
                'created_by' => 1157,
                'updated_by' => 1157,
                'deleted_by' => 0,
                'created_at' => '2026-02-05 13:38:46',
                'updated_at' => '2026-02-05 13:49:08',
                'deleted_at' => '2026-02-05 13:49:08',
                'tpid' => '0:',
                'date_in' => '2026-02-05 00:00:00',
                'status' => 'draft',
                'organization_structure_id' => 0,
            ),
            6 => 
            array (
                'id' => 142,
                'document_id' => 143,
                'sender_id' => 1157,
                'subject' => 'asdfas',
                'sent_at' => NULL,
                'previous_transaction_id' => 0,
                'next_transaction_id' => 0,
                'created_by' => 1157,
                'updated_by' => 1157,
                'deleted_by' => 0,
                'created_at' => '2026-02-05 13:33:54',
                'updated_at' => '2026-02-05 13:49:12',
                'deleted_at' => '2026-02-05 13:49:12',
                'tpid' => '0:',
                'date_in' => '2026-02-05 00:00:00',
                'status' => 'draft',
                'organization_structure_id' => 0,
            ),
            7 => 
            array (
                'id' => 141,
                'document_id' => 142,
                'sender_id' => 1157,
                'subject' => 'asdfas',
                'sent_at' => NULL,
                'previous_transaction_id' => 0,
                'next_transaction_id' => 0,
                'created_by' => 1157,
                'updated_by' => 1157,
                'deleted_by' => 0,
                'created_at' => '2026-02-05 13:33:12',
                'updated_at' => '2026-02-05 13:49:15',
                'deleted_at' => '2026-02-05 13:49:15',
                'tpid' => '0:',
                'date_in' => '2026-02-05 00:00:00',
                'status' => 'draft',
                'organization_structure_id' => 0,
            ),
            8 => 
            array (
                'id' => 140,
                'document_id' => 141,
                'sender_id' => 1157,
                'subject' => 'asdfas',
                'sent_at' => NULL,
                'previous_transaction_id' => 0,
                'next_transaction_id' => 0,
                'created_by' => 1157,
                'updated_by' => 1157,
                'deleted_by' => 0,
                'created_at' => '2026-02-05 13:32:40',
                'updated_at' => '2026-02-05 13:49:18',
                'deleted_at' => '2026-02-05 13:49:18',
                'tpid' => '0:',
                'date_in' => '2026-02-05 00:00:00',
                'status' => 'draft',
                'organization_structure_id' => 0,
            ),
            9 => 
            array (
                'id' => 139,
                'document_id' => 140,
                'sender_id' => 1157,
                'subject' => 'asdfas',
                'sent_at' => NULL,
                'previous_transaction_id' => 0,
                'next_transaction_id' => 0,
                'created_by' => 1157,
                'updated_by' => 1157,
                'deleted_by' => 0,
                'created_at' => '2026-02-05 13:32:11',
                'updated_at' => '2026-02-05 13:49:20',
                'deleted_at' => '2026-02-05 13:49:20',
                'tpid' => '0:',
                'date_in' => '2026-02-05 00:00:00',
                'status' => 'draft',
                'organization_structure_id' => 0,
            ),
            10 => 
            array (
                'id' => 138,
                'document_id' => 139,
                'sender_id' => 1157,
                'subject' => 'asdfasdf',
                'sent_at' => NULL,
                'previous_transaction_id' => 0,
                'next_transaction_id' => 0,
                'created_by' => 1157,
                'updated_by' => 1157,
                'deleted_by' => 0,
                'created_at' => '2026-02-05 13:17:24',
                'updated_at' => '2026-02-05 13:49:22',
                'deleted_at' => '2026-02-05 13:49:22',
                'tpid' => '0:',
                'date_in' => '2026-02-05 00:00:00',
                'status' => 'draft',
                'organization_structure_id' => 0,
            ),
            11 => 
            array (
                'id' => 143,
                'document_id' => 144,
                'sender_id' => 1157,
                'subject' => 'asdfas',
                'sent_at' => NULL,
                'previous_transaction_id' => 0,
                'next_transaction_id' => 0,
                'created_by' => 1157,
                'updated_by' => 1157,
                'deleted_by' => 0,
                'created_at' => '2026-02-05 13:34:06',
                'updated_at' => '2026-02-05 13:49:25',
                'deleted_at' => '2026-02-05 13:49:25',
                'tpid' => '0:',
                'date_in' => '2026-02-05 00:00:00',
                'status' => 'draft',
                'organization_structure_id' => 0,
            ),
        ));
        
        
    }
}