<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;

class DocumentsTableSeeder extends Seeder
{

    /**
     * Auto generated seed file
     *
     * @return void
     */
    public function run()
    {
        

        \DB::table('documents')->delete();
        
        \DB::table('documents')->insert(array (
            0 => 
            array (
                'id' => 50,
                'objective' => 'ចំណងជើងឯកសារ 2',
                'word_file' => 'path_to_word file',
                'pdf_file' => 'path_to_word file',
                'created_by' => 392,
                'updated_by' => 392,
                'deleted_by' => 0,
                'created_at' => '2026-01-14 16:48:23',
                'updated_at' => '2026-01-14 16:48:23',
                'deleted_at' => NULL,
                'number' => NULL,
                'file_word_name' => NULL,
                'file_pdf_name' => NULL,
                'document_type' => 0,
            ),
            1 => 
            array (
                'id' => 51,
                'objective' => 'ចំណងជើងឯកសារ 3',
                'word_file' => 'path_to_word file',
                'pdf_file' => 'path_to_word file',
                'created_by' => 430,
                'updated_by' => 430,
                'deleted_by' => 0,
                'created_at' => '2026-01-14 16:48:23',
                'updated_at' => '2026-01-14 16:48:23',
                'deleted_at' => NULL,
                'number' => NULL,
                'file_word_name' => NULL,
                'file_pdf_name' => NULL,
                'document_type' => 0,
            ),
            2 => 
            array (
                'id' => 52,
                'objective' => 'ចំណងជើងឯកសារ 4',
                'word_file' => 'path_to_word file',
                'pdf_file' => 'path_to_word file',
                'created_by' => 3470,
                'updated_by' => 3470,
                'deleted_by' => 0,
                'created_at' => '2026-01-14 16:48:23',
                'updated_at' => '2026-01-14 16:48:23',
                'deleted_at' => NULL,
                'number' => NULL,
                'file_word_name' => NULL,
                'file_pdf_name' => NULL,
                'document_type' => 0,
            ),
            3 => 
            array (
                'id' => 53,
                'objective' => 'ចំណងជើងឯកសារ 5',
                'word_file' => 'path_to_word file',
                'pdf_file' => 'path_to_word file',
                'created_by' => 2245,
                'updated_by' => 2245,
                'deleted_by' => 0,
                'created_at' => '2026-01-14 16:48:23',
                'updated_at' => '2026-01-14 16:48:23',
                'deleted_at' => NULL,
                'number' => NULL,
                'file_word_name' => NULL,
                'file_pdf_name' => NULL,
                'document_type' => 0,
            ),
            4 => 
            array (
                'id' => 54,
                'objective' => 'ចំណងជើងឯកសារ 6',
                'word_file' => 'path_to_word file',
                'pdf_file' => 'path_to_word file',
                'created_by' => 2162,
                'updated_by' => 2162,
                'deleted_by' => 0,
                'created_at' => '2026-01-14 16:48:23',
                'updated_at' => '2026-01-14 16:48:23',
                'deleted_at' => NULL,
                'number' => NULL,
                'file_word_name' => NULL,
                'file_pdf_name' => NULL,
                'document_type' => 0,
            ),
            5 => 
            array (
                'id' => 55,
                'objective' => 'ចំណងជើងឯកសារ 7',
                'word_file' => 'path_to_word file',
                'pdf_file' => 'path_to_word file',
                'created_by' => 1364,
                'updated_by' => 1364,
                'deleted_by' => 0,
                'created_at' => '2026-01-14 16:48:23',
                'updated_at' => '2026-01-14 16:48:23',
                'deleted_at' => NULL,
                'number' => NULL,
                'file_word_name' => NULL,
                'file_pdf_name' => NULL,
                'document_type' => 0,
            ),
            6 => 
            array (
                'id' => 56,
                'objective' => 'ចំណងជើងឯកសារ 8',
                'word_file' => 'path_to_word file',
                'pdf_file' => 'path_to_word file',
                'created_by' => 1813,
                'updated_by' => 1813,
                'deleted_by' => 0,
                'created_at' => '2026-01-14 16:48:23',
                'updated_at' => '2026-01-14 16:48:23',
                'deleted_at' => NULL,
                'number' => NULL,
                'file_word_name' => NULL,
                'file_pdf_name' => NULL,
                'document_type' => 0,
            ),
            7 => 
            array (
                'id' => 57,
                'objective' => 'ចំណងជើងឯកសារ 9',
                'word_file' => 'path_to_word file',
                'pdf_file' => 'path_to_word file',
                'created_by' => 110,
                'updated_by' => 110,
                'deleted_by' => 0,
                'created_at' => '2026-01-14 16:48:23',
                'updated_at' => '2026-01-14 16:48:23',
                'deleted_at' => NULL,
                'number' => NULL,
                'file_word_name' => NULL,
                'file_pdf_name' => NULL,
                'document_type' => 0,
            ),
            8 => 
            array (
                'id' => 58,
                'objective' => 'ចំណងជើងឯកសារ 10',
                'word_file' => 'path_to_word file',
                'pdf_file' => 'path_to_word file',
                'created_by' => 3280,
                'updated_by' => 3280,
                'deleted_by' => 0,
                'created_at' => '2026-01-14 16:48:23',
                'updated_at' => '2026-01-14 16:48:23',
                'deleted_at' => NULL,
                'number' => NULL,
                'file_word_name' => NULL,
                'file_pdf_name' => NULL,
                'document_type' => 0,
            ),
            9 => 
            array (
                'id' => 59,
                'objective' => 'ចំណងជើងឯកសារ 11',
                'word_file' => 'path_to_word file',
                'pdf_file' => 'path_to_word file',
                'created_by' => 1080,
                'updated_by' => 1080,
                'deleted_by' => 0,
                'created_at' => '2026-01-14 16:48:23',
                'updated_at' => '2026-01-14 16:48:23',
                'deleted_at' => NULL,
                'number' => NULL,
                'file_word_name' => NULL,
                'file_pdf_name' => NULL,
                'document_type' => 0,
            ),
            10 => 
            array (
                'id' => 60,
                'objective' => 'ចំណងជើងឯកសារ 12',
                'word_file' => 'path_to_word file',
                'pdf_file' => 'path_to_word file',
                'created_by' => 3178,
                'updated_by' => 3178,
                'deleted_by' => 0,
                'created_at' => '2026-01-14 16:48:23',
                'updated_at' => '2026-01-14 16:48:23',
                'deleted_at' => NULL,
                'number' => NULL,
                'file_word_name' => NULL,
                'file_pdf_name' => NULL,
                'document_type' => 0,
            ),
            11 => 
            array (
                'id' => 61,
                'objective' => 'ចំណងជើងឯកសារ 13',
                'word_file' => 'path_to_word file',
                'pdf_file' => 'path_to_word file',
                'created_by' => 1464,
                'updated_by' => 1464,
                'deleted_by' => 0,
                'created_at' => '2026-01-14 16:48:23',
                'updated_at' => '2026-01-14 16:48:23',
                'deleted_at' => NULL,
                'number' => NULL,
                'file_word_name' => NULL,
                'file_pdf_name' => NULL,
                'document_type' => 0,
            ),
            12 => 
            array (
                'id' => 62,
                'objective' => 'ចំណងជើងឯកសារ 14',
                'word_file' => 'path_to_word file',
                'pdf_file' => 'path_to_word file',
                'created_by' => 2501,
                'updated_by' => 2501,
                'deleted_by' => 0,
                'created_at' => '2026-01-14 16:48:23',
                'updated_at' => '2026-01-14 16:48:23',
                'deleted_at' => NULL,
                'number' => NULL,
                'file_word_name' => NULL,
                'file_pdf_name' => NULL,
                'document_type' => 0,
            ),
            13 => 
            array (
                'id' => 63,
                'objective' => 'ចំណងជើងឯកសារ 15',
                'word_file' => 'path_to_word file',
                'pdf_file' => 'path_to_word file',
                'created_by' => 468,
                'updated_by' => 468,
                'deleted_by' => 0,
                'created_at' => '2026-01-14 16:48:23',
                'updated_at' => '2026-01-14 16:48:23',
                'deleted_at' => NULL,
                'number' => NULL,
                'file_word_name' => NULL,
                'file_pdf_name' => NULL,
                'document_type' => 0,
            ),
            14 => 
            array (
                'id' => 64,
                'objective' => 'ចំណងជើងឯកសារ 16',
                'word_file' => 'path_to_word file',
                'pdf_file' => 'path_to_word file',
                'created_by' => 2712,
                'updated_by' => 2712,
                'deleted_by' => 0,
                'created_at' => '2026-01-14 16:48:23',
                'updated_at' => '2026-01-14 16:48:23',
                'deleted_at' => NULL,
                'number' => NULL,
                'file_word_name' => NULL,
                'file_pdf_name' => NULL,
                'document_type' => 0,
            ),
            15 => 
            array (
                'id' => 65,
                'objective' => 'ចំណងជើងឯកសារ 17',
                'word_file' => 'path_to_word file',
                'pdf_file' => 'path_to_word file',
                'created_by' => 3097,
                'updated_by' => 3097,
                'deleted_by' => 0,
                'created_at' => '2026-01-14 16:48:23',
                'updated_at' => '2026-01-14 16:48:23',
                'deleted_at' => NULL,
                'number' => NULL,
                'file_word_name' => NULL,
                'file_pdf_name' => NULL,
                'document_type' => 0,
            ),
            16 => 
            array (
                'id' => 66,
                'objective' => 'ចំណងជើងឯកសារ 18',
                'word_file' => 'path_to_word file',
                'pdf_file' => 'path_to_word file',
                'created_by' => 1335,
                'updated_by' => 1335,
                'deleted_by' => 0,
                'created_at' => '2026-01-14 16:48:23',
                'updated_at' => '2026-01-14 16:48:23',
                'deleted_at' => NULL,
                'number' => NULL,
                'file_word_name' => NULL,
                'file_pdf_name' => NULL,
                'document_type' => 0,
            ),
            17 => 
            array (
                'id' => 85,
                'objective' => 'កម្មវត្ថុ',
                'word_file' => NULL,
                'pdf_file' => NULL,
                'created_by' => 1342,
                'updated_by' => 1342,
                'deleted_by' => 0,
                'created_at' => '2026-01-29 14:00:53',
                'updated_at' => '2026-01-29 14:00:53',
                'deleted_at' => NULL,
                'number' => '១០១',
                'file_word_name' => NULL,
                'file_pdf_name' => NULL,
                'document_type' => 1,
            ),
            18 => 
            array (
                'id' => 86,
                'objective' => 'ABC',
                'word_file' => NULL,
                'pdf_file' => NULL,
                'created_by' => 1342,
                'updated_by' => 1342,
                'deleted_by' => 0,
                'created_at' => '2026-01-29 14:01:55',
                'updated_at' => '2026-01-29 14:01:55',
                'deleted_at' => NULL,
                'number' => '101',
                'file_word_name' => NULL,
                'file_pdf_name' => NULL,
                'document_type' => 1,
            ),
            19 => 
            array (
                'id' => 87,
                'objective' => 'ABC',
                'word_file' => NULL,
                'pdf_file' => NULL,
                'created_by' => 1342,
                'updated_by' => 1342,
                'deleted_by' => 0,
                'created_at' => '2026-01-29 14:02:27',
                'updated_at' => '2026-01-29 14:02:27',
                'deleted_at' => NULL,
                'number' => '101',
                'file_word_name' => NULL,
                'file_pdf_name' => NULL,
                'document_type' => 1,
            ),
            20 => 
            array (
                'id' => 88,
                'objective' => 'ABC',
                'word_file' => NULL,
                'pdf_file' => NULL,
                'created_by' => 1342,
                'updated_by' => 1342,
                'deleted_by' => 0,
                'created_at' => '2026-01-29 14:03:21',
                'updated_at' => '2026-01-29 14:03:21',
                'deleted_at' => NULL,
                'number' => '101',
                'file_word_name' => NULL,
                'file_pdf_name' => NULL,
                'document_type' => 1,
            ),
            21 => 
            array (
                'id' => 89,
                'objective' => 'abc',
                'word_file' => NULL,
                'pdf_file' => NULL,
                'created_by' => 1342,
                'updated_by' => 1342,
                'deleted_by' => 0,
                'created_at' => '2026-01-29 14:07:47',
                'updated_at' => '2026-01-29 14:07:47',
                'deleted_at' => NULL,
                'number' => '101',
                'file_word_name' => NULL,
                'file_pdf_name' => NULL,
                'document_type' => 1,
            ),
            22 => 
            array (
                'id' => 90,
                'objective' => ';laksjdf',
                'word_file' => NULL,
                'pdf_file' => NULL,
                'created_by' => 1342,
                'updated_by' => 1342,
                'deleted_by' => 0,
                'created_at' => '2026-01-29 14:08:43',
                'updated_at' => '2026-01-29 14:08:43',
                'deleted_at' => NULL,
                'number' => '9191',
                'file_word_name' => NULL,
                'file_pdf_name' => NULL,
                'document_type' => 1,
            ),
            23 => 
            array (
                'id' => 91,
                'objective' => 'a;slkfdj',
                'word_file' => NULL,
                'pdf_file' => NULL,
                'created_by' => 1342,
                'updated_by' => 1342,
                'deleted_by' => 0,
                'created_at' => '2026-01-29 14:11:15',
                'updated_at' => '2026-01-29 14:11:15',
                'deleted_at' => NULL,
                'number' => '101',
                'file_word_name' => NULL,
                'file_pdf_name' => NULL,
                'document_type' => 1,
            ),
            24 => 
            array (
                'id' => 92,
                'objective' => 'aklsjfd',
                'word_file' => NULL,
                'pdf_file' => NULL,
                'created_by' => 1342,
                'updated_by' => 1342,
                'deleted_by' => 0,
                'created_at' => '2026-01-29 17:06:04',
                'updated_at' => '2026-01-29 17:06:04',
                'deleted_at' => NULL,
                'number' => 'a;lskdfj',
                'file_word_name' => NULL,
                'file_pdf_name' => NULL,
                'document_type' => 1,
            ),
            25 => 
            array (
                'id' => 93,
                'objective' => 'LKAJD;L;ALSKJD',
                'word_file' => NULL,
                'pdf_file' => NULL,
                'created_by' => 1342,
                'updated_by' => 1342,
                'deleted_by' => 0,
                'created_at' => '2026-01-29 17:11:22',
                'updated_at' => '2026-01-29 17:11:22',
                'deleted_at' => NULL,
                'number' => '\';LASKDF;L',
                'file_word_name' => NULL,
                'file_pdf_name' => NULL,
                'document_type' => 1,
            ),
            26 => 
            array (
                'id' => 49,
                'objective' => 'ចំណងជើងឯកសារ 1',
                'word_file' => 'doctransaction/49/toyHfzZNoEoUbZkHD0XlpqAaYZRtaoCruOeOsbId.docx',
                'pdf_file' => 'doctransaction/49/WwMQu4EDQb83fWbk49GK1XDoAUOiTVY7xF3n94fO.pdf',
                'created_by' => 3840,
                'updated_by' => 3840,
                'deleted_by' => 0,
                'created_at' => '2026-01-14 16:48:23',
                'updated_at' => '2026-01-15 16:18:50',
                'deleted_at' => NULL,
                'number' => NULL,
                'file_word_name' => NULL,
                'file_pdf_name' => '2025_11_27_Agenda_War Economy.pdf',
                'document_type' => 0,
            ),
            27 => 
            array (
                'id' => 67,
                'objective' => 'ចំណងជើងឯកសារ 1',
                'word_file' => NULL,
                'pdf_file' => NULL,
                'created_by' => 370,
                'updated_by' => 370,
                'deleted_by' => 0,
                'created_at' => '2026-01-15 16:33:47',
                'updated_at' => '2026-01-15 16:33:47',
                'deleted_at' => NULL,
                'number' => NULL,
                'file_word_name' => NULL,
                'file_pdf_name' => NULL,
                'document_type' => 0,
            ),
            28 => 
            array (
                'id' => 68,
                'objective' => 'ចំណងជើងឯកសារ 1',
                'word_file' => NULL,
                'pdf_file' => NULL,
                'created_by' => 370,
                'updated_by' => 370,
                'deleted_by' => 0,
                'created_at' => '2026-01-15 16:43:06',
                'updated_at' => '2026-01-15 16:43:06',
                'deleted_at' => NULL,
                'number' => NULL,
                'file_word_name' => NULL,
                'file_pdf_name' => NULL,
                'document_type' => 0,
            ),
            29 => 
            array (
                'id' => 69,
                'objective' => 'ចំណងជើងឯកសារ 1',
                'word_file' => NULL,
                'pdf_file' => NULL,
                'created_by' => 370,
                'updated_by' => 370,
                'deleted_by' => 0,
                'created_at' => '2026-01-15 16:51:49',
                'updated_at' => '2026-01-15 16:51:49',
                'deleted_at' => NULL,
                'number' => NULL,
                'file_word_name' => NULL,
                'file_pdf_name' => NULL,
                'document_type' => 0,
            ),
            30 => 
            array (
                'id' => 70,
                'objective' => 'កម្មវត្ថុនៃឯកសារ',
                'word_file' => NULL,
                'pdf_file' => NULL,
                'created_by' => 1342,
                'updated_by' => 1342,
                'deleted_by' => 0,
                'created_at' => '2026-01-28 16:09:39',
                'updated_at' => '2026-01-28 16:09:39',
                'deleted_at' => NULL,
                'number' => '001',
                'file_word_name' => NULL,
                'file_pdf_name' => NULL,
                'document_type' => 0,
            ),
            31 => 
            array (
                'id' => 71,
                'objective' => 'កម្មវត្ថុ',
                'word_file' => NULL,
                'pdf_file' => NULL,
                'created_by' => 1342,
                'updated_by' => 1342,
                'deleted_by' => 0,
                'created_at' => '2026-01-28 18:15:56',
                'updated_at' => '2026-01-28 18:15:56',
                'deleted_at' => NULL,
                'number' => '១០០',
                'file_word_name' => NULL,
                'file_pdf_name' => NULL,
                'document_type' => 1,
            ),
            32 => 
            array (
                'id' => 72,
                'objective' => 'aklsjfd;lk',
                'word_file' => NULL,
                'pdf_file' => NULL,
                'created_by' => 1342,
                'updated_by' => 1342,
                'deleted_by' => 0,
                'created_at' => '2026-01-28 18:35:05',
                'updated_at' => '2026-01-28 18:35:05',
                'deleted_at' => NULL,
                'number' => ';asikfjkl',
                'file_word_name' => NULL,
                'file_pdf_name' => NULL,
                'document_type' => 1,
            ),
            33 => 
            array (
                'id' => 73,
                'objective' => 'alksjd;lj',
                'word_file' => NULL,
                'pdf_file' => NULL,
                'created_by' => 1342,
                'updated_by' => 1342,
                'deleted_by' => 0,
                'created_at' => '2026-01-28 18:36:09',
                'updated_at' => '2026-01-28 18:36:09',
                'deleted_at' => NULL,
                'number' => 'alsk;df',
                'file_word_name' => NULL,
                'file_pdf_name' => NULL,
                'document_type' => 1,
            ),
            34 => 
            array (
                'id' => 74,
                'objective' => ';alkjdf;lkj',
                'word_file' => NULL,
                'pdf_file' => NULL,
                'created_by' => 1342,
                'updated_by' => 1342,
                'deleted_by' => 0,
                'created_at' => '2026-01-28 18:37:22',
                'updated_at' => '2026-01-28 18:37:22',
                'deleted_at' => NULL,
                'number' => '09830',
                'file_word_name' => NULL,
                'file_pdf_name' => NULL,
                'document_type' => 1,
            ),
            35 => 
            array (
                'id' => 75,
                'objective' => 'al;ksjd;lk',
                'word_file' => NULL,
                'pdf_file' => NULL,
                'created_by' => 1342,
                'updated_by' => 1342,
                'deleted_by' => 0,
                'created_at' => '2026-01-28 18:38:57',
                'updated_at' => '2026-01-28 18:38:57',
                'deleted_at' => NULL,
                'number' => 'jal;ksd',
                'file_word_name' => NULL,
                'file_pdf_name' => NULL,
                'document_type' => 1,
            ),
            36 => 
            array (
                'id' => 76,
                'objective' => 'a;lskdl;\'ajsl;',
                'word_file' => NULL,
                'pdf_file' => NULL,
                'created_by' => 1342,
                'updated_by' => 1342,
                'deleted_by' => 0,
                'created_at' => '2026-01-28 18:40:03',
                'updated_at' => '2026-01-28 18:40:03',
                'deleted_at' => NULL,
                'number' => '09875t6',
                'file_word_name' => NULL,
                'file_pdf_name' => NULL,
                'document_type' => 1,
            ),
            37 => 
            array (
                'id' => 77,
                'objective' => 'l;akjsdf;l',
                'word_file' => NULL,
                'pdf_file' => NULL,
                'created_by' => 1342,
                'updated_by' => 1342,
                'deleted_by' => 0,
                'created_at' => '2026-01-28 18:43:46',
                'updated_at' => '2026-01-28 18:43:46',
                'deleted_at' => NULL,
                'number' => '8767',
                'file_word_name' => NULL,
                'file_pdf_name' => NULL,
                'document_type' => 1,
            ),
            38 => 
            array (
                'id' => 78,
                'objective' => 'alskjf;l',
                'word_file' => NULL,
                'pdf_file' => NULL,
                'created_by' => 1342,
                'updated_by' => 1342,
                'deleted_by' => 0,
                'created_at' => '2026-01-28 18:45:01',
                'updated_at' => '2026-01-28 18:45:01',
                'deleted_at' => NULL,
                'number' => ';alksjd',
                'file_word_name' => NULL,
                'file_pdf_name' => NULL,
                'document_type' => 1,
            ),
            39 => 
            array (
                'id' => 79,
                'objective' => 'kjasdlfkhj',
                'word_file' => NULL,
                'pdf_file' => NULL,
                'created_by' => 1342,
                'updated_by' => 1342,
                'deleted_by' => 0,
                'created_at' => '2026-01-29 08:35:02',
                'updated_at' => '2026-01-29 08:35:02',
                'deleted_at' => NULL,
                'number' => '625',
                'file_word_name' => NULL,
                'file_pdf_name' => NULL,
                'document_type' => 1,
            ),
            40 => 
            array (
                'id' => 80,
                'objective' => 'jjdjh',
                'word_file' => NULL,
                'pdf_file' => NULL,
                'created_by' => 1342,
                'updated_by' => 1342,
                'deleted_by' => 0,
                'created_at' => '2026-01-29 08:36:45',
                'updated_at' => '2026-01-29 08:36:45',
                'deleted_at' => NULL,
                'number' => '010',
                'file_word_name' => NULL,
                'file_pdf_name' => NULL,
                'document_type' => 1,
            ),
            41 => 
            array (
                'id' => 81,
                'objective' => 'ការវិភាគ',
                'word_file' => NULL,
                'pdf_file' => NULL,
                'created_by' => 1342,
                'updated_by' => 1342,
                'deleted_by' => 0,
                'created_at' => '2026-01-29 13:38:52',
                'updated_at' => '2026-01-29 13:38:52',
                'deleted_at' => NULL,
                'number' => '១០១',
                'file_word_name' => NULL,
                'file_pdf_name' => NULL,
                'document_type' => 1,
            ),
            42 => 
            array (
                'id' => 82,
                'objective' => 'alksjfd',
                'word_file' => NULL,
                'pdf_file' => NULL,
                'created_by' => 1342,
                'updated_by' => 1342,
                'deleted_by' => 0,
                'created_at' => '2026-01-29 13:40:12',
                'updated_at' => '2026-01-29 13:40:12',
                'deleted_at' => NULL,
                'number' => '012',
                'file_word_name' => NULL,
                'file_pdf_name' => NULL,
                'document_type' => 1,
            ),
            43 => 
            array (
                'id' => 83,
                'objective' => 'កម្មវិត្ថុ',
                'word_file' => NULL,
                'pdf_file' => NULL,
                'created_by' => 1342,
                'updated_by' => 1342,
                'deleted_by' => 0,
                'created_at' => '2026-01-29 13:42:05',
                'updated_at' => '2026-01-29 13:42:05',
                'deleted_at' => NULL,
                'number' => '១០១',
                'file_word_name' => NULL,
                'file_pdf_name' => NULL,
                'document_type' => 1,
            ),
            44 => 
            array (
                'id' => 84,
                'objective' => 'កខគ',
                'word_file' => NULL,
                'pdf_file' => NULL,
                'created_by' => 1342,
                'updated_by' => 1342,
                'deleted_by' => 0,
                'created_at' => '2026-01-29 13:43:21',
                'updated_at' => '2026-01-29 13:43:21',
                'deleted_at' => NULL,
                'number' => '១០១',
                'file_word_name' => NULL,
                'file_pdf_name' => NULL,
                'document_type' => 2,
            ),
        ));
        
        
    }
}