<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;

class MeetingMembersTableSeeder extends Seeder
{

    /**
     * Auto generated seed file
     *
     * @return void
     */
    public function run()
    {
        

        \DB::table('meeting_members')->delete();
        
        \DB::table('meeting_members')->insert(array (
            0 => 
            array (
                'id' => 4,
                'meeting_id' => 2,
                'people_id' => 2423,
                'role' => 'leader',
                'group' => 'lead_meeting',
                'remark' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            1 => 
            array (
                'id' => 5,
                'meeting_id' => 2,
                'people_id' => 2475,
                'role' => 'leader',
                'group' => 'lead_meeting',
                'remark' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            2 => 
            array (
                'id' => 6,
                'meeting_id' => 1,
                'people_id' => 2423,
                'role' => 'leader',
                'group' => 'lead_meeting',
                'remark' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            3 => 
            array (
                'id' => 7,
                'meeting_id' => 3,
                'people_id' => 2423,
                'role' => 'leader',
                'group' => 'lead_meeting',
                'remark' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            4 => 
            array (
                'id' => 8,
                'meeting_id' => 3,
                'people_id' => 805,
                'role' => 'leader',
                'group' => 'defender',
                'remark' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            5 => 
            array (
                'id' => 9,
                'meeting_id' => 4,
                'people_id' => 2386,
                'role' => 'leader',
                'group' => 'audient',
                'remark' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            6 => 
            array (
                'id' => 10,
                'meeting_id' => 4,
                'people_id' => 2264,
                'role' => 'leader',
                'group' => 'audient',
                'remark' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            7 => 
            array (
                'id' => 12,
                'meeting_id' => 1,
                'people_id' => 2475,
                'role' => 'leader',
                'group' => 'lead_meeting',
                'remark' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            8 => 
            array (
                'id' => 14,
                'meeting_id' => 5,
                'people_id' => 2423,
                'role' => 'leader',
                'group' => 'lead_meeting',
                'remark' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            9 => 
            array (
                'id' => 15,
                'meeting_id' => 5,
                'people_id' => 2475,
                'role' => 'leader',
                'group' => 'lead_meeting',
                'remark' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            10 => 
            array (
                'id' => 16,
                'meeting_id' => 6,
                'people_id' => 2475,
                'role' => 'leader',
                'group' => 'lead_meeting',
                'remark' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            11 => 
            array (
                'id' => 17,
                'meeting_id' => 6,
                'people_id' => 2423,
                'role' => 'leader',
                'group' => 'lead_meeting',
                'remark' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            12 => 
            array (
                'id' => 18,
                'meeting_id' => 8,
                'people_id' => 152,
                'role' => 'leader',
                'group' => 'lead_meeting',
                'remark' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            13 => 
            array (
                'id' => 21,
                'meeting_id' => 9,
                'people_id' => 2423,
                'role' => 'leader',
                'group' => 'lead_meeting',
                'remark' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            14 => 
            array (
                'id' => 22,
                'meeting_id' => 9,
                'people_id' => 2475,
                'role' => 'leader',
                'group' => 'lead_meeting',
                'remark' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            15 => 
            array (
                'id' => 23,
                'meeting_id' => 11,
                'people_id' => 23,
                'role' => 'leader',
                'group' => 'lead_meeting',
                'remark' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            16 => 
            array (
                'id' => 24,
                'meeting_id' => 11,
                'people_id' => 338,
                'role' => 'leader',
                'group' => 'lead_meeting',
                'remark' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            17 => 
            array (
                'id' => 25,
                'meeting_id' => 12,
                'people_id' => 23,
                'role' => 'leader',
                'group' => 'lead_meeting',
                'remark' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            18 => 
            array (
                'id' => 26,
                'meeting_id' => 12,
                'people_id' => 338,
                'role' => 'leader',
                'group' => 'lead_meeting',
                'remark' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            19 => 
            array (
                'id' => 27,
                'meeting_id' => 13,
                'people_id' => 338,
                'role' => 'leader',
                'group' => 'lead_meeting',
                'remark' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            20 => 
            array (
                'id' => 28,
                'meeting_id' => 13,
                'people_id' => 23,
                'role' => 'leader',
                'group' => 'lead_meeting',
                'remark' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            21 => 
            array (
                'id' => 29,
                'meeting_id' => 14,
                'people_id' => 23,
                'role' => 'leader',
                'group' => 'lead_meeting',
                'remark' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            22 => 
            array (
                'id' => 30,
                'meeting_id' => 14,
                'people_id' => 338,
                'role' => 'leader',
                'group' => 'lead_meeting',
                'remark' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            23 => 
            array (
                'id' => 31,
                'meeting_id' => 15,
                'people_id' => 173,
                'role' => 'leader',
                'group' => 'lead_meeting',
                'remark' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            24 => 
            array (
                'id' => 32,
                'meeting_id' => 16,
                'people_id' => 2423,
                'role' => 'leader',
                'group' => 'lead_meeting',
                'remark' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            25 => 
            array (
                'id' => 33,
                'meeting_id' => 17,
                'people_id' => 2423,
                'role' => 'leader',
                'group' => 'lead_meeting',
                'remark' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            26 => 
            array (
                'id' => 34,
                'meeting_id' => 17,
                'people_id' => 366,
                'role' => 'leader',
                'group' => 'lead_meeting',
                'remark' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            27 => 
            array (
                'id' => 35,
                'meeting_id' => 16,
                'people_id' => 366,
                'role' => 'leader',
                'group' => 'lead_meeting',
                'remark' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            28 => 
            array (
                'id' => 36,
                'meeting_id' => 18,
                'people_id' => 152,
                'role' => 'leader',
                'group' => 'lead_meeting',
                'remark' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            29 => 
            array (
                'id' => 37,
                'meeting_id' => 19,
                'people_id' => 176,
                'role' => 'leader',
                'group' => 'lead_meeting',
                'remark' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            30 => 
            array (
                'id' => 38,
                'meeting_id' => 19,
                'people_id' => 366,
                'role' => 'leader',
                'group' => 'lead_meeting',
                'remark' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            31 => 
            array (
                'id' => 39,
                'meeting_id' => 20,
                'people_id' => 176,
                'role' => 'leader',
                'group' => 'lead_meeting',
                'remark' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            32 => 
            array (
                'id' => 40,
                'meeting_id' => 20,
                'people_id' => 366,
                'role' => 'leader',
                'group' => 'lead_meeting',
                'remark' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            33 => 
            array (
                'id' => 41,
                'meeting_id' => 21,
                'people_id' => 2423,
                'role' => 'leader',
                'group' => 'lead_meeting',
                'remark' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            34 => 
            array (
                'id' => 42,
                'meeting_id' => 21,
                'people_id' => 2475,
                'role' => 'leader',
                'group' => 'lead_meeting',
                'remark' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            35 => 
            array (
                'id' => 43,
                'meeting_id' => 22,
                'people_id' => 2475,
                'role' => 'leader',
                'group' => 'lead_meeting',
                'remark' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            36 => 
            array (
                'id' => 44,
                'meeting_id' => 22,
                'people_id' => 2423,
                'role' => 'leader',
                'group' => 'lead_meeting',
                'remark' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            37 => 
            array (
                'id' => 45,
                'meeting_id' => 23,
                'people_id' => 2423,
                'role' => 'leader',
                'group' => 'lead_meeting',
                'remark' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            38 => 
            array (
                'id' => 46,
                'meeting_id' => 23,
                'people_id' => 2475,
                'role' => 'leader',
                'group' => 'lead_meeting',
                'remark' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            39 => 
            array (
                'id' => 47,
                'meeting_id' => 24,
                'people_id' => 2475,
                'role' => 'leader',
                'group' => 'lead_meeting',
                'remark' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            40 => 
            array (
                'id' => 48,
                'meeting_id' => 24,
                'people_id' => 2423,
                'role' => 'leader',
                'group' => 'lead_meeting',
                'remark' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            41 => 
            array (
                'id' => 49,
                'meeting_id' => 25,
                'people_id' => 201,
                'role' => 'leader',
                'group' => 'lead_meeting',
                'remark' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            42 => 
            array (
                'id' => 50,
                'meeting_id' => 26,
                'people_id' => 201,
                'role' => 'leader',
                'group' => 'lead_meeting',
                'remark' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            43 => 
            array (
                'id' => 51,
                'meeting_id' => 28,
                'people_id' => 181,
                'role' => 'leader',
                'group' => 'lead_meeting',
                'remark' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            44 => 
            array (
                'id' => 52,
                'meeting_id' => 29,
                'people_id' => 170,
                'role' => 'leader',
                'group' => 'lead_meeting',
                'remark' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            45 => 
            array (
                'id' => 53,
                'meeting_id' => 30,
                'people_id' => 2423,
                'role' => 'leader',
                'group' => 'lead_meeting',
                'remark' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            46 => 
            array (
                'id' => 54,
                'meeting_id' => 30,
                'people_id' => 2475,
                'role' => 'leader',
                'group' => 'lead_meeting',
                'remark' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            47 => 
            array (
                'id' => 55,
                'meeting_id' => 31,
                'people_id' => 2475,
                'role' => 'leader',
                'group' => 'lead_meeting',
                'remark' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            48 => 
            array (
                'id' => 56,
                'meeting_id' => 31,
                'people_id' => 2423,
                'role' => 'leader',
                'group' => 'lead_meeting',
                'remark' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            49 => 
            array (
                'id' => 57,
                'meeting_id' => 33,
                'people_id' => 2423,
                'role' => 'leader',
                'group' => 'lead_meeting',
                'remark' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            50 => 
            array (
                'id' => 58,
                'meeting_id' => 33,
                'people_id' => 2475,
                'role' => 'leader',
                'group' => 'lead_meeting',
                'remark' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            51 => 
            array (
                'id' => 59,
                'meeting_id' => 34,
                'people_id' => 2475,
                'role' => 'leader',
                'group' => 'lead_meeting',
                'remark' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            52 => 
            array (
                'id' => 60,
                'meeting_id' => 34,
                'people_id' => 2423,
                'role' => 'leader',
                'group' => 'lead_meeting',
                'remark' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            53 => 
            array (
                'id' => 61,
                'meeting_id' => 35,
                'people_id' => 2385,
                'role' => 'leader',
                'group' => 'lead_meeting',
                'remark' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            54 => 
            array (
                'id' => 62,
                'meeting_id' => 35,
                'people_id' => 23,
                'role' => 'leader',
                'group' => 'lead_meeting',
                'remark' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            55 => 
            array (
                'id' => 63,
                'meeting_id' => 36,
                'people_id' => 2385,
                'role' => 'leader',
                'group' => 'lead_meeting',
                'remark' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            56 => 
            array (
                'id' => 64,
                'meeting_id' => 36,
                'people_id' => 23,
                'role' => 'leader',
                'group' => 'lead_meeting',
                'remark' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            57 => 
            array (
                'id' => 65,
                'meeting_id' => 37,
                'people_id' => 23,
                'role' => 'leader',
                'group' => 'lead_meeting',
                'remark' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            58 => 
            array (
                'id' => 66,
                'meeting_id' => 37,
                'people_id' => 2385,
                'role' => 'leader',
                'group' => 'lead_meeting',
                'remark' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            59 => 
            array (
                'id' => 67,
                'meeting_id' => 38,
                'people_id' => 23,
                'role' => 'leader',
                'group' => 'lead_meeting',
                'remark' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            60 => 
            array (
                'id' => 68,
                'meeting_id' => 38,
                'people_id' => 2385,
                'role' => 'leader',
                'group' => 'lead_meeting',
                'remark' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            61 => 
            array (
                'id' => 69,
                'meeting_id' => 39,
                'people_id' => 2,
                'role' => 'leader',
                'group' => 'lead_meeting',
                'remark' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            62 => 
            array (
                'id' => 71,
                'meeting_id' => 40,
                'people_id' => 152,
                'role' => 'leader',
                'group' => 'lead_meeting',
                'remark' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            63 => 
            array (
                'id' => 72,
                'meeting_id' => 41,
                'people_id' => 2385,
                'role' => 'leader',
                'group' => 'lead_meeting',
                'remark' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            64 => 
            array (
                'id' => 73,
                'meeting_id' => 41,
                'people_id' => 23,
                'role' => 'leader',
                'group' => 'lead_meeting',
                'remark' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            65 => 
            array (
                'id' => 74,
                'meeting_id' => 42,
                'people_id' => 2385,
                'role' => 'leader',
                'group' => 'lead_meeting',
                'remark' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            66 => 
            array (
                'id' => 75,
                'meeting_id' => 42,
                'people_id' => 23,
                'role' => 'leader',
                'group' => 'lead_meeting',
                'remark' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            67 => 
            array (
                'id' => 76,
                'meeting_id' => 43,
                'people_id' => 223,
                'role' => 'leader',
                'group' => 'lead_meeting',
                'remark' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            68 => 
            array (
                'id' => 77,
                'meeting_id' => 43,
                'people_id' => 203,
                'role' => 'leader',
                'group' => 'lead_meeting',
                'remark' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            69 => 
            array (
                'id' => 78,
                'meeting_id' => 44,
                'people_id' => 152,
                'role' => 'leader',
                'group' => 'lead_meeting',
                'remark' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            70 => 
            array (
                'id' => 84,
                'meeting_id' => 45,
                'people_id' => 223,
                'role' => 'leader',
                'group' => 'lead_meeting',
                'remark' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            71 => 
            array (
                'id' => 85,
                'meeting_id' => 45,
                'people_id' => 203,
                'role' => 'leader',
                'group' => 'lead_meeting',
                'remark' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            72 => 
            array (
                'id' => 86,
                'meeting_id' => 48,
                'people_id' => 152,
                'role' => 'leader',
                'group' => 'lead_meeting',
                'remark' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            73 => 
            array (
                'id' => 87,
                'meeting_id' => 49,
                'people_id' => 2475,
                'role' => 'leader',
                'group' => 'lead_meeting',
                'remark' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            74 => 
            array (
                'id' => 88,
                'meeting_id' => 49,
                'people_id' => 2423,
                'role' => 'leader',
                'group' => 'lead_meeting',
                'remark' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            75 => 
            array (
                'id' => 89,
                'meeting_id' => 50,
                'people_id' => 2475,
                'role' => 'leader',
                'group' => 'lead_meeting',
                'remark' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            76 => 
            array (
                'id' => 90,
                'meeting_id' => 50,
                'people_id' => 2423,
                'role' => 'leader',
                'group' => 'lead_meeting',
                'remark' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            77 => 
            array (
                'id' => 91,
                'meeting_id' => 51,
                'people_id' => 2475,
                'role' => 'leader',
                'group' => 'lead_meeting',
                'remark' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            78 => 
            array (
                'id' => 93,
                'meeting_id' => 51,
                'people_id' => 2423,
                'role' => 'leader',
                'group' => 'lead_meeting',
                'remark' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            79 => 
            array (
                'id' => 94,
                'meeting_id' => 52,
                'people_id' => 2475,
                'role' => 'leader',
                'group' => 'lead_meeting',
                'remark' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            80 => 
            array (
                'id' => 95,
                'meeting_id' => 52,
                'people_id' => 2423,
                'role' => 'leader',
                'group' => 'lead_meeting',
                'remark' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            81 => 
            array (
                'id' => 96,
                'meeting_id' => 59,
                'people_id' => 173,
                'role' => 'leader',
                'group' => 'lead_meeting',
                'remark' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            82 => 
            array (
                'id' => 97,
                'meeting_id' => 60,
                'people_id' => 2475,
                'role' => 'leader',
                'group' => 'lead_meeting',
                'remark' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            83 => 
            array (
                'id' => 98,
                'meeting_id' => 60,
                'people_id' => 2423,
                'role' => 'leader',
                'group' => 'lead_meeting',
                'remark' => NULL,
                'created_at' => NULL,
                'updated_at' => '2025-01-08 10:38:30',
                'deleted_at' => NULL,
            ),
            84 => 
            array (
                'id' => 99,
                'meeting_id' => 58,
                'people_id' => 2475,
                'role' => 'leader',
                'group' => 'lead_meeting',
                'remark' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            85 => 
            array (
                'id' => 100,
                'meeting_id' => 58,
                'people_id' => 2423,
                'role' => 'leader',
                'group' => 'lead_meeting',
                'remark' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            86 => 
            array (
                'id' => 101,
                'meeting_id' => 61,
                'people_id' => 174,
                'role' => 'leader',
                'group' => 'lead_meeting',
                'remark' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            87 => 
            array (
                'id' => 102,
                'meeting_id' => 62,
                'people_id' => 174,
                'role' => 'leader',
                'group' => 'lead_meeting',
                'remark' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            88 => 
            array (
                'id' => 103,
                'meeting_id' => 62,
                'people_id' => 23,
                'role' => 'leader',
                'group' => 'lead_meeting',
                'remark' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            89 => 
            array (
                'id' => 104,
                'meeting_id' => 63,
                'people_id' => 338,
                'role' => 'leader',
                'group' => 'lead_meeting',
                'remark' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            90 => 
            array (
                'id' => 105,
                'meeting_id' => 63,
                'people_id' => 366,
                'role' => 'leader',
                'group' => 'lead_meeting',
                'remark' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            91 => 
            array (
                'id' => 106,
                'meeting_id' => 64,
                'people_id' => 338,
                'role' => 'leader',
                'group' => 'lead_meeting',
                'remark' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            92 => 
            array (
                'id' => 107,
                'meeting_id' => 64,
                'people_id' => 366,
                'role' => 'leader',
                'group' => 'lead_meeting',
                'remark' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            93 => 
            array (
                'id' => 108,
                'meeting_id' => 65,
                'people_id' => 338,
                'role' => 'leader',
                'group' => 'lead_meeting',
                'remark' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            94 => 
            array (
                'id' => 109,
                'meeting_id' => 65,
                'people_id' => 366,
                'role' => 'leader',
                'group' => 'lead_meeting',
                'remark' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            95 => 
            array (
                'id' => 110,
                'meeting_id' => 66,
                'people_id' => 338,
                'role' => 'leader',
                'group' => 'lead_meeting',
                'remark' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            96 => 
            array (
                'id' => 111,
                'meeting_id' => 66,
                'people_id' => 366,
                'role' => 'leader',
                'group' => 'lead_meeting',
                'remark' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            97 => 
            array (
                'id' => 112,
                'meeting_id' => 67,
                'people_id' => 2475,
                'role' => 'leader',
                'group' => 'lead_meeting',
                'remark' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            98 => 
            array (
                'id' => 113,
                'meeting_id' => 67,
                'people_id' => 2423,
                'role' => 'leader',
                'group' => 'lead_meeting',
                'remark' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            99 => 
            array (
                'id' => 114,
                'meeting_id' => 68,
                'people_id' => 2475,
                'role' => 'leader',
                'group' => 'lead_meeting',
                'remark' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            100 => 
            array (
                'id' => 115,
                'meeting_id' => 68,
                'people_id' => 2423,
                'role' => 'leader',
                'group' => 'audient',
                'remark' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            101 => 
            array (
                'id' => 116,
                'meeting_id' => 69,
                'people_id' => 2475,
                'role' => 'leader',
                'group' => 'lead_meeting',
                'remark' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            102 => 
            array (
                'id' => 117,
                'meeting_id' => 69,
                'people_id' => 2423,
                'role' => 'leader',
                'group' => 'lead_meeting',
                'remark' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            103 => 
            array (
                'id' => 118,
                'meeting_id' => 70,
                'people_id' => 207,
                'role' => 'leader',
                'group' => 'lead_meeting',
                'remark' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            104 => 
            array (
                'id' => 119,
                'meeting_id' => 70,
                'people_id' => 201,
                'role' => 'leader',
                'group' => 'lead_meeting',
                'remark' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            105 => 
            array (
                'id' => 120,
                'meeting_id' => 71,
                'people_id' => 2,
                'role' => 'leader',
                'group' => 'lead_meeting',
                'remark' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            106 => 
            array (
                'id' => 121,
                'meeting_id' => 72,
                'people_id' => 176,
                'role' => 'leader',
                'group' => 'lead_meeting',
                'remark' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            107 => 
            array (
                'id' => 122,
                'meeting_id' => 72,
                'people_id' => 366,
                'role' => 'leader',
                'group' => 'lead_meeting',
                'remark' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            108 => 
            array (
                'id' => 123,
                'meeting_id' => 73,
                'people_id' => 176,
                'role' => 'leader',
                'group' => 'lead_meeting',
                'remark' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            109 => 
            array (
                'id' => 124,
                'meeting_id' => 73,
                'people_id' => 366,
                'role' => 'leader',
                'group' => 'lead_meeting',
                'remark' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            110 => 
            array (
                'id' => 125,
                'meeting_id' => 74,
                'people_id' => 176,
                'role' => 'leader',
                'group' => 'lead_meeting',
                'remark' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            111 => 
            array (
                'id' => 126,
                'meeting_id' => 74,
                'people_id' => 366,
                'role' => 'leader',
                'group' => 'lead_meeting',
                'remark' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            112 => 
            array (
                'id' => 127,
                'meeting_id' => 75,
                'people_id' => 176,
                'role' => 'leader',
                'group' => 'lead_meeting',
                'remark' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            113 => 
            array (
                'id' => 128,
                'meeting_id' => 75,
                'people_id' => 366,
                'role' => 'leader',
                'group' => 'lead_meeting',
                'remark' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            114 => 
            array (
                'id' => 129,
                'meeting_id' => 76,
                'people_id' => 338,
                'role' => 'leader',
                'group' => 'lead_meeting',
                'remark' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            115 => 
            array (
                'id' => 130,
                'meeting_id' => 76,
                'people_id' => 366,
                'role' => 'leader',
                'group' => 'lead_meeting',
                'remark' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            116 => 
            array (
                'id' => 131,
                'meeting_id' => 77,
                'people_id' => 338,
                'role' => 'leader',
                'group' => 'lead_meeting',
                'remark' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            117 => 
            array (
                'id' => 132,
                'meeting_id' => 77,
                'people_id' => 366,
                'role' => 'leader',
                'group' => 'lead_meeting',
                'remark' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            118 => 
            array (
                'id' => 133,
                'meeting_id' => 78,
                'people_id' => 170,
                'role' => 'leader',
                'group' => 'lead_meeting',
                'remark' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            119 => 
            array (
                'id' => 134,
                'meeting_id' => 79,
                'people_id' => 170,
                'role' => 'leader',
                'group' => 'lead_meeting',
                'remark' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            120 => 
            array (
                'id' => 135,
                'meeting_id' => 80,
                'people_id' => 338,
                'role' => 'leader',
                'group' => 'lead_meeting',
                'remark' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            121 => 
            array (
                'id' => 137,
                'meeting_id' => 80,
                'people_id' => 2475,
                'role' => 'leader',
                'group' => 'lead_meeting',
                'remark' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            122 => 
            array (
                'id' => 138,
                'meeting_id' => 81,
                'people_id' => 338,
                'role' => 'leader',
                'group' => 'lead_meeting',
                'remark' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            123 => 
            array (
                'id' => 139,
                'meeting_id' => 81,
                'people_id' => 2475,
                'role' => 'leader',
                'group' => 'lead_meeting',
                'remark' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            124 => 
            array (
                'id' => 141,
                'meeting_id' => 82,
                'people_id' => 2475,
                'role' => 'leader',
                'group' => 'lead_meeting',
                'remark' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            125 => 
            array (
                'id' => 142,
                'meeting_id' => 83,
                'people_id' => 338,
                'role' => 'leader',
                'group' => 'lead_meeting',
                'remark' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            126 => 
            array (
                'id' => 143,
                'meeting_id' => 83,
                'people_id' => 2475,
                'role' => 'leader',
                'group' => 'lead_meeting',
                'remark' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            127 => 
            array (
                'id' => 144,
                'meeting_id' => 82,
                'people_id' => 338,
                'role' => 'leader',
                'group' => 'lead_meeting',
                'remark' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            128 => 
            array (
                'id' => 145,
                'meeting_id' => 84,
                'people_id' => 206,
                'role' => 'leader',
                'group' => 'lead_meeting',
                'remark' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            129 => 
            array (
                'id' => 146,
                'meeting_id' => 85,
                'people_id' => 176,
                'role' => 'leader',
                'group' => 'lead_meeting',
                'remark' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            130 => 
            array (
                'id' => 147,
                'meeting_id' => 85,
                'people_id' => 366,
                'role' => 'leader',
                'group' => 'audient',
                'remark' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            131 => 
            array (
                'id' => 148,
                'meeting_id' => 86,
                'people_id' => 176,
                'role' => 'leader',
                'group' => 'lead_meeting',
                'remark' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            132 => 
            array (
                'id' => 149,
                'meeting_id' => 86,
                'people_id' => 366,
                'role' => 'leader',
                'group' => 'audient',
                'remark' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            133 => 
            array (
                'id' => 150,
                'meeting_id' => 87,
                'people_id' => 176,
                'role' => 'leader',
                'group' => 'lead_meeting',
                'remark' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            134 => 
            array (
                'id' => 151,
                'meeting_id' => 87,
                'people_id' => 366,
                'role' => 'leader',
                'group' => 'audient',
                'remark' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            135 => 
            array (
                'id' => 152,
                'meeting_id' => 88,
                'people_id' => 176,
                'role' => 'leader',
                'group' => 'lead_meeting',
                'remark' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            136 => 
            array (
                'id' => 153,
                'meeting_id' => 88,
                'people_id' => 366,
                'role' => 'leader',
                'group' => 'audient',
                'remark' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            137 => 
            array (
                'id' => 155,
                'meeting_id' => 89,
                'people_id' => 176,
                'role' => 'leader',
                'group' => 'lead_meeting',
                'remark' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            138 => 
            array (
                'id' => 156,
                'meeting_id' => 90,
                'people_id' => 2423,
                'role' => 'leader',
                'group' => 'lead_meeting',
                'remark' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            139 => 
            array (
                'id' => 157,
                'meeting_id' => 90,
                'people_id' => 2475,
                'role' => 'leader',
                'group' => 'lead_meeting',
                'remark' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            140 => 
            array (
                'id' => 158,
                'meeting_id' => 94,
                'people_id' => 206,
                'role' => 'leader',
                'group' => 'lead_meeting',
                'remark' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            141 => 
            array (
                'id' => 159,
                'meeting_id' => 96,
                'people_id' => 2423,
                'role' => 'leader',
                'group' => 'lead_meeting',
                'remark' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            142 => 
            array (
                'id' => 160,
                'meeting_id' => 96,
                'people_id' => 2475,
                'role' => 'leader',
                'group' => 'lead_meeting',
                'remark' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            143 => 
            array (
                'id' => 161,
                'meeting_id' => 97,
                'people_id' => 2423,
                'role' => 'leader',
                'group' => 'lead_meeting',
                'remark' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            144 => 
            array (
                'id' => 162,
                'meeting_id' => 97,
                'people_id' => 2475,
                'role' => 'leader',
                'group' => 'lead_meeting',
                'remark' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            145 => 
            array (
                'id' => 163,
                'meeting_id' => 99,
                'people_id' => 2423,
                'role' => 'leader',
                'group' => 'lead_meeting',
                'remark' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            146 => 
            array (
                'id' => 164,
                'meeting_id' => 99,
                'people_id' => 2475,
                'role' => 'leader',
                'group' => 'lead_meeting',
                'remark' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            147 => 
            array (
                'id' => 165,
                'meeting_id' => 102,
                'people_id' => 170,
                'role' => 'leader',
                'group' => 'lead_meeting',
                'remark' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            148 => 
            array (
                'id' => 166,
                'meeting_id' => 103,
                'people_id' => 173,
                'role' => 'leader',
                'group' => 'lead_meeting',
                'remark' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            149 => 
            array (
                'id' => 167,
                'meeting_id' => 104,
                'people_id' => 171,
                'role' => 'leader',
                'group' => 'lead_meeting',
                'remark' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            150 => 
            array (
                'id' => 168,
                'meeting_id' => 105,
                'people_id' => 338,
                'role' => 'leader',
                'group' => 'lead_meeting',
                'remark' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            151 => 
            array (
                'id' => 169,
                'meeting_id' => 105,
                'people_id' => 2475,
                'role' => 'leader',
                'group' => 'lead_meeting',
                'remark' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            152 => 
            array (
                'id' => 170,
                'meeting_id' => 106,
                'people_id' => 2475,
                'role' => 'leader',
                'group' => 'lead_meeting',
                'remark' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            153 => 
            array (
                'id' => 171,
                'meeting_id' => 106,
                'people_id' => 338,
                'role' => 'leader',
                'group' => 'lead_meeting',
                'remark' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            154 => 
            array (
                'id' => 172,
                'meeting_id' => 107,
                'people_id' => 2423,
                'role' => 'leader',
                'group' => 'lead_meeting',
                'remark' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            155 => 
            array (
                'id' => 173,
                'meeting_id' => 109,
                'people_id' => 173,
                'role' => 'leader',
                'group' => 'lead_meeting',
                'remark' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            156 => 
            array (
                'id' => 174,
                'meeting_id' => 107,
                'people_id' => 23,
                'role' => 'leader',
                'group' => 'lead_meeting',
                'remark' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            157 => 
            array (
                'id' => 175,
                'meeting_id' => 110,
                'people_id' => 196,
                'role' => 'leader',
                'group' => 'lead_meeting',
                'remark' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            158 => 
            array (
                'id' => 176,
                'meeting_id' => 108,
                'people_id' => 2423,
                'role' => 'leader',
                'group' => 'lead_meeting',
                'remark' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            159 => 
            array (
                'id' => 177,
                'meeting_id' => 108,
                'people_id' => 23,
                'role' => 'leader',
                'group' => 'lead_meeting',
                'remark' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            160 => 
            array (
                'id' => 178,
                'meeting_id' => 113,
                'people_id' => 171,
                'role' => 'leader',
                'group' => 'lead_meeting',
                'remark' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            161 => 
            array (
                'id' => 179,
                'meeting_id' => 112,
                'people_id' => 2423,
                'role' => 'leader',
                'group' => 'lead_meeting',
                'remark' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            162 => 
            array (
                'id' => 180,
                'meeting_id' => 112,
                'people_id' => 23,
                'role' => 'leader',
                'group' => 'lead_meeting',
                'remark' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            163 => 
            array (
                'id' => 181,
                'meeting_id' => 111,
                'people_id' => 2423,
                'role' => 'leader',
                'group' => 'lead_meeting',
                'remark' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            164 => 
            array (
                'id' => 182,
                'meeting_id' => 111,
                'people_id' => 23,
                'role' => 'leader',
                'group' => 'lead_meeting',
                'remark' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            165 => 
            array (
                'id' => 183,
                'meeting_id' => 128,
                'people_id' => 171,
                'role' => 'leader',
                'group' => 'lead_meeting',
                'remark' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            166 => 
            array (
                'id' => 184,
                'meeting_id' => 149,
                'people_id' => 171,
                'role' => 'leader',
                'group' => 'lead_meeting',
                'remark' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            167 => 
            array (
                'id' => 185,
                'meeting_id' => 150,
                'people_id' => 2,
                'role' => 'leader',
                'group' => 'lead_meeting',
                'remark' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            168 => 
            array (
                'id' => 186,
                'meeting_id' => 152,
                'people_id' => 170,
                'role' => 'leader',
                'group' => 'lead_meeting',
                'remark' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            169 => 
            array (
                'id' => 187,
                'meeting_id' => 157,
                'people_id' => 176,
                'role' => 'leader',
                'group' => 'lead_meeting',
                'remark' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            170 => 
            array (
                'id' => 188,
                'meeting_id' => 158,
                'people_id' => 171,
                'role' => 'leader',
                'group' => 'lead_meeting',
                'remark' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            171 => 
            array (
                'id' => 189,
                'meeting_id' => 159,
                'people_id' => 171,
                'role' => 'leader',
                'group' => 'lead_meeting',
                'remark' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            172 => 
            array (
                'id' => 193,
                'meeting_id' => 1,
                'people_id' => 2386,
                'role' => 'member',
                'group' => 'audient',
                'remark' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            173 => 
            array (
                'id' => 194,
                'meeting_id' => 160,
                'people_id' => 338,
                'role' => 'leader',
                'group' => 'lead_meeting',
                'remark' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            174 => 
            array (
                'id' => 195,
                'meeting_id' => 160,
                'people_id' => 366,
                'role' => 'leader',
                'group' => 'lead_meeting',
                'remark' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            175 => 
            array (
                'id' => 196,
                'meeting_id' => 161,
                'people_id' => 338,
                'role' => 'leader',
                'group' => 'lead_meeting',
                'remark' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            176 => 
            array (
                'id' => 197,
                'meeting_id' => 161,
                'people_id' => 2475,
                'role' => 'leader',
                'group' => 'lead_meeting',
                'remark' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            177 => 
            array (
                'id' => 198,
                'meeting_id' => 162,
                'people_id' => 338,
                'role' => 'leader',
                'group' => 'lead_meeting',
                'remark' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            178 => 
            array (
                'id' => 199,
                'meeting_id' => 162,
                'people_id' => 2475,
                'role' => 'leader',
                'group' => 'lead_meeting',
                'remark' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            179 => 
            array (
                'id' => 200,
                'meeting_id' => 163,
                'people_id' => 207,
                'role' => 'leader',
                'group' => 'lead_meeting',
                'remark' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            180 => 
            array (
                'id' => 201,
                'meeting_id' => 163,
                'people_id' => 201,
                'role' => 'leader',
                'group' => 'lead_meeting',
                'remark' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            181 => 
            array (
                'id' => 202,
                'meeting_id' => 164,
                'people_id' => 170,
                'role' => 'leader',
                'group' => 'lead_meeting',
                'remark' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            182 => 
            array (
                'id' => 203,
                'meeting_id' => 165,
                'people_id' => 2423,
                'role' => 'leader',
                'group' => 'lead_meeting',
                'remark' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            183 => 
            array (
                'id' => 204,
                'meeting_id' => 165,
                'people_id' => 2475,
                'role' => 'leader',
                'group' => 'lead_meeting',
                'remark' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            184 => 
            array (
                'id' => 205,
                'meeting_id' => 166,
                'people_id' => 2423,
                'role' => 'leader',
                'group' => 'lead_meeting',
                'remark' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            185 => 
            array (
                'id' => 206,
                'meeting_id' => 166,
                'people_id' => 2475,
                'role' => 'leader',
                'group' => 'lead_meeting',
                'remark' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            186 => 
            array (
                'id' => 207,
                'meeting_id' => 167,
                'people_id' => 2423,
                'role' => 'leader',
                'group' => 'lead_meeting',
                'remark' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            187 => 
            array (
                'id' => 208,
                'meeting_id' => 167,
                'people_id' => 2475,
                'role' => 'leader',
                'group' => 'lead_meeting',
                'remark' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            188 => 
            array (
                'id' => 216,
                'meeting_id' => 168,
                'people_id' => 2475,
                'role' => 'leader',
                'group' => 'lead_meeting',
                'remark' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            189 => 
            array (
                'id' => 217,
                'meeting_id' => 168,
                'people_id' => 2423,
                'role' => 'leader',
                'group' => 'lead_meeting',
                'remark' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            190 => 
            array (
                'id' => 218,
                'meeting_id' => 169,
                'people_id' => 206,
                'role' => 'leader',
                'group' => 'lead_meeting',
                'remark' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            191 => 
            array (
                'id' => 219,
                'meeting_id' => 170,
                'people_id' => 206,
                'role' => 'leader',
                'group' => 'lead_meeting',
                'remark' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            192 => 
            array (
                'id' => 220,
                'meeting_id' => 171,
                'people_id' => 170,
                'role' => 'leader',
                'group' => 'lead_meeting',
                'remark' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            193 => 
            array (
                'id' => 221,
                'meeting_id' => 172,
                'people_id' => 184,
                'role' => 'leader',
                'group' => 'lead_meeting',
                'remark' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            194 => 
            array (
                'id' => 222,
                'meeting_id' => 173,
                'people_id' => 23,
                'role' => 'leader',
                'group' => 'lead_meeting',
                'remark' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            195 => 
            array (
                'id' => 223,
                'meeting_id' => 173,
                'people_id' => 2385,
                'role' => 'leader',
                'group' => 'lead_meeting',
                'remark' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            196 => 
            array (
                'id' => 224,
                'meeting_id' => 174,
                'people_id' => 23,
                'role' => 'leader',
                'group' => 'lead_meeting',
                'remark' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            197 => 
            array (
                'id' => 225,
                'meeting_id' => 174,
                'people_id' => 2385,
                'role' => 'leader',
                'group' => 'lead_meeting',
                'remark' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            198 => 
            array (
                'id' => 226,
                'meeting_id' => 175,
                'people_id' => 2423,
                'role' => 'leader',
                'group' => 'lead_meeting',
                'remark' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            199 => 
            array (
                'id' => 227,
                'meeting_id' => 175,
                'people_id' => 2475,
                'role' => 'leader',
                'group' => 'lead_meeting',
                'remark' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            200 => 
            array (
                'id' => 228,
                'meeting_id' => 176,
                'people_id' => 2423,
                'role' => 'leader',
                'group' => 'lead_meeting',
                'remark' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            201 => 
            array (
                'id' => 229,
                'meeting_id' => 176,
                'people_id' => 2475,
                'role' => 'leader',
                'group' => 'lead_meeting',
                'remark' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            202 => 
            array (
                'id' => 230,
                'meeting_id' => 177,
                'people_id' => 2423,
                'role' => 'leader',
                'group' => 'lead_meeting',
                'remark' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            203 => 
            array (
                'id' => 231,
                'meeting_id' => 177,
                'people_id' => 2475,
                'role' => 'leader',
                'group' => 'lead_meeting',
                'remark' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            204 => 
            array (
                'id' => 232,
                'meeting_id' => 178,
                'people_id' => 2423,
                'role' => 'leader',
                'group' => 'lead_meeting',
                'remark' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            205 => 
            array (
                'id' => 233,
                'meeting_id' => 178,
                'people_id' => 2475,
                'role' => 'leader',
                'group' => 'lead_meeting',
                'remark' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            206 => 
            array (
                'id' => 234,
                'meeting_id' => 179,
                'people_id' => 170,
                'role' => 'leader',
                'group' => 'lead_meeting',
                'remark' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            207 => 
            array (
                'id' => 235,
                'meeting_id' => 180,
                'people_id' => 2,
                'role' => 'leader',
                'group' => 'lead_meeting',
                'remark' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            208 => 
            array (
                'id' => 237,
                'meeting_id' => 181,
                'people_id' => 152,
                'role' => 'leader',
                'group' => 'lead_meeting',
                'remark' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            209 => 
            array (
                'id' => 238,
                'meeting_id' => 182,
                'people_id' => 2423,
                'role' => 'leader',
                'group' => 'lead_meeting',
                'remark' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            210 => 
            array (
                'id' => 239,
                'meeting_id' => 182,
                'people_id' => 2475,
                'role' => 'leader',
                'group' => 'lead_meeting',
                'remark' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            211 => 
            array (
                'id' => 240,
                'meeting_id' => 183,
                'people_id' => 2423,
                'role' => 'leader',
                'group' => 'lead_meeting',
                'remark' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            212 => 
            array (
                'id' => 241,
                'meeting_id' => 183,
                'people_id' => 2475,
                'role' => 'leader',
                'group' => 'lead_meeting',
                'remark' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            213 => 
            array (
                'id' => 242,
                'meeting_id' => 184,
                'people_id' => 207,
                'role' => 'leader',
                'group' => 'lead_meeting',
                'remark' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            214 => 
            array (
                'id' => 243,
                'meeting_id' => 184,
                'people_id' => 201,
                'role' => 'leader',
                'group' => 'lead_meeting',
                'remark' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            215 => 
            array (
                'id' => 244,
                'meeting_id' => 185,
                'people_id' => 152,
                'role' => 'leader',
                'group' => 'lead_meeting',
                'remark' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            216 => 
            array (
                'id' => 245,
                'meeting_id' => 187,
                'people_id' => 2423,
                'role' => 'leader',
                'group' => 'lead_meeting',
                'remark' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            217 => 
            array (
                'id' => 246,
                'meeting_id' => 187,
                'people_id' => 366,
                'role' => 'leader',
                'group' => 'lead_meeting',
                'remark' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            218 => 
            array (
                'id' => 248,
                'meeting_id' => 188,
                'people_id' => 2423,
                'role' => 'leader',
                'group' => 'lead_meeting',
                'remark' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            219 => 
            array (
                'id' => 249,
                'meeting_id' => 188,
                'people_id' => 366,
                'role' => 'leader',
                'group' => 'lead_meeting',
                'remark' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            220 => 
            array (
                'id' => 250,
                'meeting_id' => 189,
                'people_id' => 2423,
                'role' => 'leader',
                'group' => 'lead_meeting',
                'remark' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            221 => 
            array (
                'id' => 251,
                'meeting_id' => 189,
                'people_id' => 366,
                'role' => 'leader',
                'group' => 'lead_meeting',
                'remark' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            222 => 
            array (
                'id' => 254,
                'meeting_id' => 191,
                'people_id' => 170,
                'role' => 'leader',
                'group' => 'audient',
                'remark' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            223 => 
            array (
                'id' => 255,
                'meeting_id' => 190,
                'people_id' => 2385,
                'role' => 'leader',
                'group' => 'audient',
                'remark' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            224 => 
            array (
                'id' => 256,
                'meeting_id' => 190,
                'people_id' => 23,
                'role' => 'leader',
                'group' => 'audient',
                'remark' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            225 => 
            array (
                'id' => 258,
                'meeting_id' => 193,
                'people_id' => 2385,
                'role' => 'leader',
                'group' => 'audient',
                'remark' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            226 => 
            array (
                'id' => 259,
                'meeting_id' => 193,
                'people_id' => 23,
                'role' => 'leader',
                'group' => 'audient',
                'remark' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            227 => 
            array (
                'id' => 260,
                'meeting_id' => 194,
                'people_id' => 171,
                'role' => 'leader',
                'group' => 'audient',
                'remark' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            228 => 
            array (
                'id' => 261,
                'meeting_id' => 195,
                'people_id' => 231,
                'role' => 'leader',
                'group' => 'audient',
                'remark' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            229 => 
            array (
                'id' => 262,
                'meeting_id' => 196,
                'people_id' => 2423,
                'role' => 'leader',
                'group' => 'audient',
                'remark' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            230 => 
            array (
                'id' => 263,
                'meeting_id' => 196,
                'people_id' => 2475,
                'role' => 'leader',
                'group' => 'audient',
                'remark' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            231 => 
            array (
                'id' => 264,
                'meeting_id' => 197,
                'people_id' => 2423,
                'role' => 'leader',
                'group' => 'audient',
                'remark' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            232 => 
            array (
                'id' => 265,
                'meeting_id' => 197,
                'people_id' => 2475,
                'role' => 'leader',
                'group' => 'audient',
                'remark' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            233 => 
            array (
                'id' => 266,
                'meeting_id' => 198,
                'people_id' => 170,
                'role' => 'leader',
                'group' => 'audient',
                'remark' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            234 => 
            array (
                'id' => 267,
                'meeting_id' => 201,
                'people_id' => 201,
                'role' => 'leader',
                'group' => 'audient',
                'remark' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            235 => 
            array (
                'id' => 268,
                'meeting_id' => 202,
                'people_id' => 23,
                'role' => 'leader',
                'group' => 'audient',
                'remark' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            236 => 
            array (
                'id' => 269,
                'meeting_id' => 202,
                'people_id' => 2423,
                'role' => 'leader',
                'group' => 'audient',
                'remark' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            237 => 
            array (
                'id' => 270,
                'meeting_id' => 203,
                'people_id' => 2423,
                'role' => 'leader',
                'group' => 'audient',
                'remark' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            238 => 
            array (
                'id' => 271,
                'meeting_id' => 203,
                'people_id' => 23,
                'role' => 'leader',
                'group' => 'audient',
                'remark' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            239 => 
            array (
                'id' => 272,
                'meeting_id' => 204,
                'people_id' => 23,
                'role' => 'leader',
                'group' => 'audient',
                'remark' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            240 => 
            array (
                'id' => 273,
                'meeting_id' => 204,
                'people_id' => 2423,
                'role' => 'leader',
                'group' => 'audient',
                'remark' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            241 => 
            array (
                'id' => 274,
                'meeting_id' => 205,
                'people_id' => 23,
                'role' => 'leader',
                'group' => 'audient',
                'remark' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            242 => 
            array (
                'id' => 275,
                'meeting_id' => 205,
                'people_id' => 2423,
                'role' => 'leader',
                'group' => 'audient',
                'remark' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
        ));
        
        
    }
}