<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;

class OrganizationStructuresTableSeeder extends Seeder
{

    /**
     * Auto generated seed file
     *
     * @return void
     */
    public function run()
    {
        

        \DB::table('organization_structures')->delete();
        
        \DB::table('organization_structures')->insert(array (
            0 => 
            array (
                'id' => 14,
                'organization_id' => 408,
                'pid' => 95,
                'tpid' => '0:1:2:95',
                'cids' => NULL,
                'desc' => NULL,
                'image' => '',
                'pdf' => '',
                'active' => 1,
                'created_at' => '2025-06-04 00:00:00',
                'updated_at' => '2025-09-12 08:55:33',
                'deleted_at' => '2025-09-12 08:55:33',
                'created_by' => 1,
                'updated_by' => 1,
                'deleted_by' => 1,
                'total_childs' => NULL,
            ),
            1 => 
            array (
                'id' => 3,
                'organization_id' => 3,
                'pid' => 2,
                'tpid' => '0:1:2:',
                'cids' => '136',
                'desc' => NULL,
                'image' => '',
                'pdf' => '',
                'active' => 1,
                'created_at' => '2025-05-30 00:00:00',
                'updated_at' => '2025-10-01 11:42:21',
                'deleted_at' => NULL,
                'created_by' => 1,
                'updated_by' => 1,
                'deleted_by' => NULL,
                'total_childs' => 0,
            ),
            2 => 
            array (
                'id' => 15,
                'organization_id' => 256,
                'pid' => 2,
                'tpid' => '0:1:2:',
                'cids' => '81',
                'desc' => NULL,
                'image' => '',
                'pdf' => '',
                'active' => 1,
                'created_at' => '2025-06-04 00:00:00',
                'updated_at' => '2025-10-01 11:42:21',
                'deleted_at' => NULL,
                'created_by' => 1,
                'updated_by' => 1,
                'deleted_by' => NULL,
                'total_childs' => 0,
            ),
            3 => 
            array (
                'id' => 29,
                'organization_id' => 15,
                'pid' => 17,
                'tpid' => '0:1:2:98:99:17:',
                'cids' => NULL,
                'desc' => NULL,
                'image' => '',
                'pdf' => '',
                'active' => 1,
                'created_at' => '2025-06-04 00:00:00',
                'updated_at' => '2025-10-01 11:42:22',
                'deleted_at' => NULL,
                'created_by' => 1,
                'updated_by' => 1,
                'deleted_by' => NULL,
                'total_childs' => 0,
            ),
            4 => 
            array (
                'id' => 27,
                'organization_id' => 445,
                'pid' => 17,
                'tpid' => '0:1:2:98:99:17:',
                'cids' => NULL,
                'desc' => NULL,
                'image' => '',
                'pdf' => '',
                'active' => 1,
                'created_at' => '2025-06-04 00:00:00',
                'updated_at' => '2025-10-01 11:42:22',
                'deleted_at' => NULL,
                'created_by' => 1,
                'updated_by' => 1,
                'deleted_by' => NULL,
                'total_childs' => 0,
            ),
            5 => 
            array (
                'id' => 75,
                'organization_id' => 483,
                'pid' => 6,
                'tpid' => '0:1:2:98:99:6:',
                'cids' => NULL,
                'desc' => NULL,
                'image' => '',
                'pdf' => '',
                'active' => 1,
                'created_at' => '2025-07-25 00:00:00',
                'updated_at' => '2025-10-01 11:42:21',
                'deleted_at' => NULL,
                'created_by' => 1,
                'updated_by' => 1,
                'deleted_by' => NULL,
                'total_childs' => 0,
            ),
            6 => 
            array (
                'id' => 33,
                'organization_id' => 27,
                'pid' => 18,
                'tpid' => '0:1:2:98:99:18:',
                'cids' => NULL,
                'desc' => NULL,
                'image' => '',
                'pdf' => '',
                'active' => 1,
                'created_at' => '2025-06-04 00:00:00',
                'updated_at' => '2025-10-01 11:42:22',
                'deleted_at' => NULL,
                'created_by' => 1,
                'updated_by' => 1,
                'deleted_by' => NULL,
                'total_childs' => 0,
            ),
            7 => 
            array (
                'id' => 30,
                'organization_id' => 447,
                'pid' => 18,
                'tpid' => '0:1:2:98:99:18:',
                'cids' => NULL,
                'desc' => NULL,
                'image' => '',
                'pdf' => '',
                'active' => 1,
                'created_at' => '2025-06-04 00:00:00',
                'updated_at' => '2025-10-01 11:42:22',
                'deleted_at' => NULL,
                'created_by' => 1,
                'updated_by' => 1,
                'deleted_by' => NULL,
                'total_childs' => 0,
            ),
            8 => 
            array (
                'id' => 77,
                'organization_id' => 421,
                'pid' => 21,
                'tpid' => '0:1:2:98:101:21:',
                'cids' => NULL,
                'desc' => NULL,
                'image' => '',
                'pdf' => '',
                'active' => 1,
                'created_at' => '2025-07-29 00:00:00',
                'updated_at' => '2025-10-01 11:42:21',
                'deleted_at' => NULL,
                'created_by' => 1,
                'updated_by' => 1,
                'deleted_by' => NULL,
                'total_childs' => 0,
            ),
            9 => 
            array (
                'id' => 41,
                'organization_id' => 456,
                'pid' => 7,
                'tpid' => '0:1:2:98:99:6:7:',
                'cids' => NULL,
                'desc' => NULL,
                'image' => '',
                'pdf' => '',
                'active' => 1,
                'created_at' => '2025-06-10 00:00:00',
                'updated_at' => '2025-10-01 11:42:21',
                'deleted_at' => NULL,
                'created_by' => 1,
                'updated_by' => 1,
                'deleted_by' => NULL,
                'total_childs' => 0,
            ),
            10 => 
            array (
                'id' => 38,
                'organization_id' => 453,
                'pid' => 7,
                'tpid' => '0:1:2:98:99:6:7:',
                'cids' => NULL,
                'desc' => NULL,
                'image' => '',
                'pdf' => '',
                'active' => 1,
                'created_at' => '2025-06-10 00:00:00',
                'updated_at' => '2025-10-01 11:42:21',
                'deleted_at' => NULL,
                'created_by' => 1,
                'updated_by' => 1,
                'deleted_by' => NULL,
                'total_childs' => 0,
            ),
            11 => 
            array (
                'id' => 39,
                'organization_id' => 454,
                'pid' => 7,
                'tpid' => '0:1:2:98:99:6:7:',
                'cids' => NULL,
                'desc' => NULL,
                'image' => '',
                'pdf' => '',
                'active' => 1,
                'created_at' => '2025-06-10 00:00:00',
                'updated_at' => '2025-10-01 11:42:21',
                'deleted_at' => NULL,
                'created_by' => 1,
                'updated_by' => 1,
                'deleted_by' => NULL,
                'total_childs' => 0,
            ),
            12 => 
            array (
                'id' => 46,
                'organization_id' => 461,
                'pid' => 10,
                'tpid' => '0:1:2:98:99:6:10:',
                'cids' => NULL,
                'desc' => NULL,
                'image' => '',
                'pdf' => '',
                'active' => 1,
                'created_at' => '2025-06-10 00:00:00',
                'updated_at' => '2025-10-01 11:42:21',
                'deleted_at' => NULL,
                'created_by' => 1,
                'updated_by' => 1,
                'deleted_by' => NULL,
                'total_childs' => 0,
            ),
            13 => 
            array (
                'id' => 42,
                'organization_id' => 457,
                'pid' => 10,
                'tpid' => '0:1:2:98:99:6:10:',
                'cids' => NULL,
                'desc' => NULL,
                'image' => '',
                'pdf' => '',
                'active' => 1,
                'created_at' => '2025-06-10 00:00:00',
                'updated_at' => '2025-10-01 11:42:21',
                'deleted_at' => NULL,
                'created_by' => 1,
                'updated_by' => 1,
                'deleted_by' => NULL,
                'total_childs' => 0,
            ),
            14 => 
            array (
                'id' => 48,
                'organization_id' => 463,
                'pid' => 8,
                'tpid' => '0:1:2:98:99:6:8:',
                'cids' => NULL,
                'desc' => NULL,
                'image' => '',
                'pdf' => '',
                'active' => 1,
                'created_at' => '2025-06-10 00:00:00',
                'updated_at' => '2025-10-01 11:42:21',
                'deleted_at' => NULL,
                'created_by' => 1,
                'updated_by' => 1,
                'deleted_by' => NULL,
                'total_childs' => 0,
            ),
            15 => 
            array (
                'id' => 49,
                'organization_id' => 464,
                'pid' => 8,
                'tpid' => '0:1:2:98:99:6:8:',
                'cids' => NULL,
                'desc' => NULL,
                'image' => '',
                'pdf' => '',
                'active' => 1,
                'created_at' => '2025-06-10 00:00:00',
                'updated_at' => '2025-10-01 11:42:21',
                'deleted_at' => NULL,
                'created_by' => 1,
                'updated_by' => 1,
                'deleted_by' => NULL,
                'total_childs' => 0,
            ),
            16 => 
            array (
                'id' => 47,
                'organization_id' => 462,
                'pid' => 8,
                'tpid' => '0:1:2:98:99:6:8:',
                'cids' => NULL,
                'desc' => NULL,
                'image' => '',
                'pdf' => '',
                'active' => 1,
                'created_at' => '2025-06-10 00:00:00',
                'updated_at' => '2025-10-01 11:42:21',
                'deleted_at' => NULL,
                'created_by' => 1,
                'updated_by' => 1,
                'deleted_by' => NULL,
                'total_childs' => 0,
            ),
            17 => 
            array (
                'id' => 25,
                'organization_id' => 39,
                'pid' => 99,
                'tpid' => '0:1:2:98:99:',
                'cids' => NULL,
                'desc' => NULL,
                'image' => '',
                'pdf' => '',
                'active' => 1,
                'created_at' => '2025-06-04 00:00:00',
                'updated_at' => '2025-10-01 11:42:21',
                'deleted_at' => NULL,
                'created_by' => 1,
                'updated_by' => 1,
                'deleted_by' => NULL,
                'total_childs' => 0,
            ),
            18 => 
            array (
                'id' => 50,
                'organization_id' => 465,
                'pid' => 9,
                'tpid' => '0:1:2:98:99:6:9:',
                'cids' => NULL,
                'desc' => NULL,
                'image' => '',
                'pdf' => '',
                'active' => 1,
                'created_at' => '2025-06-10 00:00:00',
                'updated_at' => '2025-10-01 11:42:21',
                'deleted_at' => NULL,
                'created_by' => 1,
                'updated_by' => 1,
                'deleted_by' => NULL,
                'total_childs' => 0,
            ),
            19 => 
            array (
                'id' => 9,
                'organization_id' => 8,
                'pid' => 6,
                'tpid' => '0:1:2:98:99:6:',
                'cids' => '50,51,52',
                'desc' => NULL,
                'image' => '',
                'pdf' => '',
                'active' => 1,
                'created_at' => '2025-06-04 00:00:00',
                'updated_at' => '2025-10-01 11:42:21',
                'deleted_at' => NULL,
                'created_by' => 1,
                'updated_by' => 1,
                'deleted_by' => NULL,
                'total_childs' => 0,
            ),
            20 => 
            array (
                'id' => 82,
                'organization_id' => 409,
                'pid' => 23,
                'tpid' => '0:1:2:98:99:23:',
                'cids' => NULL,
                'desc' => NULL,
                'image' => '',
                'pdf' => '',
                'active' => 1,
                'created_at' => '2025-07-31 00:00:00',
                'updated_at' => '2025-10-01 11:42:22',
                'deleted_at' => NULL,
                'created_by' => 1,
                'updated_by' => 1,
                'deleted_by' => NULL,
                'total_childs' => 0,
            ),
            21 => 
            array (
                'id' => 23,
                'organization_id' => 28,
                'pid' => 99,
                'tpid' => '0:1:2:98:99:',
                'cids' => '82,83',
                'desc' => NULL,
                'image' => '',
                'pdf' => '',
                'active' => 1,
                'created_at' => '2025-06-04 00:00:00',
                'updated_at' => '2025-10-01 11:42:21',
                'deleted_at' => NULL,
                'created_by' => 1,
                'updated_by' => 1,
                'deleted_by' => NULL,
                'total_childs' => 0,
            ),
            22 => 
            array (
                'id' => 61,
                'organization_id' => 471,
                'pid' => 57,
                'tpid' => '0:1:2:97:57:',
                'cids' => NULL,
                'desc' => NULL,
                'image' => '',
                'pdf' => '',
                'active' => 1,
                'created_at' => '2025-07-08 00:00:00',
                'updated_at' => '2025-10-01 11:42:21',
                'deleted_at' => NULL,
                'created_by' => 1,
                'updated_by' => 1,
                'deleted_by' => NULL,
                'total_childs' => 0,
            ),
            23 => 
            array (
                'id' => 72,
                'organization_id' => 480,
                'pid' => 58,
                'tpid' => '0:1:2:97:57:58:',
                'cids' => NULL,
                'desc' => NULL,
                'image' => '',
                'pdf' => '',
                'active' => 1,
                'created_at' => '2025-07-08 00:00:00',
                'updated_at' => '2025-10-01 11:42:21',
                'deleted_at' => NULL,
                'created_by' => 1,
                'updated_by' => 1,
                'deleted_by' => NULL,
                'total_childs' => 0,
            ),
            24 => 
            array (
                'id' => 69,
                'organization_id' => 478,
                'pid' => 57,
                'tpid' => '0:1:2:97:57:',
                'cids' => NULL,
                'desc' => NULL,
                'image' => '',
                'pdf' => '',
                'active' => 1,
                'created_at' => '2025-07-08 00:00:00',
                'updated_at' => '2025-10-01 11:42:21',
                'deleted_at' => NULL,
                'created_by' => 1,
                'updated_by' => 1,
                'deleted_by' => NULL,
                'total_childs' => 0,
            ),
            25 => 
            array (
                'id' => 91,
                'organization_id' => 489,
                'pid' => 88,
                'tpid' => '0:1:2:97:87:88:',
                'cids' => NULL,
                'desc' => NULL,
                'image' => '',
                'pdf' => '',
                'active' => 1,
                'created_at' => '2025-08-29 00:00:00',
                'updated_at' => '2025-10-01 11:42:21',
                'deleted_at' => NULL,
                'created_by' => 1,
                'updated_by' => 1,
                'deleted_by' => NULL,
                'total_childs' => 0,
            ),
            26 => 
            array (
                'id' => 62,
                'organization_id' => 472,
                'pid' => 57,
                'tpid' => '0:1:2:97:57:',
                'cids' => NULL,
                'desc' => NULL,
                'image' => '',
                'pdf' => '',
                'active' => 1,
                'created_at' => '2025-07-08 00:00:00',
                'updated_at' => '2025-10-01 11:42:21',
                'deleted_at' => NULL,
                'created_by' => 1,
                'updated_by' => 1,
                'deleted_by' => NULL,
                'total_childs' => 0,
            ),
            27 => 
            array (
                'id' => 81,
                'organization_id' => 179,
                'pid' => 15,
                'tpid' => '0:1:2:15:',
                'cids' => NULL,
                'desc' => NULL,
                'image' => '',
                'pdf' => '',
                'active' => 1,
                'created_at' => '2025-07-31 00:00:00',
                'updated_at' => '2025-10-01 11:42:21',
                'deleted_at' => NULL,
                'created_by' => 1,
                'updated_by' => 1,
                'deleted_by' => NULL,
                'total_childs' => 0,
            ),
            28 => 
            array (
                'id' => 63,
                'organization_id' => 473,
                'pid' => 57,
                'tpid' => '0:1:2:97:57:',
                'cids' => NULL,
                'desc' => NULL,
                'image' => '',
                'pdf' => '',
                'active' => 1,
                'created_at' => '2025-07-08 00:00:00',
                'updated_at' => '2025-10-01 11:42:21',
                'deleted_at' => NULL,
                'created_by' => 1,
                'updated_by' => 1,
                'deleted_by' => NULL,
                'total_childs' => 0,
            ),
            29 => 
            array (
                'id' => 10,
                'organization_id' => 6,
                'pid' => 6,
                'tpid' => '0:1:2:98:99:6:',
                'cids' => '42,43,44,45,46,125',
                'desc' => NULL,
                'image' => '',
                'pdf' => '',
                'active' => 1,
                'created_at' => '2025-06-04 00:00:00',
                'updated_at' => '2025-10-01 11:42:21',
                'deleted_at' => NULL,
                'created_by' => 1,
                'updated_by' => 1,
                'deleted_by' => NULL,
                'total_childs' => 0,
            ),
            30 => 
            array (
                'id' => 64,
                'organization_id' => 474,
                'pid' => 57,
                'tpid' => '0:1:2:97:57:',
                'cids' => NULL,
                'desc' => NULL,
                'image' => '',
                'pdf' => '',
                'active' => 1,
                'created_at' => '2025-07-08 00:00:00',
                'updated_at' => '2025-10-01 11:42:21',
                'deleted_at' => NULL,
                'created_by' => 1,
                'updated_by' => 1,
                'deleted_by' => NULL,
                'total_childs' => 0,
            ),
            31 => 
            array (
                'id' => 73,
                'organization_id' => 481,
                'pid' => 58,
                'tpid' => '0:1:2:97:57:58:',
                'cids' => NULL,
                'desc' => NULL,
                'image' => '',
                'pdf' => '',
                'active' => 1,
                'created_at' => '2025-07-08 00:00:00',
                'updated_at' => '2025-10-01 11:42:21',
                'deleted_at' => NULL,
                'created_by' => 1,
                'updated_by' => 1,
                'deleted_by' => NULL,
                'total_childs' => 0,
            ),
            32 => 
            array (
                'id' => 65,
                'organization_id' => 475,
                'pid' => 57,
                'tpid' => '0:1:2:97:57:',
                'cids' => NULL,
                'desc' => NULL,
                'image' => '',
                'pdf' => '',
                'active' => 1,
                'created_at' => '2025-07-08 00:00:00',
                'updated_at' => '2025-10-01 11:42:21',
                'deleted_at' => NULL,
                'created_by' => 1,
                'updated_by' => 1,
                'deleted_by' => NULL,
                'total_childs' => 0,
            ),
            33 => 
            array (
                'id' => 90,
                'organization_id' => 488,
                'pid' => 88,
                'tpid' => '0:1:2:97:87:88:',
                'cids' => NULL,
                'desc' => NULL,
                'image' => '',
                'pdf' => '',
                'active' => 1,
                'created_at' => '2025-08-29 00:00:00',
                'updated_at' => '2025-10-01 11:42:21',
                'deleted_at' => NULL,
                'created_by' => 1,
                'updated_by' => 1,
                'deleted_by' => NULL,
                'total_childs' => 0,
            ),
            34 => 
            array (
                'id' => 66,
                'organization_id' => 476,
                'pid' => 57,
                'tpid' => '0:1:2:97:57:',
                'cids' => NULL,
                'desc' => NULL,
                'image' => '',
                'pdf' => '',
                'active' => 1,
                'created_at' => '2025-07-08 00:00:00',
                'updated_at' => '2025-10-01 11:42:21',
                'deleted_at' => NULL,
                'created_by' => 1,
                'updated_by' => 1,
                'deleted_by' => NULL,
                'total_childs' => 0,
            ),
            35 => 
            array (
                'id' => 59,
                'organization_id' => 469,
                'pid' => 57,
                'tpid' => '0:1:2:97:57:',
                'cids' => NULL,
                'desc' => NULL,
                'image' => '',
                'pdf' => '',
                'active' => 1,
                'created_at' => '2025-07-08 00:00:00',
                'updated_at' => '2025-10-01 11:42:21',
                'deleted_at' => NULL,
                'created_by' => 1,
                'updated_by' => 1,
                'deleted_by' => NULL,
                'total_childs' => 0,
            ),
            36 => 
            array (
                'id' => 67,
                'organization_id' => 247,
                'pid' => 57,
                'tpid' => '0:1:2:97:57:',
                'cids' => NULL,
                'desc' => NULL,
                'image' => '',
                'pdf' => '',
                'active' => 1,
                'created_at' => '2025-07-08 00:00:00',
                'updated_at' => '2025-10-01 11:42:21',
                'deleted_at' => NULL,
                'created_by' => 1,
                'updated_by' => 1,
                'deleted_by' => NULL,
                'total_childs' => 0,
            ),
            37 => 
            array (
                'id' => 76,
                'organization_id' => 12,
                'pid' => 21,
                'tpid' => '0:1:2:98:101:21:',
                'cids' => NULL,
                'desc' => NULL,
                'image' => '',
                'pdf' => '',
                'active' => 1,
                'created_at' => '2025-07-29 00:00:00',
                'updated_at' => '2025-10-01 11:42:21',
                'deleted_at' => NULL,
                'created_by' => 1,
                'updated_by' => 1,
                'deleted_by' => NULL,
                'total_childs' => 0,
            ),
            38 => 
            array (
                'id' => 74,
                'organization_id' => 482,
                'pid' => 58,
                'tpid' => '0:1:2:97:57:58:',
                'cids' => NULL,
                'desc' => NULL,
                'image' => '',
                'pdf' => '',
                'active' => 1,
                'created_at' => '2025-07-08 00:00:00',
                'updated_at' => '2025-10-01 11:42:21',
                'deleted_at' => NULL,
                'created_by' => 1,
                'updated_by' => 1,
                'deleted_by' => NULL,
                'total_childs' => 0,
            ),
            39 => 
            array (
                'id' => 78,
                'organization_id' => 484,
                'pid' => 19,
                'tpid' => '0:1:2:98:99:19:',
                'cids' => NULL,
                'desc' => NULL,
                'image' => '',
                'pdf' => '',
                'active' => 1,
                'created_at' => '2025-07-31 00:00:00',
                'updated_at' => '2025-10-01 11:42:22',
                'deleted_at' => NULL,
                'created_by' => 1,
                'updated_by' => 1,
                'deleted_by' => NULL,
                'total_childs' => 0,
            ),
            40 => 
            array (
                'id' => 13,
                'organization_id' => 388,
                'pid' => 94,
                'tpid' => '0:1:94:',
                'cids' => NULL,
                'desc' => NULL,
                'image' => '',
                'pdf' => '',
                'active' => 1,
                'created_at' => '2025-06-04 00:00:00',
                'updated_at' => '2025-10-01 11:42:21',
                'deleted_at' => NULL,
                'created_by' => 1,
                'updated_by' => 1,
                'deleted_by' => NULL,
                'total_childs' => 0,
            ),
            41 => 
            array (
                'id' => 11,
                'organization_id' => 386,
                'pid' => 1,
                'tpid' => '0:1:',
                'cids' => NULL,
                'desc' => NULL,
                'image' => '',
                'pdf' => '',
                'active' => 1,
                'created_at' => '2025-06-04 00:00:00',
                'updated_at' => '2025-10-01 11:42:21',
                'deleted_at' => NULL,
                'created_by' => 1,
                'updated_by' => 1,
                'deleted_by' => NULL,
                'total_childs' => 0,
            ),
            42 => 
            array (
                'id' => 35,
                'organization_id' => 450,
                'pid' => 5,
                'tpid' => '0:1:2:98:99:100:5:',
                'cids' => NULL,
                'desc' => NULL,
                'image' => '',
                'pdf' => '',
                'active' => 1,
                'created_at' => '2025-06-06 00:00:00',
                'updated_at' => '2025-10-01 11:42:22',
                'deleted_at' => NULL,
                'created_by' => 1,
                'updated_by' => 1,
                'deleted_by' => NULL,
                'total_childs' => 0,
            ),
            43 => 
            array (
                'id' => 56,
                'organization_id' => 245,
                'pid' => 97,
                'tpid' => '0:1:2:97:',
                'cids' => NULL,
                'desc' => NULL,
                'image' => '',
                'pdf' => '',
                'active' => 1,
                'created_at' => '2025-07-08 00:00:00',
                'updated_at' => '2025-10-01 11:42:21',
                'deleted_at' => NULL,
                'created_by' => 1,
                'updated_by' => 1,
                'deleted_by' => NULL,
                'total_childs' => 0,
            ),
            44 => 
            array (
                'id' => 22,
                'organization_id' => 426,
                'pid' => 99,
                'tpid' => '0:1:2:98:99:',
                'cids' => NULL,
                'desc' => NULL,
                'image' => '',
                'pdf' => '',
                'active' => 1,
                'created_at' => '2025-06-04 00:00:00',
                'updated_at' => '2025-10-01 11:42:22',
                'deleted_at' => NULL,
                'created_by' => 1,
                'updated_by' => 1,
                'deleted_by' => NULL,
                'total_childs' => 0,
            ),
            45 => 
            array (
                'id' => 36,
                'organization_id' => 451,
                'pid' => 5,
                'tpid' => '0:1:2:98:99:100:5:',
                'cids' => NULL,
                'desc' => NULL,
                'image' => '',
                'pdf' => '',
                'active' => 1,
                'created_at' => '2025-06-06 00:00:00',
                'updated_at' => '2025-10-01 11:42:22',
                'deleted_at' => NULL,
                'created_by' => 1,
                'updated_by' => 1,
                'deleted_by' => NULL,
                'total_childs' => 0,
            ),
            46 => 
            array (
                'id' => 16,
                'organization_id' => 248,
                'pid' => 2,
                'tpid' => '0:1:2:',
                'cids' => NULL,
                'desc' => NULL,
                'image' => '',
                'pdf' => '',
                'active' => 1,
                'created_at' => '2025-06-04 00:00:00',
                'updated_at' => '2025-10-01 11:42:21',
                'deleted_at' => NULL,
                'created_by' => 1,
                'updated_by' => 1,
                'deleted_by' => NULL,
                'total_childs' => 0,
            ),
            47 => 
            array (
                'id' => 34,
                'organization_id' => 452,
                'pid' => 5,
                'tpid' => '0:1:2:98:99:100:5:',
                'cids' => NULL,
                'desc' => NULL,
                'image' => '',
                'pdf' => '',
                'active' => 1,
                'created_at' => '2025-06-06 00:00:00',
                'updated_at' => '2025-10-01 11:42:22',
                'deleted_at' => NULL,
                'created_by' => 1,
                'updated_by' => 1,
                'deleted_by' => NULL,
                'total_childs' => 0,
            ),
            48 => 
            array (
                'id' => 5,
                'organization_id' => 401,
                'pid' => 100,
                'tpid' => '0:1:2:98:99:100:',
                'cids' => '34,35,37',
                'desc' => NULL,
                'image' => '',
                'pdf' => '',
                'active' => 1,
                'created_at' => '2025-05-30 00:00:00',
                'updated_at' => '2025-10-01 11:42:22',
                'deleted_at' => NULL,
                'created_by' => 1,
                'updated_by' => 1,
                'deleted_by' => NULL,
                'total_childs' => 0,
            ),
            49 => 
            array (
                'id' => 92,
                'organization_id' => 490,
                'pid' => 89,
                'tpid' => '0:1:2:97:87:89:',
                'cids' => NULL,
                'desc' => NULL,
                'image' => '',
                'pdf' => '',
                'active' => 1,
                'created_at' => '2025-08-29 00:00:00',
                'updated_at' => '2025-10-01 11:42:21',
                'deleted_at' => NULL,
                'created_by' => 1,
                'updated_by' => 1,
                'deleted_by' => NULL,
                'total_childs' => 0,
            ),
            50 => 
            array (
                'id' => 12,
                'organization_id' => 152,
                'pid' => 1,
                'tpid' => '0:1:',
                'cids' => NULL,
                'desc' => NULL,
                'image' => '',
                'pdf' => '',
                'active' => 1,
                'created_at' => '2025-06-04 00:00:00',
                'updated_at' => '2025-10-01 11:42:21',
                'deleted_at' => NULL,
                'created_by' => 1,
                'updated_by' => 1,
                'deleted_by' => NULL,
                'total_childs' => 0,
            ),
            51 => 
            array (
                'id' => 20,
                'organization_id' => 419,
                'pid' => 99,
                'tpid' => '0:1:2:98:99:',
                'cids' => NULL,
                'desc' => NULL,
                'image' => '',
                'pdf' => '',
                'active' => 1,
                'created_at' => '2025-06-04 00:00:00',
                'updated_at' => '2025-10-01 11:42:21',
                'deleted_at' => NULL,
                'created_by' => 1,
                'updated_by' => 1,
                'deleted_by' => NULL,
                'total_childs' => 0,
            ),
            52 => 
            array (
                'id' => 87,
                'organization_id' => 437,
                'pid' => 97,
                'tpid' => '0:1:2:97:',
                'cids' => '88,89',
                'desc' => NULL,
                'image' => '',
                'pdf' => '',
                'active' => 1,
                'created_at' => '2025-08-25 00:00:00',
                'updated_at' => '2025-10-01 11:42:21',
                'deleted_at' => NULL,
                'created_by' => 1,
                'updated_by' => 1,
                'deleted_by' => NULL,
                'total_childs' => 0,
            ),
            53 => 
            array (
                'id' => 83,
                'organization_id' => 410,
                'pid' => 23,
                'tpid' => '0:1:2:98:99:23:',
                'cids' => NULL,
                'desc' => NULL,
                'image' => '',
                'pdf' => '',
                'active' => 1,
                'created_at' => '2025-07-31 00:00:00',
                'updated_at' => '2025-10-01 11:42:22',
                'deleted_at' => NULL,
                'created_by' => 1,
                'updated_by' => 1,
                'deleted_by' => NULL,
                'total_childs' => 0,
            ),
            54 => 
            array (
                'id' => 6,
                'organization_id' => 5,
                'pid' => 99,
                'tpid' => '0:1:2:98:99:',
                'cids' => '7,8,9,10',
                'desc' => NULL,
                'image' => '',
                'pdf' => '',
                'active' => 1,
                'created_at' => '2025-06-04 00:00:00',
                'updated_at' => '2025-10-01 11:42:21',
                'deleted_at' => NULL,
                'created_by' => 1,
                'updated_by' => 1,
                'deleted_by' => NULL,
                'total_childs' => 0,
            ),
            55 => 
            array (
                'id' => 52,
                'organization_id' => 467,
                'pid' => 9,
                'tpid' => '0:1:2:98:99:6:9:',
                'cids' => NULL,
                'desc' => NULL,
                'image' => '',
                'pdf' => '',
                'active' => 1,
                'created_at' => '2025-06-10 00:00:00',
                'updated_at' => '2025-10-01 11:42:21',
                'deleted_at' => NULL,
                'created_by' => 1,
                'updated_by' => 1,
                'deleted_by' => NULL,
                'total_childs' => 0,
            ),
            56 => 
            array (
                'id' => 45,
                'organization_id' => 460,
                'pid' => 10,
                'tpid' => '0:1:2:98:99:6:10:',
                'cids' => NULL,
                'desc' => NULL,
                'image' => '',
                'pdf' => '',
                'active' => 1,
                'created_at' => '2025-06-10 00:00:00',
                'updated_at' => '2025-10-01 11:42:21',
                'deleted_at' => NULL,
                'created_by' => 1,
                'updated_by' => 1,
                'deleted_by' => NULL,
                'total_childs' => 0,
            ),
            57 => 
            array (
                'id' => 24,
                'organization_id' => 429,
                'pid' => 99,
                'tpid' => '0:1:2:98:99:',
                'cids' => NULL,
                'desc' => NULL,
                'image' => '',
                'pdf' => '',
                'active' => 1,
                'created_at' => '2025-06-04 00:00:00',
                'updated_at' => '2025-10-01 11:42:22',
                'deleted_at' => NULL,
                'created_by' => 1,
                'updated_by' => 1,
                'deleted_by' => NULL,
                'total_childs' => 0,
            ),
            58 => 
            array (
                'id' => 80,
                'organization_id' => 22,
                'pid' => 19,
                'tpid' => '0:1:2:98:99:19:',
                'cids' => NULL,
                'desc' => NULL,
                'image' => '',
                'pdf' => '',
                'active' => 1,
                'created_at' => '2025-07-31 00:00:00',
                'updated_at' => '2025-10-01 11:42:22',
                'deleted_at' => NULL,
                'created_by' => 1,
                'updated_by' => 1,
                'deleted_by' => NULL,
                'total_childs' => 0,
            ),
            59 => 
            array (
                'id' => 28,
                'organization_id' => 446,
                'pid' => 17,
                'tpid' => '0:1:2:98:99:17:',
                'cids' => NULL,
                'desc' => NULL,
                'image' => '',
                'pdf' => '',
                'active' => 1,
                'created_at' => '2025-06-04 00:00:00',
                'updated_at' => '2025-10-01 11:42:22',
                'deleted_at' => NULL,
                'created_by' => 1,
                'updated_by' => 1,
                'deleted_by' => NULL,
                'total_childs' => 0,
            ),
            60 => 
            array (
                'id' => 128,
                'organization_id' => 403,
                'pid' => 97,
                'tpid' => '0:1:2:97:',
                'cids' => NULL,
                'desc' => NULL,
                'image' => '',
                'pdf' => '',
                'active' => 1,
                'created_at' => '2025-09-12 00:00:00',
                'updated_at' => '2025-10-01 11:42:21',
                'deleted_at' => NULL,
                'created_by' => 1,
                'updated_by' => 1,
                'deleted_by' => NULL,
                'total_childs' => 0,
            ),
            61 => 
            array (
                'id' => 54,
                'organization_id' => 381,
                'pid' => 97,
                'tpid' => '0:1:2:97:',
                'cids' => NULL,
                'desc' => NULL,
                'image' => '',
                'pdf' => '',
                'active' => 1,
                'created_at' => '2025-07-08 00:00:00',
                'updated_at' => '2025-10-01 11:42:21',
                'deleted_at' => NULL,
                'created_by' => 1,
                'updated_by' => 1,
                'deleted_by' => NULL,
                'total_childs' => 0,
            ),
            62 => 
            array (
                'id' => 4,
                'organization_id' => 443,
                'pid' => 96,
                'tpid' => '0:1:2:96:',
                'cids' => NULL,
                'desc' => NULL,
                'image' => '',
                'pdf' => '',
                'active' => 1,
                'created_at' => '2025-05-30 00:00:00',
                'updated_at' => '2025-10-01 11:42:22',
                'deleted_at' => NULL,
                'created_by' => 1,
                'updated_by' => 1,
                'deleted_by' => NULL,
                'total_childs' => 0,
            ),
            63 => 
            array (
                'id' => 53,
                'organization_id' => 285,
                'pid' => 94,
                'tpid' => '0:1:94:',
                'cids' => NULL,
                'desc' => NULL,
                'image' => '',
                'pdf' => '',
                'active' => 1,
                'created_at' => '2025-07-07 00:00:00',
                'updated_at' => '2025-10-01 11:42:21',
                'deleted_at' => NULL,
                'created_by' => 1,
                'updated_by' => 1,
                'deleted_by' => NULL,
                'total_childs' => 0,
            ),
            64 => 
            array (
                'id' => 32,
                'organization_id' => 449,
                'pid' => 18,
                'tpid' => '0:1:2:98:99:18:',
                'cids' => NULL,
                'desc' => NULL,
                'image' => '',
                'pdf' => '',
                'active' => 1,
                'created_at' => '2025-06-04 00:00:00',
                'updated_at' => '2025-10-01 11:42:22',
                'deleted_at' => NULL,
                'created_by' => 1,
                'updated_by' => 1,
                'deleted_by' => NULL,
                'total_childs' => 0,
            ),
            65 => 
            array (
                'id' => 40,
                'organization_id' => 455,
                'pid' => 7,
                'tpid' => '0:1:2:98:99:6:7:',
                'cids' => NULL,
                'desc' => NULL,
                'image' => '',
                'pdf' => '',
                'active' => 1,
                'created_at' => '2025-06-10 00:00:00',
                'updated_at' => '2025-10-01 11:42:21',
                'deleted_at' => NULL,
                'created_by' => 1,
                'updated_by' => 1,
                'deleted_by' => NULL,
                'total_childs' => 0,
            ),
            66 => 
            array (
                'id' => 93,
                'organization_id' => 491,
                'pid' => 89,
                'tpid' => '0:1:2:97:87:89:',
                'cids' => NULL,
                'desc' => NULL,
                'image' => '',
                'pdf' => '',
                'active' => 1,
                'created_at' => '2025-08-29 00:00:00',
                'updated_at' => '2025-10-01 11:42:21',
                'deleted_at' => NULL,
                'created_by' => 1,
                'updated_by' => 1,
                'deleted_by' => NULL,
                'total_childs' => 0,
            ),
            67 => 
            array (
                'id' => 84,
                'organization_id' => 442,
                'pid' => 97,
                'tpid' => '0:1:2:97:',
                'cids' => '85',
                'desc' => NULL,
                'image' => '',
                'pdf' => '',
                'active' => 1,
                'created_at' => '2025-08-08 00:00:00',
                'updated_at' => '2025-10-01 11:42:21',
                'deleted_at' => NULL,
                'created_by' => 1,
                'updated_by' => 1,
                'deleted_by' => NULL,
                'total_childs' => 0,
            ),
            68 => 
            array (
                'id' => 68,
                'organization_id' => 477,
                'pid' => 57,
                'tpid' => '0:1:2:97:57:',
                'cids' => NULL,
                'desc' => NULL,
                'image' => '',
                'pdf' => '',
                'active' => 1,
                'created_at' => '2025-07-08 00:00:00',
                'updated_at' => '2025-10-01 11:42:21',
                'deleted_at' => NULL,
                'created_by' => 1,
                'updated_by' => 1,
                'deleted_by' => NULL,
                'total_childs' => 0,
            ),
            69 => 
            array (
                'id' => 71,
                'organization_id' => 479,
                'pid' => 58,
                'tpid' => '0:1:2:97:57:58:',
                'cids' => NULL,
                'desc' => NULL,
                'image' => '',
                'pdf' => '',
                'active' => 1,
                'created_at' => '2025-07-08 00:00:00',
                'updated_at' => '2025-10-01 11:42:21',
                'deleted_at' => NULL,
                'created_by' => 1,
                'updated_by' => 1,
                'deleted_by' => NULL,
                'total_childs' => 0,
            ),
            70 => 
            array (
                'id' => 21,
                'organization_id' => 420,
                'pid' => 101,
                'tpid' => '0:1:2:98:101:',
                'cids' => '76,77',
                'desc' => NULL,
                'image' => '',
                'pdf' => '',
                'active' => 1,
                'created_at' => '2025-06-04 00:00:00',
                'updated_at' => '2025-10-01 11:42:21',
                'deleted_at' => NULL,
                'created_by' => 1,
                'updated_by' => 1,
                'deleted_by' => NULL,
                'total_childs' => 0,
            ),
            71 => 
            array (
                'id' => 26,
                'organization_id' => 38,
                'pid' => 2,
                'tpid' => '0:1:2:',
                'cids' => NULL,
                'desc' => NULL,
                'image' => '',
                'pdf' => '',
                'active' => 1,
                'created_at' => '2025-06-04 00:00:00',
                'updated_at' => '2025-10-01 11:42:21',
                'deleted_at' => NULL,
                'created_by' => 1,
                'updated_by' => 1,
                'deleted_by' => NULL,
                'total_childs' => 0,
            ),
            72 => 
            array (
                'id' => 110,
                'organization_id' => 404,
                'pid' => 96,
                'tpid' => '0:1:2:96:',
                'cids' => NULL,
                'desc' => NULL,
                'image' => '',
                'pdf' => '',
                'active' => 1,
                'created_at' => '2025-09-12 00:00:00',
                'updated_at' => '2025-10-01 11:42:22',
                'deleted_at' => NULL,
                'created_by' => 1,
                'updated_by' => 1,
                'deleted_by' => NULL,
                'total_childs' => 0,
            ),
            73 => 
            array (
                'id' => 109,
                'organization_id' => 439,
                'pid' => 96,
                'tpid' => '0:1:2:96:',
                'cids' => NULL,
                'desc' => NULL,
                'image' => '',
                'pdf' => '',
                'active' => 1,
                'created_at' => '2025-09-12 00:00:00',
                'updated_at' => '2025-10-01 11:42:22',
                'deleted_at' => NULL,
                'created_by' => 1,
                'updated_by' => 1,
                'deleted_by' => NULL,
                'total_childs' => 0,
            ),
            74 => 
            array (
                'id' => 111,
                'organization_id' => 431,
                'pid' => 96,
                'tpid' => '0:1:2:96:',
                'cids' => NULL,
                'desc' => NULL,
                'image' => '',
                'pdf' => '',
                'active' => 1,
                'created_at' => '2025-09-12 00:00:00',
                'updated_at' => '2025-10-01 11:42:22',
                'deleted_at' => NULL,
                'created_by' => 1,
                'updated_by' => 1,
                'deleted_by' => NULL,
                'total_childs' => 0,
            ),
            75 => 
            array (
                'id' => 112,
                'organization_id' => 435,
                'pid' => 96,
                'tpid' => '0:1:2:96:',
                'cids' => NULL,
                'desc' => NULL,
                'image' => '',
                'pdf' => '',
                'active' => 1,
                'created_at' => '2025-09-12 00:00:00',
                'updated_at' => '2025-10-01 11:42:22',
                'deleted_at' => NULL,
                'created_by' => 1,
                'updated_by' => 1,
                'deleted_by' => NULL,
                'total_childs' => 0,
            ),
            76 => 
            array (
                'id' => 118,
                'organization_id' => 433,
                'pid' => 96,
                'tpid' => '0:1:2:96:',
                'cids' => NULL,
                'desc' => NULL,
                'image' => '',
                'pdf' => '',
                'active' => 1,
                'created_at' => '2025-09-12 00:00:00',
                'updated_at' => '2025-10-01 11:42:22',
                'deleted_at' => NULL,
                'created_by' => 1,
                'updated_by' => 1,
                'deleted_by' => NULL,
                'total_childs' => 0,
            ),
            77 => 
            array (
                'id' => 115,
                'organization_id' => 412,
                'pid' => 96,
                'tpid' => '0:1:2:96:',
                'cids' => NULL,
                'desc' => NULL,
                'image' => '',
                'pdf' => '',
                'active' => 1,
                'created_at' => '2025-09-12 00:00:00',
                'updated_at' => '2025-10-01 11:42:22',
                'deleted_at' => NULL,
                'created_by' => 1,
                'updated_by' => 1,
                'deleted_by' => NULL,
                'total_childs' => 0,
            ),
            78 => 
            array (
                'id' => 124,
                'organization_id' => 413,
                'pid' => 97,
                'tpid' => '0:1:2:97:',
                'cids' => NULL,
                'desc' => NULL,
                'image' => '',
                'pdf' => '',
                'active' => 1,
                'created_at' => '2025-09-12 00:00:00',
                'updated_at' => '2025-10-01 11:42:21',
                'deleted_at' => NULL,
                'created_by' => 1,
                'updated_by' => 1,
                'deleted_by' => NULL,
                'total_childs' => 0,
            ),
            79 => 
            array (
                'id' => 57,
                'organization_id' => 66,
                'pid' => 97,
                'tpid' => '0:1:2:97:',
                'cids' => '58,59,60,61,62,63,64,65,66,67,68,69',
                'desc' => NULL,
                'image' => '',
                'pdf' => '',
                'active' => 1,
                'created_at' => '2025-07-08 00:00:00',
                'updated_at' => '2025-10-01 11:42:21',
                'deleted_at' => NULL,
                'created_by' => 1,
                'updated_by' => 1,
                'deleted_by' => NULL,
                'total_childs' => 0,
            ),
            80 => 
            array (
                'id' => 58,
                'organization_id' => 468,
                'pid' => 57,
                'tpid' => '0:1:2:97:57:',
                'cids' => '70,71,72,73,74',
                'desc' => NULL,
                'image' => '',
                'pdf' => '',
                'active' => 1,
                'created_at' => '2025-07-08 00:00:00',
                'updated_at' => '2025-10-01 11:42:21',
                'deleted_at' => NULL,
                'created_by' => 1,
                'updated_by' => 1,
                'deleted_by' => NULL,
                'total_childs' => 0,
            ),
            81 => 
            array (
                'id' => 60,
                'organization_id' => 470,
                'pid' => 57,
                'tpid' => '0:1:2:97:57:',
                'cids' => NULL,
                'desc' => NULL,
                'image' => '',
                'pdf' => '',
                'active' => 1,
                'created_at' => '2025-07-08 00:00:00',
                'updated_at' => '2025-10-01 11:42:21',
                'deleted_at' => NULL,
                'created_by' => 1,
                'updated_by' => 1,
                'deleted_by' => NULL,
                'total_childs' => 0,
            ),
            82 => 
            array (
                'id' => 135,
                'organization_id' => 31,
                'pid' => 97,
                'tpid' => '0:1:2:97:',
                'cids' => NULL,
                'desc' => NULL,
                'image' => '',
                'pdf' => '',
                'active' => 1,
                'created_at' => '2025-09-12 00:00:00',
                'updated_at' => '2025-10-01 11:42:21',
                'deleted_at' => NULL,
                'created_by' => 1,
                'updated_by' => 1,
                'deleted_by' => NULL,
                'total_childs' => 0,
            ),
            83 => 
            array (
                'id' => 8,
                'organization_id' => 444,
                'pid' => 6,
                'tpid' => '0:1:2:98:99:6:',
                'cids' => '47,48,49',
                'desc' => NULL,
                'image' => '',
                'pdf' => '',
                'active' => 1,
                'created_at' => '2025-06-04 00:00:00',
                'updated_at' => '2025-10-01 11:42:21',
                'deleted_at' => NULL,
                'created_by' => 1,
                'updated_by' => 1,
                'deleted_by' => NULL,
                'total_childs' => 0,
            ),
            84 => 
            array (
                'id' => 108,
                'organization_id' => 417,
                'pid' => 97,
                'tpid' => '0:1:2:97:',
                'cids' => NULL,
                'desc' => NULL,
                'image' => '',
                'pdf' => '',
                'active' => 1,
                'created_at' => '2025-09-12 00:00:00',
                'updated_at' => '2025-10-01 11:42:21',
                'deleted_at' => NULL,
                'created_by' => 1,
                'updated_by' => 1,
                'deleted_by' => NULL,
                'total_childs' => 0,
            ),
            85 => 
            array (
                'id' => 121,
                'organization_id' => 430,
                'pid' => 97,
                'tpid' => '0:1:2:97:',
                'cids' => NULL,
                'desc' => NULL,
                'image' => '',
                'pdf' => '',
                'active' => 1,
                'created_at' => '2025-09-12 00:00:00',
                'updated_at' => '2025-10-01 11:42:21',
                'deleted_at' => NULL,
                'created_by' => 1,
                'updated_by' => 1,
                'deleted_by' => NULL,
                'total_childs' => 0,
            ),
            86 => 
            array (
                'id' => 133,
                'organization_id' => 328,
                'pid' => 97,
                'tpid' => '0:1:2:97:',
                'cids' => NULL,
                'desc' => NULL,
                'image' => '',
                'pdf' => '',
                'active' => 1,
                'created_at' => '2025-09-12 00:00:00',
                'updated_at' => '2025-10-01 11:42:21',
                'deleted_at' => NULL,
                'created_by' => 1,
                'updated_by' => 1,
                'deleted_by' => NULL,
                'total_childs' => 0,
            ),
            87 => 
            array (
                'id' => 88,
                'organization_id' => 486,
                'pid' => 87,
                'tpid' => '0:1:2:97:87:',
                'cids' => '90,91',
                'desc' => NULL,
                'image' => '',
                'pdf' => '',
                'active' => 1,
                'created_at' => '2025-08-25 00:00:00',
                'updated_at' => '2025-10-01 11:42:21',
                'deleted_at' => NULL,
                'created_by' => 1,
                'updated_by' => 1,
                'deleted_by' => NULL,
                'total_childs' => 0,
            ),
            88 => 
            array (
                'id' => 116,
                'organization_id' => 440,
                'pid' => 96,
                'tpid' => '0:1:2:96:',
                'cids' => NULL,
                'desc' => NULL,
                'image' => '',
                'pdf' => '',
                'active' => 1,
                'created_at' => '2025-09-12 00:00:00',
                'updated_at' => '2025-10-01 11:42:22',
                'deleted_at' => NULL,
                'created_by' => 1,
                'updated_by' => 1,
                'deleted_by' => NULL,
                'total_childs' => 0,
            ),
            89 => 
            array (
                'id' => 119,
                'organization_id' => 432,
                'pid' => 96,
                'tpid' => '0:1:2:96:',
                'cids' => NULL,
                'desc' => NULL,
                'image' => '',
                'pdf' => '',
                'active' => 1,
                'created_at' => '2025-09-12 00:00:00',
                'updated_at' => '2025-10-01 11:42:22',
                'deleted_at' => NULL,
                'created_by' => 1,
                'updated_by' => 1,
                'deleted_by' => NULL,
                'total_childs' => 0,
            ),
            90 => 
            array (
                'id' => 120,
                'organization_id' => 436,
                'pid' => 96,
                'tpid' => '0:1:2:96:',
                'cids' => NULL,
                'desc' => NULL,
                'image' => '',
                'pdf' => '',
                'active' => 1,
                'created_at' => '2025-09-12 00:00:00',
                'updated_at' => '2025-10-01 11:42:22',
                'deleted_at' => NULL,
                'created_by' => 1,
                'updated_by' => 1,
                'deleted_by' => NULL,
                'total_childs' => 0,
            ),
            91 => 
            array (
                'id' => 113,
                'organization_id' => 434,
                'pid' => 96,
                'tpid' => '0:1:2:96:',
                'cids' => NULL,
                'desc' => NULL,
                'image' => '',
                'pdf' => '',
                'active' => 1,
                'created_at' => '2025-09-12 00:00:00',
                'updated_at' => '2025-10-01 11:42:22',
                'deleted_at' => NULL,
                'created_by' => 1,
                'updated_by' => 1,
                'deleted_by' => NULL,
                'total_childs' => 0,
            ),
            92 => 
            array (
                'id' => 131,
                'organization_id' => 371,
                'pid' => 97,
                'tpid' => '0:1:2:97:',
                'cids' => NULL,
                'desc' => NULL,
                'image' => '',
                'pdf' => '',
                'active' => 1,
                'created_at' => '2025-09-12 00:00:00',
                'updated_at' => '2025-10-01 11:42:21',
                'deleted_at' => NULL,
                'created_by' => 1,
                'updated_by' => 1,
                'deleted_by' => NULL,
                'total_childs' => 0,
            ),
            93 => 
            array (
                'id' => 100,
                'organization_id' => 498,
                'pid' => 99,
                'tpid' => '0:1:2:98:99:',
                'cids' => NULL,
                'desc' => NULL,
                'image' => '',
                'pdf' => '',
                'active' => 1,
                'created_at' => '2025-09-04 00:00:00',
                'updated_at' => '2025-10-01 11:42:22',
                'deleted_at' => NULL,
                'created_by' => 1,
                'updated_by' => 1,
                'deleted_by' => NULL,
                'total_childs' => 0,
            ),
            94 => 
            array (
                'id' => 96,
                'organization_id' => 153,
                'pid' => 2,
                'tpid' => '0:1:2:',
                'cids' => '109,110,111,132,137,138,139',
                'desc' => NULL,
                'image' => '',
                'pdf' => '',
                'active' => 1,
                'created_at' => '2025-09-02 00:00:00',
                'updated_at' => '2025-10-01 11:42:22',
                'deleted_at' => NULL,
                'created_by' => 1,
                'updated_by' => 1,
                'deleted_by' => NULL,
                'total_childs' => 0,
            ),
            95 => 
            array (
                'id' => 19,
                'organization_id' => 19,
                'pid' => 99,
                'tpid' => '0:1:2:98:99:',
                'cids' => '78,79,80',
                'desc' => NULL,
                'image' => '',
                'pdf' => '',
                'active' => 1,
                'created_at' => '2025-06-04 00:00:00',
                'updated_at' => '2025-10-01 11:42:22',
                'deleted_at' => NULL,
                'created_by' => 1,
                'updated_by' => 1,
                'deleted_by' => NULL,
                'total_childs' => 0,
            ),
            96 => 
            array (
                'id' => 2,
                'organization_id' => 2,
                'pid' => 1,
                'tpid' => '0:1:',
                'cids' => '3,4,5,6,14,15,16,17,18,19,20,21,22,23,24,25,26,54,55,56,57,84,87,95,96,97,98,106,107',
                'desc' => NULL,
                'image' => '',
                'pdf' => '',
                'active' => 1,
                'created_at' => '2025-05-30 00:00:00',
                'updated_at' => '2025-10-01 11:42:21',
                'deleted_at' => NULL,
                'created_by' => 1,
                'updated_by' => 1,
                'deleted_by' => NULL,
                'total_childs' => 0,
            ),
            97 => 
            array (
                'id' => 129,
                'organization_id' => 394,
                'pid' => 97,
                'tpid' => '0:1:2:97:',
                'cids' => NULL,
                'desc' => NULL,
                'image' => '',
                'pdf' => '',
                'active' => 1,
                'created_at' => '2025-09-12 00:00:00',
                'updated_at' => '2025-10-01 11:42:21',
                'deleted_at' => NULL,
                'created_by' => 1,
                'updated_by' => 1,
                'deleted_by' => NULL,
                'total_childs' => 0,
            ),
            98 => 
            array (
                'id' => 136,
                'organization_id' => 4,
                'pid' => 3,
                'tpid' => '0:1:2:3:',
                'cids' => NULL,
                'desc' => NULL,
                'image' => '',
                'pdf' => '',
                'active' => 1,
                'created_at' => '2025-09-12 00:00:00',
                'updated_at' => '2025-10-01 11:42:21',
                'deleted_at' => NULL,
                'created_by' => 1,
                'updated_by' => 1,
                'deleted_by' => NULL,
                'total_childs' => 0,
            ),
            99 => 
            array (
                'id' => 104,
                'organization_id' => 113,
                'pid' => 0,
                'tpid' => '0:',
                'cids' => NULL,
                'desc' => NULL,
                'image' => '',
                'pdf' => '',
                'active' => 1,
                'created_at' => '2025-09-10 00:00:00',
                'updated_at' => '2025-09-18 08:36:32',
                'deleted_at' => '2025-09-29 08:32:41',
                'created_by' => 1,
                'updated_by' => 1,
                'deleted_by' => NULL,
                'total_childs' => 0,
            ),
            100 => 
            array (
                'id' => 43,
                'organization_id' => 458,
                'pid' => 10,
                'tpid' => '0:1:2:98:99:6:10:',
                'cids' => NULL,
                'desc' => NULL,
                'image' => '',
                'pdf' => '',
                'active' => 1,
                'created_at' => '2025-06-10 00:00:00',
                'updated_at' => '2025-10-01 11:42:21',
                'deleted_at' => NULL,
                'created_by' => 1,
                'updated_by' => 1,
                'deleted_by' => NULL,
                'total_childs' => 0,
            ),
            101 => 
            array (
                'id' => 1,
                'organization_id' => 118,
                'pid' => 0,
                'tpid' => '0:',
                'cids' => '2,11,12,13,94,102,112,113,114,115,116,117,118,119,120',
                'desc' => NULL,
                'image' => '',
                'pdf' => '',
                'active' => 1,
                'created_at' => '2025-05-30 00:00:00',
                'updated_at' => '2025-10-01 11:42:21',
                'deleted_at' => NULL,
                'created_by' => 1,
                'updated_by' => 1,
                'deleted_by' => NULL,
                'total_childs' => 0,
            ),
            102 => 
            array (
                'id' => 105,
                'organization_id' => 295,
                'pid' => 0,
                'tpid' => '0:',
                'cids' => NULL,
                'desc' => NULL,
                'image' => '',
                'pdf' => '',
                'active' => 1,
                'created_at' => '2025-09-10 00:00:00',
                'updated_at' => '2025-09-18 08:36:32',
                'deleted_at' => '2025-09-29 08:32:41',
                'created_by' => 1,
                'updated_by' => 1,
                'deleted_by' => NULL,
                'total_childs' => 0,
            ),
            103 => 
            array (
                'id' => 79,
                'organization_id' => 485,
                'pid' => 19,
                'tpid' => '0:1:2:98:99:19:',
                'cids' => NULL,
                'desc' => NULL,
                'image' => '',
                'pdf' => '',
                'active' => 1,
                'created_at' => '2025-07-31 00:00:00',
                'updated_at' => '2025-10-01 11:42:22',
                'deleted_at' => NULL,
                'created_by' => 1,
                'updated_by' => 1,
                'deleted_by' => NULL,
                'total_childs' => 0,
            ),
            104 => 
            array (
                'id' => 44,
                'organization_id' => 459,
                'pid' => 10,
                'tpid' => '0:1:2:98:99:6:10:',
                'cids' => NULL,
                'desc' => NULL,
                'image' => '',
                'pdf' => '',
                'active' => 1,
                'created_at' => '2025-06-10 00:00:00',
                'updated_at' => '2025-10-01 11:42:21',
                'deleted_at' => NULL,
                'created_by' => 1,
                'updated_by' => 1,
                'deleted_by' => NULL,
                'total_childs' => 0,
            ),
            105 => 
            array (
                'id' => 89,
                'organization_id' => 487,
                'pid' => 87,
                'tpid' => '0:1:2:97:87:',
                'cids' => '92,93',
                'desc' => NULL,
                'image' => '',
                'pdf' => '',
                'active' => 1,
                'created_at' => '2025-08-25 00:00:00',
                'updated_at' => '2025-10-01 11:42:21',
                'deleted_at' => NULL,
                'created_by' => 1,
                'updated_by' => 1,
                'deleted_by' => NULL,
                'total_childs' => 0,
            ),
            106 => 
            array (
                'id' => 137,
                'organization_id' => 500,
                'pid' => 96,
                'tpid' => '0:1:2:96:',
                'cids' => NULL,
                'desc' => NULL,
                'image' => '',
                'pdf' => '',
                'active' => 1,
                'created_at' => '2025-09-12 00:00:00',
                'updated_at' => '2025-10-01 11:42:22',
                'deleted_at' => NULL,
                'created_by' => 1,
                'updated_by' => 1,
                'deleted_by' => NULL,
                'total_childs' => 0,
            ),
            107 => 
            array (
                'id' => 125,
                'organization_id' => 418,
                'pid' => 10,
                'tpid' => '0:1:2:98:99:6:10:',
                'cids' => NULL,
                'desc' => NULL,
                'image' => '',
                'pdf' => '',
                'active' => 1,
                'created_at' => '2025-09-12 00:00:00',
                'updated_at' => '2025-10-01 11:42:21',
                'deleted_at' => NULL,
                'created_by' => 1,
                'updated_by' => 1,
                'deleted_by' => NULL,
                'total_childs' => 0,
            ),
            108 => 
            array (
                'id' => 134,
                'organization_id' => 88,
                'pid' => 97,
                'tpid' => '0:1:2:97:',
                'cids' => NULL,
                'desc' => NULL,
                'image' => '',
                'pdf' => '',
                'active' => 1,
                'created_at' => '2025-09-12 00:00:00',
                'updated_at' => '2025-10-01 11:42:21',
                'deleted_at' => NULL,
                'created_by' => 1,
                'updated_by' => 1,
                'deleted_by' => NULL,
                'total_childs' => 0,
            ),
            109 => 
            array (
                'id' => 126,
                'organization_id' => 411,
                'pid' => 97,
                'tpid' => '0:1:2:97:',
                'cids' => NULL,
                'desc' => NULL,
                'image' => '',
                'pdf' => '',
                'active' => 1,
                'created_at' => '2025-09-12 00:00:00',
                'updated_at' => '2025-10-01 11:42:21',
                'deleted_at' => NULL,
                'created_by' => 1,
                'updated_by' => 1,
                'deleted_by' => NULL,
                'total_childs' => 0,
            ),
            110 => 
            array (
                'id' => 85,
                'organization_id' => 441,
                'pid' => 84,
                'tpid' => '0:1:2:97:84:',
                'cids' => NULL,
                'desc' => NULL,
                'image' => '',
                'pdf' => '',
                'active' => 1,
                'created_at' => '2025-08-08 00:00:00',
                'updated_at' => '2025-10-01 11:42:21',
                'deleted_at' => NULL,
                'created_by' => 1,
                'updated_by' => 1,
                'deleted_by' => NULL,
                'total_childs' => 0,
            ),
            111 => 
            array (
                'id' => 103,
                'organization_id' => 193,
                'pid' => 0,
                'tpid' => '0:',
                'cids' => NULL,
                'desc' => NULL,
                'image' => '',
                'pdf' => '',
                'active' => 1,
                'created_at' => '2025-09-10 00:00:00',
                'updated_at' => '2025-09-18 08:36:32',
                'deleted_at' => '2025-09-29 08:32:41',
                'created_by' => 1,
                'updated_by' => 1,
                'deleted_by' => NULL,
                'total_childs' => 0,
            ),
            112 => 
            array (
                'id' => 127,
                'organization_id' => 406,
                'pid' => 97,
                'tpid' => '0:1:2:97:',
                'cids' => NULL,
                'desc' => NULL,
                'image' => '',
                'pdf' => '',
                'active' => 1,
                'created_at' => '2025-09-12 00:00:00',
                'updated_at' => '2025-10-01 11:42:21',
                'deleted_at' => NULL,
                'created_by' => 1,
                'updated_by' => 1,
                'deleted_by' => NULL,
                'total_childs' => 0,
            ),
            113 => 
            array (
                'id' => 122,
                'organization_id' => 416,
                'pid' => 97,
                'tpid' => '0:1:2:97:',
                'cids' => NULL,
                'desc' => NULL,
                'image' => '',
                'pdf' => '',
                'active' => 1,
                'created_at' => '2025-09-12 00:00:00',
                'updated_at' => '2025-10-01 11:42:21',
                'deleted_at' => NULL,
                'created_by' => 1,
                'updated_by' => 1,
                'deleted_by' => NULL,
                'total_childs' => 0,
            ),
            114 => 
            array (
                'id' => 55,
                'organization_id' => 422,
                'pid' => 97,
                'tpid' => '0:1:2:97:',
                'cids' => NULL,
                'desc' => NULL,
                'image' => '',
                'pdf' => '',
                'active' => 1,
                'created_at' => '2025-07-08 00:00:00',
                'updated_at' => '2025-10-01 11:42:21',
                'deleted_at' => NULL,
                'created_by' => 1,
                'updated_by' => 1,
                'deleted_by' => NULL,
                'total_childs' => 0,
            ),
            115 => 
            array (
                'id' => 94,
                'organization_id' => 493,
                'pid' => 1,
                'tpid' => '0:1:',
                'cids' => NULL,
                'desc' => NULL,
                'image' => '',
                'pdf' => '',
                'active' => 1,
                'created_at' => '2025-09-02 00:00:00',
                'updated_at' => '2025-10-01 11:42:21',
                'deleted_at' => NULL,
                'created_by' => 1,
                'updated_by' => 1,
                'deleted_by' => NULL,
                'total_childs' => 0,
            ),
            116 => 
            array (
                'id' => 117,
                'organization_id' => 402,
                'pid' => 96,
                'tpid' => '0:1:2:96:',
                'cids' => NULL,
                'desc' => NULL,
                'image' => '',
                'pdf' => '',
                'active' => 1,
                'created_at' => '2025-09-12 00:00:00',
                'updated_at' => '2025-10-01 11:42:22',
                'deleted_at' => NULL,
                'created_by' => 1,
                'updated_by' => 1,
                'deleted_by' => NULL,
                'total_childs' => 0,
            ),
            117 => 
            array (
                'id' => 114,
                'organization_id' => 438,
                'pid' => 96,
                'tpid' => '0:1:2:96:',
                'cids' => NULL,
                'desc' => NULL,
                'image' => '',
                'pdf' => '',
                'active' => 1,
                'created_at' => '2025-09-12 00:00:00',
                'updated_at' => '2025-10-01 11:42:22',
                'deleted_at' => NULL,
                'created_by' => 1,
                'updated_by' => 1,
                'deleted_by' => NULL,
                'total_childs' => 0,
            ),
            118 => 
            array (
                'id' => 98,
                'organization_id' => 496,
                'pid' => 2,
                'tpid' => '0:1:2:',
                'cids' => '99,101',
                'desc' => NULL,
                'image' => '',
                'pdf' => '',
                'active' => 1,
                'created_at' => '2025-09-02 00:00:00',
                'updated_at' => '2025-10-01 11:42:21',
                'deleted_at' => NULL,
                'created_by' => 1,
                'updated_by' => 1,
                'deleted_by' => NULL,
                'total_childs' => 0,
            ),
            119 => 
            array (
                'id' => 101,
                'organization_id' => 499,
                'pid' => 98,
                'tpid' => '0:1:2:98:',
                'cids' => NULL,
                'desc' => NULL,
                'image' => '',
                'pdf' => '',
                'active' => 1,
                'created_at' => '2025-09-05 00:00:00',
                'updated_at' => '2025-10-01 11:42:21',
                'deleted_at' => NULL,
                'created_by' => 1,
                'updated_by' => 1,
                'deleted_by' => NULL,
                'total_childs' => 0,
            ),
            120 => 
            array (
                'id' => 107,
                'organization_id' => 408,
                'pid' => 2,
                'tpid' => '0:1:2:',
                'cids' => NULL,
                'desc' => NULL,
                'image' => '',
                'pdf' => '',
                'active' => 1,
                'created_at' => '2025-09-12 00:00:00',
                'updated_at' => '2025-10-01 11:42:22',
                'deleted_at' => NULL,
                'created_by' => 1,
                'updated_by' => 1,
                'deleted_by' => NULL,
                'total_childs' => 0,
            ),
            121 => 
            array (
                'id' => 95,
                'organization_id' => 494,
                'pid' => 2,
                'tpid' => '0:1:2:',
                'cids' => NULL,
                'desc' => NULL,
                'image' => '',
                'pdf' => '',
                'active' => 1,
                'created_at' => '2025-09-02 00:00:00',
                'updated_at' => '2025-10-01 11:42:22',
                'deleted_at' => NULL,
                'created_by' => 1,
                'updated_by' => 1,
                'deleted_by' => NULL,
                'total_childs' => 0,
            ),
            122 => 
            array (
                'id' => 18,
                'organization_id' => 424,
                'pid' => 99,
                'tpid' => '0:1:2:98:99:',
                'cids' => '30,31,32,33',
                'desc' => NULL,
                'image' => '',
                'pdf' => '',
                'active' => 1,
                'created_at' => '2025-06-04 00:00:00',
                'updated_at' => '2025-10-01 11:42:22',
                'deleted_at' => NULL,
                'created_by' => 1,
                'updated_by' => 1,
                'deleted_by' => NULL,
                'total_childs' => 0,
            ),
            123 => 
            array (
                'id' => 138,
                'organization_id' => 501,
                'pid' => 96,
                'tpid' => '0:1:2:96:',
                'cids' => NULL,
                'desc' => NULL,
                'image' => '',
                'pdf' => '',
                'active' => 1,
                'created_at' => '2025-09-12 00:00:00',
                'updated_at' => '2025-10-01 11:42:22',
                'deleted_at' => NULL,
                'created_by' => 1,
                'updated_by' => 1,
                'deleted_by' => NULL,
                'total_childs' => 0,
            ),
            124 => 
            array (
                'id' => 123,
                'organization_id' => 415,
                'pid' => 97,
                'tpid' => '0:1:2:97:',
                'cids' => NULL,
                'desc' => NULL,
                'image' => '',
                'pdf' => '',
                'active' => 1,
                'created_at' => '2025-09-12 00:00:00',
                'updated_at' => '2025-10-01 11:42:21',
                'deleted_at' => NULL,
                'created_by' => 1,
                'updated_by' => 1,
                'deleted_by' => NULL,
                'total_childs' => 0,
            ),
            125 => 
            array (
                'id' => 99,
                'organization_id' => 497,
                'pid' => 98,
                'tpid' => '0:1:2:98:',
                'cids' => '100',
                'desc' => NULL,
                'image' => '',
                'pdf' => '',
                'active' => 1,
                'created_at' => '2025-09-02 00:00:00',
                'updated_at' => '2025-10-01 11:42:21',
                'deleted_at' => NULL,
                'created_by' => 1,
                'updated_by' => 1,
                'deleted_by' => NULL,
                'total_childs' => 0,
            ),
            126 => 
            array (
                'id' => 51,
                'organization_id' => 466,
                'pid' => 9,
                'tpid' => '0:1:2:98:99:6:9:',
                'cids' => NULL,
                'desc' => NULL,
                'image' => '',
                'pdf' => '',
                'active' => 1,
                'created_at' => '2025-06-10 00:00:00',
                'updated_at' => '2025-10-01 11:42:21',
                'deleted_at' => NULL,
                'created_by' => 1,
                'updated_by' => 1,
                'deleted_by' => NULL,
                'total_childs' => 0,
            ),
            127 => 
            array (
                'id' => 140,
                'organization_id' => 503,
                'pid' => 97,
                'tpid' => '0:1:2::97:',
                'cids' => NULL,
                'desc' => NULL,
                'image' => '',
                'pdf' => '',
                'active' => 1,
                'created_at' => '2025-12-23 00:00:00',
                'updated_at' => '2025-12-23 00:00:00',
                'deleted_at' => NULL,
                'created_by' => 1,
                'updated_by' => 1,
                'deleted_by' => NULL,
                'total_childs' => NULL,
            ),
            128 => 
            array (
                'id' => 97,
                'organization_id' => 495,
                'pid' => 2,
                'tpid' => '0:1:2:',
                'cids' => '121,122,123,124,126,127,128,129,130,131,133,134,135,140',
                'desc' => NULL,
                'image' => '',
                'pdf' => '',
                'active' => 1,
                'created_at' => '2025-09-02 00:00:00',
                'updated_at' => '2025-12-23 10:59:32',
                'deleted_at' => NULL,
                'created_by' => 1,
                'updated_by' => 1,
                'deleted_by' => NULL,
                'total_childs' => 0,
            ),
            129 => 
            array (
                'id' => 7,
                'organization_id' => 9,
                'pid' => 6,
                'tpid' => '0:1:2:98:99:6:',
                'cids' => '38,39,40,41',
                'desc' => NULL,
                'image' => '',
                'pdf' => '',
                'active' => 1,
                'created_at' => '2025-06-04 00:00:00',
                'updated_at' => '2025-10-01 11:42:21',
                'deleted_at' => NULL,
                'created_by' => 1,
                'updated_by' => 1,
                'deleted_by' => NULL,
                'total_childs' => 0,
            ),
            130 => 
            array (
                'id' => 17,
                'organization_id' => 423,
                'pid' => 99,
                'tpid' => '0:1:2:98:99:',
                'cids' => '27,28,29',
                'desc' => NULL,
                'image' => '',
                'pdf' => '',
                'active' => 1,
                'created_at' => '2025-06-04 00:00:00',
                'updated_at' => '2025-10-01 11:42:22',
                'deleted_at' => NULL,
                'created_by' => 1,
                'updated_by' => 1,
                'deleted_by' => NULL,
                'total_childs' => 0,
            ),
            131 => 
            array (
                'id' => 31,
                'organization_id' => 448,
                'pid' => 18,
                'tpid' => '0:1:2:98:99:18:',
                'cids' => NULL,
                'desc' => NULL,
                'image' => '',
                'pdf' => '',
                'active' => 1,
                'created_at' => '2025-06-04 00:00:00',
                'updated_at' => '2025-10-01 11:42:22',
                'deleted_at' => NULL,
                'created_by' => 1,
                'updated_by' => 1,
                'deleted_by' => NULL,
                'total_childs' => 0,
            ),
            132 => 
            array (
                'id' => 139,
                'organization_id' => 502,
                'pid' => 96,
                'tpid' => '0:1:2:96:',
                'cids' => NULL,
                'desc' => NULL,
                'image' => '',
                'pdf' => '',
                'active' => 1,
                'created_at' => '2025-09-12 00:00:00',
                'updated_at' => '2025-10-01 11:42:22',
                'deleted_at' => NULL,
                'created_by' => 1,
                'updated_by' => 1,
                'deleted_by' => NULL,
                'total_childs' => 0,
            ),
            133 => 
            array (
                'id' => 130,
                'organization_id' => 375,
                'pid' => 97,
                'tpid' => '0:1:2:97:',
                'cids' => NULL,
                'desc' => NULL,
                'image' => '',
                'pdf' => '',
                'active' => 1,
                'created_at' => '2025-09-12 00:00:00',
                'updated_at' => '2025-10-01 11:42:21',
                'deleted_at' => NULL,
                'created_by' => 1,
                'updated_by' => 1,
                'deleted_by' => NULL,
                'total_childs' => 0,
            ),
            134 => 
            array (
                'id' => 106,
                'organization_id' => 407,
                'pid' => 2,
                'tpid' => '0:1:2:',
                'cids' => NULL,
                'desc' => NULL,
                'image' => '',
                'pdf' => '',
                'active' => 1,
                'created_at' => '2025-09-12 00:00:00',
                'updated_at' => '2025-10-01 11:42:22',
                'deleted_at' => NULL,
                'created_by' => 1,
                'updated_by' => 1,
                'deleted_by' => NULL,
                'total_childs' => 0,
            ),
            135 => 
            array (
                'id' => 132,
                'organization_id' => 359,
                'pid' => 96,
                'tpid' => '0:1:2:96:',
                'cids' => NULL,
                'desc' => NULL,
                'image' => '',
                'pdf' => '',
                'active' => 1,
                'created_at' => '2025-09-12 00:00:00',
                'updated_at' => '2025-10-01 11:42:22',
                'deleted_at' => NULL,
                'created_by' => 1,
                'updated_by' => 1,
                'deleted_by' => NULL,
                'total_childs' => 0,
            ),
        ));
        
        
    }
}