<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;

class PermissionsTableSeeder extends Seeder
{

    /**
     * Auto generated seed file
     *
     * @return void
     */
    public function run()
    {
        

        \DB::table('permissions')->delete();
        
        \DB::table('permissions')->insert(array (
            0 => 
            array (
                'id' => 1,
                'name' => 'ពិនិត្យអត្តសញ្ញាណ',
                'guard_name' => 'api_portal',
                'created_at' => '2025-03-26 11:40:00',
                'updated_at' => '2025-03-26 11:40:00',
                'deleted_at' => NULL,
                'pid' => 12,
                'tpid' => '0:12',
                'created_by' => 1,
                'updated_by' => 1,
                'deleted_by' => NULL,
                'tag' => 'authentication',
                'desp' => 'allow to loggin into the portal',
                'code' => 'portal_auth',
            ),
            1 => 
            array (
                'id' => 2,
                'name' => 'ប្រព័ន្ធឯកសារអេឡិចត្រូនិក',
                'guard_name' => 'api_portal',
                'created_at' => '2025-03-26 11:44:05',
                'updated_at' => '2025-03-26 11:44:05',
                'deleted_at' => NULL,
                'pid' => 12,
                'tpid' => '0:12',
                'created_by' => 1,
                'updated_by' => 1,
                'deleted_by' => NULL,
                'tag' => 'regulator',
                'desp' => 'allow to use module regulator',
                'code' => 'portal_regulator',
            ),
            2 => 
            array (
                'id' => 3,
                'name' => 'ថតឯកសារ',
                'guard_name' => 'api_portal',
                'created_at' => '2025-03-26 11:53:31',
                'updated_at' => '2025-03-26 11:53:31',
                'deleted_at' => NULL,
                'pid' => 2,
                'tpid' => '0:12:2',
                'created_by' => 1,
                'updated_by' => 1,
                'deleted_by' => NULL,
                'tag' => 'regulator',
                'desp' => 'allow to create folder and manage it crud functions',
                'code' => 'portal_regulator_folder',
            ),
            3 => 
            array (
                'id' => 4,
                'name' => 'ស្វែងរកឯកសារ',
                'guard_name' => 'api_portal',
                'created_at' => '2025-03-26 11:52:03',
                'updated_at' => '2025-03-26 11:52:03',
                'deleted_at' => NULL,
                'pid' => 2,
                'tpid' => '0:12:2',
                'created_by' => 1,
                'updated_by' => 1,
                'deleted_by' => NULL,
                'tag' => 'regulator',
                'desp' => 'allow to use search function',
                'code' => 'portal_regulator_search',
            ),
            4 => 
            array (
                'id' => 5,
                'name' => 'ឯកសារចំណូលចិត្ត',
                'guard_name' => 'api_portal',
                'created_at' => '2025-03-26 11:53:31',
                'updated_at' => '2025-03-26 11:53:31',
                'deleted_at' => NULL,
                'pid' => 2,
                'tpid' => '0:12:2',
                'created_by' => 1,
                'updated_by' => 1,
                'deleted_by' => NULL,
                'tag' => 'regulator',
                'desp' => 'allow the user to add regulator to their favorite list',
                'code' => 'portal_regulator_favorite',
            ),
            5 => 
            array (
                'id' => 6,
                'name' => 'ប្រព័ន្ធកិច្ចប្រជុំ',
                'guard_name' => 'api_portal',
                'created_at' => '2025-03-26 11:57:20',
                'updated_at' => '2025-03-26 11:57:20',
                'deleted_at' => NULL,
                'pid' => 12,
                'tpid' => '0:12',
                'created_by' => 1,
                'updated_by' => 1,
                'deleted_by' => NULL,
                'tag' => 'meeting',
                'desp' => 'allow to use meeting module',
                'code' => 'portal_meeting',
            ),
            6 => 
            array (
                'id' => 7,
                'name' => 'បញ្ជីព័ត៌មានកិច្ចប្រជុំ',
                'guard_name' => 'api_portal',
                'created_at' => '2025-03-26 12:05:41',
                'updated_at' => '2025-03-26 12:05:41',
                'deleted_at' => NULL,
                'pid' => 6,
                'tpid' => '0:12:6',
                'created_by' => 1,
                'updated_by' => 1,
                'deleted_by' => NULL,
                'tag' => 'meeting',
                'desp' => 'allow to read all published meeting information',
                'code' => 'portal_meeting_listing',
            ),
            7 => 
            array (
                'id' => 8,
                'name' => 'បញ្ចូលព័ត៌មានកិច្ចប្រជុំ',
                'guard_name' => 'api_portal',
                'created_at' => '2025-03-26 12:05:41',
                'updated_at' => '2025-03-26 12:05:41',
                'deleted_at' => NULL,
                'pid' => 6,
                'tpid' => '0:12:6',
                'created_by' => 1,
                'updated_by' => 1,
                'deleted_by' => NULL,
                'tag' => 'meeting',
                'desp' => 'allow to create meeting information',
                'code' => 'portal_meeting_creating',
            ),
            8 => 
            array (
                'id' => 9,
                'name' => 'ចេញផ្សាយកិច្ចប្រជុំ',
                'guard_name' => 'api_portal',
                'created_at' => '2025-03-26 12:05:41',
                'updated_at' => '2025-03-26 12:05:41',
                'deleted_at' => NULL,
                'pid' => 6,
                'tpid' => '0:12:6',
                'created_by' => 1,
                'updated_by' => 1,
                'deleted_by' => NULL,
                'tag' => 'meeting',
                'desp' => 'allow to publish and unpublish meeting information',
                'code' => 'portal_meeting_publishing',
            ),
            9 => 
            array (
                'id' => 10,
                'name' => 'កែប្រែព័ត៌មាន',
                'guard_name' => 'api_portal',
                'created_at' => '2025-03-26 12:05:41',
                'updated_at' => '2025-03-26 12:05:41',
                'deleted_at' => NULL,
                'pid' => 6,
                'tpid' => '0:12:6',
                'created_by' => 1,
                'updated_by' => 1,
                'deleted_by' => NULL,
                'tag' => 'meeting',
                'desp' => 'allow to update themeeting information',
                'code' => 'portal_meeting_updating',
            ),
            10 => 
            array (
                'id' => 11,
                'name' => 'លុបកិច្ចប្រជុំ',
                'guard_name' => 'api_portal',
                'created_at' => '2025-03-26 12:05:41',
                'updated_at' => '2025-03-26 12:05:41',
                'deleted_at' => NULL,
                'pid' => 6,
                'tpid' => '0:12:6',
                'created_by' => 1,
                'updated_by' => 1,
                'deleted_by' => NULL,
                'tag' => 'meeting',
                'desp' => 'allow to delete meeting information',
                'code' => 'portal_meeting_deleting',
            ),
            11 => 
            array (
                'id' => 12,
                'name' => 'ប្រព័ន្ធច្រកសេវារួម',
                'guard_name' => 'api_portal',
                'created_at' => '2025-03-26 12:09:32',
                'updated_at' => '2025-03-26 12:09:32',
                'deleted_at' => NULL,
                'pid' => 0,
                'tpid' => '0',
                'created_by' => 1,
                'updated_by' => 1,
                'deleted_by' => NULL,
                'tag' => 'portal',
                'desp' => 'allow to use module within portal',
                'code' => 'portal',
            ),
            12 => 
            array (
                'id' => 13,
                'name' => 'ភ្ជាប់ឯកសារអេឡិចត្រូវនិក',
                'guard_name' => 'api_portal',
                'created_at' => '2025-03-26 12:24:27',
                'updated_at' => '2025-03-26 12:24:27',
                'deleted_at' => NULL,
                'pid' => 6,
                'tpid' => '0:12:6',
                'created_by' => 1,
                'updated_by' => 1,
                'deleted_by' => NULL,
                'tag' => 'meeting',
                'desp' => 'allow to add link from regulator to the meeting information',
                'code' => 'portal_meeting_link_regulator',
            ),
            13 => 
            array (
                'id' => 14,
                'name' => 'សេចក្ដីព្រាងរដ្ឋមន្ត្រី',
                'guard_name' => 'api_portal',
                'created_at' => '2025-03-26 12:24:27',
                'updated_at' => '2025-03-26 12:24:27',
                'deleted_at' => NULL,
                'pid' => 6,
                'tpid' => '0:12:6',
                'created_by' => 1,
                'updated_by' => 1,
                'deleted_by' => NULL,
                'tag' => 'meeting',
                'desp' => 'allow to upload sekdey preeng from minister to the meeting information',
                'code' => 'portal_meeting_minister_preeng',
            ),
            14 => 
            array (
                'id' => 15,
                'name' => 'សេចក្ដីព្រាង',
                'guard_name' => 'api_portal',
                'created_at' => '2025-03-26 12:24:27',
                'updated_at' => '2025-03-26 12:24:27',
                'deleted_at' => NULL,
                'pid' => 6,
                'tpid' => '0:12:6',
                'created_by' => 1,
                'updated_by' => 1,
                'deleted_by' => NULL,
                'tag' => 'meeting',
                'desp' => 'allow to upload sekdey preeng of the meeting information',
                'code' => 'portal_meeting_sekdey_preeng',
            ),
            15 => 
            array (
                'id' => 16,
                'name' => 'ឯកសារយោងផ្សេងៗ',
                'guard_name' => 'api_portal',
                'created_at' => '2025-03-26 12:24:27',
                'updated_at' => '2025-03-26 12:24:27',
                'deleted_at' => NULL,
                'pid' => 6,
                'tpid' => '0:12:6',
                'created_by' => 1,
                'updated_by' => 1,
                'deleted_by' => NULL,
                'tag' => 'meeting',
                'desp' => 'allow to upload other documents of the meeting information',
                'code' => 'portal_meeting_other_documents',
            ),
            16 => 
            array (
                'id' => 17,
                'name' => 'បន្ទប់ប្រជុំ',
                'guard_name' => 'api_portal',
                'created_at' => '2025-03-26 12:24:27',
                'updated_at' => '2025-03-26 12:24:27',
                'deleted_at' => NULL,
                'pid' => 6,
                'tpid' => '0:12:6',
                'created_by' => 1,
                'updated_by' => 1,
                'deleted_by' => NULL,
                'tag' => 'meeting',
                'desp' => 'allow to add room information for the meeting',
                'code' => 'portal_meeting_room',
            ),
            17 => 
            array (
                'id' => 18,
                'name' => 'បញ្ជីវត្តមាន',
                'guard_name' => 'api_portal',
                'created_at' => '2025-03-26 12:24:27',
                'updated_at' => '2025-03-26 12:24:27',
                'deleted_at' => NULL,
                'pid' => 6,
                'tpid' => '0:12:6',
                'created_by' => 1,
                'updated_by' => 1,
                'deleted_by' => NULL,
                'tag' => 'meeting',
                'desp' => 'allow to track the attendant of the meeting members',
                'code' => 'portal_meeting_attendant',
            ),
            18 => 
            array (
                'id' => 19,
                'name' => 'ចូលប្រព័ន្ធ',
                'guard_name' => 'api_portal',
                'created_at' => '2025-03-26 21:48:37',
                'updated_at' => '2025-03-26 21:48:37',
                'deleted_at' => NULL,
                'pid' => 1,
                'tpid' => '0:12:1',
                'created_by' => 1,
                'updated_by' => 1,
                'deleted_by' => NULL,
                'tag' => 'authentication',
                'desp' => 'allow to login into portal',
                'code' => 'portal_auth_login',
            ),
            19 => 
            array (
                'id' => 20,
                'name' => 'ចេញពីប្រព័ន្ធ',
                'guard_name' => 'api_portal',
                'created_at' => '2025-03-26 21:48:37',
                'updated_at' => '2025-03-26 21:48:37',
                'deleted_at' => NULL,
                'pid' => 1,
                'tpid' => '0:12:1',
                'created_by' => 1,
                'updated_by' => 1,
                'deleted_by' => NULL,
                'tag' => 'authentication',
                'desp' => 'allow to logout from portal',
                'code' => 'portal_auth_logout',
            ),
            20 => 
            array (
                'id' => 21,
                'name' => 'ប្រព័ន្ធគ្រប់គ្រងបុគ្គលិក',
                'guard_name' => 'api_portal',
                'created_at' => '2025-03-27 09:37:49',
                'updated_at' => '2025-03-27 09:37:49',
                'deleted_at' => NULL,
                'pid' => 12,
                'tpid' => '0:12',
                'created_by' => 1,
                'updated_by' => 1,
                'deleted_by' => NULL,
                'tag' => 'staff',
                'desp' => 'allow to use the staff module',
                'code' => 'portal_staff',
            ),
            21 => 
            array (
                'id' => 22,
                'name' => 'បញ្ជីបុគ្គលិក',
                'guard_name' => 'api_portal',
                'created_at' => '2025-03-27 09:39:33',
                'updated_at' => '2025-03-27 09:39:33',
                'deleted_at' => NULL,
                'pid' => 21,
                'tpid' => '0:12:21',
                'created_by' => 1,
                'updated_by' => 1,
                'deleted_by' => NULL,
                'tag' => 'staff',
                'desp' => 'allow to read information about the staff',
                'code' => 'portal_staff_listing',
            ),
            22 => 
            array (
                'id' => 23,
                'name' => 'បញ្ចូលព័ត៌មានបុគ្គលិក',
                'guard_name' => 'api_portal',
                'created_at' => '2025-03-27 09:41:02',
                'updated_at' => '2025-03-27 09:41:02',
                'deleted_at' => NULL,
                'pid' => 21,
                'tpid' => '0:12:21',
                'created_by' => 1,
                'updated_by' => 1,
                'deleted_by' => NULL,
                'tag' => 'staff',
                'desp' => 'allow to create the information of the staff',
                'code' => 'portal_staff_creating',
            ),
            23 => 
            array (
                'id' => 24,
                'name' => 'កែប្រែព័ត៌មានបុគ្គលិក',
                'guard_name' => 'api_portal',
                'created_at' => '2025-03-27 09:41:02',
                'updated_at' => '2025-03-27 09:41:02',
                'deleted_at' => NULL,
                'pid' => 21,
                'tpid' => '0:12:21',
                'created_by' => 1,
                'updated_by' => 1,
                'deleted_by' => NULL,
                'tag' => 'staff',
                'desp' => 'allow to updating the information of the staff',
                'code' => 'portal_staff_updating',
            ),
            24 => 
            array (
                'id' => 25,
                'name' => 'មើលគំរូកាតមុនបោះចេញ',
                'guard_name' => 'api_portal',
                'created_at' => '2025-03-27 09:44:13',
                'updated_at' => '2025-03-27 09:44:13',
                'deleted_at' => NULL,
                'pid' => 21,
                'tpid' => '0:12:21',
                'created_by' => 1,
                'updated_by' => 1,
                'deleted_by' => NULL,
                'tag' => 'staff',
                'desp' => 'allow to print preview official card of officer',
                'code' => 'portal_staff_print_preview_officer_card',
            ),
            25 => 
            array (
                'id' => 26,
                'name' => 'ប្រវត្តិរូបមន្ត្រី',
                'guard_name' => 'api_portal',
                'created_at' => '2025-03-27 09:51:53',
                'updated_at' => '2025-03-27 09:51:53',
                'deleted_at' => NULL,
                'pid' => 21,
                'tpid' => '0:12:21',
                'created_by' => 1,
                'updated_by' => 1,
                'deleted_by' => NULL,
                'tag' => 'staff',
                'desp' => 'allow to view background information of the officer',
                'code' => 'portal_staff_background_information',
            ),
            26 => 
            array (
                'id' => 27,
                'name' => 'សំបុត្រនិងលិខិត បញ្ជាក់កំណើត',
                'guard_name' => 'api_portal',
                'created_at' => '2025-03-27 09:51:53',
                'updated_at' => '2025-03-27 09:51:53',
                'deleted_at' => NULL,
                'pid' => 26,
                'tpid' => '0:12:21:26',
                'created_by' => 1,
                'updated_by' => 1,
                'deleted_by' => NULL,
                'tag' => 'staff',
                'desp' => 'allow to updating birth background',
                'code' => 'portal_staff_birth_background',
            ),
            27 => 
            array (
                'id' => 28,
                'name' => 'សំបុត្រនិងលិខិត អាពាហ៍ពិពាហ៍',
                'guard_name' => 'api_portal',
                'created_at' => '2025-03-27 09:51:53',
                'updated_at' => '2025-03-27 09:51:53',
                'deleted_at' => NULL,
                'pid' => 26,
                'tpid' => '0:12:21:26',
                'created_by' => 1,
                'updated_by' => 1,
                'deleted_by' => NULL,
                'tag' => 'staff',
                'desp' => 'allow to updating wedding background',
                'code' => 'portal_staff_wedding_background',
            ),
            28 => 
            array (
                'id' => 29,
                'name' => 'ប្រវត្តិអត្តសញ្ញាណបណ្ណ',
                'guard_name' => 'api_portal',
                'created_at' => '2025-03-27 09:51:53',
                'updated_at' => '2025-03-27 09:51:53',
                'deleted_at' => NULL,
                'pid' => 26,
                'tpid' => '0:12:21:26',
                'created_by' => 1,
                'updated_by' => 1,
                'deleted_by' => NULL,
                'tag' => 'staff',
                'desp' => 'allow to updating nid background',
                'code' => 'portal_staff_nid_background',
            ),
            29 => 
            array (
                'id' => 30,
                'name' => 'ប្រវត្តិលិខិតឆ្លងដែន',
                'guard_name' => 'api_portal',
                'created_at' => '2025-03-27 09:51:53',
                'updated_at' => '2025-03-27 09:51:53',
                'deleted_at' => NULL,
                'pid' => 26,
                'tpid' => '0:12:21:26',
                'created_by' => 1,
                'updated_by' => 1,
                'deleted_by' => NULL,
                'tag' => 'staff',
                'desp' => 'allow to updating passport background',
                'code' => 'portal_staff_passport_background',
            ),
            30 => 
            array (
                'id' => 31,
                'name' => 'កម្រិតទទួលបានការអប់រំ',
                'guard_name' => 'api_portal',
                'created_at' => '2025-03-27 09:51:53',
                'updated_at' => '2025-03-27 09:51:53',
                'deleted_at' => NULL,
                'pid' => 26,
                'tpid' => '0:12:21:26',
                'created_by' => 1,
                'updated_by' => 1,
                'deleted_by' => NULL,
                'tag' => 'staff',
                'desp' => 'allow to updating study background',
                'code' => 'portal_staff_study_background',
            ),
            31 => 
            array (
                'id' => 32,
                'name' => 'ប្រវត្តិការងារ',
                'guard_name' => 'api_portal',
                'created_at' => '2025-03-27 09:51:53',
                'updated_at' => '2025-03-27 09:51:53',
                'deleted_at' => NULL,
                'pid' => 26,
                'tpid' => '0:12:21:26',
                'created_by' => 1,
                'updated_by' => 1,
                'deleted_by' => NULL,
                'tag' => 'staff',
                'desp' => 'allow to updating working background',
                'code' => 'portal_staff_working_background',
            ),
            32 => 
            array (
                'id' => 33,
                'name' => 'កាំប្រាក់ខែ',
                'guard_name' => 'api_portal',
                'created_at' => '2025-03-27 09:51:53',
                'updated_at' => '2025-03-27 09:51:53',
                'deleted_at' => NULL,
                'pid' => 26,
                'tpid' => '0:12:21:26',
                'created_by' => 1,
                'updated_by' => 1,
                'deleted_by' => NULL,
                'tag' => 'staff',
                'desp' => 'allow to updating salary background',
                'code' => 'portal_staff_salary_background',
            ),
            33 => 
            array (
                'id' => 34,
            'name' => 'ការលើកទឹកចិត្ត (មេដៃ)',
                'guard_name' => 'api_portal',
                'created_at' => '2025-03-27 09:51:53',
                'updated_at' => '2025-03-27 09:51:53',
                'deleted_at' => NULL,
                'pid' => 26,
                'tpid' => '0:12:21:26',
                'created_by' => 1,
                'updated_by' => 1,
                'deleted_by' => NULL,
                'tag' => 'staff',
                'desp' => 'allow to updating medal history background',
                'code' => 'portal_staff_medal_history_background',
            ),
            34 => 
            array (
                'id' => 35,
                'name' => 'សំបុត្រនិងលិខិត បញ្ជាក់កំណើត កូន',
                'guard_name' => 'api_portal',
                'created_at' => '2025-03-27 09:51:53',
                'updated_at' => '2025-03-27 09:51:53',
                'deleted_at' => NULL,
                'pid' => 26,
                'tpid' => '0:12:21:26',
                'created_by' => 1,
                'updated_by' => 1,
                'deleted_by' => NULL,
                'tag' => 'staff',
                'desp' => 'allow to updating birth background of kids',
                'code' => 'portal_staff_birth_kids_background',
            ),
            35 => 
            array (
                'id' => 36,
                'name' => 'ភាសារបទេស របស់បុគ្គលិក',
                'guard_name' => 'api_portal',
                'created_at' => '2025-03-27 09:51:53',
                'updated_at' => '2025-03-27 09:51:53',
                'deleted_at' => NULL,
                'pid' => 26,
                'tpid' => '0:12:21:26',
                'created_by' => 1,
                'updated_by' => 1,
                'deleted_by' => NULL,
                'tag' => 'staff',
                'desp' => 'allow to updating forieng language',
                'code' => 'portal_staff_language_background',
            ),
            36 => 
            array (
                'id' => 37,
                'name' => 'ឡើងថ្នាក់តាមការងារ',
                'guard_name' => 'api_portal',
                'created_at' => '2025-03-27 09:51:53',
                'updated_at' => '2025-03-27 09:51:53',
                'deleted_at' => NULL,
                'pid' => 26,
                'tpid' => '0:12:21:26',
                'created_by' => 1,
                'updated_by' => 1,
                'deleted_by' => 0,
                'tag' => 'staff',
                'desp' => 'allow to updating ranking based on working',
                'code' => 'portal_staff_rank_with_work_background',
            ),
            37 => 
            array (
                'id' => 38,
                'name' => 'ឡើងថ្នាក់តាមសញ្ញាបត្រ',
                'guard_name' => 'api_portal',
                'created_at' => '2025-03-27 09:51:53',
                'updated_at' => '2025-03-27 09:51:53',
                'deleted_at' => NULL,
                'pid' => 26,
                'tpid' => '0:12:21:26',
                'created_by' => 1,
                'updated_by' => 1,
                'deleted_by' => 0,
                'tag' => 'staff',
                'desp' => 'allow to updating ranking based on certificate',
                'code' => 'portal_staff_rank_with_certificate_background',
            ),
            38 => 
            array (
                'id' => 39,
                'name' => 'ការស្ថិតនៅក្រៅក្របខណ្ឌ',
                'guard_name' => 'api_portal',
                'created_at' => '2025-03-27 09:51:53',
                'updated_at' => '2025-03-27 09:51:53',
                'deleted_at' => NULL,
                'pid' => 26,
                'tpid' => '0:12:21:26',
                'created_by' => 1,
                'updated_by' => 1,
                'deleted_by' => 0,
                'tag' => 'staff',
                'desp' => 'allow to updating the information of staying non officer',
                'code' => 'portal_staff_officer_out_krobkhan_background',
            ),
            39 => 
            array (
                'id' => 40,
                'name' => 'ការដាក់ពិន័យ',
                'guard_name' => 'api_portal',
                'created_at' => '2025-03-27 09:51:53',
                'updated_at' => '2025-03-27 09:51:53',
                'deleted_at' => NULL,
                'pid' => 26,
                'tpid' => '0:12:21:26',
                'created_by' => 1,
                'updated_by' => 1,
                'deleted_by' => 0,
                'tag' => 'staff',
                'desp' => 'allow to updating the penalty of officer',
                'code' => 'portal_staff_officer_panelty_background',
            ),
            40 => 
            array (
                'id' => 41,
                'name' => 'បញ្ចូលនិងកែប្រែឯកសារយោង កិច្ចប្រជុំ',
                'guard_name' => 'api_portal',
                'created_at' => '2025-03-27 09:51:53',
                'updated_at' => '2025-03-27 09:51:53',
                'deleted_at' => NULL,
                'pid' => 6,
                'tpid' => '0:12:6',
                'created_by' => 1,
                'updated_by' => 1,
                'deleted_by' => 0,
                'tag' => 'staff',
                'desp' => 'allow to updating the reference doucment of meeting',
                'code' => 'portal_metting_others_reference',
            ),
            41 => 
            array (
                'id' => 42,
            'name' => 'ប្ដូររូបគណនីរបស់មន្ត្រី (Profile)',
                'guard_name' => 'api_portal',
                'created_at' => '2025-03-27 09:44:13',
                'updated_at' => '2025-03-27 09:44:13',
                'deleted_at' => NULL,
                'pid' => 21,
                'tpid' => '0:12:21',
                'created_by' => 1,
                'updated_by' => 1,
                'deleted_by' => 0,
                'tag' => 'staff',
                'desp' => 'allow to change the profile picture of the officer',
                'code' => 'portal_staff_profile_photo_change',
            ),
            42 => 
            array (
                'id' => 43,
                'name' => 'នាំចេញរូបគំរូកាតមន្ត្រី',
                'guard_name' => 'api_portal',
                'created_at' => '2025-03-27 09:44:13',
                'updated_at' => '2025-03-27 09:44:13',
                'deleted_at' => NULL,
                'pid' => 25,
                'tpid' => '0:12:21:25',
                'created_by' => 1,
                'updated_by' => 1,
                'deleted_by' => 0,
                'tag' => 'staff',
                'desp' => 'allow to download the officer card',
                'code' => 'portal_staff_save_official_officier_card',
            ),
            43 => 
            array (
                'id' => 44,
                'name' => 'បោះពុម្ភកាត',
                'guard_name' => 'api_portal',
                'created_at' => '2025-03-27 09:44:13',
                'updated_at' => '2025-03-27 09:44:13',
                'deleted_at' => NULL,
                'pid' => 25,
                'tpid' => '0:12:21:25',
                'created_by' => 1,
                'updated_by' => 1,
                'deleted_by' => 0,
                'tag' => 'staff',
                'desp' => 'allow to print card',
                'code' => 'portal_staff_print_card',
            ),
            44 => 
            array (
                'id' => 45,
                'name' => 'លុបព័ត៌មានបុគ្គលិក',
                'guard_name' => 'api_portal',
                'created_at' => '2025-03-27 09:41:02',
                'updated_at' => '2025-03-27 09:41:02',
                'deleted_at' => NULL,
                'pid' => 21,
                'tpid' => '0:12:21',
                'created_by' => 1,
                'updated_by' => 1,
                'deleted_by' => 0,
                'tag' => 'staff',
                'desp' => 'allow to delete the information of the staff',
                'code' => 'portal_staff_delete',
            ),
            45 => 
            array (
                'id' => 46,
                'name' => 'វត្តមានបុគ្គលិក',
                'guard_name' => 'api_portal',
                'created_at' => '2025-03-27 09:41:02',
                'updated_at' => '2025-03-27 09:41:02',
                'deleted_at' => NULL,
                'pid' => 12,
                'tpid' => '0:12',
                'created_by' => 1,
                'updated_by' => 1,
                'deleted_by' => 0,
                'tag' => 'attendant',
                'desp' => 'allow to view attendant of the officers',
                'code' => 'portal_attendant',
            ),
            46 => 
            array (
                'id' => 47,
                'name' => 'QRCode វត្តមានបុគ្គលិក',
                'guard_name' => 'api_portal',
                'created_at' => '2025-03-27 09:41:02',
                'updated_at' => '2025-03-27 09:41:02',
                'deleted_at' => NULL,
                'pid' => 46,
                'tpid' => '0:12:46',
                'created_by' => 1,
                'updated_by' => 1,
                'deleted_by' => 0,
                'tag' => 'attendant',
                'desp' => 'allow to view list of qrcode of attendants',
                'code' => 'portal_attendant_qrcodes',
            ),
            47 => 
            array (
                'id' => 48,
                'name' => 'ចុះវត្តមានតាម QRCode',
                'guard_name' => 'api_portal',
                'created_at' => '2025-03-27 09:41:02',
                'updated_at' => '2025-03-27 09:41:02',
                'deleted_at' => NULL,
                'pid' => 46,
                'tpid' => '0:12:46',
                'created_by' => 1,
                'updated_by' => 1,
                'deleted_by' => 0,
                'tag' => 'attendant',
                'desp' => 'allow to check attendant',
                'code' => 'portal_attendant_checkin_checkout',
            ),
            48 => 
            array (
                'id' => 49,
                'name' => 'ចុះវត្តមានដោយមានកាមេរា',
                'guard_name' => 'api_portal',
                'created_at' => '2025-03-27 09:41:02',
                'updated_at' => '2025-03-27 09:41:02',
                'deleted_at' => NULL,
                'pid' => 46,
                'tpid' => '0:12:46',
                'created_by' => 1,
                'updated_by' => 1,
                'deleted_by' => 0,
                'tag' => 'attendant',
                'desp' => 'allow to check attendant with camera',
                'code' => 'portal_staff_checkin_checkout_camera',
            ),
        ));
        
        
    }
}