<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;

class SectionsTableSeeder extends Seeder
{

    /**
     * Auto generated seed file
     *
     * @return void
     */
    public function run()
    {
        

        \DB::table('sections')->delete();
        
        \DB::table('sections')->insert(array (
            0 => 
            array (
                'id' => 1,
                'number' => 'កថាភាគទី ១ ',
                'title' => 'អនីតិជន ',
                'book_id' => 1,
                'kunty_id' => 2,
                'matika_id' => 0,
                'chapter_id' => 2,
                'part_id' => 4,
                'created_by' => 0,
                'updated_by' => 0,
                'created_at' => '2015-06-16 00:00:00',
                'updated_at' => '2015-06-16 00:00:00',
            ),
            1 => 
            array (
                'id' => 2,
                'number' => 'កថាភាគទី ២ ',
                'title' => 'ជននៅក្រោមអាណាព្យាបាលទូទៅ ',
                'book_id' => 1,
                'kunty_id' => 2,
                'matika_id' => 0,
                'chapter_id' => 2,
                'part_id' => 4,
                'created_by' => 0,
                'updated_by' => 0,
                'created_at' => '2015-06-16 00:00:00',
                'updated_at' => '2015-06-16 00:00:00',
            ),
            2 => 
            array (
                'id' => 3,
                'number' => 'កថាភាគទី ៣ ',
                'title' => 'ជននៅក្រោមហិតូបត្ថម្ភ ',
                'book_id' => 1,
                'kunty_id' => 2,
                'matika_id' => 0,
                'chapter_id' => 2,
                'part_id' => 4,
                'created_by' => 0,
                'updated_by' => 0,
                'created_at' => '2015-06-16 00:00:00',
                'updated_at' => '2015-06-16 00:00:00',
            ),
            3 => 
            array (
                'id' => 4,
                'number' => 'កថាភាគទី ៤ ',
                'title' => 'ការការពារភាគីម្ខាងទៀតនៃជនដែលត្រូវបានកម្រិតសមត្ថភាព ',
                'book_id' => 1,
                'kunty_id' => 2,
                'matika_id' => 0,
                'chapter_id' => 2,
                'part_id' => 4,
                'created_by' => 0,
                'updated_by' => 0,
                'created_at' => '2015-06-16 00:00:00',
                'updated_at' => '2015-06-16 00:00:00',
            ),
            4 => 
            array (
                'id' => 5,
                'number' => 'កថាភាគទី ១ ',
                'title' => 'ការគ្រប់គ្រងទ្រព្យសម្បត្ដិរបស់បុគ្គលដែលអវត្ដមាន ',
                'book_id' => 1,
                'kunty_id' => 2,
                'matika_id' => 0,
                'chapter_id' => 2,
                'part_id' => 6,
                'created_by' => 0,
                'updated_by' => 0,
                'created_at' => '2015-06-16 00:00:00',
                'updated_at' => '2015-06-16 00:00:00',
            ),
            5 => 
            array (
                'id' => 6,
                'number' => 'កថាភាគទី ២ ',
                'title' => 'ការប្រកាសអំពីការបាត់ខ្លួន ',
                'book_id' => 1,
                'kunty_id' => 2,
                'matika_id' => 0,
                'chapter_id' => 2,
                'part_id' => 6,
                'created_by' => 0,
                'updated_by' => 0,
                'created_at' => '2015-06-16 00:00:00',
                'updated_at' => '2015-06-16 00:00:00',
            ),
            6 => 
            array (
                'id' => 7,
                'number' => 'កថាភាគទី ១ ',
                'title' => 'និយមន័យ ប្រភេទ និង គោលការណ៍នៃការបង្កើត ',
                'book_id' => 1,
                'kunty_id' => 2,
                'matika_id' => 0,
                'chapter_id' => 3,
                'part_id' => 8,
                'created_by' => 0,
                'updated_by' => 0,
                'created_at' => '2015-06-16 00:00:00',
                'updated_at' => '2015-06-16 00:00:00',
            ),
            7 => 
            array (
                'id' => 8,
                'number' => 'កថាភាគទី ២ ',
                'title' => 'នាមករណ៍នៃនីតិបុគ្គលមិនយកចំណេញ ',
                'book_id' => 1,
                'kunty_id' => 2,
                'matika_id' => 0,
                'chapter_id' => 3,
                'part_id' => 8,
                'created_by' => 0,
                'updated_by' => 0,
                'created_at' => '2015-06-16 00:00:00',
                'updated_at' => '2015-06-16 00:00:00',
            ),
            8 => 
            array (
                'id' => 9,
                'number' => 'កថាភាគទី ៣ ',
                'title' => 'ការចុះបញ្ជីនៃការបង្កើត ',
                'book_id' => 1,
                'kunty_id' => 2,
                'matika_id' => 0,
                'chapter_id' => 3,
                'part_id' => 8,
                'created_by' => 0,
                'updated_by' => 0,
                'created_at' => '2015-06-16 00:00:00',
                'updated_at' => '2015-06-16 00:00:00',
            ),
            9 => 
            array (
                'id' => 10,
                'number' => 'កថាភាគទី ៤ ',
                'title' => 'លំនៅឋាននៃនីតិបុគ្គល ',
                'book_id' => 1,
                'kunty_id' => 2,
                'matika_id' => 0,
                'chapter_id' => 3,
                'part_id' => 8,
                'created_by' => 0,
                'updated_by' => 0,
                'created_at' => '2015-06-16 00:00:00',
                'updated_at' => '2015-06-16 00:00:00',
            ),
            10 => 
            array (
                'id' => 11,
                'number' => 'កថាភាគទី ៥ ',
                'title' => 'ការចុះបញ្ជីនៃនីតិបុគ្គលបរទេស ',
                'book_id' => 1,
                'kunty_id' => 2,
                'matika_id' => 0,
                'chapter_id' => 3,
                'part_id' => 8,
                'created_by' => 0,
                'updated_by' => 0,
                'created_at' => '2015-06-16 00:00:00',
                'updated_at' => '2015-06-16 00:00:00',
            ),
            11 => 
            array (
                'id' => 12,
                'number' => 'កថាភាគទី ៦ ',
                'title' => 'ការគ្រប់គ្រង និង ការចាត់ចែងកិច្ចការនៃនីតិបុគ្គល ',
                'book_id' => 1,
                'kunty_id' => 2,
                'matika_id' => 0,
                'chapter_id' => 3,
                'part_id' => 8,
                'created_by' => 0,
                'updated_by' => 0,
                'created_at' => '2015-06-16 00:00:00',
                'updated_at' => '2015-06-16 00:00:00',
            ),
            12 => 
            array (
                'id' => 13,
                'number' => 'កថាភាគទី ៧ ',
                'title' => 'ការរំលាយ និង ការជម្រះបញ្ជី ',
                'book_id' => 1,
                'kunty_id' => 2,
                'matika_id' => 0,
                'chapter_id' => 3,
                'part_id' => 8,
                'created_by' => 0,
                'updated_by' => 0,
                'created_at' => '2015-06-16 00:00:00',
                'updated_at' => '2015-06-16 00:00:00',
            ),
            13 => 
            array (
                'id' => 14,
                'number' => 'កថាភាគទី ១ ',
                'title' => 'នីតិបុគ្គលសាជីវកម្មទទួលខុសត្រូវមានកម្រិត ',
                'book_id' => 1,
                'kunty_id' => 2,
                'matika_id' => 0,
                'chapter_id' => 3,
                'part_id' => 9,
                'created_by' => 0,
                'updated_by' => 0,
                'created_at' => '2015-06-16 00:00:00',
                'updated_at' => '2015-06-16 00:00:00',
            ),
            14 => 
            array (
                'id' => 15,
                'number' => 'កថាភាគទី ២ ',
                'title' => 'នីតិបុគ្គលសាជីវកម្មទទួលខុសត្រូវគ្មានកម្រិត ',
                'book_id' => 1,
                'kunty_id' => 2,
                'matika_id' => 0,
                'chapter_id' => 3,
                'part_id' => 9,
                'created_by' => 0,
                'updated_by' => 0,
                'created_at' => '2015-06-16 00:00:00',
                'updated_at' => '2015-06-16 00:00:00',
            ),
            15 => 
            array (
                'id' => 16,
                'number' => 'កថាភាគទី ១ ',
                'title' => 'លទ្ធកម្មនៃកម្មសិទ្ធិលើអចលនវត្ថុ ',
                'book_id' => 1,
                'kunty_id' => 3,
                'matika_id' => 0,
                'chapter_id' => 5,
                'part_id' => 17,
                'created_by' => 0,
                'updated_by' => 0,
                'created_at' => '2015-06-16 00:00:00',
                'updated_at' => '2015-06-16 00:00:00',
            ),
            16 => 
            array (
                'id' => 17,
                'number' => 'កថាភាគទី ២ ',
                'title' => 'លទ្ធកម្មនៃកម្មសិទ្ធិលើចលនវត្ថុ ',
                'book_id' => 1,
                'kunty_id' => 3,
                'matika_id' => 0,
                'chapter_id' => 5,
                'part_id' => 17,
                'created_by' => 0,
                'updated_by' => 0,
                'created_at' => '2015-06-16 00:00:00',
                'updated_at' => '2015-06-16 00:00:00',
            ),
            17 => 
            array (
                'id' => 18,
                'number' => 'កថាភាគទី ១ ',
                'title' => 'ល័ក្ខខ័ណ្ឌ ',
                'book_id' => 1,
                'kunty_id' => 4,
                'matika_id' => 0,
                'chapter_id' => 13,
                'part_id' => 27,
                'created_by' => 0,
                'updated_by' => 0,
                'created_at' => '2015-06-16 00:00:00',
                'updated_at' => '2015-06-16 00:00:00',
            ),
            18 => 
            array (
                'id' => 19,
                'number' => 'កថាភាគទី ២ ',
                'title' => 'ការកំណត់ពេល ',
                'book_id' => 1,
                'kunty_id' => 4,
                'matika_id' => 0,
                'chapter_id' => 13,
                'part_id' => 27,
                'created_by' => 0,
                'updated_by' => 0,
                'created_at' => '2015-06-16 00:00:00',
                'updated_at' => '2015-06-16 00:00:00',
            ),
            19 => 
            array (
                'id' => 20,
                'number' => 'កថាភាគទី ៣ ',
                'title' => 'អំឡុងពេល ',
                'book_id' => 1,
                'kunty_id' => 4,
                'matika_id' => 0,
                'chapter_id' => 13,
                'part_id' => 27,
                'created_by' => 0,
                'updated_by' => 0,
                'created_at' => '2015-06-16 00:00:00',
                'updated_at' => '2015-06-16 00:00:00',
            ),
            20 => 
            array (
                'id' => 21,
                'number' => 'កថាភាគទី ១ ',
                'title' => 'គោលការណ៍ទូទៅស្ដីពីការសង ',
                'book_id' => 1,
                'kunty_id' => 4,
                'matika_id' => 0,
                'chapter_id' => 19,
                'part_id' => 39,
                'created_by' => 0,
                'updated_by' => 0,
                'created_at' => '2015-06-16 00:00:00',
                'updated_at' => '2015-06-16 00:00:00',
            ),
            21 => 
            array (
                'id' => 22,
                'number' => 'កថាភាគទី ២ ',
                'title' => 'ការកាត់បំណុល ',
                'book_id' => 1,
                'kunty_id' => 4,
                'matika_id' => 0,
                'chapter_id' => 19,
                'part_id' => 39,
                'created_by' => 0,
                'updated_by' => 0,
                'created_at' => '2015-06-16 00:00:00',
                'updated_at' => '2015-06-16 00:00:00',
            ),
            22 => 
            array (
                'id' => 23,
                'number' => 'កថាភាគទី ៣ ',
                'title' => 'សំណើផ្ដល់ការសង និង ការតម្កល់ ',
                'book_id' => 1,
                'kunty_id' => 4,
                'matika_id' => 0,
                'chapter_id' => 19,
                'part_id' => 39,
                'created_by' => 0,
                'updated_by' => 0,
                'created_at' => '2015-06-16 00:00:00',
                'updated_at' => '2015-06-16 00:00:00',
            ),
            23 => 
            array (
                'id' => 24,
                'number' => 'កថាភាគទី ៤ ',
                'title' => 'ឧបាទេសកម្មដោយការសង ',
                'book_id' => 1,
                'kunty_id' => 4,
                'matika_id' => 0,
                'chapter_id' => 19,
                'part_id' => 39,
                'created_by' => 0,
                'updated_by' => 0,
                'created_at' => '2015-06-16 00:00:00',
                'updated_at' => '2015-06-16 00:00:00',
            ),
            24 => 
            array (
                'id' => 25,
                'number' => 'កថាភាគទី ១ ',
                'title' => 'ករណីយកិច្ចរបស់អ្នកលក់ ',
                'book_id' => 1,
                'kunty_id' => 5,
                'matika_id' => 0,
                'chapter_id' => 22,
                'part_id' => 49,
                'created_by' => 0,
                'updated_by' => 0,
                'created_at' => '2015-06-16 00:00:00',
                'updated_at' => '2015-06-16 00:00:00',
            ),
            25 => 
            array (
                'id' => 26,
                'number' => 'កថាភាគទី ២ ',
                'title' => 'ករណីយកិច្ចរបស់អ្នកទិញ ',
                'book_id' => 1,
                'kunty_id' => 5,
                'matika_id' => 0,
                'chapter_id' => 22,
                'part_id' => 49,
                'created_by' => 0,
                'updated_by' => 0,
                'created_at' => '2015-06-16 00:00:00',
                'updated_at' => '2015-06-16 00:00:00',
            ),
            26 => 
            array (
                'id' => 27,
                'number' => 'កថាភាគទី ១ ',
                'title' => 'ការរលត់ដោយការទាមទារ ',
                'book_id' => 1,
                'kunty_id' => 6,
                'matika_id' => 0,
                'chapter_id' => 42,
                'part_id' => 77,
                'created_by' => 0,
                'updated_by' => 0,
                'created_at' => '2015-06-16 00:00:00',
                'updated_at' => '2015-06-16 00:00:00',
            ),
            27 => 
            array (
                'id' => 28,
                'number' => 'កថាភាគទី ២ ',
                'title' => 'ការរលត់ដោយអាជ្ញាយុកាល ',
                'book_id' => 1,
                'kunty_id' => 6,
                'matika_id' => 0,
                'chapter_id' => 42,
                'part_id' => 77,
                'created_by' => 0,
                'updated_by' => 0,
                'created_at' => '2015-06-16 00:00:00',
                'updated_at' => '2015-06-16 00:00:00',
            ),
            28 => 
            array (
                'id' => 29,
                'number' => 'កថាភាគទី ១ ',
                'title' => 'ល័ក្ខខ័ណ្ឌនៃអាពាហ៍ពិពាហ៍ ',
                'book_id' => 1,
                'kunty_id' => 7,
                'matika_id' => 0,
                'chapter_id' => 48,
                'part_id' => 92,
                'created_by' => 0,
                'updated_by' => 0,
                'created_at' => '2015-06-16 00:00:00',
                'updated_at' => '2015-06-16 00:00:00',
            ),
            29 => 
            array (
                'id' => 30,
                'number' => 'កថាភាគទី ២ ',
                'title' => 'មោឃភាព និង ការលុបចោលអាពាហ៍ពិពាហ៍ ',
                'book_id' => 1,
                'kunty_id' => 7,
                'matika_id' => 0,
                'chapter_id' => 48,
                'part_id' => 92,
                'created_by' => 0,
                'updated_by' => 0,
                'created_at' => '2015-06-16 00:00:00',
                'updated_at' => '2015-06-16 00:00:00',
            ),
            30 => 
            array (
                'id' => 31,
                'number' => 'កថាភាគទី ១ ',
                'title' => 'ប្រព័ន្ធទ្រព្យសម្បត្ដិតាមកិច្ចសន្យា ',
                'book_id' => 1,
                'kunty_id' => 7,
                'matika_id' => 0,
                'chapter_id' => 48,
                'part_id' => 94,
                'created_by' => 0,
                'updated_by' => 0,
                'created_at' => '2015-06-16 00:00:00',
                'updated_at' => '2015-06-16 00:00:00',
            ),
            31 => 
            array (
                'id' => 32,
                'number' => 'កថាភាគទី ២ ',
                'title' => 'ប្រព័ន្ធទ្រព្យសម្បត្ដិដែលកំណត់ដោយច្បាប់ ',
                'book_id' => 1,
                'kunty_id' => 7,
                'matika_id' => 0,
                'chapter_id' => 48,
                'part_id' => 94,
                'created_by' => 0,
                'updated_by' => 0,
                'created_at' => '2015-06-16 00:00:00',
                'updated_at' => '2015-06-16 00:00:00',
            ),
            32 => 
            array (
                'id' => 33,
                'number' => 'កថាភាគទី ១ ',
                'title' => 'មូលហេតុនៃការលែងលះគ្នា ',
                'book_id' => 1,
                'kunty_id' => 7,
                'matika_id' => 0,
                'chapter_id' => 48,
                'part_id' => 95,
                'created_by' => 0,
                'updated_by' => 0,
                'created_at' => '2015-06-16 00:00:00',
                'updated_at' => '2015-06-16 00:00:00',
            ),
            33 => 
            array (
                'id' => 34,
                'number' => 'កថាភាគទី ២ ',
                'title' => 'នីតិវិធីនៃការលែងលះគ្នា ',
                'book_id' => 1,
                'kunty_id' => 7,
                'matika_id' => 0,
                'chapter_id' => 48,
                'part_id' => 95,
                'created_by' => 0,
                'updated_by' => 0,
                'created_at' => '2015-06-16 00:00:00',
                'updated_at' => '2015-06-16 00:00:00',
            ),
            34 => 
            array (
                'id' => 35,
                'number' => 'កថាភាគទី ១ ',
                'title' => 'បទប្បញ្ញត្ដិទូទៅ ',
                'book_id' => 1,
                'kunty_id' => 7,
                'matika_id' => 0,
                'chapter_id' => 49,
                'part_id' => 96,
                'created_by' => 0,
                'updated_by' => 0,
                'created_at' => '2015-06-16 00:00:00',
                'updated_at' => '2015-06-16 00:00:00',
            ),
            35 => 
            array (
                'id' => 36,
                'number' => 'កថាភាគទី ២ ',
                'title' => 'ការសម្រេចអំពីបុត្ដភាព ',
                'book_id' => 1,
                'kunty_id' => 7,
                'matika_id' => 0,
                'chapter_id' => 49,
                'part_id' => 96,
                'created_by' => 0,
                'updated_by' => 0,
                'created_at' => '2015-06-16 00:00:00',
                'updated_at' => '2015-06-16 00:00:00',
            ),
            36 => 
            array (
                'id' => 37,
                'number' => 'កថាភាគទី ៣ ',
                'title' => 'ការទទួលស្គាល់ ',
                'book_id' => 1,
                'kunty_id' => 7,
                'matika_id' => 0,
                'chapter_id' => 49,
                'part_id' => 96,
                'created_by' => 0,
                'updated_by' => 0,
                'created_at' => '2015-06-16 00:00:00',
                'updated_at' => '2015-06-16 00:00:00',
            ),
            37 => 
            array (
                'id' => 38,
                'number' => 'កថាភាគទី ៤ ',
                'title' => 'បណ្ដឹងទាមទារឲ្យបញ្ជាក់អំពីនត្ថិភាពនៃបុត្ដភាព ',
                'book_id' => 1,
                'kunty_id' => 7,
                'matika_id' => 0,
                'chapter_id' => 49,
                'part_id' => 96,
                'created_by' => 0,
                'updated_by' => 0,
                'created_at' => '2015-06-16 00:00:00',
                'updated_at' => '2015-06-16 00:00:00',
            ),
            38 => 
            array (
                'id' => 39,
                'number' => 'កថាភាគទី ៥ ',
                'title' => 'បណ្ដឹងទាមទារឲ្យបញ្ជាក់អំពីអត្ថិភាពនៃមាតុភាព ',
                'book_id' => 1,
                'kunty_id' => 7,
                'matika_id' => 0,
                'chapter_id' => 49,
                'part_id' => 96,
                'created_by' => 0,
                'updated_by' => 0,
                'created_at' => '2015-06-16 00:00:00',
                'updated_at' => '2015-06-16 00:00:00',
            ),
            39 => 
            array (
                'id' => 40,
                'number' => 'កថាភាគទី ១ ',
                'title' => 'ស្មុំកូនពេញលេញ ',
                'book_id' => 1,
                'kunty_id' => 7,
                'matika_id' => 0,
                'chapter_id' => 49,
                'part_id' => 97,
                'created_by' => 0,
                'updated_by' => 0,
                'created_at' => '2015-06-16 00:00:00',
                'updated_at' => '2015-06-16 00:00:00',
            ),
            40 => 
            array (
                'id' => 41,
                'number' => 'កថាភាគទី ២ ',
                'title' => 'ស្មុំកូនធម្មតា ',
                'book_id' => 1,
                'kunty_id' => 7,
                'matika_id' => 0,
                'chapter_id' => 49,
                'part_id' => 97,
                'created_by' => 0,
                'updated_by' => 0,
                'created_at' => '2015-06-16 00:00:00',
                'updated_at' => '2015-06-16 00:00:00',
            ),
            41 => 
            array (
                'id' => 42,
                'number' => 'កថាភាគទី ១ ',
                'title' => 'ការចាប់ផ្ដើមអាណាព្យាបាលសម្រាប់អនីតិជន ',
                'book_id' => 1,
                'kunty_id' => 7,
                'matika_id' => 0,
                'chapter_id' => 51,
                'part_id' => 105,
                'created_by' => 0,
                'updated_by' => 0,
                'created_at' => '2015-06-16 00:00:00',
                'updated_at' => '2015-06-16 00:00:00',
            ),
            42 => 
            array (
                'id' => 43,
                'number' => 'កថាភាគទី ២ ',
                'title' => 'អ្នកអាណាព្យាបាលសម្រាប់អនីតិជន ',
                'book_id' => 1,
                'kunty_id' => 7,
                'matika_id' => 0,
                'chapter_id' => 51,
                'part_id' => 105,
                'created_by' => 0,
                'updated_by' => 0,
                'created_at' => '2015-06-16 00:00:00',
                'updated_at' => '2015-06-16 00:00:00',
            ),
            43 => 
            array (
                'id' => 44,
                'number' => 'កថាភាគទី ៣ ',
                'title' => 'អ្នកត្រួតពិនិត្យអ្នកអាណាព្យាបាលសម្រាប់អនីតិជន ',
                'book_id' => 1,
                'kunty_id' => 7,
                'matika_id' => 0,
                'chapter_id' => 51,
                'part_id' => 105,
                'created_by' => 0,
                'updated_by' => 0,
                'created_at' => '2015-06-16 00:00:00',
                'updated_at' => '2015-06-16 00:00:00',
            ),
            44 => 
            array (
                'id' => 45,
                'number' => 'កថាភាគទី ៤ ',
                'title' => 'តួនាទីរបស់អ្នកអាណាព្យាបាលសម្រាប់អនីតិជន ',
                'book_id' => 1,
                'kunty_id' => 7,
                'matika_id' => 0,
                'chapter_id' => 51,
                'part_id' => 105,
                'created_by' => 0,
                'updated_by' => 0,
                'created_at' => '2015-06-16 00:00:00',
                'updated_at' => '2015-06-16 00:00:00',
            ),
            45 => 
            array (
                'id' => 46,
                'number' => 'កថាភាគទី ៥ ',
                'title' => 'ការរួចផុតពីអាណាព្យាបាលសម្រាប់អនីតិជន ',
                'book_id' => 1,
                'kunty_id' => 7,
                'matika_id' => 0,
                'chapter_id' => 51,
                'part_id' => 105,
                'created_by' => 0,
                'updated_by' => 0,
                'created_at' => '2015-06-16 00:00:00',
                'updated_at' => '2015-06-16 00:00:00',
            ),
            46 => 
            array (
                'id' => 47,
                'number' => 'កថាភាគទី ៦ ',
                'title' => 'ការយកមកអនុវត្ដដូចគ្នា ចំពោះកូនរបស់អនីតិជននៅក្រោមអាណាព្យាបាល ',
                'book_id' => 1,
                'kunty_id' => 7,
                'matika_id' => 0,
                'chapter_id' => 51,
                'part_id' => 105,
                'created_by' => 0,
                'updated_by' => 0,
                'created_at' => '2015-06-16 00:00:00',
                'updated_at' => '2015-06-16 00:00:00',
            ),
            47 => 
            array (
                'id' => 48,
                'number' => 'កថាភាគទី ១ ',
                'title' => 'ការចាប់ផ្ដើមអាណាព្យាបាលទូទៅ ',
                'book_id' => 1,
                'kunty_id' => 7,
                'matika_id' => 0,
                'chapter_id' => 51,
                'part_id' => 106,
                'created_by' => 0,
                'updated_by' => 0,
                'created_at' => '2015-06-16 00:00:00',
                'updated_at' => '2015-06-16 00:00:00',
            ),
            48 => 
            array (
                'id' => 49,
                'number' => 'កថាភាគទី ២ ',
                'title' => 'អ្នកអាណាព្យាបាលទូទៅ ',
                'book_id' => 1,
                'kunty_id' => 7,
                'matika_id' => 0,
                'chapter_id' => 51,
                'part_id' => 106,
                'created_by' => 0,
                'updated_by' => 0,
                'created_at' => '2015-06-16 00:00:00',
                'updated_at' => '2015-06-16 00:00:00',
            ),
            49 => 
            array (
                'id' => 50,
                'number' => 'កថាភាគទី ៣ ',
                'title' => 'អ្នកត្រួតពិនិត្យអ្នកអាណាព្យាបាលទូទៅ ',
                'book_id' => 1,
                'kunty_id' => 7,
                'matika_id' => 0,
                'chapter_id' => 51,
                'part_id' => 106,
                'created_by' => 0,
                'updated_by' => 0,
                'created_at' => '2015-06-16 00:00:00',
                'updated_at' => '2015-06-16 00:00:00',
            ),
            50 => 
            array (
                'id' => 51,
                'number' => 'កថាភាគទី ៤ ',
                'title' => 'តួនាទីរបស់អ្នកអាណាព្យាបាលទូទៅ ',
                'book_id' => 1,
                'kunty_id' => 7,
                'matika_id' => 0,
                'chapter_id' => 51,
                'part_id' => 106,
                'created_by' => 0,
                'updated_by' => 0,
                'created_at' => '2015-06-16 00:00:00',
                'updated_at' => '2015-06-16 00:00:00',
            ),
            51 => 
            array (
                'id' => 52,
                'number' => 'កថាភាគទី ៥ ',
                'title' => 'ការបញ្ចប់អាណាព្យាបាលទូទៅ ',
                'book_id' => 1,
                'kunty_id' => 7,
                'matika_id' => 0,
                'chapter_id' => 51,
                'part_id' => 106,
                'created_by' => 0,
                'updated_by' => 0,
                'created_at' => '2015-06-16 00:00:00',
                'updated_at' => '2015-06-16 00:00:00',
            ),
            52 => 
            array (
                'id' => 53,
                'number' => 'កថាភាគ ទី ១ ',
                'title' => 'ការងារសហគមន៍ ',
                'book_id' => 3,
                'kunty_id' => 19,
                'matika_id' => 3,
                'chapter_id' => 96,
                'part_id' => 188,
                'created_by' => 0,
                'updated_by' => 0,
                'created_at' => '2015-06-16 00:00:00',
                'updated_at' => '2015-06-16 00:00:00',
            ),
            53 => 
            array (
                'id' => 54,
                'number' => 'កថាភាគ ទី ២ ',
                'title' => 'ការស្ដីបន្ទោស ',
                'book_id' => 3,
                'kunty_id' => 19,
                'matika_id' => 3,
                'chapter_id' => 96,
                'part_id' => 188,
                'created_by' => 0,
                'updated_by' => 0,
                'created_at' => '2015-06-16 00:00:00',
                'updated_at' => '2015-06-16 00:00:00',
            ),
            54 => 
            array (
                'id' => 55,
                'number' => 'កថាភាគ ទី ១ ',
                'title' => 'និយមន័យនៃស្ថានទម្ងន់ទោសដោយឡែកខ្លះៗ ',
                'book_id' => 3,
                'kunty_id' => 19,
                'matika_id' => 3,
                'chapter_id' => 97,
                'part_id' => 189,
                'created_by' => 0,
                'updated_by' => 0,
                'created_at' => '2015-06-16 00:00:00',
                'updated_at' => '2015-06-16 00:00:00',
            ),
            55 => 
            array (
                'id' => 56,
                'number' => 'កថាភាគ ទី ២ ',
                'title' => 'ការមិនរាងចាល ',
                'book_id' => 3,
                'kunty_id' => 19,
                'matika_id' => 3,
                'chapter_id' => 97,
                'part_id' => 189,
                'created_by' => 0,
                'updated_by' => 0,
                'created_at' => '2015-06-16 00:00:00',
                'updated_at' => '2015-06-16 00:00:00',
            ),
            56 => 
            array (
                'id' => 57,
                'number' => 'កថាភាគ ទី ១ ',
                'title' => 'បទប្បញ្ញត្ដិរួម ',
                'book_id' => 3,
                'kunty_id' => 19,
                'matika_id' => 3,
                'chapter_id' => 98,
                'part_id' => 192,
                'created_by' => 0,
                'updated_by' => 0,
                'created_at' => '2015-06-16 00:00:00',
                'updated_at' => '2015-06-16 00:00:00',
            ),
            57 => 
            array (
                'id' => 58,
                'number' => 'កថាភាគ ទី ២ ',
                'title' => 'ការចោទប្រកាន់ចំពោះបទឧក្រិដ្ឋ ឬបទមជ្ឈិម ',
                'book_id' => 3,
                'kunty_id' => 19,
                'matika_id' => 3,
                'chapter_id' => 98,
                'part_id' => 192,
                'created_by' => 0,
                'updated_by' => 0,
                'created_at' => '2015-06-16 00:00:00',
                'updated_at' => '2015-06-16 00:00:00',
            ),
            58 => 
            array (
                'id' => 59,
                'number' => 'កថាភាគ ទី ៣ ',
                'title' => 'ការចោទប្រកាន់ចំពោះបទលហុ ',
                'book_id' => 3,
                'kunty_id' => 19,
                'matika_id' => 3,
                'chapter_id' => 98,
                'part_id' => 192,
                'created_by' => 0,
                'updated_by' => 0,
                'created_at' => '2015-06-16 00:00:00',
                'updated_at' => '2015-06-16 00:00:00',
            ),
            59 => 
            array (
                'id' => 60,
                'number' => 'កថាភាគ ទី ១ ',
                'title' => 'ការទាញយកប្រយោជន៍ដោយរំលោភលើភាពទន់ខ្សោយ ',
                'book_id' => 3,
                'kunty_id' => 21,
                'matika_id' => 7,
                'chapter_id' => 119,
                'part_id' => 236,
                'created_by' => 0,
                'updated_by' => 0,
                'created_at' => '2015-06-16 00:00:00',
                'updated_at' => '2015-06-16 00:00:00',
            ),
            60 => 
            array (
                'id' => 61,
                'number' => 'កថាភាគ ទី ២ ',
                'title' => 'ការបន្លំ ',
                'book_id' => 3,
                'kunty_id' => 21,
                'matika_id' => 7,
                'chapter_id' => 119,
                'part_id' => 236,
                'created_by' => 0,
                'updated_by' => 0,
                'created_at' => '2015-06-16 00:00:00',
                'updated_at' => '2015-06-16 00:00:00',
            ),
            61 => 
            array (
                'id' => 62,
                'number' => 'កថាភាគ ទី ៣ ',
                'title' => 'ការប៉ះពាល់ដល់សេរីភាពនៃការលក់ដេញថ្លៃ ',
                'book_id' => 3,
                'kunty_id' => 21,
                'matika_id' => 7,
                'chapter_id' => 119,
                'part_id' => 236,
                'created_by' => 0,
                'updated_by' => 0,
                'created_at' => '2015-06-16 00:00:00',
                'updated_at' => '2015-06-16 00:00:00',
            ),
            62 => 
            array (
                'id' => 63,
                'number' => 'កថាភាគ ទី ១ ',
                'title' => 'អំពើហិង្សា ',
                'book_id' => 3,
                'kunty_id' => 22,
                'matika_id' => 9,
                'chapter_id' => 128,
                'part_id' => 254,
                'created_by' => 0,
                'updated_by' => 0,
                'created_at' => '2015-06-16 00:00:00',
                'updated_at' => '2015-06-16 00:00:00',
            ),
            63 => 
            array (
                'id' => 64,
                'number' => 'កថាភាគ ទី ២ ',
                'title' => 'ការប្រមាថ ',
                'book_id' => 3,
                'kunty_id' => 22,
                'matika_id' => 9,
                'chapter_id' => 128,
                'part_id' => 254,
                'created_by' => 0,
                'updated_by' => 0,
                'created_at' => '2015-06-16 00:00:00',
                'updated_at' => '2015-06-16 00:00:00',
            ),
            64 => 
            array (
                'id' => 65,
                'number' => 'កថាភាគ ទី ១ ',
                'title' => 'ការរំលោភអំណាច ',
                'book_id' => 3,
                'kunty_id' => 22,
                'matika_id' => 11,
                'chapter_id' => 133,
                'part_id' => 265,
                'created_by' => 0,
                'updated_by' => 0,
                'created_at' => '2015-06-16 00:00:00',
                'updated_at' => '2015-06-16 00:00:00',
            ),
            65 => 
            array (
                'id' => 66,
                'number' => 'កថាភាគ ទី ២ ',
                'title' => 'ការរំលោភអំណាចប្រឆាំងនឹងបុគ្គល ',
                'book_id' => 3,
                'kunty_id' => 22,
                'matika_id' => 11,
                'chapter_id' => 133,
                'part_id' => 265,
                'created_by' => 0,
                'updated_by' => 0,
                'created_at' => '2015-06-16 00:00:00',
                'updated_at' => '2015-06-16 00:00:00',
            ),
            66 => 
            array (
                'id' => 67,
                'number' => 'កថាភាគ ទី ១ ',
                'title' => 'វីតិក្រម ',
                'book_id' => 3,
                'kunty_id' => 22,
                'matika_id' => 11,
                'chapter_id' => 133,
                'part_id' => 266,
                'created_by' => 0,
                'updated_by' => 0,
                'created_at' => '2015-06-16 00:00:00',
                'updated_at' => '2015-06-16 00:00:00',
            ),
            67 => 
            array (
                'id' => 68,
                'number' => 'កថាភាគ ទី ២ ',
                'title' => 'អំពើស៊ីសំណូក ',
                'book_id' => 3,
                'kunty_id' => 22,
                'matika_id' => 11,
                'chapter_id' => 133,
                'part_id' => 266,
                'created_by' => 0,
                'updated_by' => 0,
                'created_at' => '2015-06-16 00:00:00',
                'updated_at' => '2015-06-16 00:00:00',
            ),
            68 => 
            array (
                'id' => 69,
                'number' => 'កថាភាគ ទី ៣ ',
                'title' => 'ជំនួញឥទ្ធិពលអកម្ម ',
                'book_id' => 3,
                'kunty_id' => 22,
                'matika_id' => 11,
                'chapter_id' => 133,
                'part_id' => 266,
                'created_by' => 0,
                'updated_by' => 0,
                'created_at' => '2015-06-16 00:00:00',
                'updated_at' => '2015-06-16 00:00:00',
            ),
            69 => 
            array (
                'id' => 70,
                'number' => 'កថាភាគ ទី ៤ ',
                'title' => 'ការកេងយកផលប្រយោជន៍ដោយខុសច្បាប់ ',
                'book_id' => 3,
                'kunty_id' => 22,
                'matika_id' => 11,
                'chapter_id' => 133,
                'part_id' => 266,
                'created_by' => 0,
                'updated_by' => 0,
                'created_at' => '2015-06-16 00:00:00',
                'updated_at' => '2015-06-16 00:00:00',
            ),
            70 => 
            array (
                'id' => 71,
                'number' => 'កថាភាគ ទី ៥ ',
                'title' => 'បក្ខានុគ្រោះ ',
                'book_id' => 3,
                'kunty_id' => 22,
                'matika_id' => 11,
                'chapter_id' => 133,
                'part_id' => 266,
                'created_by' => 0,
                'updated_by' => 0,
                'created_at' => '2015-06-16 00:00:00',
                'updated_at' => '2015-06-16 00:00:00',
            ),
            71 => 
            array (
                'id' => 72,
                'number' => 'កថាភាគ ទី ១ ',
                'title' => 'អំពើសូកប៉ាន់ ',
                'book_id' => 3,
                'kunty_id' => 22,
                'matika_id' => 11,
                'chapter_id' => 134,
                'part_id' => 269,
                'created_by' => 0,
                'updated_by' => 0,
                'created_at' => '2015-06-16 00:00:00',
                'updated_at' => '2015-06-16 00:00:00',
            ),
            72 => 
            array (
                'id' => 73,
                'number' => 'កថាភាគ ទី ២ ',
                'title' => 'ជំនួញឥទ្ធិពលសកម្ម ',
                'book_id' => 3,
                'kunty_id' => 22,
                'matika_id' => 11,
                'chapter_id' => 134,
                'part_id' => 269,
                'created_by' => 0,
                'updated_by' => 0,
                'created_at' => '2015-06-16 00:00:00',
                'updated_at' => '2015-06-16 00:00:00',
            ),
            73 => 
            array (
                'id' => 74,
                'number' => 'កថាភាគ ទី ៣ ',
                'title' => 'អំពើសម្លុតគំរាម ',
                'book_id' => 3,
                'kunty_id' => 22,
                'matika_id' => 11,
                'chapter_id' => 134,
                'part_id' => 269,
                'created_by' => 0,
                'updated_by' => 0,
                'created_at' => '2015-06-16 00:00:00',
                'updated_at' => '2015-06-16 00:00:00',
            ),
            74 => 
            array (
                'id' => 75,
                'number' => 'កថាភាគទី  ១ ',
                'title' => 'បត្យាប័ន ',
                'book_id' => 4,
                'kunty_id' => 34,
                'matika_id' => 41,
                'chapter_id' => 176,
                'part_id' => 317,
                'created_by' => 0,
                'updated_by' => 0,
                'created_at' => '2015-06-16 00:00:00',
                'updated_at' => '2015-06-16 00:00:00',
            ),
            75 => 
            array (
                'id' => 76,
                'number' => 'កថាភាគទី  ២ ',
                'title' => 'លក្ខខណ្ឌនៃបត្យាប័ន ',
                'book_id' => 4,
                'kunty_id' => 34,
                'matika_id' => 41,
                'chapter_id' => 176,
                'part_id' => 317,
                'created_by' => 0,
                'updated_by' => 0,
                'created_at' => '2015-06-16 00:00:00',
                'updated_at' => '2015-06-16 00:00:00',
            ),
            76 => 
            array (
                'id' => 77,
                'number' => 'កថាភាគទី  ៣ ',
                'title' => 'នីតិវិធីនៃបត្យាប័ន ',
                'book_id' => 4,
                'kunty_id' => 34,
                'matika_id' => 41,
                'chapter_id' => 176,
                'part_id' => 317,
                'created_by' => 0,
                'updated_by' => 0,
                'created_at' => '2015-06-16 00:00:00',
                'updated_at' => '2015-06-16 00:00:00',
            ),
        ));
        
        
    }
}