<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;

class SignaturesTableSeeder extends Seeder
{

    /**
     * Auto generated seed file
     *
     * @return void
     */
    public function run()
    {
        

        \DB::table('signatures')->delete();
        
        \DB::table('signatures')->insert(array (
            0 => 
            array (
                'id' => 1,
                'name' => 'កាន់ ម៉ន',
                'desp' => NULL,
                'image' => NULL,
                'record_index' => NULL,
                'active' => 1,
                'created_at' => '2024-09-20 09:32:01',
                'updated_at' => '2024-09-20 09:32:01',
                'deleted_at' => NULL,
            ),
            1 => 
            array (
                'id' => 2,
                'name' => 'កឹម ស៊ីថន',
                'desp' => NULL,
                'image' => NULL,
                'record_index' => NULL,
                'active' => 1,
                'created_at' => '2024-09-20 09:32:01',
                'updated_at' => '2024-09-20 09:32:01',
                'deleted_at' => NULL,
            ),
            2 => 
            array (
                'id' => 3,
                'name' => 'កឹមរ័ត្ន វិសិដ្ឋ',
                'desp' => NULL,
                'image' => NULL,
                'record_index' => NULL,
                'active' => 1,
                'created_at' => '2024-09-20 09:32:01',
                'updated_at' => '2024-09-20 09:32:01',
                'deleted_at' => NULL,
            ),
            3 => 
            array (
                'id' => 4,
                'name' => 'កុយ វ៉េត',
                'desp' => NULL,
                'image' => NULL,
                'record_index' => NULL,
                'active' => 1,
                'created_at' => '2024-09-20 09:32:01',
                'updated_at' => '2024-09-20 09:32:01',
                'deleted_at' => NULL,
            ),
            4 => 
            array (
                'id' => 5,
                'name' => 'កើត រិទ្ធ',
                'desp' => NULL,
                'image' => NULL,
                'record_index' => NULL,
                'active' => 1,
                'created_at' => '2024-09-20 09:32:01',
                'updated_at' => '2024-09-20 09:32:01',
                'deleted_at' => NULL,
            ),
            5 => 
            array (
                'id' => 6,
                'name' => 'កែ គឹមយ៉ាន',
                'desp' => NULL,
                'image' => NULL,
                'record_index' => NULL,
                'active' => 1,
                'created_at' => '2024-09-20 09:32:01',
                'updated_at' => '2024-09-20 09:32:01',
                'deleted_at' => NULL,
            ),
            6 => 
            array (
                'id' => 7,
                'name' => 'កែន សត្ថា',
                'desp' => NULL,
                'image' => NULL,
                'record_index' => NULL,
                'active' => 1,
                'created_at' => '2024-09-20 09:32:01',
                'updated_at' => '2024-09-20 09:32:01',
                'deleted_at' => NULL,
            ),
            7 => 
            array (
                'id' => 8,
                'name' => 'កែវ រ៉េមី',
                'desp' => NULL,
                'image' => NULL,
                'record_index' => NULL,
                'active' => 1,
                'created_at' => '2024-09-20 09:32:01',
                'updated_at' => '2024-09-20 09:32:01',
                'deleted_at' => NULL,
            ),
            8 => 
            array (
                'id' => 9,
                'name' => 'កែវ សាផល',
                'desp' => NULL,
                'image' => NULL,
                'record_index' => NULL,
                'active' => 1,
                'created_at' => '2024-09-20 09:32:01',
                'updated_at' => '2024-09-20 09:32:01',
                'deleted_at' => NULL,
            ),
            9 => 
            array (
                'id' => 10,
                'name' => 'ខុទ្ទកាល័យសម្តេចប្រធានព្រឹទ្ធសភា',
                'desp' => NULL,
                'image' => NULL,
                'record_index' => NULL,
                'active' => 1,
                'created_at' => '2024-09-20 09:32:01',
                'updated_at' => '2024-09-20 09:32:01',
                'deleted_at' => NULL,
            ),
            10 => 
            array (
                'id' => 11,
                'name' => 'ខូយ ឃុនហ៊ូរ',
                'desp' => NULL,
                'image' => NULL,
                'record_index' => NULL,
                'active' => 1,
                'created_at' => '2024-09-20 09:32:01',
                'updated_at' => '2024-09-20 09:32:01',
                'deleted_at' => NULL,
            ),
            11 => 
            array (
                'id' => 12,
                'name' => 'គង់ វិបុល',
                'desp' => NULL,
                'image' => NULL,
                'record_index' => NULL,
                'active' => 1,
                'created_at' => '2024-09-20 09:32:01',
                'updated_at' => '2024-09-20 09:32:01',
                'deleted_at' => NULL,
            ),
            12 => 
            array (
                'id' => 13,
                'name' => 'គាត  ឈន់',
                'desp' => NULL,
                'image' => NULL,
                'record_index' => NULL,
                'active' => 1,
                'created_at' => '2024-09-20 09:32:01',
                'updated_at' => '2024-09-20 09:32:01',
                'deleted_at' => NULL,
            ),
            13 => 
            array (
                'id' => 14,
                'name' => 'ឃឹម បូរ',
                'desp' => NULL,
                'image' => NULL,
                'record_index' => NULL,
                'active' => 1,
                'created_at' => '2024-09-20 09:32:01',
                'updated_at' => '2024-09-20 09:32:01',
                'deleted_at' => NULL,
            ),
            14 => 
            array (
                'id' => 15,
                'name' => 'ឃឹម រុស្សីដា',
                'desp' => NULL,
                'image' => NULL,
                'record_index' => NULL,
                'active' => 1,
                'created_at' => '2024-09-20 09:32:01',
                'updated_at' => '2024-09-20 09:32:01',
                'deleted_at' => NULL,
            ),
            15 => 
            array (
                'id' => 16,
                'name' => 'ឃុន ជិនកេន',
                'desp' => NULL,
                'image' => NULL,
                'record_index' => NULL,
                'active' => 1,
                'created_at' => '2024-09-20 09:32:01',
                'updated_at' => '2024-09-20 09:32:01',
                'deleted_at' => NULL,
            ),
            16 => 
            array (
                'id' => 17,
                'name' => 'ង៉ោ ស្រ៊ុន',
                'desp' => NULL,
                'image' => NULL,
                'record_index' => NULL,
                'active' => 1,
                'created_at' => '2024-09-20 09:32:01',
                'updated_at' => '2024-09-20 09:32:01',
                'deleted_at' => NULL,
            ),
            17 => 
            array (
                'id' => 18,
                'name' => 'ង៉ោ ហុងលី',
                'desp' => NULL,
                'image' => NULL,
                'record_index' => NULL,
                'active' => 1,
                'created_at' => '2024-09-20 09:32:01',
                'updated_at' => '2024-09-20 09:32:01',
                'deleted_at' => NULL,
            ),
            18 => 
            array (
                'id' => 19,
                'name' => 'ចក់ ឡេង',
                'desp' => NULL,
                'image' => NULL,
                'record_index' => NULL,
                'active' => 1,
                'created_at' => '2024-09-20 09:32:01',
                'updated_at' => '2024-09-20 09:32:01',
                'deleted_at' => NULL,
            ),
            19 => 
            array (
                'id' => 20,
                'name' => 'ច័ន្ទ តានី',
                'desp' => NULL,
                'image' => NULL,
                'record_index' => NULL,
                'active' => 1,
                'created_at' => '2024-09-20 09:32:01',
                'updated_at' => '2024-09-20 09:32:01',
                'deleted_at' => NULL,
            ),
            20 => 
            array (
                'id' => 21,
                'name' => 'ច័ន្ទ សារុន',
                'desp' => NULL,
                'image' => NULL,
                'record_index' => NULL,
                'active' => 1,
                'created_at' => '2024-09-20 09:32:01',
                'updated_at' => '2024-09-20 09:32:01',
                'deleted_at' => NULL,
            ),
            21 => 
            array (
                'id' => 22,
                'name' => 'ចម និម្មល',
                'desp' => NULL,
                'image' => NULL,
                'record_index' => NULL,
                'active' => 1,
                'created_at' => '2024-09-20 09:32:01',
                'updated_at' => '2024-09-20 09:32:01',
                'deleted_at' => NULL,
            ),
            22 => 
            array (
                'id' => 23,
                'name' => 'ចម ប្រសិទ្ធ',
                'desp' => NULL,
                'image' => NULL,
                'record_index' => NULL,
                'active' => 1,
                'created_at' => '2024-09-20 09:32:01',
                'updated_at' => '2024-09-20 09:32:01',
                'deleted_at' => NULL,
            ),
            23 => 
            array (
                'id' => 24,
                'name' => 'ឆាយ ថន',
                'desp' => NULL,
                'image' => NULL,
                'record_index' => NULL,
                'active' => 1,
                'created_at' => '2024-09-20 09:32:01',
                'updated_at' => '2024-09-20 09:32:01',
                'deleted_at' => NULL,
            ),
            24 => 
            array (
                'id' => 25,
                'name' => 'ឆាយ វ៉ាន់នឿន',
                'desp' => NULL,
                'image' => NULL,
                'record_index' => NULL,
                'active' => 1,
                'created_at' => '2024-09-20 09:32:01',
                'updated_at' => '2024-09-20 09:32:01',
                'deleted_at' => NULL,
            ),
            25 => 
            array (
                'id' => 26,
                'name' => 'ឆឺយ រឿន',
                'desp' => NULL,
                'image' => NULL,
                'record_index' => NULL,
                'active' => 1,
                'created_at' => '2024-09-20 09:32:01',
                'updated_at' => '2024-09-20 09:32:01',
                'deleted_at' => NULL,
            ),
            26 => 
            array (
                'id' => 27,
                'name' => 'ឆែម ពេត',
                'desp' => NULL,
                'image' => NULL,
                'record_index' => NULL,
                'active' => 1,
                'created_at' => '2024-09-20 09:32:01',
                'updated_at' => '2024-09-20 09:32:01',
                'deleted_at' => NULL,
            ),
            27 => 
            array (
                'id' => 28,
                'name' => 'ជា ចាន់តូ',
                'desp' => NULL,
                'image' => NULL,
                'record_index' => NULL,
                'active' => 1,
                'created_at' => '2024-09-20 09:32:01',
                'updated_at' => '2024-09-20 09:32:01',
                'deleted_at' => NULL,
            ),
            28 => 
            array (
                'id' => 29,
                'name' => 'ជា វ៉ាន់ដេត',
                'desp' => NULL,
                'image' => NULL,
                'record_index' => NULL,
                'active' => 1,
                'created_at' => '2024-09-20 09:32:01',
                'updated_at' => '2024-09-20 09:32:01',
                'deleted_at' => NULL,
            ),
            29 => 
            array (
                'id' => 30,
                'name' => 'ជា ស៊ីម',
                'desp' => NULL,
                'image' => NULL,
                'record_index' => NULL,
                'active' => 1,
                'created_at' => '2024-09-20 09:32:01',
                'updated_at' => '2024-09-20 09:32:01',
                'deleted_at' => NULL,
            ),
            30 => 
            array (
                'id' => 31,
                'name' => 'ជា សុផារ៉ា',
                'desp' => NULL,
                'image' => NULL,
                'record_index' => NULL,
                'active' => 1,
                'created_at' => '2024-09-20 09:32:01',
                'updated_at' => '2024-09-20 09:32:01',
                'deleted_at' => NULL,
            ),
            31 => 
            array (
                'id' => 32,
                'name' => 'ជា សុមេធី',
                'desp' => NULL,
                'image' => NULL,
                'record_index' => NULL,
                'active' => 1,
                'created_at' => '2024-09-20 09:32:01',
                'updated_at' => '2024-09-20 09:32:01',
                'deleted_at' => NULL,
            ),
            32 => 
            array (
                'id' => 33,
                'name' => 'ជា សោភណ័',
                'desp' => NULL,
                'image' => NULL,
                'record_index' => NULL,
                'active' => 1,
                'created_at' => '2024-09-20 09:32:01',
                'updated_at' => '2024-09-20 09:32:01',
                'deleted_at' => NULL,
            ),
            33 => 
            array (
                'id' => 34,
                'name' => 'ជា សោភ័ណ',
                'desp' => NULL,
                'image' => NULL,
                'record_index' => NULL,
                'active' => 1,
                'created_at' => '2024-09-20 09:32:01',
                'updated_at' => '2024-09-20 09:32:01',
                'deleted_at' => NULL,
            ),
            34 => 
            array (
                'id' => 35,
                'name' => 'ជាប សត្ថារតន៍',
                'desp' => NULL,
                'image' => NULL,
                'record_index' => NULL,
                'active' => 1,
                'created_at' => '2024-09-20 09:32:01',
                'updated_at' => '2024-09-20 09:32:01',
                'deleted_at' => NULL,
            ),
            35 => 
            array (
                'id' => 36,
                'name' => 'ជិន ប៊ុនស៊ាន',
                'desp' => NULL,
                'image' => NULL,
                'record_index' => NULL,
                'active' => 1,
                'created_at' => '2024-09-20 09:32:01',
                'updated_at' => '2024-09-20 09:32:01',
                'deleted_at' => NULL,
            ),
            36 => 
            array (
                'id' => 37,
                'name' => 'ជ្រា សុចិន្តា',
                'desp' => NULL,
                'image' => NULL,
                'record_index' => NULL,
                'active' => 1,
                'created_at' => '2024-09-20 09:32:01',
                'updated_at' => '2024-09-20 09:32:01',
                'deleted_at' => NULL,
            ),
            37 => 
            array (
                'id' => 38,
                'name' => 'ឈាង រ៉ា',
                'desp' => NULL,
                'image' => NULL,
                'record_index' => NULL,
                'active' => 1,
                'created_at' => '2024-09-20 09:32:01',
                'updated_at' => '2024-09-20 09:32:01',
                'deleted_at' => NULL,
            ),
            38 => 
            array (
                'id' => 39,
                'name' => 'ឈិត សុខុន',
                'desp' => NULL,
                'image' => NULL,
                'record_index' => NULL,
                'active' => 1,
                'created_at' => '2024-09-20 09:32:01',
                'updated_at' => '2024-09-20 09:32:01',
                'deleted_at' => NULL,
            ),
            39 => 
            array (
                'id' => 40,
                'name' => 'ឈួន សុធី',
                'desp' => NULL,
                'image' => NULL,
                'record_index' => NULL,
                'active' => 1,
                'created_at' => '2024-09-20 09:32:01',
                'updated_at' => '2024-09-20 09:32:01',
                'deleted_at' => NULL,
            ),
            40 => 
            array (
                'id' => 41,
                'name' => 'ញឹក ប៊ុនឆៃ',
                'desp' => NULL,
                'image' => NULL,
                'record_index' => NULL,
                'active' => 1,
                'created_at' => '2024-09-20 09:32:01',
                'updated_at' => '2024-09-20 09:32:01',
                'deleted_at' => NULL,
            ),
            41 => 
            array (
                'id' => 42,
                'name' => 'ញឹម វណ្ណដា',
                'desp' => NULL,
                'image' => NULL,
                'record_index' => NULL,
                'active' => 1,
                'created_at' => '2024-09-20 09:32:01',
                'updated_at' => '2024-09-20 09:32:01',
                'deleted_at' => NULL,
            ),
            42 => 
            array (
                'id' => 43,
                'name' => 'ឌិត ទីណា',
                'desp' => NULL,
                'image' => NULL,
                'record_index' => NULL,
                'active' => 1,
                'created_at' => '2024-09-20 09:32:01',
                'updated_at' => '2024-09-20 09:32:01',
                'deleted_at' => NULL,
            ),
            43 => 
            array (
                'id' => 44,
                'name' => 'ឌិត មុន្នី',
                'desp' => NULL,
                'image' => NULL,
                'record_index' => NULL,
                'active' => 1,
                'created_at' => '2024-09-20 09:32:01',
                'updated_at' => '2024-09-20 09:32:01',
                'deleted_at' => NULL,
            ),
            44 => 
            array (
                'id' => 45,
                'name' => 'ណាឌី​ តាន់',
                'desp' => NULL,
                'image' => NULL,
                'record_index' => NULL,
                'active' => 1,
                'created_at' => '2024-09-20 09:32:01',
                'updated_at' => '2024-09-20 09:32:01',
                'deleted_at' => NULL,
            ),
            45 => 
            array (
                'id' => 46,
                'name' => 'តឹករ៉េត សំរេច',
                'desp' => NULL,
                'image' => NULL,
                'record_index' => NULL,
                'active' => 1,
                'created_at' => '2024-09-20 09:32:01',
                'updated_at' => '2024-09-20 09:32:01',
                'deleted_at' => NULL,
            ),
            46 => 
            array (
                'id' => 47,
                'name' => 'ត្រាំ អ៊ីវតឹក',
                'desp' => NULL,
                'image' => NULL,
                'record_index' => NULL,
                'active' => 1,
                'created_at' => '2024-09-20 09:32:01',
                'updated_at' => '2024-09-20 09:32:01',
                'deleted_at' => NULL,
            ),
            47 => 
            array (
                'id' => 48,
                'name' => 'ថោង ខុន',
                'desp' => NULL,
                'image' => NULL,
                'record_index' => NULL,
                'active' => 1,
                'created_at' => '2024-09-20 09:32:01',
                'updated_at' => '2024-09-20 09:32:01',
                'deleted_at' => NULL,
            ),
            48 => 
            array (
                'id' => 49,
                'name' => 'ទៀ បាញ់',
                'desp' => NULL,
                'image' => NULL,
                'record_index' => NULL,
                'active' => 1,
                'created_at' => '2024-09-20 09:32:01',
                'updated_at' => '2024-09-20 09:32:01',
                'deleted_at' => NULL,
            ),
            49 => 
            array (
                'id' => 50,
                'name' => 'ទៀ សីហា',
                'desp' => NULL,
                'image' => NULL,
                'record_index' => NULL,
                'active' => 1,
                'created_at' => '2024-09-20 09:32:01',
                'updated_at' => '2024-09-20 09:32:01',
                'deleted_at' => NULL,
            ),
            50 => 
            array (
                'id' => 51,
                'name' => 'ទេព នន្នរី',
                'desp' => NULL,
                'image' => NULL,
                'record_index' => NULL,
                'active' => 1,
                'created_at' => '2024-09-20 09:32:01',
                'updated_at' => '2024-09-20 09:32:01',
                'deleted_at' => NULL,
            ),
            51 => 
            array (
                'id' => 52,
                'name' => 'នរោត្ដម សីហមុនី',
                'desp' => NULL,
                'image' => NULL,
                'record_index' => NULL,
                'active' => 1,
                'created_at' => '2024-09-20 09:32:01',
                'updated_at' => '2024-09-20 09:32:01',
                'deleted_at' => NULL,
            ),
            52 => 
            array (
                'id' => 53,
                'name' => 'នរោត្តម រណប្ញទិ្ធ',
                'desp' => NULL,
                'image' => NULL,
                'record_index' => NULL,
                'active' => 1,
                'created_at' => '2024-09-20 09:32:01',
                'updated_at' => '2024-09-20 09:32:01',
                'deleted_at' => NULL,
            ),
            53 => 
            array (
                'id' => 54,
                'name' => 'នរោត្តម សីហនុ',
                'desp' => NULL,
                'image' => NULL,
                'record_index' => NULL,
                'active' => 1,
                'created_at' => '2024-09-20 09:32:01',
                'updated_at' => '2024-09-20 09:32:01',
                'deleted_at' => NULL,
            ),
            54 => 
            array (
                'id' => 55,
                'name' => 'នេត សាវឿន',
                'desp' => NULL,
                'image' => NULL,
                'record_index' => NULL,
                'active' => 1,
                'created_at' => '2024-09-20 09:32:01',
                'updated_at' => '2024-09-20 09:32:01',
                'deleted_at' => NULL,
            ),
            55 => 
            array (
                'id' => 56,
                'name' => 'ប៉ាន សូរស័ក្តិ',
                'desp' => NULL,
                'image' => NULL,
                'record_index' => NULL,
                'active' => 1,
                'created_at' => '2024-09-20 09:32:01',
                'updated_at' => '2024-09-20 09:32:01',
                'deleted_at' => NULL,
            ),
            56 => 
            array (
                'id' => 57,
                'name' => 'ប៉ាល ច័ន្ទតារា',
                'desp' => NULL,
                'image' => NULL,
                'record_index' => NULL,
                'active' => 1,
                'created_at' => '2024-09-20 09:32:01',
                'updated_at' => '2024-09-20 09:32:01',
                'deleted_at' => NULL,
            ),
            57 => 
            array (
                'id' => 58,
                'name' => 'ប៊ិន ឈិន',
                'desp' => NULL,
                'image' => NULL,
                'record_index' => NULL,
                'active' => 1,
                'created_at' => '2024-09-20 09:32:01',
                'updated_at' => '2024-09-20 09:32:01',
                'deleted_at' => NULL,
            ),
            58 => 
            array (
                'id' => 59,
                'name' => 'ប៊ិន ត្រឈៃ',
                'desp' => NULL,
                'image' => NULL,
                'record_index' => NULL,
                'active' => 1,
                'created_at' => '2024-09-20 09:32:01',
                'updated_at' => '2024-09-20 09:32:01',
                'deleted_at' => NULL,
            ),
            59 => 
            array (
                'id' => 60,
                'name' => 'ប៊ុន សំបូរ',
                'desp' => NULL,
                'image' => NULL,
                'record_index' => NULL,
                'active' => 1,
                'created_at' => '2024-09-20 09:32:01',
                'updated_at' => '2024-09-20 09:32:01',
                'deleted_at' => NULL,
            ),
            60 => 
            array (
                'id' => 61,
                'name' => 'ប៊ុន អ៊ុយ',
                'desp' => NULL,
                'image' => NULL,
                'record_index' => NULL,
                'active' => 1,
                'created_at' => '2024-09-20 09:32:01',
                'updated_at' => '2024-09-20 09:32:01',
                'deleted_at' => NULL,
            ),
            61 => 
            array (
                'id' => 62,
                'name' => 'បួន លឹមហេង',
                'desp' => NULL,
                'image' => NULL,
                'record_index' => NULL,
                'active' => 1,
                'created_at' => '2024-09-20 09:32:01',
                'updated_at' => '2024-09-20 09:32:01',
                'deleted_at' => NULL,
            ),
            62 => 
            array (
                'id' => 63,
                'name' => 'ប៉េង ពោធិ៍នា',
                'desp' => NULL,
                'image' => NULL,
                'record_index' => NULL,
                'active' => 1,
                'created_at' => '2024-09-20 09:32:01',
                'updated_at' => '2024-09-20 09:32:01',
                'deleted_at' => NULL,
            ),
            63 => 
            array (
                'id' => 64,
                'name' => 'ប្រាក់ សុខុន',
                'desp' => NULL,
                'image' => NULL,
                'record_index' => NULL,
                'active' => 1,
                'created_at' => '2024-09-20 09:32:01',
                'updated_at' => '2024-09-20 09:32:01',
                'deleted_at' => NULL,
            ),
            64 => 
            array (
                'id' => 65,
                'name' => 'ផៃ ស៊ីផាន',
                'desp' => NULL,
                'image' => NULL,
                'record_index' => NULL,
                'active' => 1,
                'created_at' => '2024-09-20 09:32:01',
                'updated_at' => '2024-09-20 09:32:01',
                'deleted_at' => NULL,
            ),
            65 => 
            array (
                'id' => 66,
                'name' => 'ពេជ្រ ប៊ុនធិន',
                'desp' => NULL,
                'image' => NULL,
                'record_index' => NULL,
                'active' => 1,
                'created_at' => '2024-09-20 09:32:01',
                'updated_at' => '2024-09-20 09:32:01',
                'deleted_at' => NULL,
            ),
            66 => 
            array (
                'id' => 67,
                'name' => 'ព្រុំ សុខា',
                'desp' => NULL,
                'image' => NULL,
                'record_index' => NULL,
                'active' => 1,
                'created_at' => '2024-09-20 09:32:01',
                'updated_at' => '2024-09-20 09:32:01',
                'deleted_at' => NULL,
            ),
            67 => 
            array (
                'id' => 68,
                'name' => 'ភូ លីវុឌ្ឍ',
                'desp' => NULL,
                'image' => NULL,
                'record_index' => NULL,
                'active' => 1,
                'created_at' => '2024-09-20 09:32:01',
                'updated_at' => '2024-09-20 09:32:01',
                'deleted_at' => NULL,
            ),
            68 => 
            array (
                'id' => 69,
                'name' => 'ភឿង សកុណា',
                'desp' => NULL,
                'image' => NULL,
                'record_index' => NULL,
                'active' => 1,
                'created_at' => '2024-09-20 09:32:01',
                'updated_at' => '2024-09-20 09:32:01',
                'deleted_at' => NULL,
            ),
            69 => 
            array (
                'id' => 70,
                'name' => 'ម៉ម ប៊ុនហេង',
                'desp' => NULL,
                'image' => NULL,
                'record_index' => NULL,
                'active' => 1,
                'created_at' => '2024-09-20 09:32:01',
                'updated_at' => '2024-09-20 09:32:01',
                'deleted_at' => NULL,
            ),
            70 => 
            array (
                'id' => 71,
                'name' => 'មាសសាឯម ដានី',
                'desp' => NULL,
                'image' => NULL,
                'record_index' => NULL,
                'active' => 1,
                'created_at' => '2024-09-20 09:32:01',
                'updated_at' => '2024-09-20 09:32:01',
                'deleted_at' => NULL,
            ),
            71 => 
            array (
                'id' => 72,
                'name' => 'មិន ឃិន',
                'desp' => NULL,
                'image' => NULL,
                'record_index' => NULL,
                'active' => 1,
                'created_at' => '2024-09-20 09:32:01',
                'updated_at' => '2024-09-20 09:32:01',
                'deleted_at' => NULL,
            ),
            72 => 
            array (
                'id' => 73,
                'name' => 'ម៉ុក ម៉រ៉េត',
                'desp' => NULL,
                'image' => NULL,
                'record_index' => NULL,
                'active' => 1,
                'created_at' => '2024-09-20 09:32:01',
                'updated_at' => '2024-09-20 09:32:01',
                'deleted_at' => NULL,
            ),
            73 => 
            array (
                'id' => 74,
                'name' => 'ម៉ែន សំអន',
                'desp' => NULL,
                'image' => NULL,
                'record_index' => NULL,
                'active' => 1,
                'created_at' => '2024-09-20 09:32:01',
                'updated_at' => '2024-09-20 09:32:01',
                'deleted_at' => NULL,
            ),
            74 => 
            array (
                'id' => 75,
                'name' => 'ម៉ៅ ហាវណ្ណាល់',
                'desp' => NULL,
                'image' => NULL,
                'record_index' => NULL,
                'active' => 1,
                'created_at' => '2024-09-20 09:32:01',
                'updated_at' => '2024-09-20 09:32:01',
                'deleted_at' => NULL,
            ),
            75 => 
            array (
                'id' => 76,
                'name' => 'ម្សាស់ លាស់',
                'desp' => NULL,
                'image' => NULL,
                'record_index' => NULL,
                'active' => 1,
                'created_at' => '2024-09-20 09:32:01',
                'updated_at' => '2024-09-20 09:32:01',
                'deleted_at' => NULL,
            ),
            76 => 
            array (
                'id' => 77,
                'name' => 'យឹក ឆៃលី',
                'desp' => NULL,
                'image' => NULL,
                'record_index' => NULL,
                'active' => 1,
                'created_at' => '2024-09-20 09:32:01',
                'updated_at' => '2024-09-20 09:32:01',
                'deleted_at' => NULL,
            ),
            77 => 
            array (
                'id' => 78,
                'name' => 'យូ ហុកគ្រី',
                'desp' => NULL,
                'image' => NULL,
                'record_index' => NULL,
                'active' => 1,
                'created_at' => '2024-09-20 09:32:01',
                'updated_at' => '2024-09-20 09:32:01',
                'deleted_at' => NULL,
            ),
            78 => 
            array (
                'id' => 79,
                'name' => 'លឹម គានហោ',
                'desp' => NULL,
                'image' => NULL,
                'record_index' => NULL,
                'active' => 1,
                'created_at' => '2024-09-20 09:32:01',
                'updated_at' => '2024-09-20 09:32:01',
                'deleted_at' => NULL,
            ),
            79 => 
            array (
                'id' => 80,
                'name' => 'វង សូត',
                'desp' => NULL,
                'image' => NULL,
                'record_index' => NULL,
                'active' => 1,
                'created_at' => '2024-09-20 09:32:01',
                'updated_at' => '2024-09-20 09:32:01',
                'deleted_at' => NULL,
            ),
            80 => 
            array (
                'id' => 81,
                'name' => 'វង្សី វិស្សុត',
                'desp' => NULL,
                'image' => NULL,
                'record_index' => NULL,
                'active' => 1,
                'created_at' => '2024-09-20 09:32:01',
                'updated_at' => '2024-09-20 09:32:01',
                'deleted_at' => NULL,
            ),
            81 => 
            array (
                'id' => 82,
                'name' => 'វ៉ា គឹមហុង',
                'desp' => NULL,
                'image' => NULL,
                'record_index' => NULL,
                'active' => 1,
                'created_at' => '2024-09-20 09:32:01',
                'updated_at' => '2024-09-20 09:32:01',
                'deleted_at' => NULL,
            ),
            82 => 
            array (
                'id' => 83,
                'name' => 'វេង សាខុន',
                'desp' => NULL,
                'image' => NULL,
                'record_index' => NULL,
                'active' => 1,
                'created_at' => '2024-09-20 09:32:01',
                'updated_at' => '2024-09-20 09:32:01',
                'deleted_at' => NULL,
            ),
            83 => 
            array (
                'id' => 84,
                'name' => 'វ៉េង សិរីវុឌ្ឍ',
                'desp' => NULL,
                'image' => NULL,
                'record_index' => NULL,
                'active' => 1,
                'created_at' => '2024-09-20 09:32:01',
                'updated_at' => '2024-09-20 09:32:01',
                'deleted_at' => NULL,
            ),
            84 => 
            array (
                'id' => 85,
                'name' => 'ស ខេង',
                'desp' => NULL,
                'image' => NULL,
                'record_index' => NULL,
                'active' => 1,
                'created_at' => '2024-09-20 09:32:01',
                'updated_at' => '2024-09-20 09:32:01',
                'deleted_at' => NULL,
            ),
            85 => 
            array (
                'id' => 86,
                'name' => 'សំ ប៊ុនណា',
                'desp' => NULL,
                'image' => NULL,
                'record_index' => NULL,
                'active' => 1,
                'created_at' => '2024-09-20 09:32:01',
                'updated_at' => '2024-09-20 09:32:01',
                'deleted_at' => NULL,
            ),
            86 => 
            array (
                'id' => 87,
                'name' => 'ស សុខា',
                'desp' => NULL,
                'image' => NULL,
                'record_index' => NULL,
                'active' => 1,
                'created_at' => '2024-09-20 09:32:01',
                'updated_at' => '2024-09-20 09:32:01',
                'deleted_at' => NULL,
            ),
            87 => 
            array (
                'id' => 88,
                'name' => 'សម សុត្ថា',
                'desp' => NULL,
                'image' => NULL,
                'record_index' => NULL,
                'active' => 1,
                'created_at' => '2024-09-20 09:32:01',
                'updated_at' => '2024-09-20 09:32:01',
                'deleted_at' => NULL,
            ),
            88 => 
            array (
                'id' => 89,
                'name' => 'សយ សុខា',
                'desp' => NULL,
                'image' => NULL,
                'record_index' => NULL,
                'active' => 1,
                'created_at' => '2024-09-20 09:32:01',
                'updated_at' => '2024-09-20 09:32:01',
                'deleted_at' => NULL,
            ),
            89 => 
            array (
                'id' => 90,
                'name' => 'សាយ ឈុំ',
                'desp' => NULL,
                'image' => NULL,
                'record_index' => NULL,
                'active' => 1,
                'created_at' => '2024-09-20 09:32:01',
                'updated_at' => '2024-09-20 09:32:01',
                'deleted_at' => NULL,
            ),
            90 => 
            array (
                'id' => 91,
                'name' => 'សាយ សំអាល់',
                'desp' => NULL,
                'image' => NULL,
                'record_index' => NULL,
                'active' => 1,
                'created_at' => '2024-09-20 09:32:01',
                'updated_at' => '2024-09-20 09:32:01',
                'deleted_at' => NULL,
            ),
            91 => 
            array (
                'id' => 92,
                'name' => 'ស៊ិក ប៊ុនហុក',
                'desp' => NULL,
                'image' => NULL,
                'record_index' => NULL,
                'active' => 1,
                'created_at' => '2024-09-20 09:32:01',
                'updated_at' => '2024-09-20 09:32:01',
                'deleted_at' => NULL,
            ),
            92 => 
            array (
                'id' => 93,
                'name' => 'ស៊ិន សរី',
                'desp' => NULL,
                'image' => NULL,
                'record_index' => NULL,
                'active' => 1,
                'created_at' => '2024-09-20 09:32:01',
                'updated_at' => '2024-09-20 09:32:01',
                'deleted_at' => NULL,
            ),
            93 => 
            array (
                'id' => 94,
                'name' => 'ស៊ីសុវត្ថិ សិរីរ័ត្ន',
                'desp' => NULL,
                'image' => NULL,
                'record_index' => NULL,
                'active' => 1,
                'created_at' => '2024-09-20 09:32:01',
                'updated_at' => '2024-09-20 09:32:01',
                'deleted_at' => NULL,
            ),
            94 => 
            array (
                'id' => 95,
                'name' => 'ស៊ឹម វណ្ណា',
                'desp' => NULL,
                'image' => NULL,
                'record_index' => NULL,
                'active' => 1,
                'created_at' => '2024-09-20 09:32:01',
                'updated_at' => '2024-09-20 09:32:01',
                'deleted_at' => NULL,
            ),
            95 => 
            array (
                'id' => 96,
                'name' => 'ស៊ុំ ម៉ានិត',
                'desp' => NULL,
                'image' => NULL,
                'record_index' => NULL,
                'active' => 1,
                'created_at' => '2024-09-20 09:32:01',
                'updated_at' => '2024-09-20 09:32:01',
                'deleted_at' => NULL,
            ),
            96 => 
            array (
                'id' => 97,
                'name' => 'សុក ផេង',
                'desp' => NULL,
                'image' => NULL,
                'record_index' => NULL,
                'active' => 1,
                'created_at' => '2024-09-20 09:32:01',
                'updated_at' => '2024-09-20 09:32:01',
                'deleted_at' => NULL,
            ),
            97 => 
            array (
                'id' => 98,
                'name' => 'សុខ ចិន្តាសោភា',
                'desp' => NULL,
                'image' => NULL,
                'record_index' => NULL,
                'active' => 1,
                'created_at' => '2024-09-20 09:32:01',
                'updated_at' => '2024-09-20 09:32:01',
                'deleted_at' => NULL,
            ),
            98 => 
            array (
                'id' => 99,
                'name' => 'សុខ វិឡាយ',
                'desp' => NULL,
                'image' => NULL,
                'record_index' => NULL,
                'active' => 1,
                'created_at' => '2024-09-20 09:32:01',
                'updated_at' => '2024-09-20 09:32:01',
                'deleted_at' => NULL,
            ),
            99 => 
            array (
                'id' => 100,
                'name' => 'សុខ អាន',
                'desp' => NULL,
                'image' => NULL,
                'record_index' => NULL,
                'active' => 1,
                'created_at' => '2024-09-20 09:32:01',
                'updated_at' => '2024-09-20 09:32:01',
                'deleted_at' => NULL,
            ),
            100 => 
            array (
                'id' => 101,
                'name' => 'ស៊ុន ចាន់ថុល',
                'desp' => NULL,
                'image' => NULL,
                'record_index' => NULL,
                'active' => 1,
                'created_at' => '2024-09-20 09:32:01',
                'updated_at' => '2024-09-20 09:32:01',
                'deleted_at' => NULL,
            ),
            101 => 
            array (
                'id' => 102,
                'name' => 'ស៊ុយ សែម',
                'desp' => NULL,
                'image' => NULL,
                'record_index' => NULL,
                'active' => 1,
                'created_at' => '2024-09-20 09:32:01',
                'updated_at' => '2024-09-20 09:32:01',
                'deleted_at' => NULL,
            ),
            102 => 
            array (
                'id' => 103,
                'name' => 'ស៊ូ ភិរិន្ទ',
                'desp' => NULL,
                'image' => NULL,
                'record_index' => NULL,
                'active' => 1,
                'created_at' => '2024-09-20 09:32:01',
                'updated_at' => '2024-09-20 09:32:01',
                'deleted_at' => NULL,
            ),
            103 => 
            array (
                'id' => 104,
                'name' => 'សួន វិសាល',
                'desp' => NULL,
                'image' => NULL,
                'record_index' => NULL,
                'active' => 1,
                'created_at' => '2024-09-20 09:32:01',
                'updated_at' => '2024-09-20 09:32:01',
                'deleted_at' => NULL,
            ),
            104 => 
            array (
                'id' => 105,
                'name' => 'សៀង ឈុនទ្រី',
                'desp' => NULL,
                'image' => NULL,
                'record_index' => NULL,
                'active' => 1,
                'created_at' => '2024-09-20 09:32:01',
                'updated_at' => '2024-09-20 09:32:01',
                'deleted_at' => NULL,
            ),
            105 => 
            array (
                'id' => 106,
                'name' => 'សេង លឹមនៅ',
                'desp' => NULL,
                'image' => NULL,
                'record_index' => NULL,
                'active' => 1,
                'created_at' => '2024-09-20 09:32:01',
                'updated_at' => '2024-09-20 09:32:01',
                'deleted_at' => NULL,
            ),
            106 => 
            array (
                'id' => 107,
                'name' => 'ស្វាយ ស៊ីថា',
                'desp' => NULL,
                'image' => NULL,
                'record_index' => NULL,
                'active' => 1,
                'created_at' => '2024-09-20 09:32:01',
                'updated_at' => '2024-09-20 09:32:01',
                'deleted_at' => NULL,
            ),
            107 => 
            array (
                'id' => 108,
                'name' => 'ហង់  ជូនណារ៉ុង',
                'desp' => NULL,
                'image' => NULL,
                'record_index' => NULL,
                'active' => 1,
                'created_at' => '2024-09-20 09:32:01',
                'updated_at' => '2024-09-20 09:32:01',
                'deleted_at' => NULL,
            ),
            108 => 
            array (
                'id' => 109,
                'name' => 'ហ៊ីង ថូរ៉ាក់ស៊ី',
                'desp' => NULL,
                'image' => NULL,
                'record_index' => NULL,
                'active' => 1,
                'created_at' => '2024-09-20 09:32:01',
                'updated_at' => '2024-09-20 09:32:01',
                'deleted_at' => NULL,
            ),
            109 => 
            array (
                'id' => 110,
                'name' => 'ហ៊ឹម ឆែម',
                'desp' => NULL,
                'image' => NULL,
                'record_index' => NULL,
                'active' => 1,
                'created_at' => '2024-09-20 09:32:01',
                'updated_at' => '2024-09-20 09:32:01',
                'deleted_at' => NULL,
            ),
            110 => 
            array (
                'id' => 111,
                'name' => 'ហ៊ុន ម៉ាណែត',
                'desp' => NULL,
                'image' => NULL,
                'record_index' => NULL,
                'active' => 1,
                'created_at' => '2024-09-20 09:32:01',
                'updated_at' => '2024-09-20 09:32:01',
                'deleted_at' => NULL,
            ),
            111 => 
            array (
                'id' => 112,
                'name' => 'ហ៊ុន ម៉ានី',
                'desp' => NULL,
                'image' => NULL,
                'record_index' => NULL,
                'active' => 1,
                'created_at' => '2024-09-20 09:32:01',
                'updated_at' => '2024-09-20 09:32:01',
                'deleted_at' => NULL,
            ),
            112 => 
            array (
                'id' => 113,
                'name' => 'ហ៊ុន សែន',
                'desp' => NULL,
                'image' => NULL,
                'record_index' => NULL,
                'active' => 1,
                'created_at' => '2024-09-20 09:32:01',
                'updated_at' => '2024-09-20 09:32:01',
                'deleted_at' => NULL,
            ),
            113 => 
            array (
                'id' => 114,
                'name' => 'ហួត ហាក់',
                'desp' => NULL,
                'image' => NULL,
                'record_index' => NULL,
                'active' => 1,
                'created_at' => '2024-09-20 09:32:01',
                'updated_at' => '2024-09-20 09:32:01',
                'deleted_at' => NULL,
            ),
            114 => 
            array (
                'id' => 115,
                'name' => 'ហេង​ បូ',
                'desp' => NULL,
                'image' => NULL,
                'record_index' => NULL,
                'active' => 1,
                'created_at' => '2024-09-20 09:32:01',
                'updated_at' => '2024-09-20 09:32:01',
                'deleted_at' => NULL,
            ),
            115 => 
            array (
                'id' => 116,
                'name' => 'ហេង សំរិន',
                'desp' => NULL,
                'image' => NULL,
                'record_index' => NULL,
                'active' => 1,
                'created_at' => '2024-09-20 09:32:01',
                'updated_at' => '2024-09-20 09:32:01',
                'deleted_at' => NULL,
            ),
            116 => 
            array (
                'id' => 117,
                'name' => 'ហេង សួរ',
                'desp' => NULL,
                'image' => NULL,
                'record_index' => NULL,
                'active' => 1,
                'created_at' => '2024-09-20 09:32:01',
                'updated_at' => '2024-09-20 09:32:01',
                'deleted_at' => NULL,
            ),
            117 => 
            array (
                'id' => 118,
                'name' => 'ហែម ក្រាញតូនី',
                'desp' => NULL,
                'image' => NULL,
                'record_index' => NULL,
                'active' => 1,
                'created_at' => '2024-09-20 09:32:01',
                'updated_at' => '2024-09-20 09:32:01',
                'deleted_at' => NULL,
            ),
            118 => 
            array (
                'id' => 119,
                'name' => 'ហែម វណ្ណឌី',
                'desp' => NULL,
                'image' => NULL,
                'record_index' => NULL,
                'active' => 1,
                'created_at' => '2024-09-20 09:32:01',
                'updated_at' => '2024-09-20 09:32:01',
                'deleted_at' => NULL,
            ),
            119 => 
            array (
                'id' => 120,
                'name' => 'ហោ ណាំហុង',
                'desp' => NULL,
                'image' => NULL,
                'record_index' => NULL,
                'active' => 1,
                'created_at' => '2024-09-20 09:32:01',
                'updated_at' => '2024-09-20 09:32:01',
                'deleted_at' => NULL,
            ),
            120 => 
            array (
                'id' => 121,
                'name' => 'ឡាំ ជា',
                'desp' => NULL,
                'image' => NULL,
                'record_index' => NULL,
                'active' => 1,
                'created_at' => '2024-09-20 09:32:01',
                'updated_at' => '2024-09-20 09:32:01',
                'deleted_at' => NULL,
            ),
            121 => 
            array (
                'id' => 122,
                'name' => 'ឡាយ ណាវីន',
                'desp' => NULL,
                'image' => NULL,
                'record_index' => NULL,
                'active' => 1,
                'created_at' => '2024-09-20 09:32:01',
                'updated_at' => '2024-09-20 09:32:01',
                'deleted_at' => NULL,
            ),
            122 => 
            array (
                'id' => 123,
                'name' => 'ឡាយ ព្រហស្ថ',
                'desp' => NULL,
                'image' => NULL,
                'record_index' => NULL,
                'active' => 1,
                'created_at' => '2024-09-20 09:32:01',
                'updated_at' => '2024-09-20 09:32:01',
                'deleted_at' => NULL,
            ),
            123 => 
            array (
                'id' => 124,
                'name' => 'អង្គ វង្សវឌ្ឍានា',
                'desp' => NULL,
                'image' => NULL,
                'record_index' => NULL,
                'active' => 1,
                'created_at' => '2024-09-20 09:32:01',
                'updated_at' => '2024-09-20 09:32:01',
                'deleted_at' => NULL,
            ),
            124 => 
            array (
                'id' => 125,
                'name' => 'អ៊ិត សំហេង',
                'desp' => NULL,
                'image' => NULL,
                'record_index' => NULL,
                'active' => 1,
                'created_at' => '2024-09-20 09:32:01',
                'updated_at' => '2024-09-20 09:32:01',
                'deleted_at' => NULL,
            ),
            125 => 
            array (
                'id' => 126,
                'name' => 'អ៊ីន វីរជាតិ',
                'desp' => NULL,
                'image' => NULL,
                'record_index' => NULL,
                'active' => 1,
                'created_at' => '2024-09-20 09:32:01',
                'updated_at' => '2024-09-20 09:32:01',
                'deleted_at' => NULL,
            ),
            126 => 
            array (
                'id' => 127,
                'name' => 'អ៊ីវ ខេង',
                'desp' => NULL,
                'image' => NULL,
                'record_index' => NULL,
                'active' => 1,
                'created_at' => '2024-09-20 09:32:01',
                'updated_at' => '2024-09-20 09:32:01',
                'deleted_at' => NULL,
            ),
            127 => 
            array (
                'id' => 128,
                'name' => 'អ៊ឹម ឈុនលឹម',
                'desp' => NULL,
                'image' => NULL,
                'record_index' => NULL,
                'active' => 1,
                'created_at' => '2024-09-20 09:32:01',
                'updated_at' => '2024-09-20 09:32:01',
                'deleted_at' => NULL,
            ),
            128 => 
            array (
                'id' => 129,
                'name' => 'អ៊ឹម សួស្តី',
                'desp' => NULL,
                'image' => NULL,
                'record_index' => NULL,
                'active' => 1,
                'created_at' => '2024-09-20 09:32:01',
                'updated_at' => '2024-09-20 09:32:01',
                'deleted_at' => NULL,
            ),
            129 => 
            array (
                'id' => 130,
                'name' => 'អ៊ុក រ៉ាប៊ុន',
                'desp' => NULL,
                'image' => NULL,
                'record_index' => NULL,
                'active' => 1,
                'created_at' => '2024-09-20 09:32:01',
                'updated_at' => '2024-09-20 09:32:01',
                'deleted_at' => NULL,
            ),
            130 => 
            array (
                'id' => 131,
                'name' => 'អូន ព័ន្ធមុនីរ័ត្ន',
                'desp' => NULL,
                'image' => NULL,
                'record_index' => NULL,
                'active' => 1,
                'created_at' => '2024-09-20 09:32:01',
                'updated_at' => '2024-09-20 09:32:01',
                'deleted_at' => NULL,
            ),
            131 => 
            array (
                'id' => 132,
                'name' => 'អៀង មុល្លី',
                'desp' => NULL,
                'image' => NULL,
                'record_index' => NULL,
                'active' => 1,
                'created_at' => '2024-09-20 09:32:01',
                'updated_at' => '2024-09-20 09:32:01',
                'deleted_at' => NULL,
            ),
            132 => 
            array (
                'id' => 133,
                'name' => 'ឪ វណ្ណឌិន',
                'desp' => NULL,
                'image' => NULL,
                'record_index' => NULL,
                'active' => 1,
                'created_at' => '2024-09-20 09:32:01',
                'updated_at' => '2024-09-20 09:32:01',
                'deleted_at' => NULL,
            ),
            133 => 
            array (
                'id' => 134,
                'name' => 'ឪម យ៉ិនទៀង',
                'desp' => NULL,
                'image' => NULL,
                'record_index' => NULL,
                'active' => 1,
                'created_at' => '2024-09-20 09:32:01',
                'updated_at' => '2024-09-20 09:32:01',
                'deleted_at' => NULL,
            ),
            134 => 
            array (
                'id' => 135,
                'name' => 'ឯក សំអុល',
                'desp' => NULL,
                'image' => NULL,
                'record_index' => NULL,
                'active' => 1,
                'created_at' => '2024-09-20 09:32:01',
                'updated_at' => '2024-09-20 09:32:01',
                'deleted_at' => NULL,
            ),
            135 => 
            array (
                'id' => 136,
                'name' => 'ឳក ប៊ុន',
                'desp' => NULL,
                'image' => NULL,
                'record_index' => NULL,
                'active' => 1,
                'created_at' => '2024-09-20 09:32:01',
                'updated_at' => '2024-09-20 09:32:01',
                'deleted_at' => NULL,
            ),
        ));
        
        
    }
}